### ISSUE TITLE
Cleanup notes for new onboarding

### ISSUE THREAD

**Issue by Abby-Wheelis** [e-mission/e-mission-docs#1003]
There's a few nitpicky things I've noticed in the onboarding UI:

- [x] (1st screenshot) on smaller form-factor phones, the "welcome" screen gets cut off to where you can't see the text below the scan and past buttons -- I think we can fix this by making that page scrollable?
- [x] (2nd & 3rd screenshot) in the permissions popup I believe the "how to fix" and "why do we need this" permissions are swapped / in the wrong places (for iPhone only)
- [x] (4th screenshot) on android, it seems we now have the "battery optimizations" as a pop-up rather than needing to scroll 🎉  - If this is the case across all Android platforms, I think we should update the "how to fix" text for that item

<img src="https://github.com/e-mission/e-mission-docs/assets/54848919/9e743aa9-f699-470c-877d-5cce4f359373" width="200"  />
<img src="https://github.com/e-mission/e-mission-docs/assets/54848919/5d3fdc6b-f078-4b34-ab19-7b0c128e1a68" width="200"  />
<img src="https://github.com/e-mission/e-mission-docs/assets/54848919/8a295795-d8f5-4515-ae57-3c958d729688" width="200"  />
<img src="https://github.com/e-mission/e-mission-docs/assets/54848919/6b06550c-2ecf-4ebc-b917-a4b521c1931b" width="200"  />

**Comment by JGreenlee** [comment]
If these tasks can be easily addressed today, maybe we can tack them onto https://github.com/e-mission/e-mission-phone/pull/1059

**Comment by Abby-Wheelis** [comment]
These are fixed on staging:

- added a scroll
- updated the text so the explanation was grouped with the explanations and the instructions with the instructions
- changed the android fix message

<img src="https://github.com/e-mission/e-mission-docs/assets/54848919/654efaa7-1891-4adb-8ac6-dc8b238b7180" width="200"  />
<img src="https://github.com/e-mission/e-mission-docs/assets/54848919/83137af0-0e84-4cc8-81d8-f5964aad64a6" width="200"  />
<img src="https://github.com/e-mission/e-mission-docs/assets/54848919/9603a5d9-db80-4d5d-81ba-7fdc9b3ae786" width="200"  />
<img src="https://github.com/e-mission/e-mission-docs/assets/54848919/3204939b-0528-4b0e-9656-2b49a8315bdd" width="200"  />

**Comment by Abby-Wheelis** [comment]
After the changes in [#1059)(https://github.com/e-mission/e-mission-phone/pull/1059), as shown in the screenshots, these details have been resolved.
