### ISSUE TITLE
Join page - autogenerating even when autogen false for studies

### ISSUE THREAD

**Issue by Abby-Wheelis** [e-mission/e-mission-docs#1004]
We have gotten a report that the Join Page is auto-generating opcodes for all studies, even when `autogen = false` in the config.

**Comment by Abby-Wheelis** [comment]
Looking at this, I thought of a place in the privacy policy/consent text in the phone code that might need a similar treatment - [the text about where the opcode comes from](https://github.com/e-mission/e-mission-phone/blob/e77910cccc56d67a02ea09f8a34128c184d75e02/www/js/onboarding/PrivacyPolicy.tsx#L11), which currently will show the text for autogen if that attribute exists and is true, and the text about not autogen all other times, which after looking into it might be the correct behavior?

**Comment by shankari** [comment]
Fixed in https://github.com/e-mission/nrel-openpath-join-page/pull/24
