### ISSUE TITLE
⛽ + ⚡  Adding "Hybrid" to the default list of modes?

### ISSUE THREAD

**Issue by Abby-Wheelis** [e-mission/e-mission-docs#1013]
We have received a request to add "hybrid car" to the list of available modes from a program admin with a participant who would like to be able to label as such. 

Should we add this to the "default" list of modes, or just to the list for that study?

Considerations:
- will this make the default list too long? I think it would take us from 17-19 options
- what about the idea that we'd let people input their cars? (would we want to wait for this, or just know that the list could shrink when we enable this option?)

It sounds like this particular participant is labeling their trips in the hybrid vehicle as "ecar". I also drive a hybrid, but label my trips in that vehicle as "gas car". I'd be interested to see where the estimated impact of "hybrid" falls in relation to "ecar" and "gas car". It might be hard to pick a number since the range of hybrids on the road is relatively broad (I'm thinking of plugin vs not plugin hybrids in particular).

**Comment by Abby-Wheelis** [comment]
In our meeting today, we decided to move forward with adding "hybrid car alone" and "hybrid car shared" based on the request and the observation that there are a fair number of hybrid cars on the market now. For the kgCo2/km metric, I plan to find an estimate of the average mpg of hybrids on the road, and use that to calculate. Ideally, I would take a weighted average of hybrids on the road in the US, but I'm not sure if I'll be able to get enough information to do that accurately.

**Comment by Abby-Wheelis** [comment]
Based on [this chart](https://afdc.energy.gov/data/10301), the top hybrid vehicle sales in the US in recent years are the Toyota RAV4, Ford Fusion, and Toyota Prius. 

The fuel economy of those cars (2019 model) is around 40, 30, and 50, respectively. I took all those estimates from [https://www.fueleconomy.gov/](https://www.fueleconomy.gov/). That yields an average of 40mpg, which seems like it might be about - big range but anecdotally my 2011 Prius gets around 40mpg, depending on the type of driving (highway < city).

That would then be 0.025 gallons/mile or 0.0155 gallons/km.

When I put that into it yields 0.138 kgCo2/km - falling below our standard car of  0.1659 kgCo2/km. 

Any thoughts on this number? I can always re-work it, but will begin drafting the PR for this change.

**Comment by Abby-Wheelis** [comment]
Hybrid car has been added! See [phone PR](https://github.com/e-mission/e-mission-phone/pull/1075) and [translate PR](https://github.com/e-mission/e-mission-translate/pull/51)

I verified in the emulator that these options show up when no 'label-options' is specified in the config by taking that field out of the config in my branch, pointing the phone code at the `downloadURL` for that branch, and logging out and back in. As shown below, hybrid is now an option by default.

<img src="https://github.com/e-mission/e-mission-docs/assets/54848919/75e2799e-de44-4432-80c8-a8cac43b818f" width="250" />

I checked in Spanish as well, and noticed 🌐 Moped as one of the options, signaling that we're missing the translation. I remember seeing [this comment](https://github.com/e-mission/e-mission-translate/pull/47#discussion_r1371091343) that moped is not a standard mode, but it is present in both `en.json` and `label-options.json.sample` in `e-mission-phone`. @shankari @sebastianbarry I could be looking at the wrong "default labels" file, so feel free to correct me, but we should remove Moped from both of those places if it's not a standard mode, right?

**Comment by shankari** [comment]
We should remove moped from both those places. I remember flagging this in 
https://github.com/e-mission/e-mission-translate/pull/47#discussion_r1371091343
but it looks like only the translation was fixed, not the original label mapping.
@sebastianbarry please fix this ASAP
