### ISSUE TITLE
Estimate code coverage for the current frontend codebase

### ISSUE THREAD

**Issue by jiji14** [e-mission/e-mission-docs#1023]
## Estimate code coverage for the current frontend codebase
We've made significant progress in setting up unit tests for **e-emission-phone** and are actively writing test cases as we overhaul Angular services. To gauge the effectiveness of our test suite, we aim to estimate the code coverage.

You can find test codes [here](https://github.com/e-mission/e-mission-phone/tree/master/www/__tests__)

### Related Issue
[Estimate code coverage for the current server codebase](https://github.com/e-mission/e-mission-docs/issues/729)

<br />

**I've researched 3 well-known code coverage tools that work with jest and GitHub actions.**

<br />

### jest-coverage
Jest-coverage is a tool that extends **Jest** to provide code coverage reports. To generate code coverage reports using Jest, we can run tests with coverage using the `--coverage` flag. 

**[ Report Sample ]**

* This screenshot is our test case.
<br />

![Screenshot 2023-10-26 at 11 31 17 AM](https://github.com/e-mission/e-mission-docs/assets/47590587/4721a28b-2361-46f2-893d-5130c520cb71)

1. **Function coverage**: Determines if each function has been called.
2. **Statement coverage**: Checks if each statement in the program has been executed.
3. **Branch coverage**: Evaluates whether each branch of control structures, like if and case statements, has been executed.
4. **Line coverage**: Verifies if each executable line in the source file has been executed.

**[ Pros ]**
1. Integration with Jest. (No need for complex setup)

**[ Cons]**
1. Limited to Jest, limiting integration with other testing frameworks.
2. Reports are somewhat simple compared to other options

**[ Resources ]**
[jest-coverage](https://www.valentinog.com/blog/jest-coverage/)
[stackoverflow - jest-coverage issue](https://stackoverflow.com/questions/74764070/jest-test-coverage-gives-100-coverage-for-modules-that-have-no-tests-at-all)

<br />

### Codecov
Codecov is an all-in-one code coverage reporting solution that focuses on **integration** and encourages healthy **pull requests**. It delivers coverage metrics directly into the modern workflow, particularly in pull requests.

**[ Report Sample ]**
<img width="999" alt="Screenshot 2023-10-26 at 11 20 01 AM" src="https://github.com/e-mission/e-mission-docs/assets/47590587/d372581e-536a-40c1-a61a-89010b745e5b">
1. **hit**: indicates that the source code was executed by the test suite.
2. **miss**: indicates that the source code was not executed by the test suite.
3. **partial**: indicates that the source code was not fully executed by the test suite; there are remaining branches that were not executed.

**[ Pros ]**
1. Forever **Free** for Open Source 😸 
2. Provides detailed and customizable reports

**[ Cons]**
1. Initial setup can be somewhat complex and may require additional time.

**[ Resources ]**
[codecov.io](https://about.codecov.io/codecov-free-trial/?utm_source=google&utm_medium=cpc&utm_campaign=USCA_Search_Brand_Alpha&utm_content=g&utm_term=codecov&gclid=CjwKCAjwnOipBhBQEiwACyGLuqusXr_KpX9BAYS3C1znw-Jhgr60ec3txcpSSRps7scEhscWCjefNRoCMrgQAvD_BwE&utm_id=%7B20554362434%7D&utm_campaign=&utm_source=google&utm_medium=cpc&utm_term=codecov&utm_department=marketing)

<br />

### Istanbul
Istanbul instruments your ES5 and ES2015+ JavaScript code with line counters, allowing you to track code coverage based on unit tests.

**[ Pros ]**
1. Offers more options for report formats and configuration compared to jest-coverage.

**[ Cons]**
1. For TypeScript, transpilation to JavaScript is required, introducing an additional step.

**[ Report Sample ]**
<img width="1147" alt="Screenshot 2023-10-25 at 11 46 44 AM" src="https://github.com/e-mission/e-mission-docs/assets/47590587/d9644498-cd94-435b-8bd5-446b3194f5d0">

**[ Resources ]**
[Gudie for instanbul](https://www.pluralsight.com/guides/using-istanbul-for-code-coverage-in-react)
<br />

### Jest-coverage VS Codecov VS Istanbul
<img width="782" alt="Screenshot 2023-10-26 at 11 54 37 AM" src="https://github.com/e-mission/e-mission-docs/assets/47590587/56397853-45ec-4948-a9a5-ca7413bfc2e3">

* I did not consider `JS Coverage` as an option because it lacks support for CI/CD integration, and its last update is outdated.

**[ Resources ]**
[code-coverage-js-in-2023](https://axolo.co/blog/p/code-coverage-js-in-2023#)

<br />

**Comment by shankari** [comment]
@jiji14 before we use any third party (hosted) tools, we have to get approval from NREL IT.
GitHub is pre-approved, which is why we are able to use GitHub and GH Actions.
I agree that codecov seems cool, but we should get started with the process to request approval immediately
It may be that it is also pre-approved (best case scenario!)

If not, Jest seems pretty good, but does it cover end-to-end testing? I am not sure that code coverage tools will do well with end-to-end testing anyway since they work at the code lines level.

**Comment by jiji14** [comment]
@shankari 
It **does not cover** end-to-end testing because code **coverage tools check the source code line by line**, as you mentioned. End-to-end testing is a UI-level automation, not code-level. However, there are other tools available for checking end-to-end testing coverage (although I haven't delved deeply into this).

I also agree that `jest-coverage` is a good alternative if we can't get approval with `codecov`.

**Comment by shankari** [comment]
@jiji14 sounds good. What additional feedback would you like from me?

**Comment by jiji14** [comment]
@shankari 
Nothing for now. I will contact IT and will update how it goes!

**Comment by jiji14** [comment]
@shankari 

I need to submit a `Security Impact Analysis.` I am wondering who the `System owner` will be and `how many members` will have access to the account.

**Comment by shankari** [comment]
@jiji14 I am 99% sure you don't need to submit an SIA. The SIA is for systems that we want to run internally, which is why they are asking for a system owner. We want to use an external service, which would be a technology exception. Please cc me on the discussion with IT if needed and I can clarify if there are any questions.

**Comment by jiji14** [comment]
@shankari 

I received approval from the IT team. Should I reach out to Codecov directly to request access for the open-source project? Additionally, I think you should sign up with your GitHub handle to set up Codecov in the e-mission-phone project. After I signed up with my GitHub handle, I could only see the repositories that I owned. You can find the setup documentation [here](https://docs.codecov.com/docs).


![Image](https://github.com/e-mission/e-mission-docs/assets/47590587/5109dd86-db76-445a-919a-bc6f8da10ff7)

**Comment by shankari** [comment]
@jiji14 can you add me to the ticket related to the this, so I can have the approval for the record?
I will sign up for codecov over the weekend 😄

**Comment by shankari** [comment]
@jiji14 thanks for adding me to the ticket. Signing up for codecov now...

**Comment by shankari** [comment]
Signed up!

**Comment by jiji14** [comment]
@shankari 
Can you please add the repository token to the e-mission-phone repository?

Here are the steps:

1. Sign in to the Codecov website.

2. Click on the e-mission-phone repository in dashboard.

![Image](https://github.com/e-mission/e-mission-docs/assets/47590587/22381272-b33b-485c-9edb-77ff835d69c3)

3. Copy the token.

![Image](https://github.com/e-mission/e-mission-docs/assets/47590587/fba68832-bcaf-42c2-8681-7f98dbad5fbd)

4. Go to the repository settings and paste the token in Settings > Security and Variables > Actions.
![Image](https://github.com/e-mission/e-mission-docs/assets/47590587/dcd1d7a9-571a-4138-ba68-654a6e50e324)


After you add the token, I will submit Codecov Github action PR.
Thank you!

**Comment by shankari** [comment]
Added the token
