### ISSUE TITLE
UI: White page on Dashboard when no end date is selected

### ISSUE THREAD

**Issue by TTalex** [e-mission/e-mission-docs#1027]
Hello,

I discovered an odd behavior on OpenPath Android v1.5.7.

It happens on the dashboard, when selecting a period, only setting the start date and saving. The screen turns to white.

I would expect an unselected end date to be automatically set to today.

https://github.com/e-mission/e-mission-docs/assets/7023229/1096009b-caf1-4456-81fa-56a60a4af60e

Sorry if this was already reported, I did not find any related issue.

Have a nice week.

**Comment by JGreenlee** [comment]
Thanks for reporting! Confirmed as reproducible

**Comment by the-bay-kay** [comment]
Just opened a PR with a fix for this issue!  I've currently got it set to merge into Jack's migration wrapup (since it's the most up-to-date branch), but can change that if folks would like.

**Comment by JGreenlee** [comment]
This can be closed; the fix has been on `master` + production for some time now

**Comment by TTalex** [comment]
Thanks :)
