### ISSUE TITLE
❓ `LocalNotify` is not used anymore (is that ok?)

### ISSUE THREAD

**Issue by JGreenlee** [e-mission/e-mission-docs#1028]
By my count, there is only one Angular service rewrite left that doesn't already have an open PR (yay! 🎉), and we are not even sure that we need it!

@jiji14 was going to begin on `LocalNotify` but could not find any instance of the service being invoked. I tried also, and found that `LocalNotify` is injected by `SplashCtrl`, which has not been in use since the onboarding changes.
As a result, `LocalNotify` is still initialized on `master` but not on `service_rewrite_2023`.

Since these changes, we have not noticed any regressions regarding local notifications, so this *might* be completely fine. When a permission is revoked, we still get prompted to open the app and the UX of doing so is smooth, so the permissions notifications have not seen regressions at least.

But I want to make sure there are no regressions in the 'reminders' before saying it's ok to let go of `LocalNotify`.

**Comment by JGreenlee** [comment]
### Verdict:
'Reminders', and all other local notifications, are working fine even though `LocalNotify` is not in use. `LocalNotify

**Comment by shankari** [comment]
@JGreenlee 

> 'Reminders', and all other local notifications, are working fine even though LocalNotify is not in use anymore.

Did we actually test against 'Reminders'? If so, please document here.
We will likely use 'Reminders' extensively in a few upcoming projects, but they are not enabled in open access and most of the staging environments, so I don't want to rely solely on "we haven't noticed any regressions".

**Comment by JGreenlee** [comment]
I tested it in the devapp by spinning up a new OPcode on the 'timeuse' configuration, changing the 'reminder time' to a few minutes from the current time and minimizing the app. A notification came at the specified time, and when clicked, it launched the app.

To test it on staging, we need new OPcodes or we need to make the reminder scheme last for more than ~1 week

**Comment by shankari** [comment]
Interesting. I think we can also test by uninstalling, editing your opcode's profile to remove the reminder scheme and then reinstalling. That will keep the data but set the notifications, right?

**Comment by JGreenlee** [comment]
After the reminder settings were cleared for my opcode, I tested again by adjusting the 'reminder time' and waiting for a notification to arrive. It came as expected and was functional. I did not need to uninstall and reinstall.

Just to be sure, I will keep monitoring through Friday to see that the notifications keep coming according to the scheme.

<hr>

I did notice one other issue, though: the list of "upcoming notifications" in the developer zone is not in order. It should be sorted by time (soonest first)
<img src=https://github.com/e-mission/e-mission-docs/assets/15843932/3855dee0-c475-470c-b435-3892a7d93439 width=300>

Maybe this is something @sebastianbarry can address while working on https://github.com/e-mission/e-mission-phone/pull/1092

**Comment by sebastianbarry** [comment]
Fixed in https://github.com/e-mission/e-mission-phone/pull/1092/commits/0ee468a2cd65a531c1c38f10070a79acc67f1514

**Comment by JGreenlee** [comment]
> Just to be sure, I will keep monitoring through Friday to see that the notifications keep coming according to the scheme.

The reminders ran their course on my test phone according to the scheme, with the last one on Friday. I think we are good here.
