### ISSUE TITLE
🚑 labels "lost" and performance issues when labeling with current staging

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-docs#1034]
I have noticed two issues while labeling with the new release.

1. Labeling is consistently slow
2. Labels are sometimes "lost" and only restored after reload. This only happened once, when I was on cellular data (at the Santa Clara Caltrain station).

I have uploaded videos and logs to an internal issue to avoid having to go through and remove all personal information.
After investigation there, we should add a summary here.

**Comment by JGreenlee** [comment]
(1) is getting fixed by https://github.com/e-mission/e-mission-phone/pull/1106. Labeling is now quite snappy on that branch.

**Comment by JGreenlee** [comment]
3. It takes two taps of the "yellow checkmark" to mark a pair of inferred labels as verified
4. When an addition / timeuse survey response is recorded, the timestamps initially show up as blank

**Comment by JGreenlee** [comment]
(2) and (3) are fixed in https://github.com/e-mission/e-mission-phone/pull/1106
