### ISSUE TITLE
🐛 `background/bluetooth_ble` entries disappear once they get to the server

### ISSUE THREAD

**Issue by JGreenlee** [e-mission/e-mission-docs#1067]
> I have yet to see a trip show up on my iPhone, which is what I'm testing dfc-fermata on.
> As far as I could tell, the state remained in ONGOING_TRIP the entire time I was away from home, even when I went into the store and my beacon was still in my car. Only when I got home and went inside (leaving the beacon in my car) did it transition and now says WAITING_FOR_TRIP_START.
> 
> So, I thought that a very long draft trip would show up, but I don't see one
> 
> Logs on the phone showed that there were bluetooth_ble entries (a LOT of them). Evidently, they weren't synced because when I logged into that opcode from an emulator and queried for them, there were none
> 
> Now they are gone from the phone, and seemingly gone forever

<hr>

May be due to:

```
2024-04-16 00:21:03,698:WARNING:140347683919680:Got error No module named 'emission.net.usercache.formatters.ios.bluetooth_ble' while saving entry AttrDict({'_id': ObjectId('661db723610916071b576ed5'), 'user_id': UUID('4acedfd2-de6a-4623-a968-9d5046a8573b'), 'metadata': {'time_zone': 'America/New_York', 'plugin': 'none', 'write_ts': 1713216469.099677, 'platform': 'ios', 'read_ts': 0, 'key': 'background/bluetooth_ble', 'type': 'sensor-data'}, 'data': {'major': 57280, 'minor': 65520, 'rssi': -84, 'eventType': 'RANGE_UPDATE', 'ts': 1713216469.097594, 'uuid': 'BF3DF3B1-6E46-35FA-86E5-927C95DD096C', 'proximity': 'ProximityFar', 'accuracy': 22.76727203664656}}) -> None
```

**Comment by the-bay-kay** [comment]
Observations about the iOS Code:
- [this](https://github.com/e-mission/e-mission-data-collection/blob/034b7a0cb2d9859da40bfd940d410ab38a57bacf/src/ios/Location/TripDiaryDelegate.m#L367C68-L367C81) is the line that stores the bluetooth region data into the BuiltinUserCache.  As we can see from the following logs...
<img width="1529" alt="image" src="https://github.com/e-mission/e-mission-docs/assets/98350084/35ec7b8c-1d27-4d06-9d85-b05c28e7e436">

We are at the very least successfully receiving notifications via `didRangeBeacons`.

**Comment by shankari** [comment]
This is because the server for this deployment had not yet been updated

```
$ ./e-mission-py.bash
>>> edb.get_timeseries_error_db().distinct("metadata.key")
['statemachine/transition', 'background/bluetooth_ble']
```
So the timeseries_error DB has the transition and ble entries

```
>>> edb.get_timeseries_error_db().distinct("user_id")
[UUID('118bcfb4-19b1-4d92-b02e-7d5bfc1d6032'), UUID('c8e6ad49-c7a5-4650-b1ad-c61747c761fe'), UUID('170c02b7-5937-4227-9128-5da1bcdfe8c6'), UUID('97b8efad-8c28-4ffa-870b-828de7a1cb03'), UUID('29627e30-ca62-494e-af8c-b9de8e8f0f89'), UUID('e61c0e74-82db-42aa-b3ea-ba07392efcd2'), UUID('11fc1417-0776-47fc-b306-5484c34f6138'), UUID('dfa77402-da79-4e39-9c64-7bebd1f8b410'), UUID('50fcffc9-16c7-4153-a548-1ffb3f6c379a'), UUID('519df704-2f64-400d-b84e-df6e6143dae0'), UUID('629e97a4-601a-4954-80a6-ce3c0bca5579'), UUID('10fd95ea-5065-4e1d-a861-30dc80590bbf'), UUID('4acedfd2-de6a-4623-a968-9d5046a8573b')]
```

And after fixing them, we may need to reset the pipeline for these users

**Comment by shankari** [comment]
Ran the script, everything is copied over, no errors left.


```
>>> edb.get_timeseries_error_db().distinct("metadata.key")
[]
```

Now resetting the pipeline, and re-running it for at least the ones that have BLE beacons.
These are the users we will re-run the pipeline for

```
>>> edb.get_usercache_db().find({"metadata.key": "background/bluetooth_ble"}).distinct("user_id")
[UUID('c8e6ad49-c7a5-4650-b1ad-c61747c761fe'), UUID('11fc1417-0776-47fc-b306-5484c34f6138'), UUID('629e97a4-601a-4954-80a6-ce3c0bca5579'), UUID('dfa77402-da79-4e39-9c64-7bebd1f8b410'), UUID('10fd95ea-5065-4e1d-a861-30dc80590bbf'), UUID('4acedfd2-de6a-4623-a968-9d5046a8573b')]
```

**Comment by shankari** [comment]
Reset pipelines for 13 users. Some of them were only the `None` transition errors.
6 users had BLE beacon information, manually ran the pipeline for them

One of them had obsolete transitions which we are not going to fix

```
Got error 'T_ENTERED_BLE_RANGE' while saving entry AttrDict({'_id': ObjectId('661b29806109164d65102979'), 'user_id': UUID('dfa77402-da79-4e39-9c64-7bebd1f8b410'), 'metadata': {'time_zone': 'America/Los_Angeles', 'plugin': 'none', 'write_ts': 1713041202.864598, 'platform': 'ios', 'read_ts': 0, 'key': 'statemachine/transition', 'type': 'message'}, 'data': {'currState': 'STATE_ONGOING_TRIP', 'transition': 'T_ENTERED_BLE_RANGE', 'ts': 1713041202.86425}}) -> None
Got error 'T_ENTERED_BLE_RANGE' while saving entry AttrDict({'_id': ObjectId('661b29806109164d6510297b'), 'user_id': UUID('dfa77402-da79-4e39-9c64-7bebd1f8b410'), 'metadata': {'time_zone': 'America/Los_Angeles', 'plugin': 'none', 'write_ts': 1713041203.863857, 'platform': 'ios', 'read_ts': 0, 'key': 'statemachine/transition', 'type': 'message'}, 'data': {'currState': 'STATE_ONGOING_TRIP', 'transition': 'T_ENTERED_BLE_RANGE', 'ts': 1713041203.863525}}) -> None
Got error 'T_ENTERED_BLE_RANGE' while saving entry AttrDict({'_id': ObjectId('661b29806109164d6510297d'), 'user_id': UUID('dfa77402-da79-4e39-9c64-7bebd1f8b410'), 'metadata': {'time_zone': 'America/Los_Angeles', 'plugin': 'none', 'write_ts': 1713041204.864588, 'platform': 'ios', 'read_ts': 0, 'key': 'statemachine/transition', 'type': 'message'}, 'data': {'currState': 'STATE_ONGOING_TRIP', 'transition': 'T_ENTERED_BLE_RANGE', 'ts': 1713041204.864253}}) -> None
```

**Comment by JGreenlee** [comment]
## `No vehicle identity found for major:minor pair 0000:0000`

<img src=https://github.com/e-mission/e-mission-docs/assets/15843932/50555164-2858-4db6-a6ef-213700b79a92 width=360>

<hr>

I am pretty sure this is from old simulated entries, before https://github.com/e-mission/e-mission-data-collection/pull/223, where major and minor were not filled in correctly

**Comment by JGreenlee** [comment]
After dismissing that popup (for me, there were 5 of them), it looks to be working!

<hr>

Recent trips I've taken (the beacon was with me)

<img src=https://github.com/e-mission/e-mission-docs/assets/15843932/fb6b9d06-c563-4e36-83c3-6bd5bb994937 width=330>

<hr>

Some older trips (beacon not with me)

<img src=
https://github.com/e-mission/e-mission-docs/assets/15843932/9cb8e2c7-203f-460c-8703-9db3dd588d10 width=330>

**Comment by shankari** [comment]
I can delete those (this is all test data, so I have no qualms about mucking around with it).
Let me do that now.

**Comment by shankari** [comment]
There are 127 of these spurious entries. Deleting them...

```
>>> edb.get_timeseries_db().count_documents({"metadata.key": "background/bluetooth_ble", "data.major": 0, "data.minor": 0})
127

>>> edb.get_timeseries_db().delete_many({"metadata.key": "background/bluetooth_ble", "data.major": 0, "data.minor": 0})
<pymongo.results.DeleteResult object at 0x7f38ea0dabb0>
>>> edb.get_timeseries_db().count_documents({"metadata.key": "background/bluetooth_ble", "data.major": 0, "data.minor": 0})
0
```

Done.

**Comment by JGreenlee** [comment]
Resolved by server upgrade and manually deleting the bad entries
