### ISSUE TITLE
🚒 Log sharing broken on IOS

### ISSUE THREAD

**Issue by Abby-Wheelis** [e-mission/e-mission-docs#1074]
Before the meeting today, I was trying to help someone send us their logs from an iPhone, but the attachment did not appear in the email draft. Checking on my iPhone, the log sharing also does not generate the logs attachment!

**Comment by shankari** [comment]
Fixed in https://github.com/e-mission/e-mission-phone/pull/1160
At least on a physical phone using MailDrop, this works reliably.
