### ISSUE TITLE
Should `e-mission-common` be its own repo or a subdirectory of `e-mission-server` ?

### ISSUE THREAD

**Issue by JGreenlee** [e-mission/e-mission-docs#1078]
`e-mission-common` is currently set up as a separate repo that exposes itself as both a Python package and a JS package. It's included by github URL, both in `e-mission-phone` as an npm dependency and in `e-mission-server` as a pip dependency.

This works, but it causes a few friction points in the dev workflow.

- If I want to work on `e-mission-common` and use those changes on my local instance of `e-mission-server`, I have to either commit the changes to a test branch and temporarily change `e-mission-server` to use that branch for the dependency; OR I have to continually copy-paste my changes into the place where the `e-mission-common` dependency gets installed
- Whenever my changes are pushed to `e-mission-common`, they won't reflect on the local `e-mission-server` until I re-run `setup.sh` (which can take a bit of time).
- I have to manage the versioning of `e-mission-common` separately from the versioning of `e-mission-phone` and `e-mission-server`; I create a new release and we have to update the version numbers in each place `e-mission-common` is included as a dependency.

The local dev workflow for `e-mission-phone` is not as bad because we can use `npm link`. I don't know of something similar for pip dependencies included through conda.
So far I've been the only one making changes to `e-mission-common` and just been dealing with this, but we are going to have more people collaborating on it soon and I wonder if the workflow can be simplified.

Instead of being a separate repo, the common code could be in `e-mission-server` under `emission.common`. The output JS could be in a subdirectory.

The workflow to use common code on `e-mission-server` would be much simpler, and the dashboards would still be able to use "common" code because they are built on top of `e-mission-server`.

However, I wonder if this make a bit less sense organizationally. Although all the "source" files would still be Python, there would technically be JS files in `e-mission-server`.

**Comment by shankari** [comment]
> The local dev workflow for e-mission-phone is not as bad because we can use npm link. I don't know of something similar for pip dependencies included through conda.

I think that finding the equivalent for `pip` would be a better option that checking the code (and the generated javascript) into e-mission-common. `pip` has an option for editable installs which seems like what we want
https://pip.pypa.io/en/stable/topics/local-project-installs/#editable-installs

A native approach would be to, for the packages we want to develop, uninstall the version from conda and reinstall with the `-e` option. You can then edit your copy of the package as much as you want. The rest of us will pull from the git package when we pull after your changes are merged.

If that doesn't work, I would like to explore `git submodule` before putting javascript into the server repo.

**Comment by JGreenlee** [comment]
Good find. `pip install -e ../e-mission-common` worked for me and will make the dev workflow much smoother.

When I update the README of `e-mission-common` I will describe how to do that as well as `npm link`.
