### ISSUE TITLE
Anaconda Cheat Sheet offer

### ISSUE THREAD

**Issue by MetroPietro** [e-mission/e-mission-docs#23]
After downloading the install-script for Anconda from https://www.anaconda.com/download/#download, an overlay-popup opens, offering to email me the Anaconda "Cheat Sheet" if I provide my email. Should we take up this offer? Will Anaconda then put me on their email list?

**Comment by shankari** [comment]
@MetroPietro Pretty sure they will put you on their email list. But they are not very spammy, and they are giving me a free service, so I feel I owe them something, and I gave them my email. YMMV.

**Comment by shankari** [comment]
Don't think this needs to make it into the docs
