### ISSUE TITLE
App is taking too much time to download

### ISSUE THREAD

**Issue by unaissait** [e-mission/e-mission-docs#279]
![screenshot_2018-07-05-20-26-33-99](https://user-images.githubusercontent.com/40853052/42332366-6633bea2-8095-11e8-8359-85a62ded90c8.png)
![screenshot_2018-07-05-20-36-12-38](https://user-images.githubusercontent.com/40853052/42332393-77a10df2-8095-11e8-9edd-f9030bf10402.png)
above address was used for connecting.

**Comment by shankari** [comment]
no updates for 6 months, no additional reports. closing as stale.
