### ISSUE TITLE
Interactive trip-end survey

### ISSUE THREAD

**Issue by atton16** [e-mission/e-mission-docs#281]
Hi,

We have re-enabled the disabled trip-end survey to ask user to confirm the mode of transportation of each trip. We have found that survey allow us to ask the question to use but it won't store the selected answer. If use tap on the same question (that were answered before) it does not show the previous answer.

I am wondering if there is any branch that already implemented this feature.

Cheers

**Comment by shankari** [comment]
@atton16 @asiripanich given that you had found the place to make this change, I was expecting a PR fairly soon. But haven't seen one although it has been ~ 11 days. Are you stuck on anything else?

**Comment by shankari** [comment]
@atton16 @asiripanich, any updates?

**Comment by asiripanich** [comment]
@shankari I will get back to you once I've talked with @atton16 .

**Comment by atton16** [comment]
We are trying to get the mode/purpose responses in-synced with the server in background.

We tried putting `UnifiedDataLoader.getUnifiedMessagesForInterval` in `Timeline.UPDATE_DONE` event handler so that every time we the diary list get updated the mode/purpose responses should be synced. For some reason, the `Reading from server` unexpectedly show up even when I tried to click on the `choose mode`/`choose purpose` button.

So I dig a bit deeper by instead of doing what I did above, I put `UnifiedDataLoader.getUnifiedMessagesForInterval` inside `$scope.openPurposePopover` / `$scope.openModePopover`. Still, `Reading from server` showed up.

That's why I asked if the `UnifiedDataLoader.getUnifiedMessagesForInterval` somehow trigger `Reading from server`.

**Comment by shankari** [comment]
@atton16 in my original comment (https://github.com/e-mission/e-mission-docs/issues/281#issuecomment-443484106), I suggested

> I think fixing the second issue should be as simple as replacing `$window.cordova.plugins.BEMUserCache.getAllMessages` with `UnifiedDataLoader.getUnifiedMessagesForInterval` from `www/js/services.js`

Did you try that? What happened?

> So far, I am still not certain why the **Reading from server** showed up because the fact that the code does not contain anything related to UI just confirmed it.

Can you send a PR with the changes that you are trying out? It is much easier to review code changes directly than to review a 2-line textual description of the code changes. We can always close the PR if it turns out to not be the right approach.

**Comment by shankari** [comment]
> Can you send a PR with the changes that you are trying out? It is much easier to review code changes directly than to review a 2-line textual description of the code changes. We can always close the PR if it turns out to not be the right approach.

And (as I found while creating https://github.com/e-mission/cordova-unified-logger/pull/28) github now supports _draft_ pull requests, so you don't have to worry that you are publishing an incomplete PR...

**Comment by shankari** [comment]
Closing this since https://github.com/e-mission/e-mission-phone/pull/528 was merged to the branch and is now being merged to master (https://github.com/e-mission/e-mission-phone/pull/553)
