### ISSUE TITLE
Simulator display not aligning with phone display

### ISSUE THREAD

**Issue by sam11b** [e-mission/e-mission-docs#319]
When I try going to the diary page on the simulator my trips from any day are not displaying. However, when I look at the screen on my phone, the trips display normally (though uncleaned). I tried running the debugger and it seems that the app is reporting that I have taken zero trips for the day despite the fact that I've taken multiple. Could the app simply be timing out and giving up and just returning zero trips? I ensured that the simulator is properly aligned with my uuID and that no changes were made that could have caused this display error. I'll attach the results from the debugger below. I'm not receiving an HTTP status error so I'm assuming it isn't a server issue? Thanks!
<img width="1001" alt="screen shot 2019-02-20 at 12 02 47 pm" src="https://user-images.githubusercontent.com/23513222/53123183-5ea17f80-350d-11e9-83fb-c2206d089436.png">

**Comment by shankari** [comment]
which server are you connecting to? check the `www/json/connectionConfig.json`

**Comment by shankari** [comment]
you can also check the server logs to see whether your calls from the emulator are making it to the server.

**Comment by sam11b** [comment]
Right now I'm connected to port 80. I attempted switching to port 8080 and got the same results.

**Comment by shankari** [comment]
port 80 on which host? What does the developer zone in the profile show?

**Comment by shankari** [comment]
@sam11b I believe this was resolved. can you please update with the fix and then close?

**Comment by shankari** [comment]
Closing this without waiting for @sam11b
