### ISSUE TITLE
Trying to release apk file out of cordova

### ISSUE THREAD

**Issue by deepalics0044** [e-mission/e-mission-docs#320]
With respect to [https://github.com/e-mission/e-mission-docs/blob/master/docs/e-mission-phone/create_a_new_custom_client.md](url)
I installed node.js, cordova and ionic framework and then jumped to the e-mission-ui directory. 
`deepali@deepali-HP-Pro-3090-Microtower-PC:~/e-mission-ui-final$ cordova emulate android
The platform "android" does not appear to have been added to this project.`

**Comment by shankari** [comment]
can you put the output for each of the installation instructions. There are more steps than then installing node, cordova and ionic.

**Comment by deepalics0044** [comment]
if that's installing gradle, I did install it.
`
deepali@deepali-HP-Pro-3090-Microtower-PC:~/e-mission-ui-final$ export PATH=$PATH:/Downloads/gradle-5.2.1/bin
deepali@deepali-HP-Pro-3090-Microtower-PC:~/e-mission-ui-final$ cordova emulate android
The platform "android" does not appear to have been added to this project.
`

**Comment by shankari** [comment]
No that is not just installing gradle. Can you put a link to the instruction steps that you are following?

**Comment by deepalics0044** [comment]
while trying to emulate android I get this error -

`BUILD FAILED in 3s
(node:16938) UnhandledPromiseRejectionWarning: Error: /home/deepali/e-mission-ui-final/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':CordovaLib'.
> You have not accepted the license agreements of the following SDK components:
  [Android SDK Platform 27, Android SDK Build-Tools 26.0.2].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
    at ChildProcess.whenDone (/home/deepali/e-mission-ui-final/platforms/android/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
(node:16938) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16938) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by shankari** [comment]
This is not an e-mission issue or even a cordova issue. The error message describes the fix - you need to use the Android SDK manager to accept the license agreements and complete the installation process.

```
You have not accepted the license agreements of the following SDK components:
[Android SDK Platform 27, Android SDK Build-Tools 26.0.2].
Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
```

**Comment by deepalics0044** [comment]
But 
`deepali@deepali-HP-Pro-3090-Microtower-PC:~/Android/Sdk/tools/bin$ ./sdkmanager --licenses
Warning: File /home/deepali/.android/repositories.cfg could not be loaded.      
All SDK package licenses accepted.======] 100% Computing updates...             

`

**Comment by shankari** [comment]
I am sorry, I can't really help you debug this in much greater detail since it has nothing to do with e-mission, or even cordova. This is related to your install of the Android SDK and that is not my code.

If one of the techniques for installing the licenses didn't work, try another. 
Ask on stackoverflow or the android forums.
Try opening the sdk manager UI and see if you can find something there....

**Comment by deepalics0044** [comment]
Okay I'll do that.

**Comment by deepalics0044** [comment]
I wasn't exporting the right Sdk directory. I managed to export android build e-mission folder in android-studio.

**Comment by shankari** [comment]
Great! So now you need to change the UI to your branch...
