### ISSUE TITLE
Configure link incorrect

### ISSUE THREAD

**Issue by sam11b** [e-mission/e-mission-docs#33]
Where can I find the correct link for configuration? This link sends you just back to the server.

**Comment by shankari** [comment]
@sam11b which configuration link? There are many parts to configure...

**Comment by sam11b** [comment]
For more details on configuring an auth method, see https://github.com/e-mission/e-mission-server/wiki/Configuring-authentication

Shouldn't the link be: https://github.com/e-mission/e-mission-docs/blob/master/docs/e-mission-both/configuring_authentication.md ?

**Comment by shankari** [comment]
yes. The path was not changed when we moved from the wiki -> the separate repository.
There is an issue out to fix all links #10, but @brianmickel is no longer working on this project, so doesn't have time to work on it.
So we just need to fix the links piecemeal.

If you would send a PR to fix this link, that would be great!
