### ISSUE TITLE
Location tracking off/on still broken on android

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-docs#336]
Reported by @hmharvey. She turned location services off on Tuesday night and did not see any trips on Wednesday.

**Comment by shankari** [comment]
So here's what I see from the logs

We got a `MODE_CHANGED` on Tuesday at around 20:49.

```
25691,1551847763.665,2019-03-05 20:49:23.665000-07:53,"TripDiaryStateMachineRcvr : TripDiaryStateMachineReciever onReceive(android.app.ReceiverRestrictedContext@83c1517, Intent { act=android.location.MODE_CHANGED flg=0x10 cmp=edu.berkeley.eecs.embase/edu.berkeley.eecs.emission.cordova.tracker.location.TripDiaryStateMachineReceiver }) called"
```

It was passed on to the service.

```
25699,1551847763.7470002,2019-03-05 20:49:23.747000-07:53,"TripDiaryStateMachineService : handleAction(local.state.waiting_for_trip_start, android.location.MODE_CHANGED) calle"
```

which then checked the location settings

```
25684,1551847762.726,2019-03-05 20:49:22.726000-07:53,TripDiaryStateMachineService : Checking location settings for request Request[PRIORITY_HIGH_ACCURACY requested=30000ms fastest=5000ms]
```

We got back a result but then the new state was just the same.

```
25685,1551847762.7389998,2019-03-05 20:49:22.739000-07:53,TripDiaryStateMachineService : Got back result com.google.android.gms.internal.zzasp$1@339eaf7
25686,1551847762.7410002,2019-03-05 20:49:22.741000-07:53,TripDiaryStateMachineService : newState after handling action is local.state.waiting_for_trip_start
```

If we look at the code, we expect to get a callback for the result.

```
        result.setResultCallback(new ResultCallback<LocationSettingsResult>() {
            @Override
            public void onResult(LocationSettingsResult result) {
                Log.d(ctxt, TAG, "isLocationUsable() "+result.getLocationSettingsStates().isLocationUsable());
                final Status status = result.getStatus();
..... 
```

But we never received the callback. In fact, the last two callbacks are on the 4th at the time @hmharvey was testing at her desk https://github.com/e-mission/e-mission-data-collection/issues/127#issuecomment-469160304

```
$ grep isLocationUsable /tmp/loggerDB.heather_no_geofence_exit.withdate.log | tail -n 2
16479,1551721854.7270002,2019-03-04 09:50:54.727000-07:53,TripDiaryStateMachineService : isLocationUsable() false
16887,1551721899.82,2019-03-04 09:51:39.820000-07:53,TripDiaryStateMachineService : isLocationUsable() true
```

**Comment by shankari** [comment]
@hmharvey, you got the callbacks correctly when you were testing at your desk but not when you were testing in the field. Was there anything different between the two use cases that might account for the difference?

**Comment by shankari** [comment]
Actually, the last two callbacks are from ~10am on the 4th while the testing was on midnight on the 4th. But all the previous callbacks are from around midnight. So @hmharvey, the callbacks worked at midnight on the 4th, worked around 10am on the 4th but didn't work on the 5th. Was there any difference in the way you were changing the settings?

```
15751,1551688605.131,2019-03-04 00:36:45.131000-07:53,TripDiaryStateMachineService : isLocationUsable() true
15862,1551688618.48,2019-03-04 00:36:58.480000-07:53,TripDiaryStateMachineService : isLocationUsable() false
16479,1551721854.7270002,2019-03-04 09:50:54.727000-07:53,TripDiaryStateMachineService : isLocationUsable() false
16887,1551721899.82,2019-03-04 09:51:39.820000-07:53,TripDiaryStateMachineService : isLocationUsable() true
```

**Comment by shankari** [comment]
I think that this may be an issue with how long-lived the service is. Maybe in the first case, since she was testing it actively, the OS kept the service around. But in the second case, if she turned off location services and did not launch the app again, then maybe the OS was more aggressive about killing off the service. This is going to be hard to test in the emulator; have to see if I can manually induce some memory pressure.

**Comment by hmharvey** [comment]
Sorry. If you still want my clarification: I did testing the night of the 3rd/morning of the 4th and it worked all day of the 4th and 5th. The night of the 5th was the next time I shut off location manually on my phone, had it off all night, and turned it back on the morning of the 6th before I left the house and it didn't log any trips that day.

As far as I know, I didn't do anything different. If you want I can try to turn it off for varying amounts of time and see how that affects the behavior?

**Comment by hmharvey** [comment]
Note though: The pipeline hasn't run on any trips since Monday the 4th.

**Comment by shankari** [comment]
@hmharvey the pipeline doesn't matter. Basically, the data collection and processing are separate. If the data collection is broken, no trips will be recorded. If the data processing is broken/not running, trips will be recorded, but will be in green (draft) mode. What you are seeing is that the data collection is broken.

**Comment by shankari** [comment]
> As far as I know, I didn't do anything different. If you want I can try to turn it off for varying amounts of time and see how that affects the behavior?

If I am right, it is not the amount of time, but whether you are interacting with the app and what else you are doing. So two tests could be:
- turn it off and then immediately launch the app to check the state
- turn it off but don't launch the app immediately. Check the state after ~ 5-6 hours.

**Comment by hmharvey** [comment]
I was just clarifying since the dates you listed were a little off. But sounds good, I can try that over the next day or two then.

**Comment by shankari** [comment]
> I was just clarifying since the dates you listed were a little off.

In what way were they off?

**Comment by shankari** [comment]
@hmharvey any updates on this?

**Comment by hmharvey** [comment]
Sorry about the delay. This seems to be a little hard to test because the states always appear to be correct, tracking is always on and it's in the waiting_for_trip_start state. It just doesn't end up logging trips. Relaunching the app at various time intervals doesn't seem to change anything.

**Comment by shankari** [comment]
@hmharvey couple of updates:
- I had to redo the entire MODE_CHANGED logic because the new android API (26) doesn't support implicit broadcasts
- so just wait until I upload the new apk since this is going to change dramatically anyway

**Comment by shankari** [comment]
Closing this since there is a brand new apk for testing. @hmharvey, please uninstall the version you installed from the apk before, install the current version from the play store (also version 1.2.0) and report any issues to #325
