### ISSUE TITLE
encoding error of place names in nominatim

### ISSUE THREAD

**Issue by PatGendre** [e-mission/e-mission-docs#337]
we've found an error looking at the pipeline logs.

It seems that just adding the header
`#!/usr/bin/env python`
`# coding: utf-8`

 in https://github.com/e-mission/e-mission-server/blob/master/emission/net/ext_service/geocoder/nominatim.py would correct this?

The same in the ground-truth-matching branch here
https://github.com/shankari/e-mission-server/blob/ground_truth_matching/emission/net/ext_service/transit_matching/match_stops.py ?
And maybe to check elsewhere in the code?

**Comment by shankari** [comment]
I wonder if this is a server setup issue. I am generating servers on AWS so they are set up with UTC and UTF-8 by default.

So `/etc/default/locale` has `LANG=en_US.UTF-8`. What is your server's default locale? 
Can you give me an example of a specific query that fails for you so that I can try it from my server and determine whether it works?

If so, I will update the documentation to clarify that when you set up the server, you should ensure that it is set up in UTF-8.

```
$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by PatGendre** [comment]
Hi

the /etc/default/locale is a 1-liner : 
`LANG="fr_FR.UTF-8"
`
shall we complete with all the variable you have in your file?

Sorry I could not find where the error was in the logs (Fouad, Yann? thank you if you can find the error again, it dates back from March 11 or 12 presumably),
in the intake log, though I've found many times the same places geocoded in Italy, Portugal and Idaho, I dont know why...
`2019-02-07 15:40:58,080:DEBUG:140274281658112:parsed_response = [{'place_id': '361733', 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright', 'osm_type': 'node', 'osm_id': '150978987', 'boundingbox': ['43.0057294', '43.0457294', '-115.6267478', '-115.5867478'], 'lat': '43.0257294', 'lon': '-115.6067478', 'display_name': 'Reverse, Elmore County, Idaho, USA', 'class': 'place', 'type': 'hamlet', 'importance': 0.375, 'icon': 'https://nominatim.openstreetmap.org/images/mapicons/poi_place_village.p.20.png'}, {'place_id': '6637001', 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright', 'osm_type': 'node', 'osm_id': '672404412', 'boundingbox': ['42.4171111', '42.4172111', '12.1032704', '12.1033704'], 'lat': '42.4171611', 'lon': '12.1033204', 'display_name': 'Reverse, Via Valle Piatta, Viterbo, VT, LAZ, 01100, Italia', 'class': 'amenity', 'type': 'pub', 'importance': 0.101, 'icon': 'https://nominatim.openstreetmap.org/images/mapicons/food_pub.p.20.png'}, {'place_id': '160519706', 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright', 'osm_type': 'way', 'osm_id': '369437267', 'boundingbox': ['38.703056', '38.7032984', '-9.4006996', '-9.4005378'], 'lat': '38.70322785', 'lon': '-9.40061871349235', 'display_name': 'Reverse, Paredão de Cascais, Santo António do Estoril, Monte Estoril, Estoril, Cascais e Estoril, CSC, Lisboa, Grande Lisboa, Área Metropolitana de Lisboa, 2765-249, Portugal', 'class': 'amenity', 'type': 'restaurant', 'importance': 0.101, 'icon': 'https://nominatim.openstreetmap.org/images/mapicons/food_restaurant.p.20.png'}, {'place_id': '51103322', 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright', 'osm_type': 'node', 'osm_id': '3980472520', 'boundingbox': ['43.7264975', '43.7265975', '10.4218338', '10.4219338'], 'lat': '43.7265475', 'lon': '10.4218838', 'display_name': 'Reverse, 29, Via Pietro Metastasio, La Fontina, Cafaggio, San Giuliano Terme, PI, TOS, 56124, Italia', 'class': 'amenity', 'type': 'nightclub', 'importance': 0.101}]
2019-02-07 15:40:58,080:INFO:140274281658112:Unable to pre-fill reverse geocoded information, client has to do it
2019-02-07 15:40:58,080:DEBUG:140274281658112:raw_place.user_id = d0cbf849-f9b1-4ba1-83be-1a148ec56a1e
2019-02-07 15:40:58,081:DEBUG:140274281658112:Found mapping 5c5c43704e276d5e3fbc8a19 -> 5c5c43774e276d5e3fbc8ba4, added links`

**Comment by shankari** [comment]
@PatGendre I have a question about your nominatim configuration.
The default config file does not have nominatim configured 
https://github.com/e-mission/e-mission-server/blob/master/conf/net/ext_service/nominatim.json.sample

and if there's nothing configured, then we say that the place decoding should happen on the client
https://github.com/e-mission/e-mission-server/blob/master/emission/net/ext_service/geocoder/nominatim.py#L26

so it is not clear which nominatim server you are making calls to if you didn't configure anything...

**Comment by shankari** [comment]
It looks like we also don't log what is the query we send, which would be useful to debug this, since we could run the query manually and see what the results are

Can you apply this patch and see what the actual URL is? I've also attached the patch as a file.

```
diff --git a/emission/net/ext_service/geocoder/nominatim.py b/emission/net/ext_service/geocoder/nominatim.py
index 901f321c..30ef19ce 100644
--- a/emission/net/ext_service/geocoder/nominatim.py
+++ b/emission/net/ext_service/geocoder/nominatim.py
@@ -40,6 +40,7 @@ class Geocoder(object):
         query_url = NOMINATIM_QUERY_URL + "/search?"
         encoded_params = urllib.parse.urlencode(params)
         url = query_url + encoded_params
+        logging.debug("For geocoding, using URL %s" % url)
         return url

     @classmethod
@@ -72,6 +73,7 @@ class Geocoder(object):
         query_url = NOMINATIM_QUERY_URL + "/reverse?"
         encoded_params = urllib.parse.urlencode(params)
         url = query_url + encoded_params
+        logging.debug("For reverse geocoding, using URL %s" % url)
         return url

     @classmethod
```

[additional_geocoding_logging.patch.gz](https://github.com/e-mission/e-mission-docs/files/3009463/additional_geocoding_logging.patch.gz)

**Comment by PatGendre** [comment]
Hi, thanks, I'll ask Yann for the patch,
the conf file is nominatim.json with the current content:
`{
	"query_url" : "https://nominatim.openstreetmap.org/search"
}`

**Comment by shankari** [comment]
>  `{ "query_url" : "https://nominatim.openstreetmap.org/search" }`

I think this may be the problem. If you look at the code, we add `/search` to the URL in the code
https://github.com/e-mission/e-mission-server/blob/master/emission/net/ext_service/geocoder/nominatim.py#L40

I think that the URL should only be `https://nominatim.openstreetmap.org/`.

**Comment by PatGendre** [comment]
thank you! I deleted the search at the end, we'll see tomorrow on the pipeline logs.

**Comment by shankari** [comment]
and if you also apply the logging patch by then, we should be able to know for sure what queries are happening, and explore them manually
