### ISSUE TITLE
What are we supposed to see on the web browser once we have correctly set up authentication with the token lists? 

### ISSUE THREAD

**Issue by b-i-l-l-c-a-o** [e-mission/e-mission-docs#34]
![image](https://user-images.githubusercontent.com/35613790/45934679-92747b00-bf56-11e8-8b88-b7d1fd93a18d.png)

Right now, I have edited the json file "/conf/net/auth/token_list.json" to point to the plain text file that contains our list of tokens. It seems like it has worked, as when we go on our web browser and enter the server ip address with the port and everything, it gives us a 

**ServerSelectionTimeoutError('localhost:27017: [Errno 111] Connection refused',)**

Is this to be expected when we try and connect by just entering the ip address into a web browser when token lists have been populated and activated? Or is it more likely to be an issue with our "Screen" SupervisorD substitute or maybe our token lists getting messed up? I think I am decently confident it is a good sign, because there is the e-mission favicon in the corner of the the tab on my web browser. However, I am not sure.

-Thanks
Bill

**Comment by shankari** [comment]
@b-i-l-l-c-a-o @sam11b
I think that I have answered the question about the `Connection refused` multiple times during our meetings. It is also in the second session of the workshop.

Questions:
- what is the port where the connection is refused?
- which program is that the default port for?
- which python module is the error being thrown from?

@sam11b you know the answer to this one!

**Comment by b-i-l-l-c-a-o** [comment]
![image](https://user-images.githubusercontent.com/35613790/45934900-7de5b200-bf59-11e8-909f-e9de1db300f3.png)

Ohhh ok yeah I know what the problem is; I didn't recognize it at first, because I've never seen it in the web browser. We started MongoDB and made sure the server was running, and it brought us back to the normal page as depicted above. 

However, does this mean we weren't successful in configuring out authentication method? We were able to get to that page without entering a token or anything and the site says that it is not secure and everything.

**Comment by shankari** [comment]
look at the API methods that are invoked - it is not clear that you need authentication in order to see the landing page. In general, POST calls work with private data and require authentication - their first step is to convert the token into an UUID. GET calls do not require authentication - I don't care who sees the home page icon. Also look at section 4.2 of the em-arch paper.
