### ISSUE TITLE
re-setting the pipeline when a correction is made on the pipeline code

### ISSUE THREAD

**Issue by PatGendre** [e-mission/e-mission-docs#340]
Hi, you fixed some mode detection issues in the ground-truth-matching branch, and we want to update the e-mission-server code and re run the pipeline with the previous data.
We have read this page https://github.com/e-mission/e-mission-docs/blob/master/docs/e-mission-server/pipeline_details.md (and also this issue https://github.com/e-mission/e-mission-docs/issues/191#issuecomment-312464984) : 

> if you are running the pipeline on an ongoing production server, reset the pipeline to a specific date and re-run ($ ./e-mission-py.sh bin/reset_pipeline.py -h for the format). Note that this is a trickier operation, so you may run into corner cases. In that case, file an issue, or fix it youself and send me a pull request!

and it is not clear for us how to proceed. So I file this new issue.

Related to this, we don't understand clearly the Stage_pipeline_state DB in mongo, we have currently 12 uuids and 89 entries/documents in the pipeline states, among which 45 have a not null last_processed_ts value.

**Comment by shankari** [comment]
> and it is not clear for us how to proceed. So I file this new issue.

So what is not clear? You can reset the pipeline all the way to the beginning or to a particular time point. If you have a lot of data and you reset the pipeline all the way to the beginning, then it will take a long time to re-run, so you may want to reset to a particular time point. Resetting all the way to the beginning is safer and will always work.

> Related to this, we don't understand clearly the Stage_pipeline_state DB in mongo, we have currently 12 uuids and 89 entries/documents in the pipeline states, among which 45 have a not null last_processed_ts value.

This seems consistent. The pipeline state db has one entry for each pipeline stage for each user. 
https://github.com/e-mission/e-mission-server/blob/master/emission/core/wrapper/pipelinestate.py

There are ~ 8 stages currently in the pipeline, so we expect to see 12 * 8 = 96, and you see 89. You could see which stages are missing from the database...

**Comment by PatGendre** [comment]
Hi, Ok, the reset pipeline script seems to work fine, we will update the server code (master and then merge the ground-truth-matching branch) and reset / rerun the pipeline, thanks !

**Comment by shankari** [comment]
Closing this issue for now, please re-open if there is anything related to the pipeline that is not clear. Or maybe submit a PR updating https://github.com/e-mission/e-mission-docs/blob/master/docs/e-mission-server/pipeline_details.md to be more clear?
