### ISSUE TITLE
Merge the mode and purpose selection fixes from rk-unsw to master

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-docs#353]
There are now multiple groups requesting this (e.g. @PatGendre, @jf87, @ipsita0012, maybe even @MythriNagaraju)

----------------------------
Just for the record, here's how this would have ideally happened, in a world where I don't have regular meetings with teams.

- The first team that was interested would say something like

> I tried to merge the mode and purpose changes from rk-unsw to master, but the merge has 465 files (https://github.com/e-mission/e-mission-phone/compare/master...rk-unsw?expand=1). Is this normal? What's going on?

- I would respond by saying 

> This is due to https://github.com/e-mission/e-mission-docs/issues/349. If there is enough interest, I'll do the merge myself since I reviewed the original changes.

- All the other groups who care "vote" for this issue by adding "thumbs up" reactions.

- I am motivated by the show of interest, I make the change.

**Comment by PatGendre** [comment]
Hi, thanks for the proposal, it would definitely be useful to us if you'd take care of this (depending on your other priorities!)

**Comment by deepalics0044** [comment]
Hi, we need the change for our branch asap :)

**Comment by shankari** [comment]
I am now documenting some of the changes I made during the port. I could have done a naive port, but one of the advantages of my doing it is that I can try to actually make it better.

First, the default changes simply modify the code in `www/*/incident`. There are two problems with simply merging this to master:
- it removes all the incident code and I retain potentially wishful thinking that somebody may want to use it for crowdsourcing at some point
- it is confusing, because code labelled `incident` is actually used for mode confirmation. What we really need instead is a more plugin-based UI architecture, in which we have both incident and confirmation options for the trip end. To this end, I applied the confirmation changes to a separate directory `www/*/tripconfirm` and added state support for it.

There should be a better plugin architecture later, but for now, this patch will toggle between post-trip incident reporting and trip confirmation.

[switch_to_tripconfirm.patch.gz](https://github.com/e-mission/e-mission-docs/files/3060302/switch_to_tripconfirm.patch.gz)

**Comment by shankari** [comment]
Next, I just bring the changes to the list view over completely untouched (https://github.com/e-mission/e-mission-phone/commit/10d03355269e5bc74c7ae008ca55fe363ccbedab)

The changes were actually to a fairly small number of files.

```
+++ b/www/css/main.diary.css
+++ b/www/js/diary/list.js
+++ b/www/js/diary/services.js
+++ b/www/templates/diary/list.html
+++ b/www/templates/diary/mode-popover.html
+++ b/www/templates/diary/purpose-popover.html
```

**Comment by shankari** [comment]
ok so technically, at this point, I am done. The new code works, and I confirmed that it allows editing after setting the value once. But it has some fairly serious limitations:
- there is significant repetition between the confirmation code in `list.js` and in `post-trip-map-display.js`. in particular, the list of mode and purpose confirmations is duplicated in both places.
- the confirmation buttons are only available for processed trips (@atton16 @asiripanich, any ideas on why this is the case?) This may be a problem for groups that are not running the pipeline on an ongoing basis
- there's the weird code around `getLocalTripMode` and `getLocalTripPurpose` which we don't need any more.

**Comment by shankari** [comment]
ok so my current plan is to merge what I have, which is tested code and will unblock others. I will then address some of the other pending issues and then return to this for cleaning up the issues listed above.

**Comment by shankari** [comment]
Before I do that, I am going to make the default trip-end prompt in master be tripconfirm. This is consistent with the most visible parts of the listview, and there has been a lot more interest in trip confirmation than there has been in incident reporting so far (sadly).

**Comment by shankari** [comment]
Done (in https://github.com/e-mission/e-mission-phone/commit/c0353b9cadc41ee42d97affa65f1319ead2cc31b).

After these changes, the script for switching between trip confirmation and incident reporting is
[switch_to_tripconfirm.patch.gz](https://github.com/e-mission/e-mission-docs/files/3060730/switch_to_tripconfirm.patch.gz)

**Comment by shankari** [comment]
I want to make one more change before merging. The current prompt for the mode confirmation says "How did you get here?" and the options are "WALK", "BIKE" and "CHOOSE". This is what the CCI team requested, way back when this feature was implemented. But now that I'm merging this to master, and this is not branch-specific any more, we should think about this more carefully.

When the user does tap on the prompt, it allows her to choose both mode and purpose. So if she chooses "WALK", then what should the purpose be? Should we show only the purpose screen?....

So instead of using `WALK`, `BIKE` and `MORE`, I think we should use `CHOOSE`, `MUTE` and `SNOOZE`. The  `SNOOZE` and `MUTE` options should also help with worries about people disliking the prompts, they can just stop the prompts instead of uninstalling the app in that case.

**Comment by shankari** [comment]
Made the change, see testing screenshots below

| Before              | After                 |
|----------------|----------------|
| ![Screenshot_1554841072](https://user-images.githubusercontent.com/2423263/55837056-22ce7380-5ad5-11e9-9889-70f2f2509bdf.png) | ![Screenshot_1554844130](https://user-images.githubusercontent.com/2423263/55837083-324dbc80-5ad5-11e9-84f0-3767c98855fe.png) |

Quick testing of existing functionality (mute in this case). Also confirmed that after it was muted, there is no prompt.

| Prompt for confirmation  | Now it is muted | No prompt shows up |
|----------------|----------------| --------------- |
| ![Screenshot_1554845123](https://user-images.githubusercontent.com/2423263/55837167-675a0f00-5ad5-11e9-9daa-12f3a1f5e063.png) | ![Screenshot_1554845804](https://user-images.githubusercontent.com/2423263/55837179-7640c180-5ad5-11e9-815d-81982084b1da.png) | ![Screenshot_1554847915](https://user-images.githubusercontent.com/2423263/55838611-e94c3700-5ad9-11e9-8cce-ed58f24cedd2.png) |

**Comment by shankari** [comment]
ok, so as reported by @PatGendre after testing, this only works under two scenarios:

- the current version only works for people who are running the pipeline periodically through a cronjob and are not using trip-end notification
- it is fairly trivial to change it to work only for people who are NOT running the pipeline periodically and then it will also work for trip-end notification, but it will NOT work for cleaned trips.

To fix correctness issues for the more general case in which deployers may or may not run pipelines, I will 

- change the matching logic to the more complex `get_user_input_for_trip`
- enable the buttons for non-cleaned trips as well

**Comment by shankari** [comment]
This was actually fairly complex because of all the retained `getLocalModeForTrip` and `getLocalModeForPurpose`, and its inconsistency with the data in the timeline. In particular, the data in the HTML is `tripgj` objects which have their `start_ts` in `trip_gj.data.properties.start_ts`. But `getLocalModeForTrip` is called with the trip object, which has the `start_ts` in `trip.properties.start_ts`. I had to unify that by passing assuming that the passed in trip object had the `start_ts` field in it, and then passing in `trip.data.properties` or `trip.properties` as the case may be.

Similarly, modes retrieved remotely using the unified data loader have the full `{'data': ..., 'metadata': ...}` format but we were retrieving local data without metadata. Unified that by retrieving local data with metadata, but then we now need to set internal variables to `mode.data` instead of `mode` so that the labels can be read from them.

**Comment by shankari** [comment]
Testing done:
- Created two trips; confirmed them using the post-trip prompt
- They were visible in the diary
- Killed the app, reloaded the diary, still visible
- Note that one of these is in the phone usercache and one has been pushed to the server usercache. The pipeline has not yet been run

```
In [4]: from uuid import UUID

In [5]: test_uuid = UUID('3adc309e-e56a-4d55-a720-794ebec1cad9')

In [10]: import emission.storage.timeseries.cache_series as estc

In [11]: list(estc.find_entries(test_uuid, ["manual/mode_confirm"]))
Out[11]:
[{'_id': ObjectId('5cae9657d712613323aa00fd'),
  'data': {'end_ts': 1554943721.779511,
   'label': 'bike',
   'start_ts': 1554943721.779511},
  'metadata': {'key': 'manual/mode_confirm',
   'platform': 'ios',
   'plugin': 'none',
   'read_ts': 0,
   'time_zone': 'America/Los_Angeles',
   'type': 'message',
   'write_ts': 1554943743.323597},
  'user_id': UUID('3adc309e-e56a-4d55-a720-794ebec1cad9')}]

In [12]: list(estc.find_entries(test_uuid, ["manual/purpose_confirm"]))
Out[12]:
[{'_id': ObjectId('5cae9657d712613323aa0103'),
  'data': {'end_ts': 1554943721.779511,
   'label': 'school',
   'start_ts': 1554943721.779511},
  'metadata': {'key': 'manual/purpose_confirm',
   'platform': 'ios',
   'plugin': 'none',
   'read_ts': 0,
   'time_zone': 'America/Los_Angeles',
   'type': 'message',
   'write_ts': 1554943744.907666},
  'user_id': UUID('3adc309e-e56a-4d55-a720-794ebec1cad9')}]

In [13]:
```
| Selected trips | With mode popup |
|--------------- | -----------------  |
![Simulator Screen Shot - iPhone 6 - 2019-04-10 at 20 06 44](https://user-images.githubusercontent.com/2423263/55931749-9490e500-5bdb-11e9-83e0-f4314bec4aa2.png) | ![Simulator Screen Shot - iPhone 6 - 2019-04-10 at 21 41 07](https://user-images.githubusercontent.com/2423263/55931748-93f84e80-5bdb-11e9-9c35-2858523b8458.png) |

**Comment by shankari** [comment]
Run the pipeline on the server. Note that the bike/school trip has now disappeared since it is from `2019-04-10T17:48:41.779511-07:00` -> `2019-04-10T17:48:41.779511-07:00` so has been cleaned as a spurious trip.

| Cleaned trip | With mode selection |
| ------------ | --------------------  |
| ![Simulator Screen Shot - iPhone 6 - 2019-04-10 at 22 05 51](https://user-images.githubusercontent.com/2423263/55932199-7c21ca00-5bdd-11e9-9404-ff5f6cd5aa4d.png) | ![Simulator Screen Shot - iPhone 6 - 2019-04-10 at 22 05 30](https://user-images.githubusercontent.com/2423263/55932200-7c21ca00-5bdd-11e9-91f9-ed68181e7255.png) |

**Comment by shankari** [comment]
Changing the modes again also works

| Cleaned trip changed | And changed again |
| ---------------------  | ------------------- |
| ![Simulator Screen Shot - iPhone 6 - 2019-04-11 at 10 31 02](https://user-images.githubusercontent.com/2423263/55978629-11a47480-5c45-11e9-9c70-b1c1b9751f2b.png) | ![Simulator Screen Shot - iPhone 6 - 2019-04-11 at 10 30 20](https://user-images.githubusercontent.com/2423263/55978630-11a47480-5c45-11e9-9106-ef8acc1c984b.png) |
