### ISSUE TITLE
Itinerary data analysis: Stay points

### ISSUE THREAD

**Issue by myaman17** [e-mission/e-mission-docs#355]
I would like to start creating the list of stay points (the points in which the person stays) indicating the maximum radius (e.g. 0.3km) and minimum duration (e.g. 600 seconds). Do you have any example ipynb to implement this?

**Comment by myaman17** [comment]
I found the codes in the storage folder of my e-mission-server! Thank you!

**Comment by shankari** [comment]
@myaman17 the code is for stop detection is in `emission/analysis/intake/segmentation/trip_segmentation.py` It is configurable in there

```
    dstfsm = dstf.DwellSegmentationTimeFilter(time_threshold = 5 * 60, # 5 mins
                                              point_threshold = 9,
                                              distance_threshold = 100) # 100 m

    dsdfsm = dsdf.DwellSegmentationDistFilter(time_threshold = 10 * 60, # 10 mins
                                              point_threshold = 9,
                                              distance_threshold = 50) # 50 m
```

You said that you found it in `storage`, so I am not quite sure what that means. Can you clarify that you are using the correct location?

That python code is run automatically as part of the pipeline, and it generates trips and places. Examples of accessing trips are in the `Timeseries_sample.ipynb`; you can access places in the same way using the `analysis/cleaned_place` stream.

**Comment by myaman17** [comment]
You are right. It is in emission/analysis/intake/segmentation/trip_segmentation.py. Thank you for the clarification.
