### ISSUE TITLE
Mode Inference: Codes and explanations (e.g. decision tree)

### ISSUE THREAD

**Issue by myaman17** [e-mission/e-mission-docs#357]
Is there any python code of the mode inference (walk, bike, transit, etc.) that is used here? Also, if you have suggested paper or written explanations (e.g. decision-tree) about the mode inference algorithm, is it possible to share it/them here?

**Comment by myaman17** [comment]
I found the codes in the storage folder of my e-mission-server! 
Now, I only need written explanations (e.g. decision-tree) about the mode inference algorithm to understand better and to add in my citation lists. Is it possible to share it/them here?

**Comment by shankari** [comment]
> I found the codes in the storage folder of my e-mission-server!

The mode inference code should be in `emission/analysis/classification/inference/mode/`
An initial version of the decision tree is in http://ieeexplore.ieee.org/xpl/articleDetails.jsp?arnumber=7134044

But I would actually recommend not using the decision tree and using the GIS based version (https://github.com/e-mission/e-mission-server/pull/578) instead.

**Comment by shankari** [comment]
Unfortunately, there are no written explanations of the GIS based version because of this argument :)
https://techblog.bozho.net/we-dont-need-that-documentation/

However, I will write a high level description/architecture for my thesis, and I would love to have the users of e-mission read that chapter and give me feedback. That way, I can use my time productively, but I *know* that the work makes sense to a broad audience.

**Comment by shankari** [comment]
Please let me know if you are open to reading and providing feedback!

**Comment by myaman17** [comment]
> Unfortunately, there are no written explanations of the GIS based version because of this argument :)
> https://techblog.bozho.net/we-dont-need-that-documentation/
> 
> However, I will write a high level description/architecture for my thesis, and I would love to have the users of e-mission read that chapter and give me feedback. That way, I can use my time productively, and I _know_ that the work makes sense to a broad audience.

I agree. I hope that my professors think in the same way and not asking us submitting final papers. Anyway, I just wanted to understand better and cite property when I use the codes and mention about emission.

**Comment by myaman17** [comment]
Thank you Shankari. The explanations and links that you gave me is more than enough. Now I have all materials to move forward. I appreciate your help!
