### ISSUE TITLE
add google-service.json in the phone-app readme

### ISSUE THREAD

**Issue by PatGendre** [e-mission/e-mission-docs#361]
As the phone-app has been recently updated, the phone-app readme should updated with mention of the google-service.json file

**Comment by shankari** [comment]
Good point. I did update
 https://github.com/e-mission/e-mission-docs/blob/master/docs/e-mission-phone/create_a_new_custom_client.md
but not the `e-mission-phone` `README`

For the `e-mission-phone` repository, what would be the most user-friendly option to support? I could tell people to register on the firebase console and get a `google-services.json`, but that is only really required if you are building your own app. I could check in a dummy `google-services.json` for the e-mission-phone app with fake keys to make initial development easier.

Do you think that will help, or will it be more confusing?

**Comment by PatGendre** [comment]
Ok, thanks. 

The problem is that when compiling,  the google-services.json is in the config.xml is required (and the .plist file, too, for iOS). 
So may be there could an option when generating the config.xml file, (in the configure_xml_and_json.js file), but this could be also too complicated?
As you prefer.
