### ISSUE TITLE
user_emails not saved properly

### ISSUE THREAD

**Issue by hmharvey** [e-mission/e-mission-docs#365]
Our new deployment of the server with google authentication seems to be incorrectly storing user emails. When querying the Mongo database, the "_id", "uuid", and "update_ts" have the same format of data as before, but the "user_email" field stores a string of over a 1000 characters (Both capital and lower case letters, sometimes with a period, underscore, or dash) instead of the actual email. Note, the profile on my android app still displays my email correctly.

The phone configuration is the openToAll branch of e-mission-phone. The server is a recent fork of the server (https://github.com/hmharvey/e-mission-server).

**Comment by hmharvey** [comment]
@shankari

**Comment by shankari** [comment]
how is the authentication on the server configured?

**Comment by hmharvey** [comment]
Which type of authentication? Google authentication, as mentioned.

**Comment by shankari** [comment]
I understand that google authentication is configured on the phone because I made the changes myself. However, can you confirm that it is also configured on the server?

**Comment by hmharvey** [comment]
I updated `webserver.conf` to have `"auth": "google_auth"`. Then updated `google_auth.json` to have the keys you gave me. 

I guess I'm not positive I understand the "old keys" part of the `google_auth.json` since I don't believe you ever gave me two keys. Can these be the same keys as the new ones?

**Comment by shankari** [comment]
yes, the old keys can be the same as the new ones. Did you restart the server after you made the changes?

**Comment by hmharvey** [comment]
Yes, but I can restart it again to double-check.

**Comment by hmharvey** [comment]
Restarted it again, logged out and back in and the Dashboard is working! And looking at the database, there seems to be an email alias for you, if you just tried it. Maybe that was just the problem, sorry about that.

**Comment by shankari** [comment]
@hmharvey your server is not correctly configured with google authentication. Either you did not make the changes in https://github.com/e-mission/e-mission-docs/issues/365#issuecomment-480550377 or you did not restart the server.

To test that out, I set configured my local `connectionConfig.json` with 

```
{
    "connectUrl": "<your server>",
    "android": {
        "auth": {
            "method": "prompted-auth",
            "clientID": "ignored"
        }
    },
    "ios": {
        "auth": {
            "method": "prompted-auth",
            "clientID": "ignored"
        }
    }
}
```

I was able to connect successfully with the id `i_am_shankari_king_of_kings` (please see attached screenshot). You can verify this by looking at the database. Clearly this not a valid google account. 

<img width=400>https://user-images.githubusercontent.com/2423263/55677422-db10d780-589b-11e9-9a01-ec8f68aa7a27.png</img>

Your server authentication is still set to `skip`
https://github.com/e-mission/e-mission-docs/blob/master/docs/e-mission-both/configuring_authentication.md
so the user email that you see is the incoming token which is a long alphanumeric string that changes across time.

**Comment by shankari** [comment]
> Restarted it again, logged out and back in and the Dashboard is working! And looking at the database, there seems to be an email alias for you, if you just tried it. Maybe that was just the problem, sorry about that.

And is there now an entry for your email?

**Comment by shankari** [comment]
> And looking at the database, there seems to be an email alias for you, if you just tried it. 

I just tried it with the `prompted_auth` method (https://github.com/e-mission/e-mission-docs/issues/365#issuecomment-480551474). If it succeeds, then your auth method is still set to `skip`, which means that you have effectively no authentication.

**Comment by hmharvey** [comment]
I deleted the database and restarted the server, after double checking the files that I mentioned. After logging in again, the same result is showing up in the database, so it's not fixed. I'm not sure what else to check beside those files though?

**Comment by shankari** [comment]
I am still (as of the time of this comment) able to successfully connect to your server with the `skip` method.

```
2019-04-06 18:54:13.169 6219-8491/edu.berkeley.eecs.emission D/ConnectionSettings: in getConnectURL, returning https://emission.opensidewalks.com
2019-04-06 18:54:13.169 6219-8491/edu.berkeley.eecs.emission I/System.out: Posting data to https://emission.opensidewalks.com/usercache/get
...

```2019-04-06 18:54:13.933 6219-8491/edu.berkeley.eecs.emission I/CommunicationHelper: Got response org.apache.http.message.BasicHttpResponse@7b9e8a7 with status HTTP/1.1 200 OK
2019-04-06 18:54:13.934 6219-8491/edu.berkeley.eecs.emission I/System.out: Result Summary JSON = {"server_to_phone": []}
2019-04-06 18:54:13.934 6219-8491/edu.berkeley.eecs.emission I/System.out:  length 24
2019-04-06 18:54:13.944 6219-8491/edu.berkeley.eecs.emission I/CommunicationHelper: Result Summary JSON = {"server_to_phone": []}     length 24

**Comment by hmharvey** [comment]
Yes, what else do I need to check though?

**Comment by shankari** [comment]
Check the logs? which is the standard step to resolve any problem.

**Comment by shankari** [comment]
@hmharvey any updates on what you see in the logs?

**Comment by hmharvey** [comment]
I'm going to defer this issue for Anat and you to look into tonight.

**Comment by shankari** [comment]
@hmharvey Anat and I are the backup. Can you please try to first fix it yourself? Did you find anything in the logs?

**Comment by shankari** [comment]
@hmharvey if https://github.com/e-mission/e-mission-docs/issues/365#issuecomment-480550377 is correct, the issue must be with the way in which you restart the server. How are you restarting the server?

**Comment by shankari** [comment]
From @hmharvey over email
> The server is also currently started/restarted with Docker.

**Comment by shankari** [comment]
@hmharvey 

And finally, given that you are using docker for the service, have you ensured that your changes to the configuration are reflected in the docker containers (either through mounting or copying files in the startup script)?

Can you expand on how you configured the settings inside the docker container?

**Comment by shankari** [comment]
From @hmharvey 

> I was under the impression that when you used docker-compose down and docker-compose up it reset configurations. I've never used docker though and going off of the emissions set up (https://github.com/e-mission/e-mission-server/blob/a15a8c7fc9baa7efd7823ef4759c3ce7b7417967/docker/README.md) I don't believe that was ever mentioned.

**Comment by shankari** [comment]
@hmharvey The docker version makes it easier to install the server. You still have to configure it. There are multiple possible authentication methods; you can't expect that without any further configuration, the docker container will be magically configured with your particular configuration. The README does also say:

> Configure the compose file
> Update the port mappings and environment variables if necessary. For more details on how to configure compose files please see the official documentation: https://docs.docker.com/compose/compose-file/#service-configuration-reference

that is the issue. I don't know where you have been making changes, but you presumably didn't configure the docker-compose to map that location to the container. So none of the changes you made were actually visible to the running code, which is why the server is still configured with "skip" authentication.

**Comment by shankari** [comment]
logging in to their server to see if I can fix this.
First obvious choice is to map the local `e-mission-server/conf` directory to the `conf` directory inside the container.

Log in to the container to see how the server is installed

```
$ docker exec -it docker_webserver_1 bash
/usr/src/app# ls
conf
....
```

So let's add a volume mapping to the `docker-compose.yml`

```
    volumes:
      - ./conf:/usr/src/app/conf
```

Restarting, the webserver did not start. Looking at the startup logs, we see

```
webserver_1  |     config_file = open('conf/storage/db.conf')
webserver_1  | FileNotFoundError: [Errno 2] No such file or directory: 'conf/storage/db.conf'
...
webserver_1  |     config_file = open('conf/storage/db.conf.sample')
webserver_1  | FileNotFoundError: [Errno 2] No such file or directory: 'conf/storage/db.conf.sample'
```

Is this not mapping properly?

**Comment by shankari** [comment]
Let's map to a different directory than `conf` to check the mounting

```
    volumes:
      - ./conf:/tmp/local-conf
```

Now, after starting, let's check the mounted path

```
ubuntu@emission-staging:~/e-mission-server$ docker exec -it docker_webserver_1 bash
(base) root@5a5c8d4164f4:/usr/src/app# ls /tmp/local-conf/
(base) root@5a5c8d4164f4:/usr/src/app#
```

wut! why isn't this mapping? I have successfully used this before! I wonder if this is because the path is relative to the dockerfile. Let's try absolute path @uwtcat :)

**Comment by shankari** [comment]
Using absolute path 

```
    volumes:
      - /home/ubuntu/e-mission-server/conf:/tmp/local-conf
```

and now it works!

```
ubuntu@emission-staging:~/e-mission-server$ docker exec -it docker_webserver_1 bash
/usr/src/app# ls /tmp/local-conf/
analysis  clients  log  net  storage
```

**Comment by shankari** [comment]
Let's switch back to mounting the real local config

```
    volumes:
      - /home/ubuntu/e-mission-server/conf:/usr/src/app/conf
```

The webserver does start up now

```
ubuntu@emission-staging:~/e-mission-server$ docker-compose -f docker/docker-compose.yml up -d
WARNING: Some services (db, webserver) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.
Creating network "docker_emission" with the default driver
Creating docker_caddy_1 ...
Creating docker_db_1 ...
Creating docker_caddy_1
Creating docker_db_1 ... done
Creating docker_webserver_1 ...
Creating docker_webserver_1 ... done
ubuntu@emission-staging:~/e-mission-server$ docker container list
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS              PORTS                                                NAMES
f2b1d19364bb        emission/e-mission-server:latest   "/usr/bin/tini -- /b…"   20 seconds ago      Up 17 seconds       0.0.0.0:8080->8080/tcp                               docker_webserver_1
10fad907f49b        mongo:latest                       "docker-entrypoint.s…"   23 seconds ago      Up 20 seconds       0.0.0.0:27017->27017/tcp                             docker_db_1
20b0bfe65651        abiosoft/caddy:0.10.10             "/usr/bin/caddy --co…"   23 seconds ago      Up 19 seconds       0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 2015/tcp   docker_caddy_1
```

**Comment by shankari** [comment]
And the startup script does configure everything correctly, so no further changes are needed.
And the changes are reflected on the locally checked out configuration.

```
ubuntu@emission-staging:~/e-mission-server$ less conf/storage/db.conf
{
    "timeseries": {
        "url": "db"
    }
}
```

**Comment by shankari** [comment]
Let's restart a couple of times 

```
ubuntu@emission-staging:~/e-mission-server$ docker-compose -f docker/docker-compose.yml  down
WARNING: Some services (db, webserver) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.
Stopping docker_webserver_1 ... done
Stopping docker_db_1        ... done
Stopping docker_caddy_1     ... done
Removing docker_webserver_1 ... done
Removing docker_db_1        ... done
Removing docker_caddy_1     ... done
Removing network docker_emission
ubuntu@emission-staging:~/e-mission-server$ docker-compose -f docker/docker-compose.yml up -d
WARNING: Some services (db, webserver) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.
Creating network "docker_emission" with the default driver
Creating docker_caddy_1 ...
Creating docker_db_1 ...
Creating docker_caddy_1
Creating docker_db_1 ... done
Creating docker_webserver_1 ...
Creating docker_webserver_1 ... done
ubuntu@emission-staging:~/e-mission-server$ docker container list
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS              PORTS                                                NAMES
f1dcebb0fc21        emission/e-mission-server:latest   "/usr/bin/tini -- /b…"   8 seconds ago       Up 5 seconds        0.0.0.0:8080->8080/tcp                               docker_webserver_1
40fad6fb3309        mongo:latest                       "docker-entrypoint.s…"   12 seconds ago      Up 8 seconds        0.0.0.0:27017->27017/tcp                             docker_db_1
cd97f064dbc8        abiosoft/caddy:0.10.10             "/usr/bin/caddy --co…"   12 seconds ago      Up 8 seconds        0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 2015/tcp   docker_caddy_1
ubuntu@emission-staging:~/e-mission-server$ docker-compose -f docker/docker-compose.yml  down
WARNING: Some services (db, webserver) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.
Stopping docker_webserver_1 ... done
Stopping docker_db_1        ... done
Stopping docker_caddy_1     ... done
Removing docker_webserver_1 ... done
Removing docker_db_1        ... done
Removing docker_caddy_1     ... done
Removing network docker_emission
ubuntu@emission-staging:~/e-mission-server$ docker-compose -f docker/docker-compose.yml up -d
WARNING: Some services (db, webserver) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.
Creating network "docker_emission" with the default driver
Creating docker_db_1 ...
Creating docker_caddy_1 ...
Creating docker_db_1
Creating docker_db_1 ... done
Creating docker_webserver_1 ...
Creating docker_webserver_1 ... done

ubuntu@emission-staging:~/e-mission-server$ docker container list
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS              PORTS                                                NAMES
d6ded3ef0c34        emission/e-mission-server:latest   "/usr/bin/tini -- /b…"   18 seconds ago      Up 15 seconds       0.0.0.0:8080->8080/tcp                               docker_webserver_1
0126fa4ce36b        abiosoft/caddy:0.10.10             "/usr/bin/caddy --co…"   21 seconds ago      Up 18 seconds       0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 2015/tcp   docker_caddy_1
fe0d79e7da3c        mongo:latest                       "docker-entrypoint.s…"   21 seconds ago      Up 18 seconds       0.0.0.0:27017->27017/tcp                             docker_db_1
```

Logging into the docker image, let's check the config

```
# ls conf/net/auth/
google_auth.json         openid_auth.json.sample
google_auth.json.sample  token_list.json.sample
```

**Comment by shankari** [comment]
Everything should be done.

**Comment by shankari** [comment]
Summary: if you want to use a different auth method, a cheap method is make sure that your local configuration is reflected on the server is to map your local conf directory to the conf directory in the container.

BUT, if you want to do this, you should use the absolute path - e.g.

```
    volumes:
      - /home/ubuntu/e-mission-server/conf:/usr/src/app/conf
```

**Comment by shankari** [comment]
Let's just test to make sure that we do see google auth in the logs.
Wait, I get a "502 Bad Gateway" when I try to access the URL

**Comment by shankari** [comment]
Aha! It turned out that the local configuration did not only have the google auth, but had also reconfigured the port to 8090

```
diff --git a/conf/net/api/webserver.conf.sample b/conf/net/api/webserver.conf.sample
index 01db7dc1..aa217035 100644
--- a/conf/net/api/webserver.conf.sample
+++ b/conf/net/api/webserver.conf.sample
@@ -8,9 +8,9 @@
   "__comment" : "Fill this in for the production server. port will almost certainly be 80 or 443. For iOS, using localhost allows you to test without an internet connection. For AWS and android, make sure that the host 0.0.0.0, localhost does not seem to work",
   "server" : {
     "host" : "localhost",
-    "port" : "8080",
+    "port" : "8090",
     "__comment": "1 hour = 60 min = 60 * 60 sec",
     "timeout" : "3600",
-    "auth": "skip"
+    "auth": "google_auth"
   }
 }
```

Since we pick up all local config, we picked that up too, and it was inconsistent with the `docker-compose.yml` mapping. Reverting that change now...

**Comment by shankari** [comment]
Aha! Server's back! **Now** Let's check which auth method shows up in the logs.
Accessing it with the client that I configured in https://github.com/e-mission/e-mission-docs/issues/365#issuecomment-480551474


```
$ docker-compose -f docker/docker-compose.yml logs
webserver_1  | Bottle v0.13-dev server starting up (using CherootServer())...
webserver_1  | Listening on http://0.0.0.0:8080/
webserver_1  | Hit Ctrl-C to quit.
webserver_1  |
webserver_1  | /opt/conda/envs/emission/lib/python3.6/sre_parse.py:864: DeprecationWarning: Flags not at the start of the expression \{\{((?:(?mx)(       (truncated)
webserver_1  |   p = _parse_sub(source, pattern, True, False)
webserver_1  | /usr/src/app/emission/net/auth/auth.py:26: ResourceWarning: unclosed file <_io.TextIOWrapper name='conf/net/auth/google_auth.json' mode='r' encoding='UTF-8'>
webserver_1  |   return enag.GoogleAuthMethod()
webserver_1  | Traceback (most recent call last):
webserver_1  |   File "/usr/src/app/emission/net/auth/google_auth.py", line 55, in verifyUserToken
webserver_1  |     tokenFields = goi.verify_oauth2_token(token, gatr.Request())
webserver_1  |   File "/opt/conda/envs/emission/lib/python3.6/site-packages/google/oauth2/id_token.py", line 97, in verify_oauth2_token
webserver_1  |     certs_url=_GOOGLE_OAUTH2_CERTS_URL)
webserver_1  |   File "/opt/conda/envs/emission/lib/python3.6/site-packages/google/oauth2/id_token.py", line 78, in verify_token
webserver_1  |     return jwt.decode(id_token, certs=certs, audience=audience)
webserver_1  |   File "/opt/conda/envs/emission/lib/python3.6/site-packages/google/auth/jwt.py", line 214, in decode
webserver_1  |     header, payload, signed_section, signature = _unverified_decode(token)
webserver_1  |   File "/opt/conda/envs/emission/lib/python3.6/site-packages/google/auth/jwt.py", line 127, in _unverified_decode
webserver_1  |     'Wrong number of segments in token: {0}'.format(token))
webserver_1  | ValueError: Wrong number of segments in token: b'i_am_a_dummy_and_i_hate_google'
```

Fails as expected. I think that this is now done.

**Comment by shankari** [comment]
@hmharvey I would suggest that you clear out the DB, try to login again and ensure that the token is decoded correctly.

**Comment by hmharvey** [comment]
Cleared the database and then tried to log in on my phone, I got a "User registration error. While pushing/getting from the server HTTP/1.1 500 Internal Server Error". Logged out and logged back in and got the error again. The database also doesn't show any users.

**Comment by hmharvey** [comment]
@shankari

**Comment by shankari** [comment]
@hmharvey What do you see in the logs?

**Comment by shankari** [comment]
This turned out to be due to a misconfigured `google_auth.json`. @hmharvey had used the same key for the `client_key` and `ios_client_key` fields.

**Comment by shankari** [comment]
From @hmharvey 

> Awesome, looks like it's working now. Logged in on my phone and the database shows the correct information.

Closing this issue now
