### ISSUE TITLE
Location tracking on/off button in UI is slightly broken

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-docs#367]
Reported as part of https://github.com/e-mission/e-mission-docs/issues/325

Did my own testing in the emulator.

1. Initial toggle
  state: `waiting_for_trip_start`
  during toggle: popup `local.transition.start_tracking`
  after toggle + refresh: toggle is still on, state is still `waiting_for_trip_start`

2. Try again
  state: `waiting_for_trip_start`
  during toggle: popup `local.transition.stop_tracking`
  after toggle + refresh: toggle is off, state is `tracking_off`

3. Turn it on now
  state: `tracking_off`
  during toggle: popup `local.transition.start_tracking`
  after toggle + refresh: toggle is on, state is `waiting_for_trip_start`

@PatGendre is this consistent with what you see in your testing?

**Comment by shankari** [comment]
at least on api 26, after the initial toggle, everything seems to work fine. But you can't see that it looks fine unless you click on Refresh. Yes, this is unintuitive, specially for a button that is outside the developer zone. Let's see if we can fix that first.

**Comment by shankari** [comment]
ok, so I believe this is a regression from 
https://github.com/e-mission/e-mission-phone/commit/a99c4e8798b7cfa71db5b366c73bbf4f5f2f0237

in particular, this inconsistency

```
-    $scope.trackingOn = function() {
+    $scope.isTrackingOn = function() {
+        return $ionicPlatform.ready().then(function() {
         if($scope.isAndroid()){
             return $scope.settings.collect.state != "local.state.tracking_stopped";
         } else if ($scope.isIOS()) {
             return $scope.settings.collect.state != "STATE_TRACKING_STOPPED";
         }
+        });
     };
     $scope.userStartStopTracking = function() {
         if ($scope.startStopBtnToggle){
@@ -338,7 +354,7 @@ angular.module('emission.main.control',['emission.services',
             $scope.startStopBtnToggle = true;
         }
     }
-    $scope.startStopBtnToggle = $scope.trackingOn();
+    $scope.startStopBtnToggle = $scope.trackingOn;```
```

however, while fixing it, we can get rid of the `$scope.startStopBtnToggle` entirely in favor of the new `$scope.settings.collect.trackingOn` introduced in the change. Note that is set during refresh so we will know the real state and not just toggle blindly.

**Comment by shankari** [comment]
Merged the changes to the plugin javascript into the deploy-upload-master branch
https://github.com/e-mission/e-mission-phone/pull/551

**Comment by shankari** [comment]
@PatGendre, it was only a javascript change.

I have updated the interscity and greentrip branches with the fix, so you can test emTripLog with either 
https://e-mission.eecs.berkeley.edu/#/client_setup?new_client=interscity&clear_usercache=true&clear_local_storage=true
or
https://e-mission.eecs.berkeley.edu/#/client_setup?new_client=greentrip&clear_usercache=true&clear_local_storage=true

If this now makes sense, you can update your apk again; the fixes have been merged to master. Note that there was a plugin update involved as well. If you still see weird behavior, please report details here.

@MythriNagaraju, you will get a prompt for a UI only update with this fix as well, so don't be surprised!

**Comment by PatGendre** [comment]
yes this fixes the issue with the Tracking button, thanks !
