### ISSUE TITLE
allow to choose saturdays in dashboard

### ISSUE THREAD

**Issue by PatGendre** [e-mission/e-mission-docs#368]
we noticed that it is impossible to select saturdays in the metrics dashboard.
This is because of line https://github.com/e-mission/e-mission-phone/blob/6c3cdf50afb35cfdd757669c3d3fb8dddee95346/www/js/metrics.js#L1162 

In our version we commented out this line, but maybe it should be done also in master

**Comment by shankari** [comment]
oh if you have already figured out the fix, maybe you can submit a PR?
Then the project will have more contributors!

**Comment by PatGendre** [comment]
I added a screenshot to [PR #552](https://github.com/e-mission/e-mission-phone/pull/552) and closed the PR

**Comment by shankari** [comment]
closed in e-mission/e-mission-phone#552
