### ISSUE TITLE
No trip information displayed with Timeline.getTrip(tripId)

### ISSUE THREAD

**Issue by sam11b** [e-mission/e-mission-docs#369]
I'm passing in the tripId as a string and for some reason I'm getting an error when the code tries to get the trip information from timeline.data.tripMap[tripId], saying undefined is not an object. I checked on the diary page and the tripId is given the same way (as a string) and no issues occur. Timeline is also listed as a controller at the top of recommendations.js. No other functions currently use Timeline so it is possible that I'm not importing it correctly into the controller. 
<img width="1104" alt="Screen Shot 2019-04-09 at 1 16 33 PM" src="https://user-images.githubusercontent.com/23513222/55832208-dc274c00-5ac9-11e9-9484-b3ddc3e2b1b3.png">

Here is how/where Timeline.getTrip(tripId) is being called (also in recommendations.js):

<img width="611" alt="Screen Shot 2019-04-09 at 1 18 07 PM" src="https://user-images.githubusercontent.com/23513222/55832277-0711a000-5aca-11e9-9616-7ffd4c970398.png">

Here is the information displayed by the debugger:

<img width="1000" alt="Screen Shot 2019-04-09 at 1 20 37 PM" src="https://user-images.githubusercontent.com/23513222/55832389-55bf3a00-5aca-11e9-8f6d-9be605ebd51e.png">

The tripId seems to align accurately according to information on the diary page. Hopefully, once this is resolved the main recommendation page will display start time, end time, and mode. Like so: 

![Simulator Screen Shot - iPhone 8 - 2019-04-09 at 13 21 36](https://user-images.githubusercontent.com/23513222/55832476-84d5ab80-5aca-11e9-9b1a-88b045861f90.png)

I'm unsure what next steps are here to figure out what is wrong. Any help is much appreciated.

**Comment by shankari** [comment]
In general, while copy-pasting code, can you use markdown instead of screenshots? markdown is text so it is searchable. screenshots are images and are not searchable by default

**Comment by shankari** [comment]
> Timeline is also listed as a controller at the top of recommendations.js.

Well, it is listed as a **dependency**. It is a factory, not a controller.

>  No other functions currently use Timeline so it is possible that I'm not importing it correctly into the controller.

I think this may be it. The Timeline factory is defined in the `emission.main.diary.services` and I think you need to add it as a module dependency

> I'm unsure what next steps are here to figure out what is wrong. Any help is much appreciated.

I would also connect with a debugger or add debug statements and figure out what is undefined. If you have a chain like (and here it would be nice to have markdown code to copy/paste) `timeline.data.tripMap[tripId]`, you want to know whether `timeline` or `data` or `tripMap` are undefined

**Comment by sam11b** [comment]
I added emission.main.diary.services to the module as a dependency. I have a couple debug statements as of now to ensure I'm receiving tripId and it's being converted to a string correctly (ie I'm not passing in the object from the server). I'm also logging the server results. 

```ruby
'use strict';

angular.module('emission.main.recommendations',['emission.services', 'emission.plugin.logger', 'emission.main.diary.services', 
                'emission.survey.launch',
                'ngSanitize', 'ngAnimate',
                'emission.splash.referral', 'angularLocalStorage',
                'ng-walkthrough', 'nzTour'])

.controller('RecommendationsCtrl', function(CommHelper, $state, $stateParams, $ionicLoading, $scope, $rootScope, $ionicModal, nzTour,
                                $window, $http, $ionicPopup, $timeout, storage, ReferralHandler, ReferHelper, Logger, $cordovaInAppBrowser, SurveyLaunch, DiaryHelper, Timeline) {
```
Here is the code surrounding the error. It also includes what I'm logging/printing in the debugger.

```ruby
 $scope.clickSuggestion = function(id) {
      $ionicLoading.show({
        template: 'Loading most recent suggestion, this may take a while...'
        });
      CommHelper.getSuggestion().then(function(result) {
        console.log("THIS IS THE TRIP ID AFTER BUTTON PUSHED" + result.tripid.$oid)
        $ionicLoading.hide();
        console.log(result);
        $scope.name = result.message;
        $scope.mode = result.method;
        $scope.bid = result.businessid;
        $scope.stars = result.rating;
        $scope.tripid = result.tripid.$oid
        $scope.trip = Timeline.getTrip($scope.tripid);
        console.log("THIS IS THE TRIP FROM TIMELINE" + $scope.trip);
```
Is there something else I should try printing? The code errors at $scope.trip = Timeline.getTrip($scope.tripid); and therefore never makes it to the final log.

**Comment by shankari** [comment]
Did you try my suggestion from before?

> I would also connect with a debugger or add debug statements and figure out what is undefined. If you have a chain like (and here it would be nice to have markdown code to copy/paste) timeline.data.tripMap[tripId], you want to know whether timeline or data or tripMap are undefined

**Comment by sam11b** [comment]
Yes. 
```ruby
      timeline.getTrip = function(tripId) {
        console.log(timeline);
        console.log(timeline.data);
        console.log(timeline.data.tripMap);
        return timeline.data.tripMap[tripId];
      };
```
timeline.data appears to be what is undefined.

**Comment by shankari** [comment]
Hm, so do you load the timeline before trying to access it?
The listview typically loads the timeline when you access the data for a particular day.

```
  var readAndUpdateForDay = function(day) {
    // This just launches the update. The update can complete in the background
    // based on the time when the database finishes reading.
    // TODO: Convert the usercache calls into promises so that we don't have to
    // do this juggling
    Timeline.updateForDay(day);
    // CommonGraph.updateCurrent();
  };
```

**Comment by shankari** [comment]
If you don't load the timeline already, this may be tricky to accomplish because you don't know which day the recommendation is from. @valin could return the start and end timestamp of the trip and the associated day and you could load the timeline. Or maybe we should rethink what we want to accomplish here?

**Comment by sam11b** [comment]
At that point might as well have Vanessa send everything (start time, end time, and mode). As of right now, I'm trying to use the current day. This is a little buggy and won't work if the user's latest trip is from the day before.

**Comment by sam11b** [comment]
Upon further debugging, it seems the date is sent into Timeline.updateforDay(day) in a format that looks like this 1554793200000. Not sure how this relates to the current day or how it was created? Any suggestions?

**Comment by shankari** [comment]
It's the timestamp of the day start.

https://github.com/e-mission/e-mission-phone/blob/42201ee2293116e692b917942c5deb45b5d3eb5c/www/js/diary/list.js#L133

having said that, I am not sure it helps that much to write code to load the current day because, as you point out, it won't work if the last suggestion is from the previous day

**Comment by shankari** [comment]
Closing this since this is not currently in the timeline
