### ISSUE TITLE
Unable to run push_survey

### ISSUE THREAD

**Issue by valin1** [e-mission/e-mission-docs#370]
I ran this command "python3 bin/push/send_survey.py -u valin survey_spec bio2caldec2016.survey.spec" but it keeps saying 
```
Traceback (most recent call last):
  File "bin/push/send_survey.py", line 13, in <module>
    import emission.net.ext_service.push.notify_usage as pnu
ModuleNotFoundError: No module named 'emission.net' 
```

Even though there are init files in each folder.

**Comment by shankari** [comment]
@valin1 all commands in e-mission have to be run using one of the e-mission python wrappers.
Try `./e-mission-py.bash ....`
