### ISSUE TITLE
Customize/remove push notifications

### ISSUE THREAD

**Issue by MythriNagaraju** [e-mission/e-mission-docs#371]
@shankari Is there an easy way to remove push notifications? Or customize them to have only the basic notifications that let them know trip tracking has started etc..?  I tried disabling push notifications while building the app in XCode but that doesn't seem to work.

**Comment by shankari** [comment]
I would just remove the push notification plugin from cordova (e.g. `cordova plugin rm phonegap-plugin-push`).

Note that if you remove push plugins, you cannot use the backup iOS silent push notification https://github.com/e-mission/e-mission-docs/blob/0bf397e6460b912d3026fc9daace878f13711526/docs/e-mission-server/deploying_your_own_server_to_production.md#configuring-push in case the visit detection on iOS is broken.

Also, can you tell me why you want to remove the push notification support? Before you spend a lot of time on this, I want to make sure that this is the right approach for what you are trying to accomplish.

**Comment by MythriNagaraju** [comment]
Because since this app is being used as part of a survey,  we sort of want to keep user interaction minimal after they have logged in and have been notified that their commutes are being tracked. Some of the notifications that prompt the user to report incident may even confuse the other. (I noticed that there is an option to mute the incident report notification, but it seems to appear only after a while)

**Comment by shankari** [comment]
I thought that might be it; that's why I asked! The incident reporting (and other post trip notifications in general) are not generated through push notifications; but through local processing and can be configured in javascript. 
https://github.com/e-mission/e-mission-docs/blob/b4f0278d30655c6a712a0e46933b4bc599ee2c4b/docs/tutorials/change_trip_end_prompt.md

Having said that, you may want to use the notifications to get data about mode and purpose, instead of incident reporting. Check out https://github.com/e-mission/e-mission-docs/issues/353 and the related https://github.com/e-mission/e-mission-phone/pull/553

**Comment by MythriNagaraju** [comment]
I don't think we want notifications about the mode and purpose either.

**Comment by shankari** [comment]
> I noticed that there is an option to mute the incident report notification, but it seems to appear only after a while

Hm, the mute option should appear in the notification bar. Can you show me your notification bar without the mute option? Even if you don't need this right now, reporting the issue will help make the platform better, benefit others, and maybe even you if you do decide to enable this functionality later.

| With mute                         | With click                   |  With mute selection |
| ------------------------- | --------------------- | --------------------  |
| ![Screenshot_1555011415](https://user-images.githubusercontent.com/2423263/55987515-8e8c1a00-5c56-11e9-882a-c0fd5796899c.png) | ![Screenshot_1555011407](https://user-images.githubusercontent.com/2423263/55987516-8e8c1a00-5c56-11e9-9bb1-ac4704971316.png) | ![Screenshot_1555011531](https://user-images.githubusercontent.com/2423263/55987629-cabf7a80-5c56-11e9-87c0-77813707b718.png) |

**Comment by shankari** [comment]
> I don't think we want notifications about the mode and purpose either.

Ok! 

> but can comment them out (in www/js/tripconfirm/post-trip-prompt.js) if you don't.

**Comment by MythriNagaraju** [comment]
In case I choose to remove the push notification plugin, what happens if visit detection on iOS is broken. The trips just stop getting tracked?

**Comment by shankari** [comment]
@MythriNagaraju removing the push notification plugin has no effect on the trip end notifications since they are generated locally. You have to edit the javascript to remove them.

To answer your question, the trip end is not detected on iOS and the tracking continues causing battery drain.

**Comment by MythriNagaraju** [comment]
That makes sense. Thanks @shankari . I'll send you a screenshot without the mute option. Honestly now I am not a 100% sure that I saw a notification without the mute option. (It's possible I just didn't notice it before). But if I come across one such notification, I will put up a screenshot here.

**Comment by shankari** [comment]
@MythriNagaraju couple of other clarifications for the record
- visit detection is an iOS API, so I can't fix it if it is broken
- you also need a server side cronjob to send out the notifications to get the full benefit :)

**Comment by MythriNagaraju** [comment]
got it, thanks! when do you plan to merge your most recent changes? Would I still be able to comment out the mode and purpose notifications before you merge?

**Comment by shankari** [comment]
I will merge the changes after I get the testing results from @PatGendre and @deepalics0044
You can also merge them now by pulling directly from my branch.

```
$ git pull https://github.com/shankari/e-mission-phone.git merge_mode_purpose_final_code
```

I would strongly suggest including the changes at least to the list view.
You can comment out the notifications at any time (before merge in `www/js/incident` and after the merge in `www/js/tripconfirm`)

**Comment by shankari** [comment]
I would encourage you to also test the pending changes and report any issues to the open PR.
Again, having multiple people test ensures that we get broad coverage of any unusual interaction behavior.

**Comment by shankari** [comment]
Closing this since there do not appear to be any pending questions here.
