### ISSUE TITLE
Attempting to send survey notifications but fails to reach over to the phone side

### ISSUE THREAD

**Issue by valin1** [e-mission/e-mission-docs#373]
It keeps saying success: 0 and failure:1 so I am assuming that it is not going through. 
```
DEBUG:root:Found firebase mapping from 1692257af81f776a074b13e24ea3d22ea9b949b7aa9220ea3df4b079a7916897 -> dCMX8Lmih9c:APA91bFxsSU5HdF66vgIZX3o-99v6jEXdCozcx7jSJGiaGJ3o_9pOXH96OFCrehagSNhPYYgLXYAnBpGrGBiyXaoShDCmW_U15oJb2J438LExkyoqbPpmSrgrlNI_xwaNMf-t59CJp6F at index 0
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): fcm.googleapis.com
DEBUG:requests.packages.urllib3.connectionpool:https://fcm.googleapis.com:443 "POST /fcm/send HTTP/1.1" 200 None
DEBUG:root:{'ios': {'multicast_ids': [5832574603448039065], 'success': 0, 'failure': 1, 'canonical_ids': 0, 'results': [{'error': 'InvalidParameters: AppleDeliveryError:BAD_REQUEST_TOPIC_DISALLOWED'}], 'topic_message_id': None}, 'android': {'multicast_ids': [], 'success': 0, 'failure': 0, 'canonical_ids': 0, 'results': [], 'topic_message_id': None}}
DEBUG:root:module_name = emission.net.ext_service.push.notify_interface_impl.firebase
DEBUG:root:module = <module 'emission.net.ext_service.push.notify_interface_impl.firebase' from '/home/ubuntu/e-mission-server/emission/net/ext_service/push/notify_interface_impl/firebase.py'>
DEBUG:root:interface_obj_fn = <function get_interface at 0x7f5f1c1f6378>
DEBUG:root:interface_obj = <emission.net.ext_service.push.notify_interface_impl.firebase.FirebasePush object at 0x7f5f1c50a0f0>
DEBUG:root:interface_obj = <emission.net.ext_service.push.notify_interface_impl.firebase.FirebasePush object at 0x7f5f1c50a0f0>
DEBUG:root:firebase push result for ios: success 0 failure 1 results [{'error': 'InvalidParameters: AppleDeliveryError:BAD_REQUEST_TOPIC_DISALLOWED'}]
DEBUG:root:firebase push result for android: success 0 failure 0 results []
```

**Comment by shankari** [comment]
Yes that definitely seems like a reasonable assumption. Did you try with the sample survey spec first? That way, we can determine whether this is a push configuration issue or an issue with your spec.

**Comment by valin1** [comment]
Yes, this was done through the sample survey spec.

**Comment by valin1** [comment]
I used the bic2cal.dec2016.survey.spec

**Comment by shankari** [comment]
I generally use the `hearst.survey.sample`, can you try with that?

**Comment by shankari** [comment]
Although `BAD_REQUEST_TOPIC_DISALLOWED` is apparently a known issue and I can't find a good solution

**Comment by valin1** [comment]
hearst.survey.sample does not work either

**Comment by shankari** [comment]
Can you try sending the notification to an android user?

**Comment by valin1** [comment]
It seems like it went through? I sent it to Trevor and it says success: 1 but I am not sure if he received a notification.

**Comment by valin1** [comment]
```
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): fcm.googleapis.com
DEBUG:requests.packages.urllib3.connectionpool:https://fcm.googleapis.com:443 "POST /fcm/send HTTP/1.1" 200 None
DEBUG:root:{'ios': {'multicast_ids': [], 'success': 0, 'failure': 0, 'canonical_ids': 0, 'results': [], 'topic_message_id': None}, 'android': {'multicast_ids': [7256243566658934559], 'success': 1, 'failure': 0, 'canonical_ids': 0, 'results': [{'message_id': '0:1555048330515261%abead538f9fd7ecd'}], 'topic_message_id': None}}
DEBUG:root:module_name = emission.net.ext_service.push.notify_interface_impl.firebase
DEBUG:root:module = <module 'emission.net.ext_service.push.notify_interface_impl.firebase' from '/home/ubuntu/e-mission-server/emission/net/ext_service/push/notify_interface_impl/firebase.py'>
DEBUG:root:interface_obj_fn = <function get_interface at 0x7f34a9e70378>
DEBUG:root:interface_obj = <emission.net.ext_service.push.notify_interface_impl.firebase.FirebasePush object at 0x7f34ac31a198>
DEBUG:root:interface_obj = <emission.net.ext_service.push.notify_interface_impl.firebase.FirebasePush object at 0x7f34ac31a198>
DEBUG:root:firebase push result for ios: success 0 failure 0 results []
DEBUG:root:firebase push result for android: success 1 failure 0 results [{'message_id': '0:1555048330515261%abead538f9fd7ecd'}]
```

**Comment by shankari** [comment]
yes, it worked for android. I did recently (as part of the great api26 update) switch android to FCM and I tested it after that and it worked. Did that break it for iOS?

**Comment by valin1** [comment]
I believe so?

**Comment by valin1** [comment]
None of the iOS users received anything on their phones.

**Comment by shankari** [comment]
can anybody get in touch with trevor to confirm that the android push notification was delivered to him? Because if so, I can debug the iOS stuff tomorrow. I hate push notifications because they are so finicky.

**Comment by shankari** [comment]
@valin1 can you also kill/restart the app so that push notification token is updated?

**Comment by valin1** [comment]
He is currently not responding to us but we are trying to. @trevor-wu 
I killed/restarted the app.

**Comment by shankari** [comment]
Try sending yourself a notification again

**Comment by valin1** [comment]
I still receive the same error as before.

**Comment by shankari** [comment]
ok so iOS is broken, but based on the logs, it looks like android works. I will debug this further tomorrow, but please send me the updated protocol so that I can review and you can submit in parallel

**Comment by shankari** [comment]
@valin1 I think I know what is going on. Please change `"application": "edu.berkeley.eecs.emission",` at line 63 to `"application": "edu.berkeley.eecs.embase",`
and then retry

I should really make this be configurable.

**Comment by valin1** [comment]
which file is this line supposed to be on? I don't see it in the send_survey.py

**Comment by shankari** [comment]
`emission/net/ext_service/push/notify_interface_impl/firebase.py`

**Comment by valin1** [comment]
It still gave me the same error after changing emission to embase.

**Comment by shankari** [comment]
ok well, then I have to debug further tomorrow.

**Comment by valin1** [comment]
Trevor says he isn't getting suggestions, but here is the output from the server side, which indicates it is going through. 
``` 
storage not configured, falling back to sample, default configuration
Connecting to database URL localhost
INFO:root:About to push to uuid list = [UUID('fe1ca45a-bc8b-4b09-b05e-8803cf871386')]
DEBUG:root:Getting tokens matching query {'user_id': {'$in': [UUID('fe1ca45a-bc8b-4b09-b05e-8803cf871386')]}}
DEBUG:root:adding token cwyYXIkNx5I:APA91bE6jhromnRrsNI6pg6n0UgKfE-kkrYh-cHdbXYnErlMgF6IntTEorJ5g1PrNahsjVxr_xz_urkedRXtPpcS_4y-C6xLTyEnCFCAjHh5votu7cDzeWvP4-0NO60FoxEVv2OpxazR to list for platform android
DEBUG:root:user_id_list of length 1 -> token list of length 1
DEBUG:root:module_name = emission.net.ext_service.push.notify_interface_impl.firebase
DEBUG:root:module = <module 'emission.net.ext_service.push.notify_interface_impl.firebase' from '/home/ubuntu/e-mission-server/emission/net/ext_service/push/notify_interface_impl/firebase.py'>
DEBUG:root:interface_obj_fn = <function get_interface at 0x7f9c4590b378>
DEBUG:root:interface_obj = <emission.net.ext_service.push.notify_interface_impl.firebase.FirebasePush object at 0x7f9c47dae1d0>
DEBUG:root:interface_obj = <emission.net.ext_service.push.notify_interface_impl.firebase.FirebasePush object at 0x7f9c47dae1d0>
DEBUG:root:len(token_list) == 0, skipping fcm token mapping to save API call
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): fcm.googleapis.com
DEBUG:requests.packages.urllib3.connectionpool:https://fcm.googleapis.com:443 "POST /fcm/send HTTP/1.1" 200 None
DEBUG:root:{'ios': {'multicast_ids': [], 'success': 0, 'failure': 0, 'canonical_ids': 0, 'results': [], 'topic_message_id': None}, 'android': {'multicast_ids': [8620972254063343836], 'success': 1, 'failure': 0, 'canonical_ids': 0, 'results': [{'message_id': '0:1555090669194719%abead538f9fd7ecd'}], 'topic_message_id': None}}
DEBUG:root:module_name = emission.net.ext_service.push.notify_interface_impl.firebase
DEBUG:root:module = <module 'emission.net.ext_service.push.notify_interface_impl.firebase' from '/home/ubuntu/e-mission-server/emission/net/ext_service/push/notify_interface_impl/firebase.py'>
DEBUG:root:interface_obj_fn = <function get_interface at 0x7f9c4590b378>
DEBUG:root:interface_obj = <emission.net.ext_service.push.notify_interface_impl.firebase.FirebasePush object at 0x7f9c47dae1d0>
DEBUG:root:interface_obj = <emission.net.ext_service.push.notify_interface_impl.firebase.FirebasePush object at 0x7f9c47dae1d0>
DEBUG:root:firebase push result for ios: success 0 failure 0 results []
DEBUG:root:firebase push result for android: success 1 failure 0 results [{'message_id': '0:1555090669194719%abead538f9fd7ecd'}]
```

**Comment by shankari** [comment]
ok I will test on android as well...

**Comment by shankari** [comment]
@valin1 I have debugged the iOS side and it is a real issue!
Basically, the firebase configuration for emTripLog has the same APNS Auth Key as emission, probably because I cloned the emission project and wasn't careful enough to test. And apparently nobody has been testing this use case.

If I send a push notification to the emission app, it works

```
DEBUG:root:interface_obj_fn = <function get_interface at 0x7f98fc2c0d90>
DEBUG:root:interface_obj = <emission.net.ext_service.push.notify_interface_impl.firebase.FirebasePush object at 0x7f98fe9f3710>
DEBUG:root:interface_obj = <emission.net.ext_service.push.notify_interface_impl.firebase.FirebasePush object at 0x7f98fe9f3710>
DEBUG:root:firebase push result for ios: success 1 failure 0 results [{'message_id': '0:1555614629102759%697a1786697a1786'}]
DEBUG:root:firebase push result for android: success 0 failure 0 results []
```

Let me first fix this configuration.

**Comment by shankari** [comment]
wait no, that is the expected behavior - the same key is supposed to work for all apps.

> Apple Push Notifications service (APNs)
> Establish connectivity between your notification server and the Apple Push Notification service. One key is used for all of your apps.

**Comment by shankari** [comment]
ok I know the fix, at least on iOS. It is essentially the change from emission -> embase
https://github.com/e-mission/e-mission-docs/issues/373#issuecomment-482453863

I know you tested it and it didn't work. However, this is because we also cache the tokens to avoid re-querying firebase every time. So when you re-ran after making the fix, the script used the old cached token, which was generated for the wrong package name and so it didn't work.

This should not affect you any more since you are working with a new database anyway ().
So if you ensure that the package is `application": "edu.berkeley.eecs.embase` and try to generate push notifications on iOS now, it should work. If you run into a similar error on iOS again, just clear out `edb.get_push_token_mapping_db()` and retry. That is basically a cache so deleting it should be safe and will almost always fix the problem.

Testing done (iOS only):
- with `application": "edu.berkeley.eecs.emission`, tried to send notification to emission app - worked
- changed to `application": "edu.berkeley.eecs.embase`, tried to send notification to emission app - still worked (due to caching)
- cleared out entry for this token from the cache
    ```
    In [262]: edb.get_push_token_mapping_db().delete_one({"native_token": "e187d4ec87f91883d
     ...: ad4ab5b99357302f297d757fe6ae8ce72bb516220558f9a"})
    Out[262]: <pymongo.results.DeleteResult at 0x7f670c045a88>
    ```
- now, tried to send notification to emission app - failed
- uninstalled emission and installed emTrip log
- tried to send notification to emTripLog app - succeeded

**Comment by shankari** [comment]
And I just tried to send on android and it worked just fine

```
DEBUG:root:interface_obj_fn = <function get_interface at 0x7fce15601d90>
DEBUG:root:interface_obj = <emission.net.ext_service.push.notify_interface_impl.firebase.FirebasePush object at 0x7fce185356d8>
DEBUG:root:interface_obj = <emission.net.ext_service.push.notify_interface_impl.firebase.FirebasePush object at 0x7fce185356d8>
DEBUG:root:firebase push result for ios: success 0 failure 0 results []
DEBUG:root:firebase push result for android: success 1 failure 0 results [{'message_id': '0:1555622441483179%abead538f9fd7ecd'}]
```

<img width=250 src="https://user-images.githubusercontent.com/2423263/56392239-c14d8980-61e5-11e9-93d4-d2ce138fdae9.png">

**Comment by shankari** [comment]
@valin1 I will make the package name configurable, but you should be unblocked for now.
