### ISSUE TITLE
Error on Force Sync

### ISSUE THREAD

**Issue by MythriNagaraju** [e-mission/e-mission-docs#378]
I am running into this error on Force Sync. I suspected it occurred only when there are no trips to log to the server, but it also shows up otherwise.

![force_sync_error](https://user-images.githubusercontent.com/1181774/56161597-c230b200-5f7e-11e9-967c-5f44c20db400.PNG)

**Comment by shankari** [comment]
@MythriNagaraju the error popup tells you the line number where the error occurred. Maybe you can look there, and at the logs generated right before the error to see what is going on. I don't have access to your source code, and the popup is not very informative otherwise.

**Comment by shankari** [comment]
I am going to assume that this is related to the failing force sync in #377. Please reopen if it turns out to be some substantive.
