### ISSUE TITLE
How can I import all my trips data into MongoDB (Windows10)

### ISSUE THREAD

**Issue by myaman17** [e-mission/e-mission-docs#379]
How can I import all my trips data into MongoDB, which can be read from scripts in my e-mission-server. I am using a PC with Windows10.

**Comment by shankari** [comment]
do you already have the trip data exported, or do you need to export it first?

**Comment by myaman17** [comment]
I already have multiple .gz files of trips data.

**Comment by shankari** [comment]
Did you check the docs? I think I sent a link to this doc to you earlier as well
https://github.com/e-mission/e-mission-docs/blob/master/docs/e-mission-server/requesting_data_as_a_collaborator.md
Look at the "Load the data" section

**Comment by myaman17** [comment]
I got it. I could successfully import my data into MongoDB. Thank you a lot!
