### ISSUE TITLE
Issue: Getting zero output for cleaned_place

### ISSUE THREAD

**Issue by myaman17** [e-mission/e-mission-docs#380]
I am using the following code for getting the number of cleaned_place for each subject. 
```
all_users = pd.DataFrame(list(edb.get_uuid_db().find({}, {"user_email":1, "uuid": 1, "_id": 0})))
all_users_unique = all_users.uuid.unique()

for i in range(len(all_users.uuid.unique())):
    test_user_id = all_users_unique[i]
    ts = esta.TimeSeries.get_time_series(test_user_id)
    cp_df = ts.get_data_df("analysis/cleaned_place", time_query=None)
    print(len(cp_df))
```
My issue is that I am getting 106 as the output of cleaned_place for one user, but all the other users' output for claned_place is zero.

**Comment by shankari** [comment]
@myaman17 have you run the pipeline? "Run the pipeline" step of 
https://github.com/e-mission/e-mission-docs/blob/master/docs/e-mission-server/requesting_data_as_a_collaborator.md

**Comment by myaman17** [comment]
I run the script, though I am getting the following error: 
```
File "C:\Users\megum\e-mission-server\bin\intake_multiprocess.py", line 5, in <module>
    from future import standard_library
ImportError: No module named future
```

**Comment by shankari** [comment]
Searching for that error in the existing issues 
https://github.com/e-mission/e-mission-docs/search?q=%22No+module+named+future%22&type=Issues 
returns 
https://github.com/e-mission/e-mission-docs/issues/327

Can you try the solution there?

**Comment by shankari** [comment]
Closing this because I assume it is the same issue.
