### ISSUE TITLE
Intake_multiprocess.py Output not Running Pipeline

### ISSUE THREAD

**Issue by ecvick85** [e-mission/e-mission-docs#381]
Due to the recent movement/mounting of a new disk with the e-mission-server directory in it, I had to edit the cronjob to accommodate for the new placement of the server directory. After doing so, running the pipeline (without the cronjob) to test, intake_multiprocess.py ran but gave me the following output...

```
ubuntu@ip-******: $ cd /new_disk/e-mission-server && PYTHONPATH=. /home/ubuntu/miniconda3/envs/emission/bin/python bin/intake_multiprocess.py 3
storage not configured, falling back to sample, default configuration
Connecting to database URL localhost
overpass not configured, falling back to default overleaf.de
transit stops query not configured, falling back to default
storage not configured, falling back to sample, default configuration
Connecting to database URL localhost
storage not configured, falling back to sample, default configuration
Connecting to database URL localhost
storage not configured, falling back to sample, default configuration
Connecting to database URL localhost
overpass not configured, falling back to default overleaf.de
transit stops query not configured, falling back to default
overpass not configured, falling back to default overleaf.de
transit stops query not configured, falling back to default
overpass not configured, falling back to default overleaf.de
transit stops query not configured, falling back to default 
```

Do you have any tips? I checked issues and the docs, and couldn't find anything regarding `overpass not configured, falling back to default overleaf.de` or `transit stops query not configured, falling back to default` I don't know what's stopping the pipeline from running.

**Comment by shankari** [comment]
neither `overpass not configured`, nor `transit stops query not configured` should stop the pipeline from running, because as they print out, they fallback to defaults. What do you see in the pipeline logs?

**Comment by ecvick85** [comment]
In the pipeline logs I see the same thing ... 

```
Connecting to database URL localhost
overpass not configured, falling back to default overleaf.de
transit stops query not configured, falling back to default
storage not configured, falling back to sample, default configuration
Connecting to database URL localhost
overpass not configured, falling back to default overleaf.de
transit stops query not configured, falling back to default
storage not configured, falling back to sample, default configuration
Connecting to database URL localhost
overpass not configured, falling back to default overleaf.de
transit stops query not configured, falling back to default
storage not configured, falling back to sample, default configuration
Connecting to database URL localhost
overpass not configured, falling back to default overleaf.de
transit stops query not configured, falling back to default
storage not configured, falling back to sample, default configuration
Connecting to database URL localhost
overpass not configured, falling back to default overleaf.de
transit stops query not configured, falling back to default
```

**Comment by shankari** [comment]
@ecvick85 which pipeline log?

**Comment by ecvick85** [comment]
That was the incorrect file -- my mistake. In the intake.log file we see ...

```
2019-04-16 18:00:04,272:INFO:140284612998912:processing UUID list = []
2019-04-16 19:00:04,182:INFO:140389958465280:processing UUID list = []
```

I am assuming that there are no UUID's for the pipeline to run on, and therefore it isn't executing on anything. Therefore this is not a problem with the command line in the crontab, but rather our UUIDs. I think it s because google_auth isn't producing a UUID as of now, for it looks as though a related error is happening with google_auth in webserver logs ...

```
Traceback (most recent call last):
  File "emission/net/api/cfc_webapp.py", line 467, in getUUID
    retUUID = enaa.getUUID(request, auth_method, inHeader)
  File "/new_disk/e-mission-server/emission/net/auth/auth.py", line 63, in getUUID
    retUUID = getUUIDFromToken(authMethod, userToken)
  File "/new_disk/e-mission-server/emission/net/auth/auth.py", line 37, in getUUIDFromToken
    userEmail = AuthMethodFactory.getAuthMethod(authMethod).verifyUserToken(token)
  File "/new_disk/e-mission-server/emission/net/auth/google_auth.py", line 67, in verifyUserToken
    verifiedEmail = self.__verifyTokenFields(tokenFields, "audience", "issuer")
  File "/new_disk/e-mission-server/emission/net/auth/google_auth.py", line 34, in __verifyTokenFields
    (tokenFields, audienceKey))
ValueError: Invalid token {'error': 'invalid_token', 'error_description': 'Invalid Value'}, does not contain audience

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/new_disk/e-mission-server/emission/net/api/bottle.py", line 997, in _handle
    out = route.call(**args)
  File "/new_disk/e-mission-server/emission/net/api/bottle.py", line 1998, in wrapper
    rv = callback(*a, **ka)
  File "emission/net/api/cfc_webapp.py", line 294, in updateUserProfile
    user_uuid = getUUID(request)
  File "emission/net/api/cfc_webapp.py", line 474, in getUUID
    abort(401, e.message)
AttributeError: 'ValueError' object has no attribute 'message'
```

So from my understanding, the pipeline should run on our UUIDs once google_auth is fixed and produces UUIDs. Please let me know if my intuition is wrong.

**Comment by shankari** [comment]
@ecvick85 nice try, but I don't think that is it. It is true that the google auth is failing and that is expected since the client has not yet been updated; I am waiting on the migration script.

However, you should still have the users from before the switch, and they should have uuids. Is there more in the intake log? Two lines may not give the full picture.

**Comment by ecvick85** [comment]
The intake log only has those two (now three) lines. The webserver.log file also shows no indication of my UUID when starting emTripLog either. If it isn't google_auth - what may be causing the lost UUIDs?

**Comment by shankari** [comment]
you can check whether the uuids are in the database. See the top of the Timeseries_sample for an example of how to retrieve users (and uuids).

**Comment by ecvick85** [comment]
It doesn't look like they are (given the empty df), after running the Timeseries_sample example:

```
>>> import emission.core.get_database as edb
storage not configured, falling back to sample, default configuration
Connecting to database URL localhost
>>> import pandas as pd
>>> all_users = pd.DataFrame(list(edb.get_uuid_db().find({}, {"user_email":1, "uuid": 1, "_id": 0})))
>>> all_users
Empty DataFrame
Columns: []
Index: []
```

**Comment by shankari** [comment]
ok so it looks like as part of the migration, your database got messed up. You can also try a more basic query:

```
edb.get_uuid_db().find().count()
```

but if that returns `0`, then your database appears to be empty.

You can also try a couple of other collections to see if anything is retrievable

```
edb.get_timeseries_db().find().count()
edb.get_analysis_timeseries_db().find().count()
```

**Comment by ecvick85** [comment]
So it looks as though there are timeseries in the database, but still no UUIDs. 

```
>>> import emission.core.get_database as edb
storage not configured, falling back to sample, default configuration
Connecting to database URL localhost
>>> edb.get_uuid_db().find().count()
0
>>> edb.get_timeseries_db().find().count()
682
```

Any tips on how to retrieve UUIDs or at least get the current timeseries through the pipeline?

**Comment by shankari** [comment]
the timeseries may just be the server stats.

```
edb.get_timeseries_db().distinct('metadata.key')
```

will tell you what they are

**Comment by ecvick85** [comment]
ah yes it is just `['stats/server_api_time']` ... looks like all the previous data is gone. Once our new data is attached to a UUID with google_auth, is it safe to assume the pipeline will run again?

**Comment by shankari** [comment]
yes, but I would spend some time trying to figure out what happened to the previous data. 
- If you don't know the root cause of why this happened, how do you know that it won't happen again once the study has started?
- One of our goals was to start the final analysis with the data that you have so far and make sure you are collecting all the data required. Then, once the study is over, we can just re-run with the real data. But that is not possible if you don't have any data at this point.

**Comment by shankari** [comment]
Spoke to @ecvick85 in person; it turns out that they mounted a new disk for more storage on the same mount point as the existing data (e.g. mount mongodb stores data in `/data/db` and she mounted the new disk on `/data`). Clearly, this masks all the old data. We can still recover it by unmounting the new disk, but have decided to defer that since the study plans to start soon.
