### ISSUE TITLE
Missing R, MainActivity, BuildConfig in custom client

### ISSUE THREAD

**Issue by xubowenhaoren** [e-mission/e-mission-docs#383]
Expected behavior: `ionic cordova build android` to build the unmodified Emission app correctly

Problem: 
Missing MainActivity, R, BuildConfig
Taken from output log, full log [attached][build_log.txt](https://github.com/e-mission/e-mission-docs/files/3105144/build_log.txt)

`/Users/bowenxu2/Documents/GitHub/e-mission-phone/platforms/android/src/edu/berkeley/eecs/emission/cordova/tracker/location/TripDiaryStateMachineForegroundService.java:3: error: cannot find symbol
import edu.berkeley.eecs.emission.MainActivity;
  symbol:   class MainActivity
location: package edu.berkeley.eecs.emission`

`/Users/bowenxu2/Documents/GitHub/e-mission-phone/platforms/android/src/edu/berkeley/eecs/emission/cordova/tracker/location/LocationChangeIntentService.java:3: error: cannot find symbol
import edu.berkeley.eecs.emission.R;
symbol:   class R
  location: package edu.berkeley.eecs.emission`

`/Users/bowenxu2/Documents/GitHub/e-mission-phone/platforms/android/src/edu/berkeley/eecs/emission/cordova/tracker/location/TripDiaryStateMachineReceiver.java:3: error: cannot find symbol
import edu.berkeley.eecs.emission.BuildConfig; 
symbol:   class BuildConfig
location: package edu.berkeley.eecs.emission`

Details: 
We would like to embed the emission app into our existing native Android project. I began by setting up a local Cordova environment from the `opentoall` branch in [e-mission-phone](https://github.com/e-mission/e-mission-phone/tree/opentoall). I followed the guide [here](https://github.com/e-mission/e-mission-docs/blob/master/docs/e-mission-phone/create_a_new_custom_client.md) and added my `google-services.json`. Note that I didn't generate my `GoogleService-Info.plist` as we haven't set up an Apple dev account yet. 

Working environment
MacOS Mojave 10.14.4
`ionic -v 3.19.1`
`cordova -v 8.0.0` 
`gradle -v 5.4`
`java version "1.8.0_212"
Java(TM) SE Runtime Environment (build 1.8.0_212-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.212-b10, mixed mode)`

**Comment by shankari** [comment]
> Expected behavior: ionic cordova build android to build the unmodified Emission app correctly

Not sure why this would be expected behavior. Those are not the build instructions in the README. The README says 'cordova build prepare` and then `cordova build android`

Can you please list all the commands that you ran to get the above output?
And thank you for the detailed issue description!

**Comment by xubowenhaoren** [comment]
I have followed the steps on the build instructions [here](https://github.com/e-mission/e-mission-docs/blob/master/docs/e-mission-phone/create_a_new_custom_client.md). 
I initially didn't set up an iOS App ID, and `cordova prepare` complains 
`(node:94705) UnhandledPromiseRejectionWarning: Error: Source path does not exist: GoogleService-Info.plist
    at updatePathInternal (/Users/bowenxu2/Documents/GitHub/e-mission-phone/platforms/ios/cordova/node_modules/cordova-common/src/FileUpdater.js:145:19)
    at /Users/bowenxu2/Documents/GitHub/e-mission-phone/platforms/ios/cordova/node_modules/cordova-common/src/FileUpdater.js:223:19
    at Array.forEach (<anonymous>)
    at Object.updatePaths (/Users/bowenxu2/Documents/GitHub/e-mission-phone/platforms/ios/cordova/node_modules/cordova-common/src/FileUpdater.js:221:33)
    at updateFileResources (/Users/bowenxu2/Documents/GitHub/e-mission-phone/platforms/ios/cordova/lib/prepare.js:506:17)
    at /Users/bowenxu2/Documents/GitHub/e-mission-phone/platforms/ios/cordova/lib/prepare.js:65:13
    at _fulfilled (/Users/bowenxu2/Documents/GitHub/e-mission-phone/platforms/ios/cordova/node_modules/q/q.js:854:54)
    at /Users/bowenxu2/Documents/GitHub/e-mission-phone/platforms/ios/cordova/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/Users/bowenxu2/Documents/GitHub/e-mission-phone/platforms/ios/cordova/node_modules/q/q.js:816:13)
    at /Users/bowenxu2/Documents/GitHub/e-mission-phone/platforms/ios/cordova/node_modules/q/q.js:570:49
(node:94705) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:94705) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. `

After I set up the iOS App ID on Firebase and obtained the `GoogleService-Info.plist`, running `cordova prepare` copies some image files and exits without error codes. The full log can be found here [cordova_prepare.txt](https://github.com/e-mission/e-mission-docs/files/3111476/cordova_prepare.txt)

I ran `cordova build android` again, and the same issue still exists: 

`/Users/bowenxu2/Documents/GitHub/e-mission-phone/platforms/android/src/edu/berkeley/eecs/emission/cordova/tracker/location/TripDiaryStateMachineForegroundService.java:3: error: cannot find symbol import edu.berkeley.eecs.emission.MainActivity; symbol: class MainActivity location: package edu.berkeley.eecs.emission`

`/Users/bowenxu2/Documents/GitHub/e-mission-phone/platforms/android/src/edu/berkeley/eecs/emission/cordova/tracker/location/LocationChangeIntentService.java:3: error: cannot find symbol import edu.berkeley.eecs.emission.R; symbol: class R location: package edu.berkeley.eecs.emission`

`/Users/bowenxu2/Documents/GitHub/e-mission-phone/platforms/android/src/edu/berkeley/eecs/emission/cordova/tracker/location/TripDiaryStateMachineReceiver.java:3: error: cannot find symbol import edu.berkeley.eecs.emission.BuildConfig; symbol: class BuildConfig location: package edu.berkeley.eecs.emission`

The full log can be found here [cordova_build_android.txt](https://github.com/e-mission/e-mission-docs/files/3111488/cordova_build_android.txt)

**Comment by shankari** [comment]
The issue is with the way that the plugin hooks are run. Unfortunately, since you already built android through ionic and don't have the logs of that, I don't know why the plugin hooks didn't run properly.

Please remove the plugins and platforms and rebuild

```
(emission) shankari$ rm -rf platforms/
(emission) shankari$ rm -rf plugins/
(emission) shankari$ ./bin/configure_xml_and_json.js cordovabuild
Copied config.cordovabuild.xml -> config.xml and package.cordovabuild.json -> package.json
(emission) shankari$ cordova platform add android
```

You should see lines like so

```
walk callback with files = ...
```

Then the build will work.

**Comment by shankari** [comment]
The plugin hook modifies the plugin files to change `edu.berkeley.eecs.emission.MainActivity` -> `<your.package.name>.MainActivity` so that everything still works.

**Comment by xubowenhaoren** [comment]
After running `./bin/configure_xml_and_json.js cordovabuild`, I noticed that my `id` field was overwritten from `<my.cutom.package.name>` to `edu.berkeley.eecs.emission`. 

Assuming that was the appropriate behavior, I ran `cordova prepare` and `cordova platform add android`. The log is here: [prepare_android.txt](https://github.com/e-mission/e-mission-docs/files/3114020/prepare_android.txt)

However, running `cordova build android` (no ionic this time) results in a new error: 
`* What went wrong:
Execution failed for task ':processDebugGoogleServices'.
No matching client found for package name 'edu.berkeley.eecs.emission'`
The new log is here: [build_android_new.txt](https://github.com/e-mission/e-mission-docs/files/3114045/build_android_new.txt)

> The plugin hook modifies the plugin files to change `edu.berkeley.eecs.emission.MainActivity` -> `<your.package.name>.MainActivity` so that everything still works.

I then modified `config.cordovabuild.xml` and `prepare_android.txt`, changing their `id` fields to `<my.custom.package.name>`. I restarted the whole process again: 

```
rm -rf platforms/
rm -rf plugins/
./bin/configure_xml_and_json.js cordovabuild
cordova platform add android
cordova build android
```

Unfortunately, the same issue persists: 
`* What went wrong:
Execution failed for task ':processDebugGoogleServices'.
No matching client found for package name 'edu.berkeley.eecs.emission'`

**Comment by shankari** [comment]
> Assuming that was the appropriate behavior, I ran cordova prepare and cordova platform add android. The log is here: prepare_android.txt

That is not expected; you should edit the `config.xml` after running `./bin/configure_xml_and_json.js cordovabuild`

So the first error makes sense - your `config.xml` still says that you are building package `edu.berkeley.eecs.emission` and presumably your `google-services.json` is configured with a different app name.

```
Creating Cordova project for the Android platform:
	Path: platforms/android
	Package: edu.berkeley.eecs.emission
	Name: emission
	Activity: MainActivity
	Android target: android-26
```

> I then modified config.cordovabuild.xml and prepare_android.txt, changing their id fields to <my.custom.package.name>. I restarted the whole process again:
> Unfortunately, the same issue persists:

This is surprising. Can you upload the related log? In particular, it would be interesting to see what package name is detected by `cordova build android` as in the lines above.

**Comment by xubowenhaoren** [comment]
I obtained a fresh new copy of the `e-mission-phone`, `opentoall` branch via the GitHub app. 
```
   master
* opentoall
```
I then enabled the platform hooks and ran the setup config. 
I got the `google-services.json` and `GoogleService-Info.plist` and put them into the project root, and changed the `id/name` field of `package.json` and `config.xml` to `<my.custom.package.name>`. 

I then ran `bower update` and `npm install`. [bower_update.txt](https://github.com/e-mission/e-mission-docs/files/3114507/bower_update.txt) [npm_install.txt](https://github.com/e-mission/e-mission-docs/files/3114508/npm_install.txt)

Since I obtained the local copy directly from my GitHub fork, the upstream was already set and I didn't do anything extra. 

`pod setup` was also trivial. [pod_setup.txt](https://github.com/e-mission/e-mission-docs/files/3114516/pod_setup.txt)

Since I just wanted to test the app without any modifications, I didn't set any config values. 

I then ran `cordova prepare`. The package names for both platforms are the same as in my `google-services.json`. [cordova_prepare.txt](https://github.com/e-mission/e-mission-docs/files/3114553/cordova_prepare.txt)
```
Using cordova-fetch for cordova-ios@^4.5.4
Adding ios project...
Creating Cordova project for the iOS platform:
	Path: platforms/ios
	Package: com.aware.plugin.cmu.sup
	Name: emission
iOS project created with cordova-ios@4.5.5
Discovered platform "android@^6.4.0" in config.xml or package.json. Adding it to the project
Using cordova-fetch for cordova-android@^6.4.0
Adding android project...
Creating Cordova project for the Android platform:
	Path: platforms/android
	Package: com.aware.plugin.cmu.sup
	Name: emission
	Activity: MainActivity
	Android target: android-26
```
I then ran `cordova build android` and the debug apk was generated successfully. [cordova_build_android.txt](https://github.com/e-mission/e-mission-docs/files/3114573/cordova_build_android.txt)

Thanks a lot for your support! I put together this step-by-step so you may point to this issue if someone else runs into similar problems.

**Comment by shankari** [comment]
Thanks @xubowenhaoren! If you can update the instructions at 
https://github.com/e-mission/e-mission-docs/blob/master/docs/e-mission-phone/create_a_new_custom_client.md
to clarify the parts that are unclear, that would also be great!
