### ISSUE TITLE
some "" and null values user_id in the timeseries db

### ISSUE THREAD

**Issue by PatGendre** [e-mission/e-mission-docs#386]
I've found several entries in the timeseries collection with user_id values empty string and null, how can this occur? (we use the skip method auth for the moment)

**Comment by shankari** [comment]
what are the related keys? I bet they are almost all `stats/server_api_time`.

Note that if you access the webapp through a browser, then no authentication is required, so there is no user_id passed in. So all calls to retrieve the webapp pages will have user_id None.

Similarly, all aggregate calls (currently) do not require authentication, so they will have `user_id` = `None`. I haven't seen the empty string before, though. what are the related keys?

**Comment by PatGendre** [comment]
you're right, only stats/server_api_time, even for user_id:"".
Thanks for the explanation.
