### ISSUE TITLE
trips data in usercache Collection

### ISSUE THREAD

**Issue by PatGendre** [e-mission/e-mission-docs#392]
On our instance there are still some data in the usercache Collection which was supposedly not processed by the pipeline. I attach the data as the file is quite small (1 MB), there are few background/battery and config/consent keys but there as also some diary/trips-YYYY-MM-DD keys.

In the code comments, it is said that the diary trips are stored in the usercache for the last 3 days, here we have trips older than 3 days : do you know why this can be?
I checked rapidly in the logs for one trip, grepping the objectid in the pipeline logs, I find that the trip has been "upserted" correctly, nothing more. 
[usercache.json.tar.gz](https://github.com/e-mission/e-mission-docs/files/3130755/usercache.json.tar.gz)

Thanks in advance. It is definitely not an urgent issue, just a question for understanding.

**Comment by shankari** [comment]
> In the code comments, it is said that the diary trips are stored in the usercache for the last 3 days, here we have trips older than 3 days : do you know why this can be?

The usercache has data from the last 3 processed days. If you have no new data or it has not been processed, the usercache won't be updated. Please see the pipeline state information from my thesis for why we use the last processed ts instead of the last run timestamp

**Comment by PatGendre** [comment]
> The usercache has data from the last 3 processed days. 

Thanks, sorry for not having read in sufficient detail, I thought it was the last 3 days but the last 3 _processed_ days is more logical!
