### ISSUE TITLE
Custom client doesn't show welcome screen

### ISSUE THREAD

**Issue by xubowenhaoren** [e-mission/e-mission-docs#394]
Current customization: The e-mission-phone code, `opentoall` branch, has been embedded to a native Android project. In `authenticator.xml` and `ServerSyncPlugin.java`, the `account`, `account_type` and `authority` fields are changed to match with the native project. Other codes and plugins are untouched.

Expected behavior: I should see a welcome screen and be able to click a link to join a specific study. Below is the screenshot of the EmTripLog app which demonstrates the expected behavior. 
![image](https://user-images.githubusercontent.com/20229080/57123855-3ec1df80-6d38-11e9-8167-ef2aa4fd3ac1.png)

Actual behavior: The embed client app "skips" the welcome screen and reaches the "getting started" screen directly. 
![image](https://user-images.githubusercontent.com/20229080/57123904-7761b900-6d38-11e9-80c8-2b69cea387db.png)

When I attempt to proceed and login with my Google account, the app prompts "dummy dev mode": 
![image](https://user-images.githubusercontent.com/20229080/57123969-babc2780-6d38-11e9-8dee-ead344c694ed.png)

I would like to note that before I embedded the Cordova project, I built a debug app using directly the Cordova CLI. The debug app also had no welcome screen. 

A complete log, from the native project launching Cordova activity to the custom client reaching "dummy dev mode" is attached here. [emission_login_log.txt](https://github.com/e-mission/e-mission-docs/files/3140928/emission_login_log.txt)

Working environment: 
Android Studio 3.3.2
Build #AI-182.5107.16.33.5314842, built on February 15, 2019
JRE: 1.8.0_152-release-1248-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.4

**Comment by shankari** [comment]
@xubowenhaoren emTripLog is not the main e-mission app. It is an alternate version, built from 
https://github.com/e-mission/e-mission-base
that has all the native plugins installed but a very minimal UX.
It is intended to be used by groups that want to customize the UX but do not want to build and publish an app to the stores.

Since you are not building a base app that other studies can join, you don't need the welcome screen.
The e-mission app is the one built from 
https://github.com/e-mission/e-mission-phone
and it does not have a welcome screen.

**Comment by shankari** [comment]
> Current customization: The e-mission-phone code, opentoall branch, has been embedded to a native Android project. In authenticator.xml and ServerSyncPlugin.java, the account, account_type and authority fields are changed to match with the native project. Other codes and plugins are untouched.

I'm not sure what you mean by these. If you only changed `authenticator.xml` and `ServerSyncPlugin.java`, the `account, account_type and authority fields` are changed to match with the native project. then you are still building a hybrid app in that the UX is javascript and it interfaces with native plugins.

So how is this different from the previous "debug app" that you built.

> I would like to note that before I embedded the Cordova project, I built a debug app using directly the Cordova CLI. The debug app also had no welcome screen.

**Comment by shankari** [comment]
> When I attempt to proceed and login with my Google account, the app prompts "dummy dev mode":

https://github.com/e-mission/e-mission-docs/blob/487edf956bf92c2f8f06647f25e33b7330729e4f/docs/e-mission-both/configuring_authentication.md

https://github.com/e-mission/e-mission-docs/blob/0bf397e6460b912d3026fc9daace878f13711526/docs/e-mission-server/deploying_your_own_server_to_production.md

**Comment by xubowenhaoren** [comment]
> > Current customization: The e-mission-phone code, opentoall branch, has been embedded to a native Android project. In authenticator.xml and ServerSyncPlugin.java, the account, account_type and authority fields are changed to match with the native project. Other codes and plugins are untouched.
> 
> I'm not sure what you mean by these. If you only changed the set of files above to match with the native project, then you are still building a hybrid app in that the UX is javascript and it interfaces with native plugins.
> 
> So how is this different from the previous "debug app" that you built?
> 
> > I would like to note that before I embedded the Cordova project, I built a debug app using directly the Cordova CLI. The debug app also had no welcome screen.

I only mean that the issue exists in the "original" debug app; I didn't introduce the issue while embedding it to the native project. 
I have yet to find a solution. I've switched to building `e-mission-base` instead, as a workaround. With the `e-mission-base` client, I was able to properly log in with my google account.

**Comment by shankari** [comment]
ah if you want to login via the google account, you need to set up authentication correctly
For obvious reasons, the authentication credentials are not checked in to the opentoall branch :)
