### ISSUE TITLE
Autoreload in e-mission-phone

### ISSUE THREAD

**Issue by atton16** [e-mission/e-mission-docs#395]
The `e-mission-phone` does not perform `autoreload` as expected when the code changes. The only thing that does work is the development server refreshes and ready to serve the new code. So when I change the code I have to force-exit the app / open the app / connect to the server again. 

At first I thought this is whole Modify-Force Exit-Launch-Connect loop is normal and I have been working with this pain in my mind until I saw @shankari 's short video clip demonstrating the autoreload functionality of phonegap is performed correctly within the clip.

I have tested and found out that in my environment, the `devapp` did not even try to call `/__api__/autoreload` and hence **no** reload occurs.

I have tested on both Android and iOS and got the same result.

Perhaps there is something that I am missing?

Please note that I am using the latest release version of `e-mission-devapp` (v2.1.0).

**Comment by shankari** [comment]
The index.html needs to be in a particular format for the websocket to work.
As you can see from the history for `index.html` this is the commit that made those changes
https://github.com/e-mission/e-mission-phone/commit/8893a329806c5d4a2113e280ce3f7a180e4011ac#diff-ab469c2203f00940178ab4d78eacaad6

Is your `index.html` in that format?

**Comment by atton16** [comment]
It was initially

```
<script src="cordova.js"></script>
```

After I watched the clip mentioned before, I looked up on the stackoverflow and found the same suggestion.

I tried both

```
<script type="text/javascript" src="cordova.js"></script>
```

```
<script type="text/javascript" charset="utf-8" src="cordova.js"></script>
```

But still no luck.

As for CSP, the CSP suggested on the commit is the same as what I have atm.

**Comment by shankari** [comment]
can you first try on unmodified master and confirm that it works? Then, you just need to diff what you have with unmodified master and figure out what the difference is.

**Comment by shankari** [comment]
you should know that the autoreload works by rewriting the `index.html` so it is very picky in terms for formatting (e.g. if your CSP looks the same but is in multiple lines, it will fail).

If everything works right, in the `index.html` in the simulator, you should see that after the `cordova.js` tag, a bunch of code dealing with the autoreload has been inserted.

```
 <script type="text/javascript" src="cordova.js"></script><script type="text/javascript" src="http://127.0.0.1:3000/socket.io/socket.io.js"></script><script type="text/javascript">//
// Reload the app if server detects local change
//
```

**Comment by atton16** [comment]
It just worked when I tried with your suggestion the second time. Not sure why it did not work the first time I tried it out.

```
<script type="text/javascript" src="cordova.js"></script>
```

However, the one with `charset="utf-8"` definitely not working.

I am closing the issue now.
