### ISSUE TITLE
ground truth matching : Error while inferring modes

### ISSUE THREAD

**Issue by PatGendre** [e-mission/e-mission-docs#398]
I have an error when running the inference stage of the pipeline. I attach the message.
The error occurs when overpass returns a null response in [transit_matching](https://github.com/shankari/e-mission-server/blob/db1978c0854603612bb7483aa1becdab688e979d/emission/net/ext_service/transit_matching/match_stops.py#L30)

The `get_public_transit_stops` method should return a empty stop list when overpass does not return any result?

**Comment by PatGendre** [comment]
we added 2 lines just after the nominatim request.post call : 
`    if response == None:
        return []
    if response.json() == None:
return []`

this prevents the exception to occur, but maybe there is a more appropriate solution to the issue?

**Comment by shankari** [comment]
I looked at some pending changes that I had from the tripaware deployment, and apparently we fixed it by retrying (see below). Let me merge the pending changes now....

```
-    all_results = response.json()["elements"]
+    try:
+        all_results = response.json()["elements"]
+    except json.decoder.JSONDecodeError as e:
+        logging.info("Unable to decode response with status_code %s, text %s" %
+            (response.status_code, response.text))
+        time.sleep(5)
+        logging.info("Retrying after 5 second sleep")
+        response = requests.post("http://overpass-api.de/api/interpreter", data=overpass_query)
+        all_results = response.json()["elements"]
+
```

**Comment by PatGendre** [comment]
Ok, thank you, these lines from tripaware seem definitely useful to minimize the number of null responses.

**Comment by shankari** [comment]
Fixed in https://github.com/e-mission/e-mission-server/pull/578/commits/dc60ccdfab34e0be4fe76154911243e648085672
