### ISSUE TITLE
App behavior when connectionConfig is not set up

### ISSUE THREAD

**Issue by xubowenhaoren** [e-mission/e-mission-docs#403]
Last week, we found out that the HTTP 500 issue (https://github.com/e-mission/e-mission-docs/issues/397) was due to connectionConfig not properly set up. To resolve this issue and let e-mission sync properly, we would need to deploy new connectionConfig profiles on our server (call this server A). However, we are trying to build a hybrid app, and the native app also has syncing functionalities with another server of ours (call this server B). We wish to somehow disable the syncing feature in e-mission to save battery life. 

Expected outcome: e-mission functions as an offline component of the native app. It still logs the trip, triggers surveys, but doesn't sync with server A. All processing should be done on the phone. 

What would be the actual outcome? I've heard that some of the finalizing steps of trip segmentation are actually done on server A. Please correct me if I'm wrong. Thanks!

**Comment by shankari** [comment]
@xubowenhaoren 

> We wish to somehow disable the syncing feature in e-mission to save battery life.

I am not sure why you think that disabling the syncing feature in e-mission would save battery life.
e-mission syncs to the server at a pretty coarse frequency (roughly every hour) and the sync frequency is configurable to be even lower.

> What would be the actual outcome? I've heard that some of the finalizing steps of trip segmentation are actually done on server A. Please correct me if I'm wrong. Thanks!

Yes, there is an analysis pipeline that runs on the server. Please see the architecture paper (sent via email) for more details and ask specific questions if you have them.

**Comment by xubowenhaoren** [comment]
Thanks!

**Comment by shankari** [comment]
Link to arch tech report http://www2.eecs.berkeley.edu/Pubs/TechRpts/2019/EECS-2019-88.html if needed.
