### ISSUE TITLE
Restore Survey Answers

### ISSUE THREAD

**Issue by atton16** [e-mission/e-mission-docs#404]
Hi,

I am developing the survey system based on `enketo-core` as you already knows it.

Right at the time the form validation is done, we can get the data using `$scope.form.getDataStr()`.

I then tried to use this data by convert the return string to XMLDocument as the library suggested. Then use the data like followings:

```js
var dataStrFromValidation = '...';

var data = {
  modelStr: $scope.loaded_model,
  instanceStr: 'answer',
  submitted: false,
  external: [{
    id: 'answer',
    xml: (new window.DOMParser()).parseFromString(dataStrFromValidation, 'text/xml'),
  }],
  session: {}
};
```

However, there seems to be the problem with parsing XMLDocument.

See the screenshot below:

<img width="299" alt="Screen Shot 2019-05-22 at 15 15 48" src="https://user-images.githubusercontent.com/5247367/58158393-8cc96380-7ca4-11e9-98ee-e09b92a84082.png">

Here is the sample data returned from validation
```xml
<trip-end-survey_v5
  xmlns:jr="http://openrosa.org/javarosa"
  xmlns:odk="http://www.opendatakit.org/xforms"
  xmlns:orx="http://openrosa.org/xforms"
  id="trip-end-survey_v5"
  version="veMfY6eZ2W9qoGhmfzJX8F">
  <start>2019-05-21T21:14:28.317+07:00</start>
  <end>2019-05-21T21:14:28.320+07:00</end>
  <group_vs9ga59>
    <trip_purpose_main>1</trip_purpose_main>
    <trip_purpose_sub_category/>
  </group_vs9ga59>
  <group_ee9rk21>
    <travel_mode_main>vehicle</travel_mode_main>
    <travel_mode_sub_category>4</travel_mode_sub_category>
    <Total_people_in_trip_party>1</Total_people_in_trip_party>
    <Non_household_member_s_on_trip>2</Non_household_member_s_on_trip>
    <Household_member_s_on_trip>5</Household_member_s_on_trip>
    <group_bn3jd79>
      <Vehicle_trip_with_2_Driver_or_passenger>1</Vehicle_trip_with_2_Driver_or_passenger>
      <Vehicle_trip_Parking_location>5</Vehicle_trip_Parking_location>
      <Parking_cost>10</Parking_cost>
    </group_bn3jd79>
    <Rail_payment_method/>
    <Transit_fees_AUD/>
    <Taxi_fees/>
  </group_ee9rk21>
  <__version__>vLX8oPb8xP2pLvxNBagygU</__version__>
  <_version_>vwpCadzPYVsW9XEjxZzwnR</_version_>
  <_version__001>vSuFDQ2DcmpRpKcRfSXReq</_version__001>
  <_version__002>veMfY6eZ2W9qoGhmfzJX8F</_version__002>
  <meta>
    <instanceID>uuid:25c045ff-e8e6-4799-acdb-7d15f8f80b70</instanceID>
  </meta>
</trip-end-survey_v5>
```

**Comment by shankari** [comment]
@atton16 yes it is pretty clear that something is undefined. not sure whether it is the `DOMParser` or the method or the string. Maybe add some more logging/check the debugger to figure it out?

Also, the `external` field is not intended to pre-populate the values in the form; it is intended to pre-populate the *options* in the form - e.g. list of countries or list of cities.
http://xlsform.org/en/#external-xml-data
or https://duckduckgo.com/?q=xlsforms+external&t=ffsb&ia=web

**Comment by shankari** [comment]
There is also some additional discussion and a live example in https://github.com/XLSForm/pyxform/issues/30

**Comment by shankari** [comment]
FYI, I have confirmed that the DOMParser is available on both Firefox and Safari - e.g.

<img width="1440" alt="Screen Shot 2019-05-22 at 10 19 44 AM" src="https://user-images.githubusercontent.com/2423263/58194731-30058300-7c7b-11e9-9e65-9b7889192add.png">

**Comment by atton16** [comment]
> There is also some additional discussion and a live example in [XLSForm/pyxform#30](https://github.com/XLSForm/pyxform/issues/30)

Thanks, I am looking at it now.

**Comment by atton16** [comment]
It appears that the correct field is `instanceStr`.

So the code should looks like this:

```js
var dataStrFromValidation = '...';

var data = {
  modelStr: $scope.loaded_model,
  instanceStr: dataStrFromValidation,
  submitted: false,
  external: [],
  session: {}
};
```

Very simple!!

**Comment by shankari** [comment]
Closing, implemented in https://github.com/e-mission/e-mission-phone/pull/572
