### ISSUE TITLE
Breakdown of the trip segmentation algorithm

### ISSUE THREAD

**Issue by xubowenhaoren** [e-mission/e-mission-docs#427]
To better understand the algorithm behind the trip segmentation plugin and to migrate it, we dived into the logs and made a breakdown. Please comment on any incorrect or missing parts. Thanks! 

#### Before the trip starts 
- In edu.berkeley.eecs.emission.cordova.tracker, `BootReceiver` gets called by the Android system as soon as the phone gets booted. 
- `BootReceiver` then sends a broadcast `R.string.transition_initialize`. `TripDiaryStateMachineReceiver` gets called. It then calls `TripDiaryStateMachineService`.
`TripDiaryStateMachineService : in start state, sending initialize`
- When initializing a trip, `TripDiaryStateMachineService` calls `TripDiaryStateMachineForegroundService`. 
`TripDiaryStateMachineForegroundService : onStartCommand called on oreo+, starting foreground service`
- Also, it creates a GeoFence at the current location. We went dormant and waited a GeoFence exit event to signal the start of a new trip.
`CreateGeofenceAction : creating geofence at location Location[fused 24.XXX,114.XXX hAcc=78 et=+6h4m17s115ms vAcc=??? sAcc=??? bAcc=???]`
- Now we wait for the trip to start. 
`TripDiaryStateMachineService : newState after handling action is local.state.waiting_for_trip_start`
#### During the trip
- When the user exits the GeoFence, it means that he/she is on the go. `GeofenceExitIntentService` gets called. 
```
GeofenceExitIntentService : onStartCommand called with intent Intent { cmp=com.aware.plugin.cmu.sup/edu.berkeley.eecs.emission.cordova.tracker.location.GeofenceExitIntentService (has extras) } flags 0 startId 1
GeofenceExitIntentService : got geofence intent callback with type 2 and location Location[fused 36.XXX,117.XXX hAcc=3 et=+12h0m47s821ms alt=145.35443115234375 vel=1.62 bear=2.0 vAcc=4 sAcc=??? bAcc=??? {Bundle[mParcelledData.dataSize=52]}]
GeofenceExitIntentService : Geofence exited! Intent = Intent { cmp=com.aware.plugin.cmu.sup/edu.berkeley.eecs.emission.cordova.tracker.location.GeofenceExitIntentService (has extras) } Starting ongoing monitoring...
TripDiaryStateMachineService : service started with flags = 0 startId = 1 action = local.transition.exited_geofence
```
- `LocationTrackingActions` then calls `LocationChangeIntentService`, which calls `TripDiaryStateMachineForegroundService`. 
    - This is where the notification “Recording location” gets displayed. 
- It keeps track of the locations update: 
```
LocationChangeIntentService : FINALLY! Got location update, intent is Intent { cmp=com.aware.plugin.cmu.sup/edu.berkeley.eecs.emission.cordova.tracker.location.LocationChangeIntentService (has extras) }
LocationChangeIntentService : Extras keys are [com.google.android.location.LOCATION, com.google.android.gms.location.EXTRA_LOCATION_RESULT]
LocationChangeIntentService : Read location Location[fused 36.XXX,117.XXX hAcc=3 et=+12h0m47s821ms alt=145.35443115234375 vel=1.62 bear=2.0 vAcc=4 sAcc=??? bAcc=??? {Bundle[mParcelledData.dataSize=52]}] from intent
```
- Then it calls the cache DB and determines whether we have a trip completed: 
```
BuiltinUserCache : While searching for regex of last transition, got 0 results
BuiltinUserCache : While searching for all, got 2 results
BuiltinUserCache : Considering transition 1.56085205268E9: {"currState":"local.state.waiting_for_trip_start","transition":"local.transition.exited_geofence","ts":1.560852052679E9}
BuiltinUserCache : Considering transition 1.560832069945E9: {"currState":"local.state.start","transition":"local.transition.initialize","ts":1.560832069944E9}
```
#### After the trip
- How the algorithm decides the end of a trip: Take 10 most recent location points. Take another 10 location points from 5 minutes ago. Then calculate the distances respectively. If both indicate that the user stops moving, mark `stoppedMoving = true`
If there’s not enough evidence, continue collecting data. 
```
LocationChangeIntentService : After filtering at -1.0 number of points goes from 41 -> 41
LocationChangeIntentService : last10Points.length = 10
LocationChangeIntentService : points5MinsAgo.length = 41
LocationChangeIntentService : last5MinsSpan = 276.0 secs, threshold + fuzz = 270
LocationChangeIntentService : maxDistance = 14.526287078857422 TRIP_END_RADIUS = 100
LocationChangeIntentService : stoppedMoving: stoppedMoving = true
LocationChangeIntentService : maxDistance = 118.92298889160156 TRIP_END_RADIUS = 100
LocationChangeIntentService : stoppedMoving: stoppedMoving = false
LocationChangeIntentService : isTripEnded: stoppedMoving = false
```
- If stoppedMoving = true for both methods (`stoppedMoving, isTripEnded`), mark the end of the trip. Generate the notification. 
```
LocationChangeIntentService : stoppedMoving: stoppedMoving = true
LocationChangeIntentService : isTripEnded: stoppedMoving = true
LocationChangeIntentService : Finished broadcasting state change to receiver, ending trip now
TripDiaryStateMachineRcvr : TripDiaryStateMachineReciever onReceive(android.app.ReceiverRestrictedContext@2829887, Intent { act=local.transition.stopped_moving flg=0x10 pkg=com.aware.plugin.cmu.sup cmp=com.aware.plugin.cmu.sup/edu.berkeley.eecs.emission.cordova.tracker.location.TripDiaryStateMachineReceiver (has extras) }) called
TransitionNotificationReceiver : Received platform-specification notification local.transition.stopped_moving
TransitionNotificationReceiver : Broadcasting generic transition trip_ended and generating notification
```

**Comment by shankari** [comment]
@xubowenhaoren that looks pretty correct!
Couple of notes:

> When initializing a trip, TripDiaryStateMachineService calls TripDiaryStateMachineForegroundService.
TripDiaryStateMachineForegroundService : onStartCommand called on oreo+, starting foreground service

This is really a short-lived service that is used to perform operations in the background due to restrictions on oreo+ - you can read more about the details on why this is needed https://github.com/e-mission/e-mission-docs/issues/325 On older phones, we will create the geofence directly

> How the algorithm decides the end of a trip:

This happens continuously during the trip because obviously the app doesn't know, a priori, that we have ended the trip.

> If stoppedMoving = true for both methods (stoppedMoving, isTripEnded), mark the end of the trip. Generate the notification.

This involves two different plugins (modularity!) since displaying a notification is not an essential part of detecting that the trip has ended. In the architecture paper
https://www2.eecs.berkeley.edu/Pubs/TechRpts/2019/EECS-2019-88.pdf
this is in the local processing versus transition notifier modules.

**Comment by shankari** [comment]
> Then it calls the cache DB and determines whether we have a trip completed:

Also, note that the cache DB is also in a separate module (database in the paper). So you can theoretically swap in another database as long as it supports the same interface (no code changes to the data collection module) or a similar interface (will require minor code changes). If you have an existing database + sync mechanism, then using the existing database may be an easy integration point.

**Comment by shankari** [comment]
All ongoing tracking for the native plugin migration is happening in #410, so I'm closing this now.
