### ISSUE TITLE
No destinations listed for choose destination

### ISSUE THREAD

**Issue by valin1** [e-mission/e-mission-docs#440]
We tested on Trevor's simulator as well as our phones and there are no destinations listed in the choose destination even after having cleaned trips. Trevor will attach the screenshots below.

**Comment by shankari** [comment]
@valin1 @trevor-wu I don't see any updates here.
Not that screenshots are a reasonable debugging tool anyway. Ideally you would look at the logs, figure out what is going on and who made the relevant change...

**Comment by trevor-wu** [comment]
Sorry for the delay: here is the error log:
START 2019-07-22 22:31:43.306311 POST /result/metrics/timestamp
START 2019-07-22 22:31:43.314973 POST /profile/update
END 2019-07-22 22:31:43.332569 POST /profile/update f3dc99ea-889d-40f5-985b-b7c31093685f 0.017080068588256836 
END 2019-07-22 22:31:43.668267 POST /result/metrics/timestamp f3dc99ea-889d-40f5-985b-b7c31093685f 0.36139392852783203 
START 2019-07-22 22:31:45.641560 POST /timeline/getTrips/2019-07-22
START 2019-07-22 22:31:45.646706 POST /pipeline/get_complete_ts
END 2019-07-22 22:31:45.651186 POST /pipeline/get_complete_ts f3dc99ea-889d-40f5-985b-b7c31093685f 0.004105091094970703 
END 2019-07-22 22:31:45.680608 POST /timeline/getTrips/2019-07-22 f3dc99ea-889d-40f5-985b-b7c31093685f 0.038971900939941406 
START 2019-07-22 22:31:46.088905 POST /datastreams/find_entries/timestamp
END 2019-07-22 22:31:46.109965 POST /datastreams/find_entries/timestamp f3dc99ea-889d-40f5-985b-b7c31093685f 0.020949840545654297 
START 2019-07-22 22:31:46.245801 POST /datastreams/find_entries/timestamp
START 2019-07-22 22:31:46.267481 POST /datastreams/find_entries/timestamp
END 2019-07-22 22:31:46.275282 POST /datastreams/find_entries/timestamp f3dc99ea-889d-40f5-985b-b7c31093685f 0.029379844665527344 
END 2019-07-22 22:31:46.284144 POST /datastreams/find_entries/timestamp f3dc99ea-889d-40f5-985b-b7c31093685f 0.016589879989624023 
START 2019-07-22 22:31:48.580468 POST /timeline/getTrips/2019-07-21
START 2019-07-22 22:31:48.581422 POST /pipeline/get_complete_ts
END 2019-07-22 22:31:48.591475 POST /pipeline/get_complete_ts f3dc99ea-889d-40f5-985b-b7c31093685f 0.009968757629394531 
Found error 'NoneType' object has no attribute 'get_id' while processing trip Entry({'_id': ObjectId('5d369b7ace81ca9d2cd1c053'), 'metadata': {'write_ts': 1563728433.5726352, 'key': 'analysis/cleaned_trip', 'time_zone': 'America/Los_Angeles', 'write_local_dt': {'minute': 0, 'hour': 10, 'second': 33, 'day': 21, 'weekday': 6, 'month': 7, 'timezone': 'America/Los_Angeles', 'year': 2019}, 'write_fmt_time': '2019-07-21T10:00:33.572635-07:00', 'platform': 'server'}, 'data': {'end_ts': 1563726461.733742, 'end_loc': {'type': 'Point', 'coordinates': [-71.08652964131221, 42.36277828905417]}, 'start_fmt_time': '2019-07-21T12:08:47.539901-04:00', 'end_place': ObjectId('5d349a319258b92a815414ca'), 'end_fmt_time': '2019-07-21T12:27:41.733742-04:00', 'raw_trip': ObjectId('5d349a309258b92a81541498'), 'source': 'DwellSegmentationDistFilter', 'start_ts': 1563725327.539901, 'start_loc': {'type': 'Point', 'coordinates': [-71.10239446488428, 42.36430680157185]}, 'end_local_dt': {'minute': 27, 'hour': 12, 'second': 41, 'day': 21, 'weekday': 6, 'month': 7, 'timezone': 'America/New_York', 'year': 2019}, 'start_place': ObjectId('5d33ab1d9258b921d317ca6f'), 'duration': 1134.1938409805298, 'start_local_dt': {'minute': 8, 'hour': 12, 'second': 47, 'day': 21, 'weekday': 6, 'month': 7, 'timezone': 'America/New_York', 'year': 2019}, 'distance': 2284.1260446362166}, 'user_id': UUID('f3dc99ea-889d-40f5-985b-b7c31093685f')})
Traceback (most recent call last):
  File "/Users/trevorwu/urap-2018/urap2018-2019/e-mission-server/emission/analysis/plotting/geojson/geojson_feature_converter.py", line 284, in get_geojson_for_timeline
    trip_geojson = trip_to_geojson(trip, tl)
  File "/Users/trevorwu/urap-2018/urap2018-2019/e-mission-server/emission/analysis/plotting/geojson/geojson_feature_converter.py", line 229, in trip_to_geojson
    start_place_geojson = place_to_geojson(curr_start_place)
  File "/Users/trevorwu/urap-2018/urap2018-2019/e-mission-server/emission/analysis/plotting/geojson/geojson_feature_converter.py", line 76, in place_to_geojson
    ret_feature.id = str(place.get_id())
AttributeError: 'NoneType' object has no attribute 'get_id'
END 2019-07-22 22:31:48.631111 POST /timeline/getTrips/2019-07-21 f3dc99ea-889d-40f5-985b-b7c31093685f 0.05051684379577637 
Traceback (most recent call last):
  File "/Users/trevorwu/urap-2018/urap2018-2019/e-mission-server/emission/net/api/bottle.py", line 997, in _handle
    out = route.call(**args)
  File "/Users/trevorwu/urap-2018/urap2018-2019/e-mission-server/emission/net/api/bottle.py", line 1998, in wrapper
    rv = callback(*a, **ka)
  File "emission/net/api/cfc_webapp.py", line 262, in getTrips
    ret_geojson = timeline.get_trips_for_day(user_uuid, day, force_refresh)
  File "/Users/trevorwu/urap-2018/urap2018-2019/e-mission-server/emission/net/api/timeline.py", line 41, in get_trips_for_day
    return gfc.get_geojson_for_dt(user_uuid, start_dt, end_dt)
  File "/Users/trevorwu/urap-2018/urap2018-2019/e-mission-server/emission/analysis/plotting/geojson/geojson_feature_converter.py", line 274, in get_geojson_for_dt
    return get_geojson_for_timeline(user_id, tl)
  File "/Users/trevorwu/urap-2018/urap2018-2019/e-mission-server/emission/analysis/plotting/geojson/geojson_feature_converter.py", line 289, in get_geojson_for_timeline
    raise e
  File "/Users/trevorwu/urap-2018/urap2018-2019/e-mission-server/emission/analysis/plotting/geojson/geojson_feature_converter.py", line 284, in get_geojson_for_timeline
    trip_geojson = trip_to_geojson(trip, tl)
  File "/Users/trevorwu/urap-2018/urap2018-2019/e-mission-server/emission/analysis/plotting/geojson/geojson_feature_converter.py", line 229, in trip_to_geojson
    start_place_geojson = place_to_geojson(curr_start_place)
  File "/Users/trevorwu/urap-2018/urap2018-2019/e-mission-server/emission/analysis/plotting/geojson/geojson_feature_converter.py", line 76, in place_to_geojson
    ret_feature.id = str(place.get_id())
AttributeError: 'NoneType' object has no attribute 'get_id'
/Users/trevorwu/anaconda3/envs/emission/lib/python3.6/sre_parse.py:864: DeprecationWarning: Flags not at the start of the expression \{\{((?:(?mx)(       (truncated)
  p = _parse_sub(source, pattern, True, False)
START 2019-07-22 22:31:48.754707 POST /datastreams/find_entries/timestamp
END 2019-07-22 22:31:48.817251 POST /datastreams/find_entries/timestamp f3dc99ea-889d-40f5-985b-b7c31093685f 0.06245708465576172 
START 2019-07-22 22:31:48.950795 POST /datastreams/find_entries/timestamp
START 2019-07-22 22:31:48.957642 POST /datastreams/find_entries/timestamp
START 2019-07-22 22:31:49.005798 POST /datastreams/find_entries/timestamp
START 2019-07-22 22:31:49.017006 POST /datastreams/find_entries/timestamp
END 2019-07-22 22:31:49.033831 POST /datastreams/find_entries/timestamp f3dc99ea-889d-40f5-985b-b7c31093685f 0.08289003372192383 
END 2019-07-22 22:31:49.039108 POST /datastreams/find_entries/timestamp f3dc99ea-889d-40f5-985b-b7c31093685f 0.0813908576965332 
START 2019-07-22 22:31:49.043366 POST /datastreams/find_entries/timestamp
START 2019-07-22 22:31:49.048034 POST /datastreams/find_entries/timestamp
START 2019-07-22 22:31:49.051988 POST /datastreams/find_entries/timestamp
END 2019-07-22 22:31:49.115789 POST /datastreams/find_entries/timestamp f3dc99ea-889d-40f5-985b-b7c31093685f 0.10961294174194336 
END 2019-07-22 22:31:49.148678 POST /datastreams/find_entries/timestamp f3dc99ea-889d-40f5-985b-b7c31093685f 0.10057902336120605 
END 2019-07-22 22:31:49.149174 POST /datastreams/find_entries/timestamp f3dc99ea-889d-40f5-985b-b7c31093685f 0.13210010528564453 
END 2019-07-22 22:31:49.174991 POST /datastreams/find_entries/timestamp f3dc99ea-889d-40f5-985b-b7c31093685f 0.131547212600708 
END 2019-07-22 22:31:49.184875 POST /datastreams/find_entries/timestamp f3dc99ea-889d-40f5-985b-b7c31093685f 0.1328291893005371 
START 2019-07-22 22:32:01.424584 POST /timeline/getTrips/2019-07-21
START 2019-07-22 22:32:01.426122 POST /pipeline/get_complete_ts
END 2019-07-22 22:32:01.430429 POST /pipeline/get_complete_ts f3dc99ea-889d-40f5-985b-b7c31093685f 0.004241228103637695 
Found error 'NoneType' object has no attribute 'get_id' while processing trip Entry({'_id': ObjectId('5d369b7ace81ca9d2cd1c053'), 'metadata': {'write_ts': 1563728433.5726352, 'key': 'analysis/cleaned_trip', 'time_zone': 'America/Los_Angeles', 'write_local_dt': {'minute': 0, 'hour': 10, 'second': 33, 'day': 21, 'weekday': 6, 'month': 7, 'timezone': 'America/Los_Angeles', 'year': 2019}, 'write_fmt_time': '2019-07-21T10:00:33.572635-07:00', 'platform': 'server'}, 'data': {'end_ts': 1563726461.733742, 'end_loc': {'type': 'Point', 'coordinates': [-71.08652964131221, 42.36277828905417]}, 'start_fmt_time': '2019-07-21T12:08:47.539901-04:00', 'end_place': ObjectId('5d349a319258b92a815414ca'), 'end_fmt_time': '2019-07-21T12:27:41.733742-04:00', 'raw_trip': ObjectId('5d349a309258b92a81541498'), 'source': 'DwellSegmentationDistFilter', 'start_ts': 1563725327.539901, 'start_loc': {'type': 'Point', 'coordinates': [-71.10239446488428, 42.36430680157185]}, 'end_local_dt': {'minute': 27, 'hour': 12, 'second': 41, 'day': 21, 'weekday': 6, 'month': 7, 'timezone': 'America/New_York', 'year': 2019}, 'start_place': ObjectId('5d33ab1d9258b921d317ca6f'), 'duration': 1134.1938409805298, 'start_local_dt': {'minute': 8, 'hour': 12, 'second': 47, 'day': 21, 'weekday': 6, 'month': 7, 'timezone': 'America/New_York', 'year': 2019}, 'distance': 2284.1260446362166}, 'user_id': UUID('f3dc99ea-889d-40f5-985b-b7c31093685f')})
Traceback (most recent call last):
  File "/Users/trevorwu/urap-2018/urap2018-2019/e-mission-server/emission/analysis/plotting/geojson/geojson_feature_converter.py", line 284, in get_geojson_for_timeline
    trip_geojson = trip_to_geojson(trip, tl)
  File "/Users/trevorwu/urap-2018/urap2018-2019/e-mission-server/emission/analysis/plotting/geojson/geojson_feature_converter.py", line 229, in trip_to_geojson
    start_place_geojson = place_to_geojson(curr_start_place)
  File "/Users/trevorwu/urap-2018/urap2018-2019/e-mission-server/emission/analysis/plotting/geojson/geojson_feature_converter.py", line 76, in place_to_geojson
    ret_feature.id = str(place.get_id())
AttributeError: 'NoneType' object has no attribute 'get_id'
END 2019-07-22 22:32:01.464051 POST /timeline/getTrips/2019-07-21 f3dc99ea-889d-40f5-985b-b7c31093685f 0.039350032806396484 
Traceback (most recent call last):
  File "/Users/trevorwu/urap-2018/urap2018-2019/e-mission-server/emission/net/api/bottle.py", line 997, in _handle
    out = route.call(**args)
  File "/Users/trevorwu/urap-2018/urap2018-2019/e-mission-server/emission/net/api/bottle.py", line 1998, in wrapper
    rv = callback(*a, **ka)
  File "emission/net/api/cfc_webapp.py", line 262, in getTrips
    ret_geojson = timeline.get_trips_for_day(user_uuid, day, force_refresh)
  File "/Users/trevorwu/urap-2018/urap2018-2019/e-mission-server/emission/net/api/timeline.py", line 41, in get_trips_for_day
    return gfc.get_geojson_for_dt(user_uuid, start_dt, end_dt)
  File "/Users/trevorwu/urap-2018/urap2018-2019/e-mission-server/emission/analysis/plotting/geojson/geojson_feature_converter.py", line 274, in get_geojson_for_dt
    return get_geojson_for_timeline(user_id, tl)
  File "/Users/trevorwu/urap-2018/urap2018-2019/e-mission-server/emission/analysis/plotting/geojson/geojson_feature_converter.py", line 289, in get_geojson_for_timeline
    raise e
  File "/Users/trevorwu/urap-2018/urap2018-2019/e-mission-server/emission/analysis/plotting/geojson/geojson_feature_converter.py", line 284, in get_geojson_for_timeline
    trip_geojson = trip_to_geojson(trip, tl)
  File "/Users/trevorwu/urap-2018/urap2018-2019/e-mission-server/emission/analysis/plotting/geojson/geojson_feature_converter.py", line 229, in trip_to_geojson
    start_place_geojson = place_to_geojson(curr_start_place)
  File "/Users/trevorwu/urap-2018/urap2018-2019/e-mission-server/emission/analysis/plotting/geojson/geojson_feature_converter.py", line 76, in place_to_geojson
    ret_feature.id = str(place.get_id())
AttributeError: 'NoneType' object has no attribute 'get_id'
START 2019-07-22 22:32:01.582294 POST /datastreams/find_entries/timestamp
END 2019-07-22 22:32:01.628298 POST /datastreams/find_entries/timestamp f3dc99ea-889d-40f5-985b-b7c31093685f 0.04591202735900879 
START 2019-07-22 22:32:01.788183 POST /datastreams/find_entries/timestamp
START 2019-07-22 22:32:01.802273 POST /datastreams/find_entries/timestamp
START 2019-07-22 22:32:01.819508 POST /datastreams/find_entries/timestamp
END 2019-07-22 22:32:01.843692 POST /datastreams/find_entries/timestamp f3dc99ea-889d-40f5-985b-b7c31093685f 0.05542802810668945 
START 2019-07-22 22:32:01.844373 POST /datastreams/find_entries/timestamp
START 2019-07-22 22:32:01.853875 POST /datastreams/find_entries/timestamp
END 2019-07-22 22:32:01.859242 POST /datastreams/find_entries/timestamp f3dc99ea-889d-40f5-985b-b7c31093685f 0.056899070739746094 
START 2019-07-22 22:32:01.875163 POST /datastreams/find_entries/timestamp
START 2019-07-22 22:32:01.882379 POST /datastreams/find_entries/timestamp
END 2019-07-22 22:32:01.928566 POST /datastreams/find_entries/timestamp f3dc99ea-889d-40f5-985b-b7c31093685f 0.08322691917419434 
END 2019-07-22 22:32:01.932475 POST /datastreams/find_entries/timestamp f3dc99ea-889d-40f5-985b-b7c31093685f 0.1124868392944336 
END 2019-07-22 22:32:01.975748 POST /datastreams/find_entries/timestamp f3dc99ea-889d-40f5-985b-b7c31093685f 0.09305191040039062 
END 2019-07-22 22:32:01.994043 POST /datastreams/find_entries/timestamp f3dc99ea-889d-40f5-985b-b7c31093685f 0.11880779266357422 
END 2019-07-22 22:32:02.007618 POST /datastreams/find_entries/timestamp f3dc99ea-889d-40f5-985b-b7c31093685f 0.15366911888122559

**Comment by trevor-wu** [comment]
![67360772_469539673607442_8827776209971576832_n](https://user-images.githubusercontent.com/35517530/62751289-fe998980-ba17-11e9-8586-e4907c78a8d5.png)
![67287458_333734324238022_4254011260959457280_n](https://user-images.githubusercontent.com/35517530/62751291-ff322000-ba17-11e9-86dc-89e39d71b754.png)

**Comment by shankari** [comment]
> Sorry for the delay: here is the error log:

This is the **server** log. You need to check the **client** log.

**Comment by shankari** [comment]
My last merge to this branch has screenshots showing the popup working
https://github.com/e-mission/e-mission-phone/pull/574

After that, @trevor-wu checked in a bunch of commits and posted screenshots indicating that it worked https://github.com/e-mission/e-mission-phone/pull/582#issuecomment-508909258

And then he changed variable names. And the testing screenshot after that does not include any screenshots of this working.

**Comment by shankari** [comment]
rip greentrip.
