### ISSUE TITLE
Pushing trip-end survey notification in native Android migration

### ISSUE THREAD

**Issue by xubowenhaoren** [e-mission/e-mission-docs#441]
Hello, 

We've run into issues pushing trip-end survey notification in the migration of the trip segmentation plugin for a native Android project. We've identified the source of the issue at [line 144 in TransitionNotificationNotifier.java](https://github.com/e-mission/e-mission-transition-notify/blob/1c3f25da7477e7d26b66335abfa098e1e1e35f62/src/android/TransitionNotificationReceiver.java#L144): 
```
            JSONObject notifyConfigWrapper = UserCacheFactory.getUserCache(context).getLocalStorage(eventName, false);
            if (notifyConfigWrapper == null) {
                Log.d(context, TAG, "no configuration found for event "+eventName+", skipping notification");
                return;
        }
```
According to our previous communication, `notifyConfigWrapper` fetches the user-custom format in Javascript to customize the trip-end survey page. However, this feature is not required in our study project as of yet. How should we change the code so it opens up a custom `Activity` and launch a survey? 

Another relevant question: in our migration, where is the `UserCache` stored and in which database format? (SQLite perhaps?) Is there documentation specifying the table structure?

**Comment by shankari** [comment]
@xubowenhaoren can you please add this to the existing migration issue so that we have one thread that has all the requirements, and documents all the changes required?
