### ISSUE TITLE
Error while forcing sync

### ISSUE THREAD

**Issue by atton16** [e-mission/e-mission-docs#448]
I got a report that there is an error in forcing sync (screenshot below)

![69393620_2575630522467904_5383326809263702016_n](https://user-images.githubusercontent.com/5247367/64102175-967d5f80-cd99-11e9-87b3-6409618550b3.jpg)

I have looked into the code in `general-settings.js:318` and found that the snippet is trying to call `getEndTransition` function. But the function is no where to be found in such file.

Here is the snippet from line `317-323`
```js
            var isTripEnd = function(entry) {
                if (entry.metadata.key == getEndTransition()) {
                    return true;
                } else {
                    return false;
                }
            };
```

Can you please clarify to me where should I find the declaration of `getEndTransition` function?

**Comment by atton16** [comment]
After I looked closely into the file, I found `getEndTransitionKey` that has somewhat similar use case with other functions in the same file. Perhaps this is just a typo??

**Comment by shankari** [comment]
This was fixed back in May in the master branch
https://github.com/e-mission/e-mission-phone/search?q=getEndTransition&type=Commits
