### ISSUE TITLE
Some users in stage_Profiles collection are not in stage_uuids collection

### ISSUE THREAD

**Issue by PatGendre** [e-mission/e-mission-docs#451]
While testing the survey requests, I've found that we had 7 more entries in the Profiles collection than in the uuid collection. (and so for theses 7 entries there was no e-mail - and no data - and the survey could not be sent to them)

So the question is: "why can we have more entries in stage_Profiles than in stage_uuids?"

For 6 of the 7 entries, the last update_ts is May or earlier so we don't have any logs. For 1 of the entries, we have some logs in July, and the user with the uuid seems to have been quite active.

**Comment by PatGendre** [comment]
I remove by hand the uuid which were in the Profiles and not in the uuid, it is cleaner now and may have been due to improper data. restoration when the db was attacked. So I close the issue.
FYI: 3 of the removed users had also some data in the usercache and pipeline.

**Comment by shankari** [comment]
@PatGendre if you had actual location entries, you could plot them to see their locations and figure out their home/work locations. which would give you a sense of who they are. But if you deleted the entries, too late now :(

**Comment by PatGendre** [comment]
@shankari
 no i have saved the entries, i can try to locate the (very few) trips, good idea:-)

**Comment by PatGendre** [comment]
@shankari I have checked, one may be me (with another login), the other one may be user in the paris area I know and anyway I have told him that older data were being deleted anyway...
