### ISSUE TITLE
how to clean the usercache collection?

### ISSUE THREAD

**Issue by PatGendre** [e-mission/e-mission-docs#455]
We have a few user with a lot of entries in the usercache collection in mongob : 
`2019-09-06 11:04:04,603:DEBUG:139878968489728:For 3ccd84c1-aeaf-4c74-9067-464966d49b1d, found 82162 messages in usercache
bdbfe145-3b66-4eb4-91c4-4a34f44dfe36, found 86221 messages in usercache
2019-09-06 11:04:04,912:DEBUG:139878968489728:For bbf7ae66-7068-4592-9736-a2aec0ab9251, found 37047 messages in usercache
2019-09-06 11:04:05,017:DEBUG:139878968489728:For 6c0249c4-dcc7-4520-9aec-cf32f2a75c13, found 46756 messages in usercache
`
The users are all iOS users, may be by coincidence.
Every night usually the pipeline run without any error but the number of messages continues to grow.

**Comment by PatGendre** [comment]
I checked in the logs, I have very long usercache/put dumps with many motion_activity entries (a single usercache/put log make 2.2MB and takes 4 seconds to complete!).
So it will be useful to clean the usercache db even if the issue is fixed and background/motion_activity entries don't accumulate any more.

**Comment by shankari** [comment]
I would delete all usercache entries before the time that you applied the fix. Otherwise, you may end up deleting entries that have not yet been processed.

e.g.

`deleteMany({"metadata.key": "background/motion_activity", "metadata.write_ts": {"$lte": <timestap for update>}})`

**Comment by shankari** [comment]
@PatGendre I have included the patch in #434

**Comment by PatGendre** [comment]
Ok thank you!
for the moment I have deleted the entries before Sep 1, and when we apply the patch I will delete the more recent data before the time the fix will be apply.
