### ISSUE TITLE
white screen on the live channel

### ISSUE THREAD

**Issue by atton16** [e-mission/e-mission-docs#457]
Hi,

The app is displayed white screen on the live channel after I update the branch (`rk-unsw`) to keep updated with the master.

I am not sure what cause this since the app is working just fine in development environment.

Can you please guide me the approach to debug this?

Cheers,
Attawit

**Comment by atton16** [comment]
I have checked the e-mission-phone log and found that there is a problem executing `/usr/src/app/hooks/before_prepare/download_translation.js`. I fixed it.

Now there is a missing file....

```bash
[phonegap] Running command: /usr/src/app/hooks/before_prepare/download_translation.js /usr/src/app
[phonegap] starting app server...
[phonegap] listening on 172.19.0.5:3000
[phonegap] 
[phonegap] ctrl-c to stop the server
[phonegap] 
Using cordova-fetch for cordova-browser@~5.0.0


Adding browser project...

Creating Cordova project for cordova-browser:
	Path: /usr/src/app/platforms/browser

	Name: emission

Running command: /usr/src/app/hooks/before_prepare/download_translation.js /usr/src/app

Running command: /usr/src/app/hooks/after_prepare/010_add_platform_class.js /usr/src/app

add to body class: platform-browser

Running command: /usr/src/app/hooks/after_prepare/015_copy_icon_to_drawable.js /usr/src/app

Android platform not specified, skipping...

Running command: /usr/src/app/hooks/after_prepare/020_copy_notification_icons.js /usr/src/app

Android platform not specified, skipping...

Error: ENOENT: no such file or directory, stat '/usr/src/app/package-hooks/ios9_allow_http.sh'


[phonegap] Running command: /usr/src/app/hooks/before_prepare/download_translation.js /usr/src/app
[phonegap] Running command: /usr/src/app/hooks/after_prepare/010_add_platform_class.js /usr/src/app
add to body class: platform-browser
[phonegap] Running command: /usr/src/app/hooks/after_prepare/015_copy_icon_to_drawable.js /usr/src/app
Android platform not specified, skipping...
[phonegap] Running command: /usr/src/app/hooks/after_prepare/020_copy_notification_icons.js /usr/src/app
Android platform not specified, skipping...
```

**Comment by shankari** [comment]
`/usr/src/app/package-hooks/ios9_allow_http.sh` is added as part of the 
> Enable platform hooks, including http on iOS9

But this should not affect WSOD on a channel since the channel does not build native code. Let me take a look.

**Comment by shankari** [comment]
The error is 

```
Uncaught Error: [$injector:modulerr] Failed to instantiate module emission due to:
Error: [$injector:modulerr] Failed to instantiate module pascalprecht.translate due to:
Error: [$injector:nomod] Module 'pascalprecht.translate' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
```

I didn't update all the newly added javascript libraries to the channel before deploying.
Fixing now...

**Comment by shankari** [comment]
So this is super weird, but apparently `bower update` and `bower update --force` don't work to update the libraries. I had to manually add the newly added packages. Pushing the changes soon...

**Comment by shankari** [comment]
fixed now. Note to self (and others): after running `bower update`, check `www/lib/` to ensure that packages newly added to `bower.json` have actually been installed. If they are not there, install them manually (e.g. `bower install <pkg>`

**Comment by shankari** [comment]
FYI for others investigating similar issues, you can install the emTripLog apk in the android emulator by dragging and dropping it, and connect to it with Chrome to see the error logs. The released apks are available in the releases https://github.com/e-mission/e-mission-phone/releases
