### ISSUE TITLE
Change the log out so that the user get disconnected (and data cleared): gdpr issue

### ISSUE THREAD

**Issue by PatGendre** [e-mission/e-mission-docs#472]
Hi @shankari 
We have a requirement from our partner in Nantes who asks that for GDPR compliance, we change the app behaviour so that the user really get disconnected when he/she logs out.
The user would be warned that when she/he logs out, the local data in app cache would be cleared, but this would also prevent that another logs user logs in and sees the data of the user previously logged in.

How would you implement this change in the app? It is not clear to us. Clearing the data seems easy as there is already a button for that in the profile screen, however, logging out does not seem so simple. For example, the user would have to re-accept the terms of use when logging in again, although he has already accepted the terms.
Thanks for any advice.

**Comment by shankari** [comment]
I think it is important to have a list of exactly what you want to accomplish with the log out.
- clearing local data: as you point out, there is an existing API for this
- returning to the login screen: we control which screen is launched on startup here
https://github.com/e-mission/e-mission-phone/blob/b1e73b8e59ce3c674ac895dc94d26b3fabf83af0/www/js/splash/startprefs.js#L164
which calls
https://github.com/e-mission/e-mission-phone/blob/b1e73b8e59ce3c674ac895dc94d26b3fabf83af0/www/js/splash/startprefs.js#L110

So resetting `intro_done` in memory and storage will ensure that we will always go back to the onboarding steps.

> For example, the user would have to re-accept the terms of use when logging in again, although he has already accepted the terms.

Is that a problem? The user accepted the terms of use when they logged in the first time, but then they logged out. Before they log in again, potentially as a different user, it seems reasonable that they can refresh their memory on the terms of use.

**Comment by shankari** [comment]
FYI, this is a dup of #141, which also has some questions. Closing this to concentrate discussion there. I think that we really need to figure out what the requirements are - implementing the requirements will not be as challenging.
