### ISSUE TITLE
what happens if the intake pipeline is launched twice?

### ISSUE THREAD

**Issue by PatGendre** [e-mission/e-mission-docs#473]
I launched inadvertently the pipeline twice.
In the intake_launcher.log, the 2X3 process are launched.
However in the intake-errors.log, I have a few errors like this one :

```
2019-11-25 09:16:33,783:ERROR:140099547424512:Found error curr_state.curr_run_ts
 = 1574669715.9499054 while processing pipeline for user bbf7ae66-7068-4592-9736
-a2aec0ab9251, skipping
Traceback (most recent call last):
  File "/var/emission/e-mission-server/emission/pipeline/intake_stage.py", line 
72, in run_intake_pipeline
    run_intake_pipeline_for_user(uuid)
  File "/var/emission/e-mission-server/emission/pipeline/intake_stage.py", line 
162, in run_intake_pipeline_for_user
    uh.storeViewsToCache()
  File "/var/emission/e-mission-server/emission/net/usercache/builtin_usercache_
handler.py", line 107, in storeViewsToCache
    time_query = esp.get_time_range_for_output_gen(self.user_id)
  File "/var/emission/e-mission-server/emission/storage/pipeline_queries.py", li
ne 161, in get_time_range_for_output_gen
    return get_time_range_for_stage(user_id, ps.PipelineStages.OUTPUT_GEN)
  File "/var/emission/e-mission-server/emission/storage/pipeline_queries.py", li
ne 234, in get_time_range_for_stage
    assert curr_state.curr_run_ts is None, "curr_state.curr_run_ts = %s" % curr_
state.curr_run_ts
AssertionError: curr_state.curr_run_ts = 1574669715.9499054
```

I understand that it is safe to launch twice the pipeline because at each stage and for each user, there is a check of whether another pipeline is run in parallel, in this case the run time stamp is different and therefore the user is skipped.
Am I correct?

**Comment by shankari** [comment]
This is a known error.

https://github.com/e-mission/e-mission-docs/blob/6a0c1ec9ddc31036d64dfc087458bfa46b94cecf/docs/dev/archi/pipeline_details.md#curr_run_ts---while-processing-pipeline

The `curr_run_ts` essentially acts as a lock for a particular (user, stage) combination. If two processes try to operate on the same stage for the same user, the process that enters the stage first grabs the lock. The process that tries to operate second cannot grab the lock and skips the stage.

@st-patrick I think you were also asking about the pipeline states.

So it should be fine, but I haven't tested it, so you should spot check to make sure that the analysed data looks fine.

**Comment by PatGendre** [comment]
@shankari thanks! sorry I overlooked this troubleshooting section in the pipeline docs.
I am among the 7 users who have an error so I checked my data and it still appears as draft, so I suppose I have to reset the pipeline to the date when the error occurred and rerun the intake pipeline again.

**Comment by PatGendre** [comment]
@shankari I did reset my pipeline but the execution stopped at stage Trip Segmentation because the curr_run_ts was still not null for this stage for my user in the Stage_pipeline_state collection, so I've set it to null manually. And then the intake pipeline could run til the end. And in the app my diary data appeared as processed (not draft anymore).
So it means that the  curr_run_ts assertion check is a good safeguard but that there may additional manual action to correct the analysis data.

**Comment by PatGendre** [comment]
@shankari I [completed a little the doc](https://github.com/fabmob/e-mission-docs/blob/e-mission-contrib/docs/dev/archi/pipeline_details.md)

**Comment by shankari** [comment]
looks good, do you want to submit a PR to the main fork?

**Comment by PatGendre** [comment]
Yes I did : https://github.com/e-mission/e-mission-docs/pull/460

**Comment by lgharib** [comment]
Thank you
