### ISSUE TITLE
the trip diary UI on iOS is incomplete 

### ISSUE THREAD

**Issue by asiripanich** [e-mission/e-mission-docs#482]
Hi

I recently found that on our branch (rk-unsw) the testing iOS devices (all on iOS 13) have a problem displaying processed trips correctly in the diary tab as shown in the attached image. You can see that some elements are missing from the trips such as the timestamps, the outlines, and the mode and distance information. We are not sure if this is a branch specific problem since there are no other issues that are similar to this in recent time. 

![IMG_3403](https://user-images.githubusercontent.com/17020181/71041832-2b0ba200-217e-11ea-96cb-7304604258f9.png)

**Comment by shankari** [comment]
@asiripanich in the logs that you sent me, I consistently see server errors

```
75818,1569895252.159,2019-09-30T19:00:52.159000-07:00,CommunicationHelper : Got response org.apache.http.message.BasicHttpResponse@969ade7 with status HTTP/1.1 521 Origin Down
```

Checking the server from the browser, it is definitely down

<img width="809" alt="Screen Shot 2019-12-17 at 11 36 00 PM" src="https://user-images.githubusercontent.com/2423263/71065407-084d9f00-2126-11ea-9f99-2523fc3d1f1c.png">

Can you try bringing up the server and see if the problem persists? If it does, please send me the logs via email again. Then we can also ask others whether they see similar errors on iOS 13 when connected to their own servers.

**Comment by asiripanich** [comment]
Well Shankari, as you may have already figured out. It was my ignorant that made me think this was an issue with the app without checking my super unreliable server. Sorry for the trouble! :(
