### ISSUE TITLE
iOS location permission during on boarding doesn't show the "always" option

### ISSUE THREAD

**Issue by asiripanich** [e-mission/e-mission-docs#483]
Hi @shankari 

iOS location permission during on boarding doesn't show the "always" option. This means users have to go to their setting to set the option to "always" which adds another complication for some users. I'm not sure if the other developers are experiencing this too. 

![IMG_4014](https://user-images.githubusercontent.com/17020181/71077410-7902c300-21db-11ea-9d33-e1c87ff142f6.png)

**Comment by shankari** [comment]
This is definitely not expected. If you are using emTripLog, then I know for a fact that it has worked in the past, because I haven't changed the code since early this year.

I wonder if this is an iOS 13 issue.
@jf87 @PatGendre @st-patrick are any of you testing on iOS13? Do you see this behavior?

@asiripanich is using
https://e-mission.eecs.berkeley.edu/#/client_setup?new_client=rkunsw&clear_usercache=true&clear_local_storage=true

If this does turn out to be broken on iOS13, I will probably have to bump up the priority of the app update (#465).

**Comment by stephhuerre** [comment]
@shankari @asiripanich 
I just recently updated to iOS13 and have started noticing the same problem.

**Comment by shankari** [comment]
@stephhuerre can you confirm that before the update (on iOS12), you did not have the same problem?

**Comment by shankari** [comment]
@jf87 @PatGendre @st-patrick any more confirmation that this is a change in iOS 13 before we freak out and start focusing on getting the maintenance updates done?

**Comment by PatGendre** [comment]
@shankari no for the moment I am not aware for any user complaining about an iOS13 issue; but our tests are completed for this year, our testers are much less active

**Comment by stephhuerre** [comment]
@shankari I confirm. This is problem is introduced with iOS13. I just tested on the simulator on iOS12.4 and am offered the "Always allow" option the popup.

**Comment by shankari** [comment]
So apparently this is a new feature in iOS 13, and it is not something that we can fix programatically. Apple has designed the UX like this to make it hard for apps to request continuous location access when they don't need it.

https://engineering.q42.nl/apple-location-permission-ios13/ has the outline, but basically, your users have to select "when in use", after some time of background tracking, they will get a report on what has been tracked in the background, and a prompt asking them if they want it to be "always".

> After your app has been tracking the user’s location in the background for a while, iOS will make sure it still has the user’s consent. In this new iOS version this consent renewal dialog will include a small report with the locations your app has been tracking. This makes it more transparent to the user what is happening in the background.

@asiripanich can you confirm this behavior?

So the good news is that there are no code changes required, so this is not tied to the app updates. The bad news is that the instructions for users with iOS12 and iOS13 will be different.

**Comment by asiripanich** [comment]
@shankari Yes, that has been happening on my phone (iOS13).
![Screen Shot 2019-12-23 at 2 09 17 pm](https://user-images.githubusercontent.com/17020181/71333394-e624a880-258d-11ea-8598-85999a741502.png)
