### ISSUE TITLE
Configuring silent push notifications

### ISSUE THREAD

**Issue by stephhuerre** [e-mission/e-mission-docs#486]
Hi @shankari, I'm a little confused with the silent push notifications. I saw there were a few issues on the subject this summer but have a hard time deciphering what the latest status is. 

1) My understanding is that silent push notifications are still required for an optimized use of the app. Is this correct? 

2) To configure the push notifications, I have followed the step 5 of the documentation on creating a new custom client -> https://e-mission.readthedocs.io/en/latest/dev/front/create_a_new_custom_client/

On the server side, e-mission-server-pve/conf/net/ext_service/push.json has to be updated
{
    "provider": "firebase",
    "server_auth_token": "Get from firebase console"
    "app_package_name": "full package name from config.xml. e.g. edu.berkeley.eecs.emission or edu.berkeley.eecs.embase. Defaults to edu.berkeley.eecs.embase"
}

Are these the correct steps for the configuration? 

3) I'm not sure where to find the "server_auth_token" in the firebase console. Can you point me where to go?

4) Is there a protocol to test the silent push notifications? 

Thanks for your input

**Comment by shankari** [comment]
@stephhuerre responses inline.

> My understanding is that silent push notifications are still required for an optimized use of the app. Is this correct?

Yes. The app works fine without the silent push, but as you can see from figures 7.7 and 7.8 of my thesis (https://www2.eecs.berkeley.edu/Pubs/TechRpts/2019/EECS-2019-180.html) the built-in trip end detection is sometimes flaky. If the built-in detection does not work and there are no silent push notifications, sensing will continue until the next trip ends, which could lead to periodic spikes in power consumption on iOS.

> On the server side, e-mission-server-pve/conf/net/ext_service/push.json has to be updated
> Are these the correct steps for the configuration?

You need to configure both the phone app and the server. But that is the only change on the server.

> I'm not sure where to find the "server_auth_token" in the firebase console. Can you point me where to go?

Settings -> Cloud Messaging -> Server key 

I've attached a screenshot

<img width="1054" alt="Screen Shot 2019-12-31 at 11 10 53 AM" src="https://user-images.githubusercontent.com/2423263/71631636-8b5b0480-2bbe-11ea-88d8-b225d55b769c.png">

> Is there a protocol to test the silent push notifications?

When you run the silent push notification script, it will report the successful and failed pushes. You can also check the client logs to ensure that they were received. I believe that turning on the "Simulate user input" option from the developer zone sensing settings will allow you to see the messages as notifications on the UI although I haven't tested this for a super long time.

**Comment by shankari** [comment]
@stephhuerre once you are done with this, can you update the docs to clarify the parts that you found unclear?
https://e-mission.readthedocs.io/en/latest/dev/front/create_a_new_custom_client/

**Comment by stephhuerre** [comment]
Hi @shankari,

**Comment by shankari** [comment]
@stephhuerre are you **sure** you have the json file in the deployed config (e.g. if using docker, have it copied into the docker container?)

because [the only place where the error message above shows up is](https://github.com/e-mission/e-mission-server/search?q=%22push+service+not+configured%2C+push+notifications+not+supported%22&unscoped_q=%22push+service+not+configured%2C+push+notifications+not+supported%22)

```
try:
    push_config_file = open('conf/net/ext_service/push.json')
    push_config = json.load(push_config_file)
except:
    logging.warning("push service not configured, push notifications not supported")
```

**Comment by shankari** [comment]
Assuming this was fixed since the Nantes deployment is complete. @stephhuerre please reopen if this is still an issue.
