### ISSUE TITLE
play store publishing

### ISSUE THREAD

**Issue by bokibocko** [e-mission/e-mission-docs#489]
Hello. I have a question. I publish the app and on the google play console the application has the status of Posted, but in the - Edition management/application version - says - You have a production version that is not featured. What does it mean? Am I was wrong somewhere or should I wait?

**Comment by shankari** [comment]
Where is the "Edition management" screen? I don't see it on my console. Some screenshots would help!

What is the name of your app? Do you find it if you search directly for it in the play store from an android phone?

**Comment by bokibocko** [comment]
![Untitled](https://user-images.githubusercontent.com/45509049/71743785-b61ab680-2e65-11ea-930d-2e6fb0ba4eca.png)
![Untitled1](https://user-images.githubusercontent.com/45509049/71743860-e1050a80-2e65-11ea-9a53-30fdc516ec25.png)

I can't find it in play store.

**Comment by bokibocko** [comment]
![Untitled3](https://user-images.githubusercontent.com/45509049/71762679-9f5e7900-2ed2-11ea-83b5-4e4c26fcfb5e.png)
when I search through play console it shows me where it should be, but when I search for it on play store cannot be found.
![Untitled4](https://user-images.githubusercontent.com/45509049/71762681-a38a9680-2ed2-11ea-821b-ac8148819d21.png)

**Comment by bokibocko** [comment]
![Untitled5](https://user-images.githubusercontent.com/45509049/71762776-e862fd00-2ed3-11ea-945f-9da712f8e801.png)
It says here that it is 100% published.

**Comment by shankari** [comment]
wait, is this related to e-mission in any way? I am not sure why you need e-mission support for an english grammar app.

**Comment by shankari** [comment]
>  when I search through play console it shows me where it should be, but when I search for it on play store cannot be found.

If the "View on Google Play" link is live, then it should be published on google play. If you are not able to find it through a search, try different search terms or contact Google. I am sorry, but I don't have any more insights into google play internals than you do.

**Comment by bokibocko** [comment]
Thanks for taking the time to respond. Maybe I'll try putting it on the play console again. Thank you.

**Comment by shankari** [comment]
why not contact google play support? They should be able to let you know what is going on. Alternatively, put up a web page with appropriate search terms and links to the app on google play

**Comment by bokibocko** [comment]
https://play.google.com/store/apps/details?id=com.playnfungames.grammar_exercise
I tried to put a link on the site but it was not what I wanted so I removed it. I will contact google play service. Thank you.

**Comment by shankari** [comment]
Closing since this does not have anything to do with e-mission
