### ISSUE TITLE
Attribute Error on Data_exploration_template.ipynb

### ISSUE THREAD

**Issue by jesbu1** [e-mission/e-mission-docs#490]
There's an attribute error `AttributeError: module 'emeval.viz.phone_view' has no attribute 'get_geojson_for_leg'` under the `Display the leg` code block in the `data_exploration_template.ipynb`

**Comment by shankari** [comment]
Fixed in https://github.com/e-mission/e-mission-eval-public-data/commit/e4abd561ac1130ab0b627e122169915e17df9527
