### ISSUE TITLE
Failed to installl docker example

### ISSUE THREAD

**Issue by xubowenhaoren** [e-mission/e-mission-docs#496]
Hello, 

I was trying to install the example docker [here](https://github.com/e-mission/e-mission-docker/tree/master/examples/juypter-notebook). However, it failed to deploy the docker image when I ran this: 
`sudo docker-compose -f docker-compose.yml up -d`

The output was:
```
 ---> 681ed722a9db
Step 2/8 : RUN conda env update --name emission --file setup/environment36.notebook.additions.yml
 ---> Running in f35b10eedbb0
Solving environment: ...working... ERROR: Service 'web-server' failed to build: The command '/bin/sh -c conda env update --name emission --file setup/environment36.notebook.additions.yml' returned a non-zero code: 247
```
My exact procedures are [here](https://github.com/xubowenhaoren/emission-docker-setup/blob/master/setup.md). I am using GCP.

**Comment by shankari** [comment]
@xubowenhaoren I am not able to reproduce this on my OSX laptop. Please see the attached log. I am not sure whether this is related to the deployment on GCP - that is not a configuration that I have tested. Can you try to run the same command on your laptop first and check the result?

[docker-compose-success.gz](https://github.com/e-mission/e-mission-docs/files/4121000/docker-compose-success.gz)

**Comment by xubowenhaoren** [comment]
Issue resolved after I re-configured the GCP instance to one with a larger memory spec. It follows that 1 CPU, 1.7 GB RAM is the minimum requirement for a docker container.
