### ISSUE TITLE
explaining how server-initiated surveys work?

### ISSUE THREAD

**Issue by PatGendre** [e-mission/e-mission-docs#50]
Hi, as discussed yesterday, could explain how the surveys / forms in e-mission-servers work and can be reused and adapted? Thanks in advance.

**Comment by shankari** [comment]
@PatGendre you might have already seen this, but there is pretty good documentation for the trip-end surveys. Note that these are generated directly on the phone and do not need any communication with the server.
1. Tutorial: https://github.com/e-mission/e-mission-docs/blob/master/docs/tutorials/change_trip_end_prompt.md
1. More detail on the kinds of data that can be collected: https://github.com/e-mission/e-mission-docs/blob/master/docs/e-mission-both/supporting_user_inputs.md
This also links to documents with more details

If you want to generate a survey from the server (e.g. for all users whose mode share is > 50% bike), you send a push notification from the server. The related scripts are in https://github.com/e-mission/e-mission-server/tree/master/bin/push

I am adding some additional documentation for that use case right now.

**Comment by shankari** [comment]
oh wait, I do have documentation for that use case. I am awesome!
https://github.com/e-mission/e-mission-docs/blob/master/docs/e-mission-server/pushing_surveys_from_the_server_to_the_phone.md

@PatGendre please let me know what is unclear in that and I will clarify.

**Comment by PatGendre** [comment]
thanks Shankari, it seems quite clear! we will test this feature but not for the moment. I close the issue.
