### ISSUE TITLE
correction of a trip’s transportation mode in case of multi-modal trips

### ISSUE THREAD

**Issue by sosias** [e-mission/e-mission-docs#500]
A manual correction of a trip’s transportation mode is not assigned to a specific trip-segment (in case of multi-modal trips)

Manual trip mode overwrite was not intended or available in the pre-existing source code.

The "dfki-App" [branch](https://github.com/e-mission/e-mission-phone/tree/dfki) currently offers a manual selection of the correct transportation mode in addition to the automated server-interpretation, which is stored as a label on the server and shown in the app.

As a next step fields in the server database for additional labels must be created. Then each trip-segment must have a label assigned to it, so that the user has the option to correct each segment’s mode.
-> See image as opposed to current design.

Each label – if used – must then “cover up” the original server-mode. (this way the correction does not interfere with the automated interpretation and the originally interpreted mode remains in the database for research purposes, such as machine learning

![Screen Shot 2020-02-12 at 17 09 07](https://user-images.githubusercontent.com/38495175/74353581-6a3f2380-4dba-11ea-9f87-9afd5a9a942f.png)

**Comment by shankari** [comment]
@sosias 

> Manual trip mode overwrite was not intended or available in the pre-existing source code.

This is incorrect. Manual trip mode overwrite has been supported for a few years, and is currently in the master branch on both the server and the phone.

> The "dfki-App" branch currently offers a manual selection of the correct transportation mode in addition to the automated server-interpretation, which is stored as a label on the server and shown in the app.

the ability to override the trip mode is in master, not just in the DFKI branch.
phone: https://github.com/e-mission/e-mission-phone/search?q=mode_confirm&unscoped_q=mode_confirm
server: https://github.com/e-mission/e-mission-server/search?q=mode_confirm&unscoped_q=mode_confirm

You may want to read the docs: https://github.com/e-mission/e-mission-docs/search?q=confirm&unscoped_q=confirmation
and prior issues, in particular, prior issues from the DFKI team - e.g. https://github.com/e-mission/e-mission-docs/issues/476

**Comment by shankari** [comment]
@sosias Given that mode confirmation is supported in the master branch on both the server and the phone, I am closing this issue. Please re-open if anything is still unclear.
