### ISSUE TITLE
Timeseries_Sample fails trying to create map_list

### ISSUE THREAD

**Issue by EstherEu** [e-mission/e-mission-docs#503]
`map_list = lo.get_maps_for_geojson_trip_list(trips_geojson_list)`

AttributeError :
'PolyLine' object has no attribute 'location'

When we tried to print "trips_geojson_list" the json encoder is failing with this error:
TypeError: Object of type 'ObjectId' is not JSON serializable

The data we used are the shankari_2015-07-22 data.
Any idea what could have caused this? 
We suspect it has something to do with MongoDB's Object_Id attribute.

**Comment by shankari** [comment]
@EstherEu sorry for the late reply - I was out on a 5 day backpacking trip with no connectivity.

For this error,
> AttributeError : 'PolyLine' object has no attribute 'location'

Can you put in the full stacktrace? It seems reasonable that a PolyLine doesn't have a location - it would have a set of locations instead - https://python-visualization.github.io/folium/modules.html#folium.vector_layers.PolyLine

So it seems like we are getting a polyline where we shouldn't be.

> When we tried to print "trips_geojson_list" the json encoder is failing with this error:
> TypeError: Object of type 'ObjectId' is not JSON serializable

You need to use the bson encoder to encode objects retrieved directly from MongoDB - e.g. something like the following.

```
import json
import bson.json_util as bju

json.dumps(trips_geojson_list, indent=4, default=bju.default)
```

This is going to be incredibly verbose, and I would suggest printing out only the important subfields instead.

**Comment by EstherEu** [comment]
```
start_place 5e4bb9a528aa84354f26f0db
end_place 5e4bb9a528aa84354f26f0dc
stop 5e4bb9a428aa84354f26efba
stop 5e4bb9a428aa84354f26efbb
stop 5e4bb9a428aa84354f26efbc
stop 5e4bb9a428aa84354f26efbd
stop 5e4bb9a428aa84354f26efbe
stop 5e4bb9a428aa84354f26efbf
stop 5e4bb9a428aa84354f26efc0
section 5e4bb9a428aa84354f26ef21

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-43-e1b932216091> in <module>
----> 1 map_list = lo.get_maps_for_geojson_trip_list(trips_geojson_list)

~/e-mission-server/emission/analysis/plotting/leaflet_osm/our_plotter.py in get_maps_for_geojson_trip_list(trip_geojson_list)
     74     map_list = []
     75     for trip_doc in trip_geojson_list:
---> 76         curr_map = get_map_for_geojson_trip(trip_doc)
     77         map_list.append(curr_map)
     78     return map_list

~/e-mission-server/emission/analysis/plotting/leaflet_osm/our_plotter.py in get_map_for_geojson_trip(geojson_trip)
    104                 if (section["properties"]["feature_type"] == "section"):
    105                     section_line = get_section_ui(section)
--> 106                     location_points.extend(section_line.location)
    107                     section_line.add_to(m)
    108                 else:

AttributeError: 'PolyLine' object has no attribute 'location'
```

**Comment by shankari** [comment]
@EstherEu 

thanks! sections are represented as folium polylines, so the error is while reading the `location` property. It looks like this will happen for all sections, so I am surprised that I didn't run into this before. I wonder if this is related to an API change in folium.

Let me try to reproduce.

**Comment by shankari** [comment]
Aha! This is almost certainly an API change in folium.

Here's an MPE that works for me

```
$ ./e-mission-ipy.bash
Python 3.6.1 | packaged by conda-forge | (default, May 11 2017, 18:00:28)
Type "copyright", "credits" or "license" for more information.

IPython 5.3.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import folium

In [2]: pl = folium.PolyLine([[1,2], [2,3]])

In [3]: pl.location
Out[3]: [[1, 2], [2, 3]]
```

Which version of folium are you using and how did you install it?
The pinned version of folium in the environment file for ipython notebooks is `folium=0.5.0=py_0`
https://github.com/e-mission/e-mission-server/blob/master/setup/environment36.notebook.yml

**Comment by EstherEu** [comment]
That solved it. I had the wrong version of folium installed.
Thank you!
