### ISSUE TITLE
Implement a custom sign out logic

### ISSUE THREAD

**Issue by asiripanich** [e-mission/e-mission-docs#509]
Hi @shankari, we would like to add more behaviours to the sign out button. As you know our branch uses the embedded survey feature. We would like to prompt a post-experience survey then force sync and sign out when the user uses the sign out button in the Profile tab. Could you please advise how this should be done? I think @atton16 tried something but it crashed the UI.

@atton16 could you let Shankari know what you have tried?

**Comment by atton16** [comment]
I have fixed the UI crash now by moving UI logic to the same file.

Now we have another issue. Please check https://github.com/e-mission/e-mission-phone/pull/624

**Comment by asiripanich** [comment]
superceded by https://github.com/e-mission/e-mission-phone/pull/629
