### ISSUE TITLE
e-mission-phone installation instructions point to inexistent conf file 

### ISSUE THREAD

**Issue by lefterav** [e-mission/e-mission-docs#518]
The following line in the [README](https://github.com/e-mission/e-mission-phone/blob/master/README.md) of e-mission-phone suggests the following installation step
`cp www/json/setupConfig.json.sample www/json/setupConfig.json`

but the former file doesn't exist, so an error is given

**Comment by shankari** [comment]
hm that was supposed to be `startupConfig.json` :)
I'll fix it in tomorrow's PR.

Also, if you don't need to change the startup, you don't need to copy it. I think that's why it hasn't been reported yet - nobody has tried to change it before...
