### ISSUE TITLE
Experiencing a 4 - 5 seconds lag after login

### ISSUE THREAD

**Issue by asiripanich** [e-mission/e-mission-docs#523]
@shankari I'm seeing a 4 - 5 seconds lag before the Google login disappear. 

Nothing serious, just want to report this. An ideal fix would be to put a loading icon when ever the app is loading.

**Comment by shankari** [comment]
After the user logs in to google, the app contacts the server to register. Not sure why the registration should take 4-5 seconds. If you send me the phone and server logs, I can take a look at the source of the slowdown.

**Comment by asiripanich** [comment]
In my case, it returned to the log-in page and stayed there for 4 - 5 seconds before the app ui showed up.

**Comment by shankari** [comment]
Right, so after the google sign in is complete, the server registration call launches. We don't go on to the next screen until the registration returns. With the logs, I should be able to figure out where the slowdown is.

**Comment by shankari** [comment]
@asiripanich waiting for logs. Will close in a week if I don't get them.

**Comment by asiripanich** [comment]
I'm not seeing that huge delay anymore.. will reopen this if it occurs again.
