### ISSUE TITLE
UI suggestion: display a text on the daily tab when there is no trip

### ISSUE THREAD

**Issue by asiripanich** [e-mission/e-mission-docs#524]
Many people who helped us to during our pilot seemed to be puzzled when they first saw a large blank white screen on their daily tab, after they had logged in. Maybe adding a text to indicate that no trips have been made today on the blank screen can help? What do you think?

**Comment by shankari** [comment]
IIRC, we used to have an alert about no trips found for a particular day. During a prior design revision, the testers found the message confusing and we removed it.

However, you don't need my permission to change any aspect of your UI. Feel free to add it back! This should be trivial - I think that there is already code in `services.js` to detect this condition.

**Comment by shankari** [comment]
Here's a prior point of time when we had such an alert
https://github.com/e-mission/e-mission-phone/blob/51f8d7ccf4ff7d357b8da66fd83119a4d36ccca7/www/js/diary/list.js#L119

Sorry, I don't have the time to dig through git history to see when we removed it, but you can if you want to see the reason why.

**Comment by shankari** [comment]
ah here's where we removed it
https://github.com/e-mission/e-mission-phone/commit/488308b2fd6b36b712a6f4c8889b12033b740b1d

> - Turn off the popup on zero trips

**Comment by shankari** [comment]
if you come up with a better UX design, please submit a PR to master as well!

**Comment by asiripanich** [comment]
I’m not talking about a pop up alert. A small text saying “no trip for today” just under the date picker icon instead of just a plain white background should be adequate.

**Comment by asiripanich** [comment]
Will explore this design if we have time.. ;)
