### ISSUE TITLE
Enketo survey via InAppBrowser

### ISSUE THREAD

**Issue by asiripanich** [e-mission/e-mission-docs#525]
@atton16 opened this [issue](https://github.com/asiripanich/e-mission-phone/issues/35) on our dev repo. I want to open it here since its a feature in the master branch as well... 

We are moving from embedded survey to online survey by opening the survey link with in-app browser.

Now we need to work on communication between the in-app browser and the current $scope.

What we are trying to achieve is when user submit the survey we want to redirect them to the main view.

So what we need is the IAB postMessage API from cordova-plugin-inappbrowser version 3.1.0-dev. (ref: https://www.andreszsogon.com/how-to-close-inappbrowser-window-in-cordova-by-itself/)

postMessage API allows JavaScript code from inside iab to communicate to the current $scope. But we are using the customized inappbrowser version 1.6. I am not sure why we are using the custom version but I am certain there is a good reason behind it.

So I am thinking either upgrade IAB plugin to 3.1.0-dev or perhaps there is a workaround that you could point us to.

**Comment by shankari** [comment]
>  I am not sure why we are using the custom version but I am certain there is a good reason behind it.

The reason for the custom version is to handle the buttons correctly. 
e.g. https://github.com/shankari/cordova-plugin-inappbrowser/commit/9da7fefabb6687a56045285e715e8503318aef72

Upgrading the IAB plugin will require a new app release in the stores - including going through app review for the iOS app store.

**Comment by shankari** [comment]
I have a pending branch that upgrades everything (`cordova-android` and `cordova-ios` and a bunch of the plugins including IAB). If we do want to upgrade the app, that is probably the way to go. But that relies on the ability to pass through app store review, so no guarantees, specially for a white label app.

**Comment by asiripanich** [comment]
I see. So the short answer is the app needs the update to make this works. I’m closing the issue now since we found a workaround and there is no immediate fix to this.
