### ISSUE TITLE
HTML not render properly on emTripLog

### ISSUE THREAD

**Issue by asiripanich** [e-mission/e-mission-docs#526]
@shankari can you advice why this list is not displayed properly on emTripLog? 

![image](https://user-images.githubusercontent.com/17020181/80439081-0ce25980-8949-11ea-84b6-aa750cb5f8db.png)

This is what I see on emTripLog
![image](https://user-images.githubusercontent.com/17020181/80439142-2a172800-8949-11ea-8553-e054a034e1e3.png)

**Comment by shankari** [comment]
@asiripanich sorry, no idea. emTripLog is essentially a set of native plugins and I can answer questions about that. You can change all the HTML and javascript on top to whatever you want. If you reuse the javascript that I wrote, I can help with that, but HTML formatting of your own file is something that I have no special insights into.

Have you looked at your CSS? Have you looked at other consent files and how they are displayed?
