### ISSUE TITLE
swiping to the right can skip the consent page

### ISSUE THREAD

**Issue by asiripanich** [e-mission/e-mission-docs#527]
I'm not sure if this is an expected behavior of emTripLog but I don't think it should do that.

**Comment by shankari** [comment]
hm... I don't think anybody has tried that before :)
I use an `ion-slide-box` for the onboarding intro and I guess it allows swiping by default.

Stackoverflow has some suggestions to turn it off:
https://stackoverflow.com/questions/25037166/disable-swipe-in-ionic-slidebox

**Comment by asiripanich** [comment]
Got it. Thank you :).
