### ISSUE TITLE
Link to the documentation website

### ISSUE THREAD

**Issue by laem** [e-mission/e-mission-docs#532]
Hi, it took some time for me to find the docs website : https://e-mission.readthedocs.io/en/latest
Would it be possible to put it as a header above the files and at the beginning of the README :) ?

https://e-mission.readthedocs.io/en/latest/

**Comment by PatGendre** [comment]
Hi @laem there is a link to the readthedocs site in the Getting Started section, you want to add another more explicit link to it? Maybe you can directly propose a PR for this

**Comment by laem** [comment]
I can make a PR for the docs, but I can't for github the header URL as far as I know

**Comment by PatGendre** [comment]
you mean you'd want to add a link to readthedocs in this page https://github.com/e-mission/e-mission-docs/ and in this text?

    Repository for docs and issues. If you need help, please file an issue here. Public conversations are better for open source projects than private email.

**Comment by shankari** [comment]
I put the readthedocs link as the "website" for this repo. So it shows up in the title.
@laem is that more clear now?
