### ISSUE TITLE
Up to date android app

### ISSUE THREAD

**Issue by laem** [e-mission/e-mission-docs#533]
Is it possible to test an up to date version of the app on my phone, before trying to build it ? On the play store, the latest is october 2018, quite old.

It is possible to configure the downloaded app to use my personal server that I would have deployed somewhere ?

**Comment by PatGendre** [comment]
you mean you'd want to add a link to readthedocs in this page https://github.com/e-mission/e-mission-docs/ and in this text? 

> Repository for docs and issues. If you need help, please file an issue here. Public conversations are better for open source projects than private email.

**Comment by shankari** [comment]
The emTripLog app is more recent - you can use it to explore the tripaware UI, for example.
https://e-mission.eecs.berkeley.edu/#/client_setup?new_client=urap2017emotion&clear_usercache=true&clear_local_storage=true

Alternatively, @PatGendre can send you an beta invite to the FabMob app.

There is currently no way to change the server in the downloaded app - we were concerned that people would make inadvertently edit it, have the data not be synced, and complain that the app was "not working". 

If you feel strongly about this, we should discuss also adding some form of reporting that the website is incorrect.

**Comment by laem** [comment]
Thanks, I'll give it a try :)

**Comment by shankari** [comment]
@laem if you are able to use the app, can you please close this issue?

**Comment by laem** [comment]
Yes, I'll raise a more precise issue if I have problems.
