### ISSUE TITLE
UIWebview App Store error

### ISSUE THREAD

**Issue by tarekeg** [e-mission/e-mission-docs#539]
Hello, I have a problem with the publication of the app for testflight and it is due to UIWebview I updated the inappbrowser plugin to 3.2.0 and added 

` <preference name="WKWebViewOnly" value="true" />
    <preference name="WKSuspendInBackground" value="false" />`

But i still get the error
thanks

**Comment by shankari** [comment]
@tarekeg as you can see from the main e-mission-phone README

> ✨ As part of experimenting with a COVID-19 reference app, we upgraded to the most recent cordova version and added CI ✨ We are now porting this over to the main e-mission repo. The ported code is currently in https://github.com/e-mission/e-mission-phone/tree/upgrade_to_latest_cordova and the current status is in https://github.com/e-mission/e-mission-docs/issues/519. The branch is usable although not all functionality has been tested. Please contribute your testing results so that we feel confident promoting it to master.

Can you take a look at the current status and see if it meets your needs? If so, you can use that branch. If not, please update the issue with what you need, and I'll try to re-enable it on the weekend. Would be great if you can contribute testing so I can feel confident promoting it to master.

**Comment by shankari** [comment]
Let's continue this discussion in #519

**Comment by shankari** [comment]
Note also that the new branch has a new setup script that is also used with CI. So if the CI is passing, then the setup is guaranteed to be correct.

**Comment by tarekeg** [comment]
Hi shankari thank you for your quick answer. In fact we did a fork of emission for our app Weflow so i will try to see what you have done for this issue and try to adapt it on our project if it works i will let know and will make a PR 
Thanks

**Comment by shankari** [comment]
Sounds great. Note that I upgraded a bunch of plugins, not just the cordova version.

**Comment by shankari** [comment]
@tarekeg did you run into any issues with this? I think I am finally getting to the end of the licensing updates and other random legal stuff and should be able to get to this fairly soon.
