### ISSUE TITLE
Upgrade pyfcm to 1.4.4 or Downgrade to 1.4.2

### ISSUE THREAD

**Issue by njriasan** [e-mission/e-mission-docs#54]
I'm not sure which is appropriate but for the manual installation process the conda environment setup errors (at least on Ubuntu 16.04) because of a bug in pyfcm 1.4.3 which prevents it from being pip installed in python 3. You can see the bug documented here: https://github.com/olucurious/PyFCM/pull/179. Can we migrate the installation dependency to either 1.4.4 or 1.4.2 (I'm not sure which is appropriate or if it matters at all)?

**Comment by shankari** [comment]
Closing since this doesn't appear to be a real issue any more
