### ISSUE TITLE
readthedocs site is out of date?

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-docs#541]
@PatGendre I just noticed that the ReadTheDocs site is out of date. I thought (from https://github.com/e-mission/e-mission-docs/pull/429) that it would auto-update? Do I have to follow the instructions to allow auto-updating?

**Comment by PatGendre** [comment]
@shankari yes it seems the last compilation is 10 months old, I thought it would autoupdate too! I've tried to compare with our fabmob https://fabmob.readthedocs.io/en/latest/ , but I dont't see any difference in the configuration. Only the latest version is marked as active, like for our fabmob repo.   
https://readthedocs.org/projects/e-mission/versions/ I don't know if'd have to activate master too, I don't see why you would have too.   
Sorry, I did not solve the issue yet:-(

**Comment by shankari** [comment]
@PatGendre It looks like, since you are not an owner of the e-mission repo, the github webhook was not set up properly. I followed the instructions here:
https://docs.readthedocs.io/en/stable/webhooks.html
and set it up manually. It should auto-update now :)

**Comment by PatGendre** [comment]
@shankari ok great! So did it actually update? I still have the latest compilation dated from 10 months ago.

**Comment by shankari** [comment]
So the webhook is definitely set up properly and works.

<img width="608" alt="Screen Shot 2020-05-28 at 7 51 07 AM" src="https://user-images.githubusercontent.com/2423263/83157160-20075700-a0b8-11ea-907f-8ac554a6800a.png">

Based on this:

<img width="873" alt="Screen Shot 2020-05-28 at 7 53 52 AM" src="https://user-images.githubusercontent.com/2423263/83157430-6eb4f100-a0b8-11ea-8adb-ec72fe7619b5.png">

I think it will update on the next push to the docs repo.

I can manually update before then, but maybe this is the time to actually improve the documentation and check that it works :)

**Comment by PatGendre** [comment]
Yes, it could be an opportunity to improve the doc now that you fixed the webhook :-)

**Comment by shankari** [comment]
I updated the docs to close https://github.com/e-mission/e-mission-docs/issues/517
and now the site does appear to be updated!
