### ISSUE TITLE
Error while installing server via docker

### ISSUE THREAD

**Issue by nlehuby** [e-mission/e-mission-docs#543]
I've tried to run the e-mission server using the docker files from [this repo](https://github.com/e-mission/e-mission-docker/tree/master/examples/em-server)

`docker-compose -f docker-compose.dev.yml up` ends up with an error on the webserver: `ModuleNotFoundError: No module named 'future'`

I'm not familiar with conda, so it may not be related, but during the installation, I got
`CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.` and an error while installing package 'conda-forge::cachetools-2.1.0-py_0'

**Comment by shankari** [comment]
so I currently have a docker-based CI in the server repo (https://github.com/e-mission/e-mission-server/actions?query=workflow%3Atest-with-docker) which passed 4 days ago.

So there is nothing wrong with the docker image - the difference must be in the two startup scripts. Comparing `clone_and_start_server.sh` in the `e-mission-docker` repo and `setup/tests/start_script.sh` in the `e-mission-server` repo, the main differences are in the setup script that is run and in the line `source /opt/conda/etc/profile.d/conda.sh`

The two setup scripts are functionally identical

```
 echo "Setting up blank environment"
-conda create --name emission python=3.6
-conda activate emission
+conda create --name emissiontest python=3.6
+conda activate emissiontest

 echo "Downloading packages"
 curl -o /tmp/cachetools-2.1.0-py_0.tar.bz2 -L https://anaconda.org/conda-forge/cachetools/2.1.0/download/noarch/cachetools-2.1.0-py_0.tar.bz2
@@ -22,5 +17,7 @@
 echo "Installing manually downloaded packages"
 conda install /tmp/*.bz2

-echo "Updating using conda now"
-conda env update --name emission --file setup/environment36.yml
+conda env update --name emissiontest --file setup/environment36.yml
```

So the difference must be the conda setup script.

**Comment by shankari** [comment]
Fixed by uploading new "latest" version to dockerhub pointing to version 2.8.2

The container works fine now, I can access localhost:8080. Will deal with CI after I think a bit about how best to organize the various docker options. Right now, it looks like the e-mission server testing docker is very close to the dev docker-compose. Can we unify them somehow?

```
C02KT61MFFT0:em-server shankari$ docker-compose -f docker-compose.dev.yml up
...
Creating em-server_db_1 ... done
Creating em-server_web-server_1 ... done
Attaching to em-server_db_1, em-server_web-server_1
web-server_1  | Cloning from repo https://github.com/e-mission/e-mission-server.git and branch master
db_1          | 2020-06-04T05:47:50.254+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=5bb3a71c1d34
db_1          | 2020-06-04T05:47:50.256+0000 I CONTROL  [initandlisten] db version v3.4.19
db_1          | 2020-06-04T05:47:50.257+0000 I CONTROL  [initandlisten] git version: a2d97db8fe449d15eb8e275bbf318491781472bf
...
web-server_1  | Installing manually downloaded packages
########## | 100%
########## | 100%
########## | 100%
########## | 100%
########## | 100%
########## | 100%
web-server_1  | Downloading and Extracting Packages
web-server_1  | Preparing transaction: ...working... done
web-server_1  | Verifying transaction: ...working... done
web-server_1  | Executing transaction: ...working... done
web-server_1  |
web-server_1  | Updating using conda now
web-server_1  | Solving environment: ...working... done
web-server_1  |
...
web-server_1  | Connecting to database URL db
web-server_1  | analysis.debug.conf.json not configured, falling back to sample, default configuration
web-server_1  | Finished configuring logging for <RootLogger root (WARNING)>
web-server_1  | Replaced json_dumps in plugin with the one from bson
web-server_1  | Changing bt.json_loads from <function <lambda> at 0x7feeeaf3bd08> to <function loads at 0x7feee91b4d90>
web-server_1  | Running with HTTPS turned OFF - use a reverse proxy on production
web-server_1  | START 2020-06-04 06:06:11.284368 GET /
web-server_1  | END 2020-06-04 06:06:11.299876 GET /  0.015290260314941406
web-server_1  | START 2020-06-04 06:06:11.443965 GET /lib/ionic/css/ionic.css
web-server_1  | END 2020-06-04 06:06:11.447049 GET /lib/ionic/css/ionic.css  0.002894878387451172
```
