### ISSUE TITLE
License file for the docs repo is not in the main directory

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-docs#546]
In this repo, the LICENSE file is at `docs/LICENSE.md`.

@PatGendre is there a reason for that?

GitHub repos typically have the `LICENSE` in the root directory. This was moved in https://github.com/e-mission/e-mission-docs/commit/aa0efae7aad538dfcd332d7a6e8832d6fb1c3d04#diff-fe0606a2151266b339beaba9bed2e034

It looks to me like it was moved as part of moving all files out of the main directory to be consistent with readthedocs. But this is not directly visible as a file in readthedocs.

Can I move it back? Or is there a strong reason to keep it in the docs directory?

**Comment by PatGendre** [comment]
Hi @shankari, ni particular reason, you can move it back

**Comment by shankari** [comment]
Fixed in https://github.com/e-mission/e-mission-docs/commit/12b940d61c7db016e15f3fa88bf562d9b484aac8
