### ISSUE TITLE
Encountered Error during Android Emulation

### ISSUE THREAD

**Issue by eugenetan3** [e-mission/e-mission-docs#550]
Hi!

I was following #475 and I came across a different error while following the instructions listed there. It's resulting because of an UnhandledPromiseRejectionWarning from CordovaError indicating a Requirements Check for JDK1.8 or greater was failed. 
<img width="1033" alt="Screen Shot 2020-06-27 at 12 57 40 PM" src="https://user-images.githubusercontent.com/44623905/85931020-e58b0880-b875-11ea-8d64-5ce80be9e174.png">

I believe my iOS emulation should work if I compile in XCode 10.3, because the commandline issue of the "toLowerCase" is resolved via Xcode compilation if I read that correctly. 

Something I encounter during iOS build is a reference to a config file AndroidManifest.xml that is not found in my platform/ios folder. Is that intended? I am unfamiliar with Android applications.

Thanks for the help!

**Comment by shankari** [comment]
@eugenetan3 As you can see from the phone repo README

> ✨ As part of experimenting with a COVID-19 reference app, we upgraded to the most recent cordova version and added CI ✨ We are now porting this over to the main e-mission repo. The ported code is currently in https://github.com/e-mission/e-mission-phone/tree/upgrade_to_latest_cordova and the current status is in https://github.com/e-mission/e-mission-docs/issues/519. The branch is usable although not all functionality has been tested. Please contribute your testing results so that we feel confident promoting it to master.

I would strongly encourage using that branch instead of master. I could try to debug this for you, but you won't be able to publish the resulting app anyway (https://github.com/e-mission/e-mission-docs/issues/539). I haven't heard back from @tarekg yet so I assume the branch worked fine :)

**Comment by shankari** [comment]
If you run into any issues with the branch, please report them at https://github.com/e-mission/e-mission-docs/issues/519
I'm finally getting done with the license updates, and can get to this if there are high priority bugs.

**Comment by eugenetan3** [comment]
Awesome thanks, I'll move to that branch and update the issue thread accordingly.

**Comment by eugenetan3** [comment]
Quick question, the setup for the branch looks to be a lot easier in terms of installation. Do the same instructions apply previously?

**Comment by shankari** [comment]
The installation hasn't changed - the branch just automates the installation instructions in a script.

Putting the installation instructions in the script also makes it easier to run CI. Then, if there are issues with the build, people can check the CI to see what to expect.

**Comment by shankari** [comment]
One caveat, if you installed modules globally (e.g. `npm install -g cordova`) you might want to uninstall (e.g. `npm uninstall -g cordova`) before running the setup script. This will ensure that you don't have conflicts with the global and local versions. Of course, if you have other cordova projects, you can keep the global version around as well.

**Comment by shankari** [comment]
LMK if you have any other questions, otherwise, please close this issue.
