### ISSUE TITLE
Calculation of the average carbon footprint in dashboard

### ISSUE THREAD

**Issue by EstherEu** [e-mission/e-mission-docs#551]
I would like to understand how the "average" footprint in the dashboard is calculated.
It can't really be calculated from the same trips as the "optimal" and "worst" since it is always higher than the "worst". 
Is this calculation based on the trips of all users?
Where exactly is it calcuated?

**Comment by shankari** [comment]
@EstherEu Yes, the "average" footprint is based on the trips of all users.
"optimal" and "worst" are based on the trips for a particular user.
it is currently calculated on the phone.

User values: https://github.com/e-mission/e-mission-phone/blob/5fe208d8623fcb1b933e167e83bed3cebf17134f/www/js/metrics.js#L702
Aggregate values: https://github.com/e-mission/e-mission-phone/blob/5fe208d8623fcb1b933e167e83bed3cebf17134f/www/js/metrics.js#L760
