### ISSUE TITLE
understanding parameters in app's developer zone

### ISSUE THREAD

**Issue by EstherEu** [e-mission/e-mission-docs#552]
Could you please explain the parameters in the app's developer zone so we have a better understanding of how to adjust them?
Duty Cycling, Accuracy, Filter Interval, geofence responsiveness etc...

**Comment by shankari** [comment]
@EstherEu Could you read chapter 4 of my thesis https://www2.eecs.berkeley.edu/Pubs/TechRpts/2019/EECS-2019-180.pdf to understand how the sensing works and what the parameters represent?

For a quick start, a shorter, summarized version is in the https://www.climatechange.ai/papers/iclr2020/15/paper.pdf
For a fairly comprehensive evaluation, please see section 7.2 of the thesis.

If it is still not clear, please let me know what is unclear and I can elaborate here.

**Comment by shankari** [comment]
Closing this, @EstherEu please reopen if you have any other questions.
