### ISSUE TITLE
App not recognizing email in internal beta

### ISSUE THREAD

**Issue by jRaffill** [e-mission/e-mission-docs#555]
In version 2.9.0-beta1 I tried to use the 'email log' button but it didn't work. It said that my email was not configured. 
"Alert: No email address configured. TypeError: cordova.plugins.email.isAvailable is not a function."

**Comment by shankari** [comment]
@jRaffill thank you for your feedback. It turns out that this was due to an incompatible change in the emailComposer plugin.
https://github.com/katzer/cordova-plugin-email-composer/blob/41994ee4a5f9f06837ae34a84b5c6151d19e9712/CHANGELOG.md#L12

**Comment by shankari** [comment]
Unfortunately, the wrapper we were using to access this data (`ngCordova`) is now deprecated and does not support the new `hasAccount` method. Switched to using the plugin directly without the `ngCordova` wrapper. Removing the `ngCordova` wrapper also meant that I had to switch to direct access for the inAppBrowser as well.

All related changes are in 
https://github.com/e-mission/e-mission-phone/commit/61513d92e2223aabef929c072b05110b518c0462

**Comment by shankari** [comment]
And then it turned out that the behavior of `isAvailable` is now subtly different without access to the `GET_ACCOUNTS` permission.

Fixed in https://github.com/e-mission/e-mission-phone/commit/38d0ab2fc1ae9901eab82c9a2374062211f8811b

**Comment by shankari** [comment]
Emailing logs now works on both android and iOS
