### ISSUE TITLE
Emission modules for Jupyter Notebook

### ISSUE THREAD

**Issue by myaman17** [e-mission/e-mission-docs#56]
How can I link my Jupyter Notebook with Emission modules?

**Comment by myaman17** [comment]
I am using the installation guide at https://github.com/e-mission/e-mission-docker.
I have an issue removing existing Docker images: Unknown shorthand flag: 'a' in -a 
![image](https://user-images.githubusercontent.com/31378904/52740786-af9efa00-2f88-11e9-8269-c1bc69b159e7.png)

**Comment by shankari** [comment]
I assume you are following the instructions from the linked document 
https://techoverflow.net/2013/10/22/docker-remove-all-images-and-containers/

Note that the images command does not have `-a`

```
docker rmi $(docker images -q)
```

**Comment by myaman17** [comment]
> I assume you are following the instructions from the linked document
> https://techoverflow.net/2013/10/22/docker-remove-all-images-and-containers/
> 
> Note that the images command does not have `-a`
> 
> ```
> docker rmi $(docker images -q)
> ```

I tried that one, though I am having the same error. 
![image](https://user-images.githubusercontent.com/31378904/52744272-12948f00-2f91-11e9-8b49-1abbb6cea1f3.png)

**Comment by shankari** [comment]
does `docker images -q` (without the `$()`)  work?

**Comment by myaman17** [comment]
> does `docker images -q` (without the `$()`) work?

It does not remove Docker images.
![image](https://user-images.githubusercontent.com/31378904/52745925-2fcb5c80-2f95-11e9-95f8-1e1af8a5d83b.png)

**Comment by shankari** [comment]
I just really wanted to see the first command.
This does appear to be a Windows issue.

Have you tried gitbash as recommended? 
> I would recommend using a POSIX-compliant CLI (such as gitbash) on windows.

If that doesn't work, a fallback is to just delete the images one by one - e.g.
```
docker image remove emission/e-mission-server:latest
```
OR 
```
docker image remove e42cfbc61764
```

**Comment by myaman17** [comment]
I am getting the following error: 
![image](https://user-images.githubusercontent.com/31378904/53849707-9547b300-3f6d-11e9-98f8-b7d9e54254d1.png)

**Comment by myaman17** [comment]
It is solved. In Windows 10, the use of GitBash made things easier, as you showed. Thank you!
