### ISSUE TITLE
Choosing travel mode

### ISSUE THREAD

**Issue by JackBikes** [e-mission/e-mission-docs#563]
I haven't actually been able to choose what my travel mode is when the notification pops up asking "How do you get here?" but instead just go to the dashboard.

**Comment by shankari** [comment]
Hm. I should be able to figure out this behavior from the logs as well. But you can always go to the diary and choose the dropdowns if this doesn't work. Does that work for you? Do we need to highlight the diary more?

**Comment by JackBikes** [comment]
Ah, I got it! I think making that selection drop down clearer somehow would
benefit us.

Jack Todd
Director of Communications and Policy, Bicycle Colorado
Pronouns: he/him/his
1525 Market Street, Suite 100
Denver, CO 80202
Cell: (303) 523-4231
bicyclecolorado.org

<https://www.bicyclecolorado.org/bike-news/social-justice/>

**Comment by shankari** [comment]
Sounds good, let's brainstorm next week on how best to fix this.

**Comment by shankari** [comment]
We now always go to the diary.
