### ISSUE TITLE
kobotoolbox also does not store the UUID field even though it is filled in

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-docs#587]
Similar to #582 
Looks like everybody is using extra logic around user entered values.
Looks like there is a similar workaround for pre-filled values.

This time, let's not spend a whole day trying to programmatically generate user interaction, and go directly to trying out pre-filled values.

Looks like kobotoolbox does support pre-filled values:
- https://community.kobotoolbox.org/t/prefill-fields-via-url-in-enketo/2698
- https://help.ona.io/knowledge-base/how-do-i-prefill-form-fields-using-enketo-express/

**Comment by shankari** [comment]
Looks like;
- enketo only supports prefilled values for online forms
https://github.com/kobotoolbox/enketo-express/issues/1093#issuecomment-409639087

- it requires that you get the prefilled URL using a web API
https://apidocs.enketo.org/v2#/post-survey

**Comment by shankari** [comment]
online forms might actually even be better because there is no "draft" and having to wait until the form is submitted

**Comment by shankari** [comment]
FYI, the xpath to use for kobotoolbox surveys is the "name" field from the html of the element

<img width="1248" alt="Screen Shot 2020-11-19 at 5 37 57 PM" src="https://user-images.githubusercontent.com/2423263/99745175-fee35a00-2a8d-11eb-91ad-3e511ecb5791.png">

for the form above, the prefill URL is
https://ee.kobotoolbox.org/x/hEkHk50v?&d[/arcEm5iPB4F9CQZR258k4r/group_hg4zz25/Here_is_your_UUID_wh_ake_any_change_to_it]=prefilled

**Comment by asiripanich** [comment]
@shankari See one of our RCITI branches if you want to see an example of a hidden prefilled value.
