### ISSUE TITLE
e-mission-phone: drifyco has moved to ionic-team

### ISSUE THREAD

**Issue by robfitzgerald** [e-mission/e-mission-docs#590]
e-mission-phone makes references to [driftyco](https://github.com/driftyco) which clearly used to have repos but no longer does. this is a problem when running `bash setup/setup_serve.sh`:

```
bower ionic-platform-web-client#0.7.0  
ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/driftyco/ionic-platform-web-client.git", 
exit code of #128 remote: Repository not found. fatal: repository 
'https://github.com/driftyco/ionic-platform-web-client.git/' not found
```

they [left us a note](https://github.com/driftyco) that says:

> Hey there 👋 The Ionic organization has moved to https://github.com/ionic-team/ 🚀  https://github.com/ionic-team/

however, https://github.com/ionic-team/ionic-platform-web-client does not seem to exist.

**Comment by robfitzgerald** [comment]
i am attempting to run this setup script on the nrel_location_history branch.

**Comment by robfitzgerald** [comment]
first question, truly nrel-branch-specific: should i merge in master or would that possibly break anything we're depending on?

i did make a quick scan of master though and found drifyco mentioned in [at least one spot](https://github.com/e-mission/e-mission-phone/blob/master/bower.json#L5).

**Comment by shankari** [comment]
@robfitzgerald The NREL branch is up to date with master ("This branch is 7 commits ahead of master. "). I synced 6 days ago (https://github.com/e-mission/e-mission-phone/commit/a722ae298e06f8b795f5c4fddd388dab65097690).

The phone repo has continuous integration set up, and setup-serve was working as of 2 days ago
(https://github.com/e-mission/e-mission-phone/actions?query=workflow%3Aosx-serve-install)

The only reference to driftyco that I see in those logs is 

```
bower ionic#1.3.1           not-cached https://github.com/driftyco/ionic-bower.git#1.3.1
bower ionic#1.3.1           resolve https://github.com/driftyco/ionic-bower.git#1.3.1
.........
bower ionic#1.3.1           download https://github.com/driftyco/ionic-bower/archive/v1.3.1.tar.gz
```

And that repo still exists https://github.com/ionic-team/ionic-bower
although it has been archived

The only reference to driftyco that I see in master is the same `ionic-bower`
https://github.com/e-mission/e-mission-phone/blob/140549b3a2dd6ee09d73191f7d1d366c5cb84598/bower.json#L5
which is the same in the branch
https://github.com/e-mission/e-mission-phone/blob/nrel_location_history/bower.json

**Comment by shankari** [comment]
can you compare your logs to the logs from the CI and see what (if anything) is different?

**Comment by robfitzgerald** [comment]
> And that repo still exists https://github.com/ionic-team/ionic-bower

but the url is https://github.com/driftyco/ionic-bower - note "ionic-team" instead of "driftyco".

**Comment by robfitzgerald** [comment]
hmm, but on bower, they are still registered as driftyco.

i'll dig into my logs and see what i find.

**Comment by shankari** [comment]
> but the url is https://github.com/driftyco/ionic-bower - note "ionic-team" instead of "driftyco".

If you access https://github.com/driftyco/ionic-bower it automatically redirects to https://github.com/ionic-team/ionic-bower

There is no such auto-redirection for https://github.com/driftyco/ionic-platform-web-client but I am not sure why the setup script is trying to install it on your laptop when it isn't installing it in the CI, which is also running on OSX.

**Comment by shankari** [comment]
FYI, I just set up a brand new e-mission-phone repo from a fresh checkout and didn't run into this issue.

**Comment by robfitzgerald** [comment]
once you mentioned above that bower handles the re-direct, i started getting the sneaking suspicion that this might have something to do with installing e-mission stuff on a managed NREL laptop with limited admin rights. it may be a NREL problem, not an e-mission-phone problem. i'll try and investigate it again with that in mind.

**Comment by robfitzgerald** [comment]
it's working now with a fresh install fixed my issue. i'm guessing it was an invalid cached dependency. i should know by now that installing new software on this managed laptop will _most often fail the first time_ thanks to proxy stuff.

i've made it to the app on the emulator.
