### ISSUE TITLE
ServerSyncAdapter : IO Error java.io.IOException while posting converted trips to JSON

### ISSUE THREAD

**Issue by PatGendre** [e-mission/e-mission-docs#598]
Hi @shankari and happy New Year !!
We've installed an e-mission server for the la Rochelle pilot and started to test the e-mission app a few days ago.
It appears that the location data is not transmitted to the server; we don't see any errors in the server logs (maybe because the logging is not correctly configured but I don't think so), 
and in the phone logs we have an `"ServerSyncAdapter : IO Error java.io.IOException while posting converted trips to JSON"` message. I attach the logs
Do you see any reason why this could happen? Could it be the previously solved #333 issue? Or another problem when building the app?
This errors occurs for my app but for all others too (currently only 4 Android testers).

[phonelog.tar.gz](https://github.com/e-mission/e-mission-docs/files/5771412/phonelog.tar.gz)

**Comment by shankari** [comment]
@PatGendre there is an 500 Internal Error on the server

```
2361,1609778591.9520001,2021-01-04T08:43:11.952000-08:00,CommunicationHelper : Got response org.apache.http.me
ssage.BasicHttpResponse@d85854 with statusHTTP/1.1 500 Internal Server Error
2362,1609778591.985,2021-01-04T08:43:11.985000-08:00,ServerSyncAdapter : IO Error java.io.IOException while po
sting converted trips to JSON
```

You have to check the server to see what the error is. I really doubt that this is #333 because:
- #333 is fixed
- you did not see the same issue when you tested with emTripLog and the NRELlh client

What do you see in the terminal where you are running the server program?

**Comment by shankari** [comment]
Also, this is not related but I note that the server is running at a non-standard port, but with https. Is there a reason that you are not just running it with a reverse proxy and a separate domain name? With let's encrypt, there is no real reason why you have to use a non-standard port. LMK if you want a standard docker-based example with LE, I can probably create one based on @atton16's PR

```
2360,1609778589.676,2021-01-04T08:43:09.676000-08:00,"ConnectionSettings : in getConnectURL, returning https:/
/trace.grfmap.com:8081"
```

**Comment by PatGendre** [comment]
thanks

> Is there a reason that you are not just running it with a reverse proxy and a separate domain name? With let's encrypt, there is no real reason why you have to use a non-standard port.

I did not install the server, I think the disk is not mounted with let's encrypt, and there is no reverse proxy either, simply because it takes a little time so set it up. I will ask is it can be useful to see an example docker setup with LE.
The 8081 port is because the 8080 is already taken by another application.

I could not access to the server terminal but I will look at it on Monday hopefully. I've seen no errors on the server logs but I suspect this is because of the logs config.

**Comment by PatGendre** [comment]
hi @shankari 
we've made a mistake in the server config apparently, so now the problem seems to be solved! Sorry...
I close the issue
