### ISSUE TITLE
update recent e-mission-server to GIS branch?

### ISSUE THREAD

**Issue by PatGendre** [e-mission/e-mission-docs#604]
Hi @shankari . We work on the GIS branch. I'v seen you've made recently several commits to e-mission-server master branch. 
Do these commits benefit also the GIS branch? (it looks like they could).
Do you intend to push the commits to the GIS branch? Shall we wait until you do so?
Thanks

**Comment by shankari** [comment]
The changes were not that substantial, and primarily related to the tour model code
but that also made them easy to merge!
