### ISSUE TITLE
No trips segmented after running the pipeline

### ISSUE THREAD

**Issue by varkon256** [e-mission/e-mission-docs#612]
I have tuples in the following form collected for a device over the span of a few months: 

|id|timestamp|device_id|double_latitude|	double_longitude|double_bearing|double_speed|double_altitude|provider|accuracy|label|
| ----------- | ----------- | ----------- | ----------- | ----------- | ----------- | ----------- | ----------- | ----------- | ----------- | ----------- |
|1|1530925911228|6ceaa823-9149-4fa5-880e-958328aa7df2|47.654862200000004|-122.30661699999999|0|0.0|23.299999237061|fused|33.027|

I converted each tuple to the format the pipeline requires (i.e. the format the test examples follow):
```json
{
  "user_id": {
      "$uuid": "0c3c11e0b66d494eb4c45e887d4b555f"
  }, 
  "_id": {
      "$oid": "576810cb4a9bba50e3fa1d90"
  }, 
  "data": {
      "loc": {
          "type": "Point", 
          "coordinates": [
              -122.0836009, 
              37.3891289
          ]
      }, 
      "fmt_time": "2016-06-20T08:30:28.542000-07:00", 
      "altitude": 0, 
      "ts": 1466436628.542, 
      "longitude": -122.0836009, 
      "filter": "time", 
      "latitude": 37.3891289, 
      "heading": 0, 
      "sensed_speed": 0, 
      "accuracy": 97.565,
       "local_dt": {
          "hour": 8, 
          "month": 6, 
          "second": 28, 
          "weekday": 0, 
          "year": 2016, 
          "timezone": "America/Los_Angeles", 
          "day": 20, 
          "minute": 30
      }, 
  }, 
  "metadata": {
        "write_fmt_time": "2016-06-20T08:28:47.131000-07:00", 
        "write_ts": 1466436527.131, 
        "write_local_dt": {
                "hour": 8, 
                "month": 6, 
                "second": 47, 
                "weekday": 0, 
                "year": 2016, 
                "timezone": "America/Los_Angeles", 
                "day": 20, 
                "minute": 28
            }, 
      "time_zone": "America/Los_Angeles", 
      "platform": "android", 
      "key": "background/location", 
      "read_ts": 0, 
      "type": "sensor-data",
  }
}
```
I replaced information I can in this json object for each tuple and loaded an array of these json objects with the load_timeline command. After that I ran the intake_single_user script.

But after opening up the Timeseries_sample.ipynb notebook and selecting the corresponding uuid no trips show up. Any idea of what the problem could be or where I should look?

**Comment by shankari** [comment]
@varkon256 the code typically works with `background/filtered_location`, since we filter the locations on the client to determine when to stop tracking.

You need to either enable the filter_accuracy in `conf/analysis`

```
    "intake.cleaning.filter_accuracy.enable": true,
```

or if that doesn't work (because it has bitrotted), change the references to `background/filtered_location` in `emission/analysis/intake` - e.g. 
https://github.com/e-mission/e-mission-server/blob/0475b456db197edacb524c5ab7a1124cd33b5333/emission/analysis/intake/segmentation/section_segmentation.py#L97
to `background/location`

**Comment by varkon256** [comment]
@shankari I tried these three things (all separately and then running the intake script): 

- Enabling the filter_accuracy
- Changing the references in `emission/analysis/intake` from `background/filtered_location` to `background/location`
- Changing the key of json object in my data to `background/filtered_location` instead of `background/location`

When I run the intake script for the last 2 things I tried it looks like the pipeline takes longer to get past the segmenting trips part but runs successfully. But I still can't find any segmented trips for the corresponding uuids when I use the Jupyter notebook. Is there anything else I could try to get this working?

**Comment by shankari** [comment]
If it takes a while, I assume it is working properly.
How did you look for segmented trips in the notebook?
Are there any errors in the intake logs (in `/var/tmp`)?

**Comment by varkon256** [comment]
@shankari I cleared the logs and ran the pipeline after doing the third thing above (i.e. replacing `background/location` with `background/filtered_location` in my data). 

`intake-single.log` had some output but` intake_single-errors.log` was empty. This is the output of the Jupyter notebook: 

<img width="1143" alt="image" src="https://user-images.githubusercontent.com/24356659/107290790-ff9be480-6a1b-11eb-9ad8-acc34eced601.png">
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/24356659/107290838-15110e80-6a1c-11eb-8061-b42cbc1289a9.png">
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/24356659/107290855-1d694980-6a1c-11eb-815d-03a1695e483d.png">

**Comment by shankari** [comment]
@varkon256 as I said earlier, the section segmentation uses the motion activity entries, which you don't have. So you would only have trips, not sections. Not sure why there are no `cleaned_trip` entries.
- You might want to check the `segmentation/raw_trip` entries instead of `analysis/cleaned_trip` entries
- Also, can you send me the intake log via email? We print out all the trips before we insert them, so we should be able to figure out which trips, if any, were created.

**Comment by varkon256** [comment]
@shankari I replaced `analysis/cleaned_trip` with `segmentation/raw_trip` and still didn't get any entries. I sent the intake_single.log file over email.

**Comment by shankari** [comment]
@varkon256 here's what i see in the intake logs

```
2021-02-08 14:37:03,943:DEBUG:4476595712:orig_ts_db_matches = 228934, analysis_ts_db_matches = 0
2021-02-08 14:37:40,795:DEBUG:4476595712:Found 228934 results
2021-02-08 14:37:40,840:DEBUG:4476595712:After de-duping, converted 228934 points to 1
```

It looks like you have a lot of entries, but my de-duping code detects that they are all the same.

And looking at the input file that you attached, it looks like all the inputs for the `fmt_time` and `write_fmt_time` are the same

```
      "fmt_time": "2020-11-05T10:21:24.817000-08:00",
      "write_fmt_time": "2020-11-05T10:21:24.817000-08:00",
      "fmt_time": "2020-11-05T10:21:24.817000-08:00",
      "write_fmt_time": "2020-11-05T10:21:24.817000-08:00",
      "fmt_time": "2020-11-05T10:21:24.817000-08:00",
      "write_fmt_time": "2020-11-05T10:21:24.817000-08:00",
      "fmt_time": "2020-11-05T10:21:24.817000-08:00",
      "write_fmt_time": "2020-11-05T10:21:24.817000-08:00",
      "fmt_time": "2020-11-05T10:21:24.817000-08:00",
      "write_fmt_time": "2020-11-05T10:21:24.817000-08:00",
      "fmt_time": "2020-11-05T10:21:24.817000-08:00",
      "write_fmt_time": "2020-11-05T10:21:24.817000-08:00",
      "fmt_time": "2020-11-05T10:21:24.817000-08:00",
      "write_fmt_time": "2020-11-05T10:21:24.817000-08:00",
      "fmt_time": "2020-11-05T10:21:24.817000-08:00",
      "write_fmt_time": "2020-11-05T10:21:24.817000-08:00",
      "fmt_time": "2020-11-05T10:21:24.817000-08:00",
      "write_fmt_time": "2020-11-05T10:21:24.817000-08:00",
      "fmt_time": "2020-11-05T10:21:24.817000-08:00",
      "write_fmt_time": "2020-11-05T10:21:24.817000-08:00",
      "fmt_time": "2020-11-05T10:21:24.817000-08:00",
      "write_fmt_time": "2020-11-05T10:21:24.817000-08:00",
      "fmt_time": "2020-11-05T10:21:24.817000-08:00",
      "write_fmt_time": "2020-11-05T10:21:24.817000-08:00",
```

**Comment by shankari** [comment]
As you can see from the de-duping code

```
kshankar-35069s:em-bug-upload kshankar$ grep -r de-duping ~/e-mission/e-mission-server/emission/
/Users/kshankar/e-mission/e-mission-server/emission//storage/timeseries/builtin_timeseries.py:            logging.debug("After de-duping, converted %s points to %s " %
```

we de-dup everything with the same write timestamp

```
282         if len(df) > 0:
283             dedup_check_list = [item for item in ecwe.Entry.get_dedup_list(key)
284                                 if item in df.columns] + ["metadata_write_ts"]
285             numeric_check_list = [col for col in dedup_check_list if df[col].dtype != 'object']
286             deduped_df = df.drop_duplicates(subset=numeric_check_list)
287             logging.debug("After de-duping, converted %s points to %s " %
288                           (len(df), len(deduped_df)))
```

**Comment by shankari** [comment]
you could also try scikit-mobility on github.com. Suggested by @PatGendre

**Comment by varkon256** [comment]
@shankari thanks for all the help! I was able to get the segmented trips after fixing the duplication issue in my data. 

I still had to set the key of the json objects in my data to "background/filtered_location" and replace "analysis/cleaned_trip" with "segmentation/raw_trip" in the jupyter notebook to get the trips. 

I got around 2900 trip segments for 22000 coordinates. Is there a way to reduce this or change the number of coordinates pooled in each trip segment? Most of trips I got had (< 10 coordinates).

**Comment by shankari** [comment]
the trip segmentation (at least on android) currently happens based on the dwell time. The default dwell time is here
https://github.com/e-mission/e-mission-server/blob/0475b456db197edacb524c5ab7a1124cd33b5333/emission/analysis/intake/segmentation/trip_segmentation.py#L56

You should first verify that the trips you get are consistent with the current dwell time and then you can tweak the dwell time parameter to get the trips that you want.

**Comment by shankari** [comment]
> eplace "analysis/cleaned_trip" with "segmentation/raw_trip" in the jupyter notebook to get the trips.

That is surprising. You might want to look at the intake logs to see why that is the case. I would expect you to find `cleaned_trip`s with mode `UNKNOWN` instead.

**Comment by shankari** [comment]
@varkon256 closing this issue, please reopen if you have any other questions.
