### ISSUE TITLE
Failed to extract UserCache on a custom E-mission build

### ISSUE THREAD

**Issue by xubowenhaoren** [e-mission/e-mission-docs#613]
Hello, 

we are working on a custom E-mission build and we are interested to do some data analysis on local data collected by an IMU sensor (the relevant `UserCache` access is [here](https://github.com/xubowenhaoren/e-mission-integrity-detect/blob/master/src/android/IntegrityDetector.java#L117)). Thus I wanted to extract the local database. I understand that E-mission currently provides this feature in Profile -> Developer zone -> Check sensed data. 

### What the custom app is behaving

However, when I sent the email to myself, I noticed that there are no `UserCache` attachments. I also tried the "Check log" and the "Email log" functions, but likewise, I wasn't able to extract the `LoggerDB`. I wasn't able to find a similar post in the existing issues, either.

### What solutions I've tried

I downloaded the regular e-mission from the Play Store and noticed that it was able to extract the local databases.  

I also removed my custom plugin from the app. However, in my plugin, I included an `edit-config` flag ([context](https://github.com/xubowenhaoren/e-mission-integrity-detect/blob/master/plugin.xml#L21)) that helps resolve a cleartext communication issue. I found out that an alternative is 

```
npx cordova plugin add cordova-plugin-cleartext
```

However, even after removing my custom plugin and adding `cordova-plugin-cleartext`, the issue still persists.

**Comment by xubowenhaoren** [comment]
Issue resolved after running

```
rm -rf plugins
rm -rf platforms
source setup/setup_android_native.sh
npx cordova plugin add cordova-plugin-cleartext
npx cordova build android
```

**Comment by xubowenhaoren** [comment]
I was able to also add back my IMU plugin. The ability to email `UserCache` and `LoggerDB` attachments was also intact.

**Comment by shankari** [comment]
@xubowenhaoren I also added new functionality to upload files directly to a simple pastebin-like server. The server would be deployed as part of docker-compose. Take a look at https://github.com/e-mission/e-mission-docs/issues/609 if it helps.
