### ISSUE TITLE
Server-side analysis pipeline not working

### ISSUE THREAD

**Issue by xubowenhaoren** [e-mission/e-mission-docs#615]
Hello, 

We set up an azure E-mission server and I was able to register my custom E-mission app. (It works at this step because I was asked to fill in a unique identifier instead of Dummy Debug mode and I don't get a server error upon landing the app homepage.) However, I noticed that I couldn't get motion mode prediction analysis for a mock trip over 24 hours. I mocked through the [Lockito](https://play.google.com/store/apps/details?id=fr.dvilleneuve.lockito&hl=en_US&gl=US) simulator app. 

![Screenshot_2021-02-09-09-51-13-868_edu berkeley eecs emission](https://user-images.githubusercontent.com/20229080/107447846-6b05b500-6af5-11eb-8686-06c31a0ef5cf.jpg)

### What I think the problem is

I believe the problem is that the server-side analysis pipeline is not working. It looks like one has to manually start the pipeline after deploying the server. Is this true that [these steps outlined here](https://github.com/e-mission/e-mission-server#running-the-analysis-pipeline) have to be manually run? I didn't personally deploy the server instance so I don't know the details. I also searched through the existing issue base but I didn't find a similar case.

**Comment by shankari** [comment]
you can run them in a crontab or scheduled tasks

https://github.com/e-mission/e-mission-docker/blob/d0cf0036782102b84a0b3f47c7961cb9ff483a21/examples/em-server-multi-tier-cronjob/analysis/crontab

https://github.com/e-mission/e-mission-docker/blob/d0cf0036782102b84a0b3f47c7961cb9ff483a21/examples/em-server-multi-tier-cronjob/analysis/start_cron.sh#L32

I use `devcron` for my docker deployments to auto-configure the pipeline without manually copying things around

**Comment by shankari** [comment]
Closing this, please reopen if you have other questions.
