### ISSUE TITLE
Android build error messages

### ISSUE THREAD

**Issue by amaksumova** [e-mission/e-mission-docs#617]
Hi there, 

After cloning the repo and following the instructions on the emission phone README, I am getting some errors when running "npx cordova build android" (refer to screenshot below):
<img width="1270" alt="Screen Shot 2021-02-12 at 1 30 09 PM" src="https://user-images.githubusercontent.com/13455293/107824867-020d7f80-6d37-11eb-9cb1-15a55e3f46e3.png">

So far none of the solutions I've found have worked. Here's what I've already tried:
- Checking bash environment variables ($ANDROID_HOME)
- Checking correct installation and path for Android SDK, build tools
- Checking correct versions for Android SDK, build tools
- Re-installing necessary plugins
- Re-cloning the repo and re-running the bash setup script

I'm using the Android Emulator on Android Studio for debugging and was able to build the app successfully before I got these errors. As far as I know the only thing that has changed since then is that my MacOS has updated (Catalina to Big Sur). This might factor into the issue, but I'm unsure. Is there something I'm missing?

**Comment by shankari** [comment]
@amaksumova The automated build on android succeeded 4 days ago.
https://github.com/e-mission/e-mission-phone/actions?query=workflow%3Aosx-ubuntu-build-android

```
Current runner version: '2.276.1'
Operating System
  Mac OS X
  10.15.7
  19H114
Virtual Environment
  Environment: macos-10.15
  Version: 20210130.1
  Included Software: https://github.com/actions/virtual-environments/blob/macOS-10.15/20210130.1/images/macos/macos-10.15-Readme.md
```

That is on version 10.15.7, which I believe is still Catalina.
https://support.apple.com/kb/DL2052?locale=en_US

**Comment by shankari** [comment]
The workflow runs on `macos-latest`
https://github.com/e-mission/e-mission-phone/blob/master/.github/workflows/android-build.yml#L21

which GitHub still maps to `macos-10.15`
https://github.com/actions/virtual-environments#available-environments

**Comment by shankari** [comment]
As an aside, in the future, can you copy-paste the stack trace, so I can copy the relevant lines here.

Did you also upgrade Android Studio as part of the switch to Big Sur?
The main error that I see is "No installed build tools found. Install the Android build tools version 19.1.0 or higher"

I know you said that you checked the Android build tools version. Can you indicate how, and confirm that the version was 19.1.0 or higher?

**Comment by shankari** [comment]
Seems to be primarily related to ANDROID_HOME

> Simply replace System.getenv("ANDROID_HOME") with your real Android SDK path (but you should remember that SDK location differs on other PCs)

Note also from your logs that the "Using SDK" is different from your ANDROID_HOME
I bet that is the problem.

Please close after confirming :)

**Comment by shankari** [comment]
@amaksumova closing this, please reopen if it is still an issue
