### ISSUE TITLE
Change the E-mission landing page from Dashboard to Diary

### ISSUE THREAD

**Issue by xubowenhaoren** [e-mission/e-mission-docs#625]
Hello, 

We wish to change the E-mission landing page from Dashboard to Diary for our custom app. Could you point to the source which specifies the landing page?

**Comment by shankari** [comment]
@xubowenhaoren did you look at existing issues, docs or PRs?
e.g. https://github.com/e-mission/e-mission-phone/pull/737

**Comment by xubowenhaoren** [comment]
This slipped through my search. Thank you!
