### ISSUE TITLE
Suggestion needed regarding creating simplified data analysis scripts with IMU data integration

### ISSUE THREAD

**Issue by xubowenhaoren** [e-mission/e-mission-docs#627]
In our previous email conversations and as indicated in issues #624 and #626, we face difficulties and challenges with generating the pre-defined trips and running the MobilityNet data analysis. Today my project admin suggested another approach: an API that provides a simplified IMU data integration with the E-mission data. This API should also serve as the foundational work for future research that fully integrates the IMU data into the e-mission motion prediction models. 

Roughly in my view, this API should realistically be a Python/Jupyter data analysis notebook with the following requirements: 

1. Connects to an instance of the e-mission server
2. Accepts a user UUID (e.g. email) and use it to fetch all processed trip data
3. For each trip segment, fetch all corresponding IMU data from the SQLite phone UserCache
4. Also for each trip segment, check and fetch user input ground truth. 

Naturally, a prerequisite for this data analysis script is the correct trip segmentation (start/end detection). This is not in the scope of this data analysis script. 

What I have already done: (Please note that the UI is not fully integrated yet)

1. Allow the user to modify each trip segment on the "trip detail" page. 
2. Store the user input to the UserCache, and fetch any existing user input from the UserCache. 

![image](https://user-images.githubusercontent.com/20229080/110564540-d85f3280-8101-11eb-8c8f-462220bf4519.png)
![image](https://user-images.githubusercontent.com/20229080/110564555-e01ed700-8101-11eb-83c1-335e08d9ef4d.png)
 

What I think I need to do to make this notebook working, especially for the requirements 1 and 2 above: 
- Either write the Python equivalent code for the e-mission server connection ~~(rebuilding the wheel)~~
- ~~Or decouple the existing E-mission JS code and call them~~

My questions: 
- When you worked on the MobilityNet scripts, how did you get the server data to run analysis in Jupyter? 
- Is this plan easier than the "alternative plan" that [I proposed here](https://github.com/e-mission/e-mission-docs/issues/624#issuecomment-791594565) and in the email conversation?

**Comment by xubowenhaoren** [comment]
I think I got it. After reading more in the `e-mission-phone` code ([context](https://github.com/e-mission/e-mission-phone/blob/master/www/js/services.js#L49)), I now know how to send a POST request to get all trips of a given day. 

Note this only works for the prompted auth login. 
```
POST http://URL:PORT/timeline/getTrips/2021-03-01

{
    "user": "ACTUAL_USERNAME"
}
```

**Comment by shankari** [comment]
@xubowenhaoren glad you figured it out.
The MobilityNet scripts do pull data from the server using a similar POST call 
https://github.com/MobilityNet/mobilitynet-analysis-scripts/blob/master/emeval/input/spec_details.py#L18

you may have noticed that the MobilityNet server only supports `skip` login for this very reason.
If you don't have `skip` login, you can also dump individual user data using the scripts in `bin/debug`

**Comment by shankari** [comment]
> indicated in issues #624 and #626,

can you highlight again what these issues are:
- wrt #624, the UI needed to be updated to handle the new spec format, but I finished that last night
- wrt #626, not sure what the problem is - there are multiple ways of generating trajectories. The spec expects the trajectory input in a standard format (polylines). You can use whatever method you want to generate polylines. We give you some suggestions, but you are not constrained to use them.

**Comment by xubowenhaoren** [comment]
> > indicated in issues #624 and #626,
> 
> can you highlight again what these issues are:
> 
> * wrt #624, the UI needed to be updated to handle the new spec format, but I finished that last night
> * wrt #626, not sure what the problem is - there are multiple ways of generating trajectories. The spec expects the trajectory input in a standard format (polylines). You can use whatever method you want to generate polylines. We give you some suggestions, but you are not constrained to use them.

I added more tips regarding #626. However, due to a change of the plan, I won't continue working on #624 and #626 for the time being.

**Comment by xubowenhaoren** [comment]
The analysis script can be found here: https://github.com/xubowenhaoren/mobilitynet-analysis-scripts/blob/master/emeval/input/read_server_trip_and_IMU_data.ipynb
