### ISSUE TITLE
Cleanup clustering code implementation

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-docs#631]
1. Fix the comments in https://github.com/e-mission/e-mission-eval-private-data/pull/19, notably:
2. Pull out the filtering code from the binning code so we can filter without binning

**Comment by corinne-hcr** [comment]
check codes #21 needs to be cleaned up later
In get_request_percentage.py, `bin_date`, needs to be changed by using `dataframe.groupby`
In get_plot.py, `get_scatter` needs to be changed by using a dataframe or a numpy array directly

**Comment by shankari** [comment]
- first task is to clean up the notebook, so I can merge it and I can run the code myself as well
- second task is to address the pending issues in this issue which can be summarized as "use dataframes throughout"

- before the second task, you should probably create unit tests for the current functions, so the refactoring can be smooth and relatively bug-free
- the easiest way to add unit tests is to move the python files from here into the e-mission server code, presumably in `emission/analysis/modelling/tour_model`

**Comment by shankari** [comment]
first task + unit tests would take me around 1 day or 1.5 days. If @corinne-hcr can finish it, get it reviewed and merged, in 4 days, I think she can do both the additional analysis and the system integration. If not, I will see if another intern can work on the system integration pieces instead.

**Comment by shankari** [comment]
existing examples of unit tests are in https://github.com/e-mission/e-mission-server/blob/master/emission/tests/

A good example is `analysisTests/intakeTests/TestFilterAccuracy.py` which loads sample data and runs other code (e.g. the pipeline) on it and then expects to see some results.

**Comment by shankari** [comment]
The tests will delete all data in the database that you are running them against. So you should create a new empty mongodb container to run the tests against.

**Comment by shankari** [comment]
Please also remember to add the `tabulate` package to the setup environment file so that the notebook runs without errors

**Comment by corinne-hcr** [comment]
By 6/9 I will finish the notebook refactoring
By 6/13 I will probably finish the unit test
By 6/18 I will finish the dataframe part.

**Comment by shankari** [comment]
@corinne-hcr it is now 6/12, and I don't see an update of the notebook refactoring. At this point, you are behind schedule, which means that finishing the dataframe part by 6/18 is at risk. Do you have a plan to catch up? I don't see any meetings with me this weekend to ask questions.

**Comment by shankari** [comment]
Over the weekend:
- Finish unit tests
- Finish addressing "notebook" comments
- Finish placeholder functions
- Finish dataframe refactoring

**Comment by shankari** [comment]
For "replace placeholder functions", you need to create probabilities at the cluster level. For each cluster, you can get a dataframe with the userinputs for the trips in it. Then you can use `uniq()` and `value_counts()` to figure out the unique set of labels and the number of times that the label occurs. Not sure why you need to link this back to trips.

**Comment by shankari** [comment]
I am now working on refactoring https://github.com/e-mission/e-mission-server/pull/829 to be runnable on production.

**Comment by shankari** [comment]
The first issue was that the codebase was reading all the user trips twice while determining the parameters.
First, in get_user_ls (emission/analysis/modelling/tour_model/get_users.py) and second, in emission/analysis/modelling/tour_model/evaluation_pipeline.py as part of the main function.

**Comment by shankari** [comment]
Tracking initial codebase deployment in https://github.com/corinne-hcr/e-mission-server/pull/2

**Comment by shankari** [comment]
@corinne-hcr I hope you saw the mapping code to handle proper labeling for similarity in the notebook, and including it into a dataframe https://github.com/e-mission/e-mission-eval-private-data/pull/28/commits/18144ef4d1b839196f6b0e3dba3756f2789aacd6

Note that the simple change obviates the need for your "track" data structure and all the complexity in your code from mapping values back and forth. Mapping values is brittle, specially from a 2-D list, and makes everything more prone to errors. 

This has now been checked into the server code:
https://github.com/corinne-hcr/e-mission-server/pull/2/commits/b46a370cc656b4c28f38986375ba4a296ec05f60

**Comment by shankari** [comment]
@corinne-hcr is not going to work on any more code, so closing this for now.
