### ISSUE TITLE
purge_user should also purge usercache and other collections

### ISSUE THREAD

**Issue by PatGendre** [e-mission/e-mission-docs#636]
I use the scripts in the /bin (and in particular in the /bin/debug) for managing some e-mission server back-office tasks.

The [purge_user](https://github.com/e-mission/e-mission-server/blob/master/bin/debug/purge_user.py) script has a --pipeline-purge options, but still 3 collections are not deleted and I had to delete the entries manually in mongodb for the Stage_Profiles Stage_timeseries_error and Stage_usercache collections.

Will this script be updated or should I propose a correction to the script?

More generally, are all the scripts maintained and should I propose updates to other scripts? (such as export and load_timelines)

**Comment by shankari** [comment]
@PatGendre `--pipeline-purge` does what it says - it purges the pipeline database. You are right that the profiles, timeseries_error and usercache collections are not currently purged.

I can fix this towards the end of May, but a PR would definitely be welcome!

In general, the export and load timeline scripts are maintained. Scripts in `bin/historical` were created for one-off tasks and are *not* maintained.

**Comment by shankari** [comment]
Maybe a better way to phrase this is that although the scripts are maintained, they are not necessarily super well designed. 

They are basically created/modified by me to solve whatever immediate problem I have, with the goal of making existing scripts more comprehensive over time. So feel free to modify them to meet your needs, or to suggest improvements/changes needed 😄

**Comment by PatGendre** [comment]
Ok I created [a PR](https://github.com/e-mission/e-mission-server/pull/806), it works but not sure it will save you time ;-)

**Comment by shankari** [comment]
Merged https://github.com/e-mission/e-mission-server/pull/806
Closing this issue.
