### ISSUE TITLE
protecting e-mission's web API

### ISSUE THREAD

**Issue by PatGendre** [e-mission/e-mission-docs#638]
Hi, to my knowledge the e-mission server web API is completely open (datastream, heatmap, etc.). 

What would be the solution to allow only phone users and certain other authorized users to access it ?    
Thanks for your advice!

**Comment by shankari** [comment]
Hi @PatGendre you might want to check out https://github.com/e-mission/e-mission-server/pull/801
which fixed the prior issue filed for this
https://github.com/e-mission/e-mission-docs/issues/408
