### ISSUE TITLE
Explanation of the accuracy field under the developer section of the Profile tab

### ISSUE THREAD

**Issue by asiripanich** [e-mission/e-mission-docs#665]
There are quite a few options to choose from. The master branch has one option, and the CanBikeCO has something different. However, I have no ideas what those options actually do. I have tried to find this field in the codebase of phone and server but couldn't find anything related to that. Can you point me to the location where this option lives in the codebase?

**Comment by shankari** [comment]
@asiripanich the actual data collection code is in the data collection plugin. The phone code is just the UI for the app.
The data collection plugin is at
https://github.com/e-mission/e-mission-data-collection/blob/master/src/ios/BEMDataCollection.m

As an example, the mapping to the iOS constants are at
https://github.com/e-mission/e-mission-data-collection/blob/master/src/ios/BEMDataCollection.m#L244

**Comment by asiripanich** [comment]
@shankari Thanks! Is it true that we should use `kCLLocationAccuracyBest` because it is the "best" possible one? :)

**Comment by shankari** [comment]
First, you can choose to use any accuracy that you want as a deployer. The default is indeed to use the "best" accuracy. See Chapter 3 of my thesis for some intuition around the difference between "best" and "medium" and Chapter 7.2 paper for a more generalized comparison of the power/accuracy tradeoff.

**Comment by shankari** [comment]
Most of the testing and deployment (other than chapter 3 and chapter 7.2) has also been with "best" accuracy.
