### ISSUE TITLE
Documentation for new Label UI

### ISSUE THREAD

**Issue by GabrielKS** [e-mission/e-mission-docs#666]
This is to track the documentation we will have to write to teach users of the old Label UI how the new label UI works. Off the top of my head, it should cover:
 * What we're hoping to accomplish with this update
 * New workflow: go to Label instead of Diary; note that there is a delay before trips appear in Label; you're done when there's nothing more in To Label
 * Label screen scrolling direction is reversed; also you have to click a button to load older trips
 * The default tab is To Label, where only the trips you need to label appear; if you want to see all your trips, go to the All Trips tab
 * What the red/yellow/green label colors mean
 * High-level overview of how inference works (to motivate the user to label their trips)
 * How the confirm button works
 * High-level overview of how client-side on-the-fly inference works
 * Something vague about multiple collection modes ("the exact requirements for a trip to appear in To Label may change from time to time depending on…")

and of course it should be concise as possible and written for an audience with no technical background.

@shankari Can you think of anything else?

**Comment by shankari** [comment]
that looks pretty comprehensive. @andyduvall can you think of anything else?

**Comment by GabrielKS** [comment]
# FAQ on the new Label screen interface
## What is the new Label screen interface?
Recently, we began testing a new look for the app's Label screen. The purpose of the new interface is to reduce the amount of labeling work you have to do by trying to guess labels for you.

## How should I use the new interface?
Instead of using the Diary screen to label trips, use the Label screen. Trips take a little longer to appear here, but once they do they will be more accurate. Within the Label screen, there are a few tabs, including one called "To Label." On this screen, only the trips that you need to label will appear; trips will automatically disappear when you label them. Once no more trips appear in To Label, you are done labeling for the day. See below for how to use some more time-saving features we've added.

## Any major changes to how trips are displayed?
Before, the newest trip appeared at the top of the screen and you scrolled down to get to more, like an email inbox. Now, the newest trip appears at the bottom of the screen and you scroll up to get more, like a texting app. Also, to load older trips, you now have to click a button.

## Why are some of my trips not appearing?
The "To Label" tab only shows trips that you need to label. For some of your trips, an algorithm was able to predict what the labels were so accurately that you don't need to tell us anything about those trips. If you want to see all of your unlabeled trips or all of your trips anyway, you can use the "All Unlabeled" and "All Trips" tabs.

## What do the red, yellow, and green label colors mean?
Red means we were not able to predict anything for that label and you should enter it manually just like before. Yellow means we tried to predict something, but if the trip is on the To Label screen we need you to confirm that this prediction is correct. If it's correct, you can use the "confirm" button (see below). If it's incorrect, you can correct it as if it were a red label. Green means you have already manually entered or confirmed the label.

## What does the checkmark button do?
Each trip on the Label screen now has a checkmark button. If the trip has any yellow labels, pressing this button will turn them green and let us know that those yellow labels are correct. Only press this button if the yellow labels are correct! If some of them are correct and some of them are incorrect, you can correct the ones that need correcting and then push the button.

## How does the prediction algorithm work?
The prediction algorithm tries to match each trip you take to a trip you have taken before. For instance, if you bike to work every day and label that trip, eventually the algorithm will learn what biking to work looks like and be able to automatically enter those labels for you. This works better the more times you take a certain trip, so if you take a new trip, the algorithm will not be able to predict it for you. It also only works if you've labeled your trips in the past — labeling trips will eventually keep you from having to label as many trips!

If the same trip sometimes has different labels (e.g. if you mostly bike to work but sometimes take the bus), the algorithm will first predict the most common. But if you correct one of the labels for one of these trips, the algorithm will try to instantly correct the trip's other labels for you.

## Why do certain trips sometimes appear under To Label and sometimes not?
The exact requirements for a trip to appear in To Label may change from time to time so that we can collect the most useful data while requiring you to do the least amount of work.

**Comment by GabrielKS** [comment]
^ There's a draft. Thoughts?

Also, how much would it benefit from screenshots?

**Comment by shankari** [comment]
> Also, how much would it benefit from screenshots?

In general, the admins think that both screenshots and videos are helpful

**Comment by shankari** [comment]
Based on 
My daughter's feedback:
I mostly get it but I am confused about the difference between the "To Label" and "All Unlabeled" tabs. Do the red trips show up in To Label and the yellow trips in All Unlabled? If so do I need to also check the All Unlabled tab every day and confirm the yellow trips? If not then what shows up in All Unlabled and do I have to do anything with it?

**Comment by GabrielKS** [comment]
Draft FAQ with screenshots is now up using GitHub Pages at https://gabrielks.github.io/e-mission-server/webapp/www/faq/hybrid_labeling.html so the deployers can review it. Not planning to leave that site up long after the PR is merged, so if it's down by the time you get there that's probably why.

**Comment by GabrielKS** [comment]
Without objection, I'd say this is ready to be merged.

**Comment by GabrielKS** [comment]
Here's a draft of the two-paragraph summary aimed at participants:

> Starting today, we are updating the CanBikeCO app to reduce the amount of labeling work you have to do. We do this with an algorithm that tries to guess labels for you. The Label screen is the only screen that has changed, so we recommend you do your labeling there instead of on the Diary screen. Trips take an hour or two to appear on the Label screen, but when they do they will be more accurate. On the Label screen, trips are now sorted so the most recent trip is at the bottom, you scroll up to see older trips, and you can press a button to see even older trips.
> 
> The Label screen now has three tabs, including "To Label." On the To Label screen, only the trips you need to label will appear — for some of your trips, the algorithm was able to predict the labels with such confidence that we don't need your input at all. (Those trips appear on the "All Unlabeled" and "All Trips" tabs if you're curious.) On the Label screen, labels are red if we couldn't predict them, yellow if we could predict them, and green if you entered or confirmed them yourself. If you see yellow labels on the To Label tab, this means you need to confirm or correct them. If all of a trip's yellow labels are correct, you can click the checkmark button, which will turn them green (the checkmark button doesn't do anything to red or green labels). If certain yellow labels are incorrect, you can correct them just like you'd enter a label normally. Labeled trips disappear from the To Label tab after a minute, and when the To Label tab is empty, you're done labeling for the day! As you label your trips, the algorithm will get better at predicting labels, so keeping up-to-date with your labeling will save you work in the long run!
> 
> For more information and instructions, see https://www.canbikeco.org/faq/hybrid_labeling.html. Please contact k.shankari@nrel.gov if you have any confusion about how to use this new update and we will be glad to assist.

However, I'm thinking about the users I encountered at the Boulder distribution events, and I'm worried that even this and the online FAQ will not be enough to give some of them the confidence they need to use the new system. We should keep in close contact with these users and consider videos, synchronous help sessions, etc. if necessary.

**Comment by shankari** [comment]
@andyduvall I've deployed the updated website with "more information and instructions" at 
https://stage.canbikeco.org/faq/hybrid_labeling.html

@GabrielKS I wonder if you could have the three screenshots appear side by side instead of one below the other (by using a `<table>` or `<div row`). Because the website supports responsive design, I believe the screenshots will appear one below the other on mobile screens.

**Comment by GabrielKS** [comment]
I will first get a draft of the walkthrough working, as that should also help a lot with documentation, and then come back to condense the summary into bullet points and reposition the screenshots on the webpage.

**Comment by GabrielKS** [comment]
Condensing the above two-paragraph summary into bullet points as per @andyduvall's suggestions:

The tutorial itself:
 * The CanBikeCO app now tries to predict some of your trip labels for you!
 * To use this new feature, use the Label screen instead of the Diary screen.
 * You only need to label the trips under the "To Label" tab; the rest are taken care of automatically.
 * Yellow labels are the app's "guesses." If these guesses are all correct for a particular trip, click on the trip's checkmark button. If they are wrong, label them normally.
 * Once the "To label" tab is empty, you are done labeling for the day!

One or more of these "for more information" options may be added:
 * The ‘?’ button at the top of the Label screen gives you a tour of some more timesaving features.
 * See https://www.canbikeco.org/faq/hybrid_labeling.html for more timesaving features!
 * Please contact k.shankari@nrel.gov if you have any questions or confusion and we'd be glad to help.

**Comment by GabrielKS** [comment]
I sent the following email to deployers last night. For now, that closes this issue.

> Hello deployers,
> Tonight, we are deploying the auto-labeling updates to the Label interface! I’ve composed a few resources to help your participants learn how to use the updates:
>  * First of all, there’s [this](https://canbikeco.org/faq/hybrid_labeling.html) specialized FAQ page. It’s distinct from the general FAQ page so the new information is all in one place. The general FAQ page remains relevant; it and the CanBikeCO homepage have been updated with a link to the new page.
>  * Second, within the app, if users go to the Label screen and click on the question mark icon in the top left corner, there is an in-app walkthrough showcasing some of the new features. This is still a little bit buggy, but it works for the most part and in all cases should be better than nothing; we’re hoping to polish it up tomorrow.
>  * Third, I have condensed the updates down to a set of bullet points, which are given below. There are several “for more information” options given depending on the context. You might consider sending these bullet points out in an email to participants.
>  * Fourth, I have condensed the updates down to two paragraphs, also given below. It’s been suggested that these are a bit much for participants to read, so use them (or not) with that in mind.
>  
> I hope these resources are helpful. Let me know if you have any suggestions for improvements!
> -Gabriel
>  
>  
> **Tutorial bullet points:**
>  * The CanBikeCO app now tries to predict some of your trip labels for you!
>  * To use this new feature, use the Label screen instead of the Diary screen.
>  * You only need to label the trips under the "To Label" tab; the rest are taken care of automatically.
>  * Yellow labels are the app's "guesses." If these guesses are all correct for a particular trip, click on the trip's checkmark button. If they are wrong, label them normally. Red labels are labels the app could not guess; these must also be labeled manually.
>  * Once the "To label" tab is empty, you are done labeling for the day!
>  * The more you label, the better the guesses get and the less work you have to do!
> [Deployers: one or more of these "for more information" options may be added:]
>  * The ‘?’ button at the top of the Label screen gives you a tour of some more timesaving features.
>  * See https://www.canbikeco.org/faq/hybrid_labeling.html for more timesaving features!
>  * Please contact k.shankari@nrel.gov if you have any questions or confusion and we'd be glad to help.
>  
>  
> **Two paragraphs:**
> Starting today, we are updating the CanBikeCO app to reduce the amount of labeling work you have to do. We do this with an algorithm that tries to guess labels for you. The Label screen is the only screen that has changed, so we recommend you do your labeling there instead of on the Diary screen. Trips take an hour or two to appear on the Label screen, but when they do they will be more accurate. On the Label screen, trips are now sorted so the most recent trip is at the bottom, you scroll up to see older trips, and you can press a button to see even older trips.
>  
> The Label screen now has three tabs, including "To Label." On the To Label screen, only the trips you need to label will appear — for some of your trips, the algorithm was able to predict the labels with such confidence that we don't need your input at all. (Those trips appear on the "All Unlabeled" and "All Trips" tabs if you're curious.) On the Label screen, labels are red if we couldn't predict them, yellow if we could predict them, and green if you entered or confirmed them yourself. If you see yellow labels on the To Label tab, this means you need to confirm or correct them. If all of a trip's yellow labels are correct, you can click the checkmark button, which will turn them green (the checkmark button doesn't do anything to red or green labels). If certain yellow labels are incorrect, you can correct them just like you'd enter a label normally. Labeled trips disappear from the To Label tab after a minute, and when the To Label tab is empty, you're done labeling for the day! As you label your trips, the algorithm will get better at predicting labels, so keeping up-to-date with your labeling will save you work in the long run!
>  
> The ‘?’ button at the top of the Label screen gives you a tour of these features. For more information and instructions, see https://www.canbikeco.org/faq/hybrid_labeling.html. Please contact k.shankari@nrel.gov if you have any confusion about how to use this new update and we will be glad to assist.
