### ISSUE TITLE
Walkthrough broken for certain elements on the Label screen

### ISSUE THREAD

**Issue by GabrielKS** [e-mission/e-mission-docs#669]
Placeholder so I can reference this issue in commits; I'll add more details in the next posts.

**Comment by shankari** [comment]
Try a different, lamer fix in which we just highlight the entire list for all row level entries, since it is not even clear that we will have a single row.
nzTour is deprecated anyway, maybe the suggested replacement 
https://github.com/tannerlinsley/tour
will fix this.

**Comment by shankari** [comment]
Immediate fix in https://github.com/e-mission/e-mission-phone/pull/796
Moving to "revisit later" pile and closing.
