### ISSUE TITLE
Questions about app data ?

### ISSUE THREAD

**Issue by PatGendre** [e-mission/e-mission-docs#685]
Hi @shankari 
I try to solve some problems for a few users and want to understand better how the app data work, so I have questions on this topic, and it may be useful to answer when you have time, so as to update the documentation.

As far as I understand :
- there are 3 kinds of data in the app : 
   1) **usercache** (local-storage (user inputs), messages (states), sensor (battery), rw (config))

   2) **loggerDB** (logs, including communication the server)
- both user cache and logs are stored in sqlite. The user can send the sqlite files wia email (but when they exceed say 25MB it is not possible and then it could be useful to save on the phone ; in canbikeco the logs are uploaded to a server not sent by email).
- it is possible to view the logs and the user cache (sensed data) in the app (profile / dev zone)
- in the dev zone, there are 2 buttons ; invalidate-cached-docs and nuke-all. **->** Does the 1st one clear UserCache and the second one clear UserCache and logs? 
- in the Android application parameters, (I guess it's similar for iOS) the user can also clear Cache, and clear Data. **->** Is the app cache the same as the usercache DB ? and is the app Data the same as loggerDB (+ possibly the trip data, see below) ?? 
- For my app on the android parameters screen, I see the app is 24MB, the user data 67MB, the cache is 103MB, which is quite large. For the user data I suppose it is large because the pipeline doesn't work currently for my data (but this is another issue). As for the cache : **->** What are the rules for cleaning the cache? (and for cleaning the loggerDB?) Is it possible that a too large cache causes app malfunctions, is it a good idea to clear it from time to time?

   3) trip data
I understand that the app stores the trip data until it can send it to the server, and the data can already been viewed as draft trips in the diary.
But I do not understand **where the trip data is actually stored in the app**, I don't see it when I browse the usercache, is there another sqlite db ? (maybe I should browse the apk for understanding this?)
Then when the data is sent to the server and stored in the timeseries db collection, and the user still sees it as draft in the trip diary until they have been processed by the pipeline. 
If i click on the "download json dump" button in the profile **->** is the data fetched from the server or the app depending on the date ? (and whether the data is available locally or not) 
  
 Sorry for all the questions, thanks if you (or another committer) have time to answer :-)

**Comment by shankari** [comment]
> The app cache should not be the same as the usercache. The usercache (since it is stored in SQLite) should be part of the app data. I have not tested clearing the usercache/app data to see what happens to the usercache, will do that and update the issue.

Here are my findings which are consistent with my explanation above.

| Stage | Cache | Data | 
|-------------------------|------|-----|
| Install the app on a new emulator | 1.44MB | ~ 500 kb |
| Clear the cache | 0 MB | ~ 500 kb | 
| Return to app; force sync (no error); return to settings | 40 kb  | ~ 500 kb |
| Clear data | 0 MB | 0 MB |
| App had crashed; relaunch; back to first intro screen (all usercache data cleared) | 1.41 MB | ~ 500 kb |

**Comment by PatGendre** [comment]
@shankari thanks for the great answers :-)
it is much clearer for me now :-)
to sum up, 
- app cache and usercache are two separate things.
- usercache include sensed data which are used for building draft trips when data has not yet been sent to server
- usercache contains also other data : messages (mostly stats?), and rw-documents (mostly consent and config data?) and local storage documents (which include geofence location, which should also be sent to the server in the timeseries collection)

**Comment by shankari** [comment]
@PatGendre all correct, except:
- I don't think we should send the local storage documents to the timeseries, but instead, just make sure that we delete the older versions when we create new versions of the document
- the draft trips are built from both the usercache (before it has been sent to the server) and the server (before the data has been processed)

**Comment by PatGendre** [comment]
@shankari thanks again, for the 2nd point, I had got it, but omitted to include it in my recap, I should have included it :-)

**Comment by shankari** [comment]
Closing this issue now.
