### ISSUE TITLE
document page links broken

### ISSUE THREAD

**Issue by sichen1234** [e-mission/e-mission-docs#690]
These links on the https://github.com/e-mission/e-mission-docs/tree/master/docs are not working:

- e-mission web site
- TRB paper describing how to use e-mission functionality
- The in-review paper on the e-mission architecture, please do not distribute

**Comment by shankari** [comment]
Fixed in https://github.com/e-mission/e-mission-docs/commit/fb82f1c4f401bc7911f5f6e68a4de4d8636ecdc1
