### ISSUE TITLE
trips are recorded but no CO2 footprint is available

### ISSUE THREAD

**Issue by sichen1234** [e-mission/e-mission-docs#691]
We've gotten the android app running and recording trips.  They are in the server's mongo database.  But there is no CO2 footprint in the android app.

Does something else need to be installed for the Co2 footprint?

**Comment by shankari** [comment]
@sichen1234 can you provide additional information about your configuration?

Concretely, how did you configure your server? How did you configure the phone?
What do you see in the phone UI?...

**Comment by rybalko** [comment]
we are using docker-compose.dev.yml to run docker images for server and mongo
it is running on our ec2 server
in phone app connectionConfig.json connectUrl is set to our ec2 instance access point for e-mission server.
after trip is created, i.e. it has 'draft' status I run intake_single_user.py for our test users
and 'draft' status is disapeared, but footprint on Dashboard still shows 0 CO2
I don't sure what to say about 'trips in the server', I see our trips data stored in the mongo Stage_timeseries.

**Comment by rybalko** [comment]
there are screenshots form my device
![Screenshot_20211208-210745_emission](https://user-images.githubusercontent.com/357010/145269325-93eea530-d4ef-44c8-aae7-7670a5f5fff9.jpg)
![Screenshot_20211208-210753_emission](https://user-images.githubusercontent.com/357010/145269328-45cadd97-5a69-4efe-81ec-006e96aa0f4e.jpg)
![Screenshot_20211208-210759_emission](https://user-images.githubusercontent.com/357010/145269332-f6647f6a-ec2b-4f84-99f2-3ec840533f00.jpg)

**Comment by shankari** [comment]
@rybalko the CO2 calculation uses `inferred_section` objects by default (see `conf/analysis/`).

If you have non-draft trips, but still don't see CO2 calculations, it is probably that you have an error in going from cleaned trips to inferred trips.

Troubleshooting:
- Is the CO2 expected to be non-zero? If you are walking everywhere, the carbon footprint (according to current calculations) is zero.
- do you have `analysis/inferred_trip` objects in the analysis timeseries?
-  Are there any errors with running the pipeline `intake_single_user.py`?

Potential solutions:
- If you are running from the master branch you need a saved model for the mode inference. You should probably switch to the `gis-based-mode-detection` branch instead.
- or you could change the config in `conf/analysis` to use `analysis/cleaned_section` instead of `analysis/inferred_section`

LMK how it goes!

**Comment by rybalko** [comment]
Do you mean Stage_analysis_timeseries with "metadata.key" : "analysis/inferred_trip" ?
I don't see such objects for new trips.

intake_single_user.py shows 2 errors
FileNotFoundError: [Errno 2] No such file or directory: 'conf/net/ext_service/habitica.json'
FileNotFoundError: [Errno 2] No such file or directory: 'seed_model.json'
but continue calculation, all steps, up to "storing views to cache"
there is a console log:
````
FileNotFoundError: [Errno 2] No such file or directory: 'conf/net/ext_service/habitica.json'
2021-12-09T14:39:33.537253+00:00**********UUID f419ee42-ee92-441a-a695-f969b72d102e: moving to long term**********
2021-12-09T14:39:34.223392+00:00**********UUID f419ee42-ee92-441a-a695-f969b72d102e: updating incoming user inputs**********
2021-12-09T14:39:34.301786+00:00**********UUID f419ee42-ee92-441a-a695-f969b72d102e: filter accuracy if needed**********
2021-12-09T14:39:34.307472+00:00**********UUID f419ee42-ee92-441a-a695-f969b72d102e: segmenting into trips**********
2021-12-09T14:39:35.883894+00:00**********UUID f419ee42-ee92-441a-a695-f969b72d102e: segmenting into sections**********
2021-12-09T14:39:36.044609+00:00**********UUID f419ee42-ee92-441a-a695-f969b72d102e: smoothing sections**********
2021-12-09T14:39:36.195457+00:00**********UUID f419ee42-ee92-441a-a695-f969b72d102e: cleaning and resampling timeline**********
2021-12-09T14:39:36.615473+00:00**********UUID f419ee42-ee92-441a-a695-f969b72d102e: inferring transportation mode**********
FileNotFoundError: [Errno 2] No such file or directory: 'seed_model.json'
2021-12-09T14:39:36.637558+00:00**********UUID f419ee42-ee92-441a-a695-f969b72d102e: inferring labels**********
2021-12-09T14:39:36.656329+00:00**********UUID f419ee42-ee92-441a-a695-f969b72d102e: populating expectations**********
2021-12-09T14:39:36.669164+00:00**********UUID f419ee42-ee92-441a-a695-f969b72d102e: creating confirmed objects **********
2021-12-09T14:39:36.689132+00:00**********UUID f419ee42-ee92-441a-a695-f969b72d102e: storing views to cache**********
````

**Comment by shankari** [comment]
@rybalko have you resolved this? can I close the issue?

**Comment by rybalko** [comment]
I've run intake_single_user.py on gis-based-mode-detection branch
total co2 still be zero, but there are some not zero numbers on the footprint section rows
and some calories. See screenshot.
![Screenshot_20211216-153940_emission-mini](https://user-images.githubusercontent.com/357010/146384205-789c68b7-aea2-4c36-9764-33ea467746f0.jpg)

**Comment by shankari** [comment]
@rybalko as I said, if all your trips are walking trips, the carbon footprint *will* be zero. The CO2 factors for the various modes are defined at https://github.com/e-mission/e-mission-phone/blob/master/www/js/services.js#L444

**Comment by sichen1234** [comment]
@rybalko leads a very good lifestyle.  It is working for me calculating the CO2 emissions now.
![Screenshot_20211216-084559_emission](https://user-images.githubusercontent.com/1706353/146424930-2c79d499-9b35-4b10-8252-46c854087b59.jpg)

So are optimal, average, worst based on different calculated paths for the trips recorded, as compared to the actual trips recorded?

**Comment by shankari** [comment]
These two might help understand better:
https://github.com/e-mission/e-mission-docs/issues/149
https://github.com/e-mission/e-mission-server/blob/master/front/server/carbon_calc_details.html

**Comment by sichen1234** [comment]
Thank you.  That is helpful.  I think this can be closed now.
-----
Si Chen
Open Source Strategies, Inc.

Free e-Book: Open Climate Investing
<https://climate-investing-book.opensourcestrategies.com/v/main/book>
