### ISSUE TITLE
app behavior after having manually stopped tracking

### ISSUE THREAD

**Issue by PatGendre** [e-mission/e-mission-docs#692]
@shankari a user tested the "stop tracking" button and she seems to have difficulties to have her trips detected when she turned tracking off again.    
Could this be related to the usage on the tracking off/on button?   
To what state does the app transitions to when tracking is turned on ? To "waiting for trip start" ?

**Comment by shankari** [comment]
If tracking is turned back on, it should transition back to `waiting_for_trip_start` unless there were issues with the settings, in which case it will stay in `state_start`

**Comment by PatGendre** [comment]
Thanks! I'll check in the logs.

**Comment by PatGendre** [comment]
Thanks! I'll check in the logs.
