### ISSUE TITLE
no inferred labels

### ISSUE THREAD

**Issue by PatGendre** [e-mission/e-mission-docs#720]
In our la Rochelle instance, we don't use the mode/purpose prediction algorithm currently, however the stage is executed by the pipeline.

Although some users do complete some mode / purpose data manually with the app, we don't have any inferred labelling.

That is, we have 21k inferred trips but the data.inferred_labels field is always [].

Same with the inference/labels and inference/prediction objets in the analysis_timeseries collection, they are always empty.

  Why is that? Do we need to configure the algorithm somewhere if we'd like to see some label predictions  ?

**Comment by shankari** [comment]
Yes, you need to enable the model building pipeline. 
- The model is built based on previously labeled trips.
- The intake pipeline reads the model and applies it to incoming trips.

I have added the model building pipeline stage to my crontab and run it once a day
https://github.com/e-mission/e-mission-docker/commit/3eb39cdc2f5eb5b88f9eacf992c146758ea01723

**Comment by PatGendre** [comment]
@shankari thanks !
I'll with the la Rochelle team, it should be a good idea to test the model building :-)
So I close the issue. But we should take the time the time to document this.
