### ISSUE TITLE
Couple of native code fixes

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-docs#722]
#### Crash reported in the app store

<img width="890" alt="Screen Shot 2022-04-26 at 10 02 28 AM" src="https://user-images.githubusercontent.com/2423263/165354155-a309b931-3270-4cda-b65b-4f092216548f.png">

Related code is:

```
    NSAssert([lastLocArray count] > 0, @"Found no locations while ending trip!");
```

#### Force-kill message is too long to view but doesn't show details when app is opened

Looks like I fixed this anyway....

| overlap | force kill
|----|----|
| <img width="400" alt="Screen Shot 2022-04-26 at 10 26 47 AM" src="https://user-images.githubusercontent.com/2423263/165359558-073e1f6c-b325-4972-808f-da749b20e8e4.png"> | <img width="400" alt="Screen Shot 2022-04-26 at 10 41 17 AM" src="https://user-images.githubusercontent.com/2423263/165360228-175f0fad-0c8b-4b11-ac56-05fbf37cfba6.png"> |

**Comment by shankari** [comment]
cutout overlap seems to require `viewport-fit=cover`
Not sure if that works with ionic 1

**Comment by shankari** [comment]
For the first issue, let's replace the assert by

```
    if ([lastLocArray count] == 0) {
        StatsEvent* se = [[StatsEvent alloc] initForEvent:@"no_locations_while_ending_trip"];
        [[BuiltinUserCache database] putMessage:@"key.usercache.client_error" value:se];
    }
```

**Comment by shankari** [comment]
There are a bunch of additional asserts in the transition notifier code.
Let's replace all of them for now.
We may remove it completely later.

**Comment by shankari** [comment]
for the second issue:
https://developer.mozilla.org/en-US/docs/Web/HTML/Viewport_meta_tag

https://udn.realityripple.com/docs/Web/CSS/@viewport/viewport-fit
> The viewport is scaled to fill the device display. It is highly recommended to make use of the [safe area inset variables](https://udn.realityripple.com/docs/Web/CSS/env) to ensure that important content doesn't end up outside the display.

**Comment by shankari** [comment]
So ionic1 does not support the safe area inset variables

```
$ grep -r safe-area-inset-top css/ js/
$
```

Tried to add them manually per instructions:
https://developer.mozilla.org/en-US/docs/Web/CSS/env
https://udn.realityripple.com/docs/Web/CSS/env

```
body {
  padding:
    env(safe-area-inset-top, 20px)
    env(safe-area-inset-right, 20px)
    env(safe-area-inset-bottom, 20px)
    env(safe-area-inset-left, 20px);
}
```

But they are overridden by `app.css` from `www/build/app.css`.

<img width="762" alt="Screen Shot 2022-04-26 at 12 48 00 PM" src="https://user-images.githubusercontent.com/2423263/165380415-2a95464b-fd06-40c1-8f12-ca2699d41be9.png">

All the stuff in `www/build/` is related to habitica. 
https://github.com/e-mission/e-mission-phone/commits/master/www/build/app.css

Can we just remove it, or will it break anything else?

**Comment by shankari** [comment]
removed, next overridden by entry is `styles.css`
removed that as well.

**Comment by shankari** [comment]
Turned out that this was because the `ion-view` was set to a height of 100%, which caused it to go off the screen if we changed the padding of the body.

Further changes:
- view container height = 100% - safe-area-inset-top
- this causes the scroll bar inside the view to not be at 100%, so we set its height to 100% - 50px as well
- and then we make all of this apply only to iOS https://stackoverflow.com/questions/27432360/how-to-isolate-specific-platforms-using-css-selectors-in-the-ionic-framework to avoid regressions on android

**Comment by shankari** [comment]
| No body | Body but no scroll content height |  Body but with a limited offset | Everything + scroll height |
|----------|---------|------|----|
| <img width="387" alt="Screen Shot 2022-04-26 at 3 33 26 PM" src="https://user-images.githubusercontent.com/2423263/165403638-7badcf66-aa2a-4a83-9ecc-3fb6da939294.png"> | <img width="387" alt="Screen Shot 2022-04-26 at 3 27 33 PM" src="https://user-images.githubusercontent.com/2423263/165403035-6a83ace0-90c5-45e5-a15d-2d8a46565c0e.png"> | <img width="387" alt="Screen Shot 2022-04-26 at 3 38 20 PM" src="https://user-images.githubusercontent.com/2423263/165404209-7e36d081-49bf-4027-a200-a17ccf7832e5.png"> |  <img width="387" alt="Screen Shot 2022-04-26 at 3 47 29 PM" src="https://user-images.githubusercontent.com/2423263/165405253-f5aad4a6-f749-4564-87b0-a2d95e451db0.png"> |

**Comment by shankari** [comment]
Apparently, the right way to select by class is:

```
body.platform-ios {
  padding-top: calc(env(safe-area-inset-top) / 2);
  margin: 0 10px 0 0;
}

.platform-ios .view-container {
  height: calc(100% - (env(safe-area-inset-top) / 2));
}

.platform-ios .scroll-content {
    height: calc(100% - 50px);
}
```

**Comment by shankari** [comment]
Looks fine on both android and iOS

| android | iOS |
|--------|------|
| <img width="387" alt="Screen Shot 2022-04-26 at 4 26 28 PM" src="https://user-images.githubusercontent.com/2423263/165408950-abb20609-0035-4fe0-bdbb-f3a303f993e6.png"> | <img width="387" alt="Screen Shot 2022-04-26 at 4 25 10 PM" src="https://user-images.githubusercontent.com/2423263/165408953-e7f3bffc-a8a6-49d2-893d-a9f51fc0d9ec.png"> |

**Comment by shankari** [comment]
One final issue: Giving additional notification privileges causes the notification check on iOS to fail.
We currently request 

```
    return [UIUserNotificationSettings
            settingsForTypes:UIUserNotificationTypeAlert|UIUserNotificationTypeBadge
            categories:nil];
```

which maps to a types of 5
https://developer.apple.com/documentation/uikit/uiusernotificationtype?language=objc

If the user allows sound as well, the requested types are 5, but the provided types are 7, which causes this check to fail

```
return requestedSettings.types == currSettings.types;
```

Couple of potential fixes:
- request everything including sound
- check for provided > requested
   - this could be incorrect because UIUserNotificationTypeSound|UIUserNotificationTypeAlert = 6 > 5 but it means that we don't have the badge permission
- check for the actual permissions using bitwise operators
   - this should be `actual settings & requested settings = requested settings`

**Comment by shankari** [comment]
There seems to be a minor difference between CanBikeCO and master - CanBikeCO does not need the `scroll-content` fix. And in fact, if it has the scroll-context fix, it breaks because we cannot see the lowest card fully.

| with scroll-content override | without scroll-content override |
|-----|-----|
| <img width="387" alt="Screen Shot 2022-04-26 at 10 31 05 PM" src="https://user-images.githubusercontent.com/2423263/165447496-d5d5a014-860f-4428-b374-a97e7696f97a.png"> | <img width="387" alt="Screen Shot 2022-04-26 at 10 28 49 PM" src="https://user-images.githubusercontent.com/2423263/165447236-adf695a8-88d9-4637-abb5-8cbfff8d63fa.png"> |

**Comment by shankari** [comment]
@asiripanich here are some fit and finish fixes for iOS, including a crash and the "notch" UI on recent model phones.
LMK if you notice any of them!

**Comment by asiripanich** [comment]
@shankari thanks! I will get our team to test this.
