### ISSUE TITLE
Simple Usability Fix: Upload logs changes

### ISSUE THREAD

**Issue by sebastianbarry** [e-mission/e-mission-docs#742]
**The Account button "Upload Logs" has a usability issue where, while the popup is uploading the logs, the popup says "sending ___MB to server..." but there is not obvious enough graphics to reflect that the user cannot just click away immediately**

<img width="381" alt="image" src="https://user-images.githubusercontent.com/61334340/175387109-a6c8995c-e406-47a7-9c86-16808ad8ae47.png">

### 3 things I can think of to make this better:

1. Change the "OK" button to be a "Cancel" button
2. Change the color of the OK button to red (from green)
3. Add a graphic to indicate to the user that the page is loading while it is "sending..."

------

**Comment by shankari** [comment]
how did you try to find the code for the "upload log" button?

**Comment by sebastianbarry** [comment]
> how did you try to find the code for the "upload log" button?

I found the code by using the Safari Debugger _target_ feature to select the "Upload" button which took me to the HTML for the button, and then from there I found the function name being called, which is located in the uploadService.js file

**Comment by sebastianbarry** [comment]
### Issue 4. Cancel button uploads logs

I found that both the cancel button, and the Upload button do the same behavior, as can be seen by this code snippet:

<img width="1256" alt="image" src="https://user-images.githubusercontent.com/61334340/175618984-75bbb6f3-7b61-414a-904b-b6acfea93a71.png">

When you click either button, the logs still begin to send anyways (even if you click cancel)

**At first thought, I considered simply changing the `ng-click` attribute to somehow cancel out instead of calling `$buttonTapped`, but I looked at another button in this example, which just cancels out when you click it yet still is using `$buttonTapped`**

<img width="1241" alt="Screen Shot 2022-06-24 at 12 18 12 PM" src="https://user-images.githubusercontent.com/61334340/175628885-87a85ff8-7554-458f-8002-d30a4fe9c500.png">

I think I am confused on exactly how the `$buttonTapped` function works. Is there some sort of queue for the pages/popups, similar to how the `intro` function `next()` works?

-------

_Regarding the other issues_

**Issue 1: Change the "OK" button to be a "Cancel" button**
- I am genuinely not sure how the program is displaying this "OK", as I did a ctrl+f search for both "'OK'" and "'button-accept'" and neither show up in the uploadService.js file

<img width="738" alt="image" src="https://user-images.githubusercontent.com/61334340/175643304-a1838a7f-9596-4489-bd15-a2bfc3695e35.png">

<img width="941" alt="image" src="https://user-images.githubusercontent.com/61334340/175643597-674ef362-b828-49d9-a0ae-fbc717d25c28.png">

<img width="932" alt="image" src="https://user-images.githubusercontent.com/61334340/175643718-15fb8a92-2b15-4940-90b7-c1cd88741bbe.png">

- Because I don't know where the '$buttonTapped' funciton is sending us to when we click the "Upload" button in the Upload logs popup, I am having a difficult time debugging it, as I don't know where to put the breakpoint. 

**Issue 2: Change the color of the OK button to red (from green)**
- Same as Issue 1

**Issue 3: Add a graphic to indicate to the user that the page is loading while it is "sending..."**
- I believe we could just add a spinning circle animation to indicate that it is loading, or perhaps a progress bar which might be more technical
- I believe once we find out where the "OK" button is located, then we can also throw this image in that spot as well

**Comment by shankari** [comment]
@sebastianbarry you need to read the ionic framework documentation. Carefully. 

> Is there a list of these types? I searched for "button ng type" "ionic button positive type" "button positive type angular" but could not find anything online for a list of these button types. Are the types something we've created, located somewhere in the code?

Look at the section on buttons.

> Issue 4. Cancel button uploads logs

Are you sure this actually happens? Both of them call `buttonTapped`, but one of the parameters is the button. I assume that that ionic directive calls the appropriate function based on the tapped button. Add logs to the `onTap` function and see if they are printed when we click on "Cancel"

**Comment by sebastianbarry** [comment]
### I worked on both of these issues: Cancel button uploads logs AND Change color of button

**Issue 4. Cancel button uploads logs**

- Here is a video of the app uploading logs when I hit cancel
- I noticed this behavior also happens on the CanBikeCO phone app I have as well

https://user-images.githubusercontent.com/61334340/176226015-11235fb9-27a1-49eb-ae2c-eed0b71e678f.mov

- I stepped through the debugger and this is the spot where the popup is drawn

<img width="1558" alt="image" src="https://user-images.githubusercontent.com/61334340/176227982-78ab7765-9d5f-4878-a489-e7d57994f263.png">

_Before_

<img width="1299" alt="image" src="https://user-images.githubusercontent.com/61334340/176228138-5a079fb9-864a-4e8a-816e-b60970f14863.png">

_After_

- In the `onTap` for the Cancel button, I tried closing the popup in the code with either of these 2 lines
```
detailsPopup.close();
return;
```
If I don't execute these lines (commented out), the close button does nothing and the popup doesn't go away.
If I DO execute these lines, the popup closes and then the upload begins. I have a feeling that it has something to do with the popup closing that causes the upload to begin. (regardless of whether you click cancel or upload)

- I included a didCancel variable as you can see here, with an if statement to prevent the latter half of the function to run. It fixed the cancel button issue, but now the upload button does nothing:

```
this.uploadFile = function (database) {
          getUploadConfig().then((uploadConfig) => {
            var parentDir = "unknown";

            if (ionic.Platform.isAndroid()) {
                parentDir = cordova.file.applicationStorageDirectory+"/databases";
            }
            if (ionic.Platform.isIOS()) {
                parentDir = cordova.file.dataDirectory + "../LocalDatabase";
            }

            if (parentDir === "unknown") {
                alert("parentDir unexpectedly = " + parentDir + "!")
            }

            const newScope = $rootScope.$new();
            newScope.data = {};
            newScope.fromDirText = $translate.instant('upload-service.upload-from-dir',  {parentDir: parentDir});
            newScope.toServerText = $translate.instant('upload-service.upload-to-server',  {serverURL: uploadConfig});

            const didCancel = true;

            const detailsPopup = $ionicPopup.show({
                title: $translate.instant("upload-service.upload-database", { db: database }),
                template: newScope.toServerText
                    + '<input type="text" ng-model="data.reason"'
                    +' placeholder="{{ \'upload-service.please-fill-in-what-is-wrong \' | translate}}">',
                scope: newScope,
                buttons: [
                  { 
                    text: 'Cancel',
                    onTap: function(e) {
                        console.log("CANCEL CANCEL CANCEL")
                        detailsPopup.close();
                        didCancel = true;
                    }
                  },
                  {
                    text: '<b>Upload</b>',
                    type: 'button-positive',
                    onTap: function(e) {
                        didCancel = false;
                        console.log("UPLOADING UPLOADING UPLOADING")
                        if (!newScope.data.reason) {
                        //don't allow the user to close unless he enters wifi password
                            e.preventDefault();
                        } else {
                            return newScope.data.reason;
                        }
                    }
                  }
                ]
            });

            
            Logger.log(Logger.LEVEL_INFO, "Going to upload " + database);
            const readFileAndInfo = [readDBFile(parentDir, database), detailsPopup];
            Promise.all(readFileAndInfo).then(([binString, reason]) => {
            if(!didCancel)
            {
                console.log("Uploading file of size "+binString.byteLength);
                const progressScope = $rootScope.$new();
                const params = {
                    reason: reason,
                    tz: Intl.DateTimeFormat().resolvedOptions().timeZone
                }
                uploadConfig.forEach((url) => {
                    const progressPopup = $ionicPopup.show({
                        title: $translate.instant("upload-service.upload-database",
                            { db: database }),
                        template: $translate.instant("upload-service.upload-progress",
                            {filesizemb: binString.byteLength / (1000 * 1000),
                            serverURL: uploadConfig}) 
                            + '<center><ion-spinner></ion-spinner></center>',
                        scope: progressScope,
                        buttons: [
                        { text: '<b>Cancel</b>', type: 'button-assertive',  },
                        ]
                    });
                    sendToServer(url, binString, params).then((response) => {
                        console.log(response);
                        progressPopup.close();
                        const successPopup = $ionicPopup.alert({
                            title: $translate.instant("upload-service.upload-success"),
                            template: $translate.instant("upload-service.upload-details",
                                {filesizemb: binString.byteLength / (1000 * 1000),
                                serverURL: uploadConfig})
                        });
                    }).catch(onUploadError);
                });
            }
            }).catch(onReadError);
          }).catch(onReadError);
        };
```

----

**Issue 2: Change the color of the OK button to red (from green)**

- I read up on the Ionic framework documentation for [Buttons](https://www.tutorialspoint.com/ionic/ionic_buttons.htm) and found that the color we're looking for is labeled `button-assertive` (for red)
- I changed the `type='button-assertive'`, however it looks like the app is defaulting to drawing it as our blue-green default color of the app still
- I looked into Ionic framework documentation for [Themes](https://ionicframework.com/docs/theming/themes) and I believe the option we need to change is `--ion-item-background`, but I don't know how to include this in our portion of code for the `$ionicPopup.show(...button(....))`
```
                    const progressPopup = $ionicPopup.show({
                        title: $translate.instant("upload-service.upload-database",
                            { db: database }),
                        template: $translate.instant("upload-service.upload-progress",
                            {filesizemb: binString.byteLength / (1000 * 1000),
                            serverURL: uploadConfig}) 
                            + '<center><ion-spinner></ion-spinner></center>',
                        scope: progressScope,
                        buttons: [
                        { text: '<b>Cancel</b>', type: 'button-assertive',  },
                        ]
                    });
```

**Comment by shankari** [comment]
> I changed the type='button-assertive', however it looks like the app is defaulting to drawing it as our blue-green default color of the app still

I would expect this to work. Does using any of the other pre-defined labels work - e.g. `button-royal`?

> Issue 4. Cancel button uploads logs

I can see your breakpoints, but they are in the ionic code `tapTouchMove` etc
You need to have them in our code. I think you may need to add an `onTap` for the cancel button as well to fix this.

```
            const detailsPopup = $ionicPopup.show({
                title: $translate.instant("upload-service.upload-database", { db: database }),
                template: newScope.toServerText
                    + '<input type="text" ng-model="data.reason"'
                    +' placeholder="{{ \'upload-service.please-fill-in-what-is-wrong \' | translate}}">',
                scope: newScope,
                buttons: [
                  { text: 'Cancel' },
                  {
                    text: '<b>Upload</b>',
                    type: 'button-positive',
                    onTap: function(e) {
                      if (!newScope.data.reason) {
                        //don't allow the user to close unless he enters wifi password
                        e.preventDefault();
                      } else {
                        return newScope.data.reason;
                      }
                    }
                  }
                ]
            });
```

**Comment by sebastianbarry** [comment]
Solved these issues with Shankari in our meeting today

This issue should be good to close, code is located in https://github.com/e-mission/e-mission-phone/pull/849

**Comment by sebastianbarry** [comment]
Here are the videos of the issues outlined above, **resolved**

_Shown below:_

_Issue 4. Cancel button doesn't upload logs anymore_

https://user-images.githubusercontent.com/61334340/177395824-6b2ae120-890d-4c2b-b1f0-60c3a2108d7e.mov


_Shown below:_

_Issue 1: Change the "OK" button to be a "Cancel" button_

_Issue 2: Change the color of the OK button to red (from green)_

_Issue 3: Add a graphic to indicate to the user that the page is loading while it is "sending..."_

https://user-images.githubusercontent.com/61334340/177395829-f232e550-924a-4075-bab4-ec02bcb52434.mov

**Comment by shankari** [comment]
Another minor fix in https://github.com/e-mission/e-mission-phone/pull/851
