### ISSUE TITLE
Broken UI in the diary tab

### ISSUE THREAD

**Issue by asiripanich** [e-mission/e-mission-docs#748]
Hi @shankari, I tried to run the master branch of e-mission-phone using my own staging database and found that the diary UI is broken. The bottom part of each of the trip cards in the attached screenshot, where there should be a "add trip details" button and the addresses of the trip, is missing, leaving a large blank space. 

PS: in the screenshot, the maps are intentionally blurred out.

<img src="https://user-images.githubusercontent.com/17020181/177182288-66e48ecb-23d6-4b56-b602-24f13632b454.jpeg" 
     width="250" 
     height="500" />

**Comment by shankari** [comment]
@asiripanich which simulator are you testing this on? I just tested with the devapp on an iPhone 12 simulator running iOS 15.2 and it works fine.

<img src="https://user-images.githubusercontent.com/2423263/177239241-14d535f7-080e-48c3-b0ed-6c8abfb47287.png" width="330px"/>
 
@sebastianbarry @tyleryandt18 can you confirm that the diary screen looks correct for you?

**Comment by asiripanich** [comment]
I tested this on my iPhone 13 Pro using Test flight. I had the same issue on the CanBikeCO app as well.

**Comment by shankari** [comment]
For the record, the height of the diary card is set to 

```
const DEFAULT_ITEM_HT = 335;
```

which is what the computed value is as well

<img width="1629" alt="Screen Shot 2022-07-04 at 7 51 21 PM" src="https://user-images.githubusercontent.com/2423263/177240008-7b3857cb-603f-4c14-86ea-f8f13b37c2d0.png">

**Comment by asiripanich** [comment]
Also, it can be fixed by tapping on the button next to the refresh button on the top right.

**Comment by shankari** [comment]
>  I had the same issue on the CanBikeCO app as well.

That is interesting. Yes, the button next to the refresh button resizes the item.
Which version of iOS do you have?

@sebastianbarry you have an iPhone as well, right? Do you see this issue too?

**Comment by asiripanich** [comment]
> That is interesting. Yes, the button next to the refresh button resizes the item.

I take that back. Maybe it was in my Android emulator. I was testing this very late last night so my memory is a little blurry right now.

**Comment by asiripanich** [comment]
> @asiripanich which simulator are you testing this on? I just tested with the devapp on an iPhone 12 simulator running iOS 15.2 and it works fine.
> 
> <img alt="" width="330px" src="https://user-images.githubusercontent.com/2423263/177239241-14d535f7-080e-48c3-b0ed-6c8abfb47287.png">
> 

Didn't you already fix the map tile issue?

**Comment by asiripanich** [comment]
Also, I was using `SurveyOptions.ENKETO`.

**Comment by shankari** [comment]
I did fix the map tile issue. Sometimes they are still a bit slow to load but they do load eventually.

> Also, I was using SurveyOptions.ENKETO.

Can you first check if it works with `SurveyOptions.MULTILABEL`?
Then, when using `SurveyOptions.ENKETO`, see if there are any errors in the logs?
You may not have any trip-level survey configured....

**Comment by asiripanich** [comment]
Sure, I will check.
>  You may not have any trip-level survey configured....

How can I do that?

**Comment by shankari** [comment]
@atton16 set that up - you need to edit `www/json/enketoSurveyConfig.json.sample` and ensure that there is a `TripConfirmSurvey` configured and the JSON file for it exists.

**Comment by shankari** [comment]
I don't have an ios 15.5 simulator in my xcode; the max is 15.2. I think I have to upgrade xcode, for which I need to upgrade my OSX for which I need to get IT involved. Will see if @Sebastianbarry or I can try this out on a 15.5 emulator later this week.

**Comment by asiripanich** [comment]
> il

I had already changed that. :) 
I reinstalled the app this morning and haven't seen the UI issue since.

**Comment by shankari** [comment]
which app did you reinstall? Is this still an issue or can it be closed?

**Comment by asiripanich** [comment]
> 

Let's close it first as it might be related to my fork. Sorry for the trouble.
