### ISSUE TITLE
Demographics Survey Changes

### ISSUE THREAD

**Issue by sebastianbarry** [e-mission/e-mission-docs#754]
As demographics survey changes are requested by users, I will put the updates here:

**Comment by sebastianbarry** [comment]
First changes: https://github.com/e-mission/e-mission-phone/pull/857

**Comment by shankari** [comment]
For the record, I have edited the XML manually many times and I think you are close (at least for this set of changes).
Please see my reviews.
I won't wait for the change, but will incorporate it if it gets to me before I finish committing my changes.

**Comment by sebastianbarry** [comment]
Added fixes to the changes I made in https://github.com/e-mission/e-mission-phone/pull/857

<img width="395" alt="Screen Shot 2022-07-11 at 3 06 21 PM" src="https://user-images.githubusercontent.com/61334340/178358947-eabcaf40-d362-426e-bad5-ed4fea845172.png">

<img width="364" alt="Screen Shot 2022-07-11 at 3 06 31 PM" src="https://user-images.githubusercontent.com/61334340/178358950-2ae00674-3388-4880-a021-0fb226aa8e3b.png">

<img width="408" alt="Screen Shot 2022-07-11 at 3 06 42 PM" src="https://user-images.githubusercontent.com/61334340/178358953-3010beba-5a02-4c03-ad6a-c90a7d5bf17b.png">

It is working now

**Comment by shankari** [comment]
@sebastianbarry were these all the changes requested by the testers so far, or are there still some more complex pending changes?

**Comment by shankari** [comment]
From Durham:

> Regarding the survey, here are the demographic questions we have included in our user registration. Would it be possible to update the in-app questions to match to some extent?:

Gender Identity (select one)
- Woman
- Man
- Non-binary/genderqueer/gender non-conforming 
- Prefer not to answer

Do you consider yourself to be transgender? (select one)
- Yes
- No
- Prefer not to say

Race/Ethnicity (check all that apply)
- Black or African American
- White or Caucasian
- Hispanic, Latino/a/x, or Spanish
- East Asian
- South Asian
- American Indian or Alaska Native
- Native Hawaiian or Other Pacific Islander
- Multiracial/Multiethnic
- Other

**Comment by sebastianbarry** [comment]
These changes above have been reflected in the https://github.com/e-mission/e-mission-phone/pull/868 PR:

> Demo-survey-v1.xlsx
> 
>     Added this file so that it lives in the repository, and can be imported to KoBotoolbox by other devs (right now, KoBotoolbox can't import XML, only XLS files, despite having an export to both option)
>     Added spanish translations to the KoBotoolbox XLS version
> 
> Demo-survey-v1.xml
> 
>     Added "What is your race/ethnicity?" question
>     Added "Do you consider yourself transgender?" question
>     Added answer to "What is your gender?" -> "Non-binary/genderqueer/gender non-conforming"
>     Added answer to "Which one below describes you best?" -> "None of the above"
>     Added answer to "Which best describes your current job?" -> "Other"
>     Added skip rules to "Job related questions" if user indicates they don't work
> 
> Demo-survey-v1.json
> 
>     Export of Demo-survey-v1.xml
>

**Comment by shankari** [comment]
@sebastianbarry did you also remove the primary mode question? I don't recall interest in keeping it, but I also think we didn't hear from some of them....

**Comment by sebastianbarry** [comment]
As of right now, the only questions relating to mode of transportation are:

"How did you usually get to your primary job last week? If you used more than one mode of transportation, please select the one used for most of the distance"

And if they selected _Public Transport_:
"What is your typical access/egress mode to/from the transit stop?"

Should we remove this question? I did not see any feedback in my notes regarding removing this question (however I do vaguely remember us talking to Jeanne(i think?) about not needing this question), but I can make the change if we feel that this question is unneeded

**Comment by shankari** [comment]
As you can see from my email titled "Request feedback around demographic survey update"

> Should we remove this question?

That was my proposal in the email. can you ping Bingrong and Andy again on this? I will merge these changes for now.

**Comment by shankari** [comment]
@sebastianbarry We can either keep this issue open, or if we want to have the satisfaction of closing it, create a follow-on issue for the next round of changes.

**Comment by sebastianbarry** [comment]
I created a new issue to tackle this question, this issue should be good to close now

 Demographics Survey Changes 2 #771
