### ISSUE TITLE
Using iframe in the intro screen

### ISSUE THREAD

**Issue by asiripanich** [e-mission/e-mission-docs#756]
@shankari, would you know why iframe doesn't work in the intro screen? I was only able to use iframe to display a youtube player on an Android emulator but it did not show up on the other screens shown below.

| iOS emulator | Android emulator | iOS phone | Android phone |
|---|---|---|---|
|![image](https://user-images.githubusercontent.com/17020181/179149621-a6955489-7a01-42af-8ff4-aa6857569496.png) | ![image](https://user-images.githubusercontent.com/17020181/179149500-69daad80-96ea-459f-bf62-8378fb628ee1.png) | ![image](https://user-images.githubusercontent.com/17020181/179150069-d7c906f9-115c-4e6c-8694-bd43f476e5b1.png) | ![image](https://user-images.githubusercontent.com/17020181/179149571-bdd724a3-bb9c-4108-bec3-7968a846b781.png)|

**Comment by shankari** [comment]
at least for android, the error is right there "ERR_BLOCKED_BY_CSP".
https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP
You need to add youtube to the list of allowed URLs in index.html

I only use youtube for videos that deployers request me to push to participants, such as https://www.youtube.com/watch?v=va7msqgFgmk and then I open it in an in-app-browser.
https://github.com/e-mission/e-mission-phone/blob/c0395cf3bf981e45257debad82c9c56e87dc4361/www/js/splash/remotenotify.js#L28

**Comment by asiripanich** [comment]
>  You need to add youtube to the list of allowed URLs in index.html

So I changed line 6 in `index.html` to:

```
<meta http-equiv="Content-Security-Policy" content="default-src 'self' data: gap: https://ssl.gstatic.com https://api.ionicjs.com https://pro-deploy.ionicjs.com https://nominatim.openstreetmap.org https://youtube.com emission: 'unsafe-eval'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; img-src 'self' ionic: data: https://*.tile.openstreetmap.org 'unsafe-inline'">
```

But it is still not enough to make the youtube iframe work! :(

**Comment by asiripanich** [comment]
Wait I don't think I added the youtube url in the right place..

**Comment by asiripanich** [comment]
Appending `frame-src 'self' https://www.youtube.com/`.

```
<meta http-equiv="Content-Security-Policy" content="default-src 'self' data: gap: https://ssl.gstatic.com https://api.ionicjs.com https://pro-deploy.ionicjs.com https://nominatim.openstreetmap.org emission: 'unsafe-eval'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; img-src 'self' ionic: data: https://*.tile.openstreetmap.org 'unsafe-inline'; frame-src 'self' https://www.youtube.com/">
```

**Comment by asiripanich** [comment]
> Appending `frame-src 'self' https://www.youtube.com/`.
> 
> ```
> <meta http-equiv="Content-Security-Policy" content="default-src 'self' data: gap: https://ssl.gstatic.com https://api.ionicjs.com https://pro-deploy.ionicjs.com https://nominatim.openstreetmap.org emission: 'unsafe-eval'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; img-src 'self' ionic: data: https://*.tile.openstreetmap.org 'unsafe-inline'; frame-src 'self' https://www.youtube.com/">
> ```

Ok, so this fix allows the iframe to work on my test Android phone and emulator. However, it doesn't fix the issue for iPhone.

**Comment by asiripanich** [comment]
@shankari would you know why iframe doesn't work on iPhone? Thanks

**Comment by shankari** [comment]
no, I have not tried using an iframe in OpenPATH.
You have to connect the safari debugger to see the error

**Comment by shankari** [comment]
But a simple search finds this:
https://stackoverflow.com/questions/54469341/can-iframes-work-in-wkwebview-with-cordova

You may want to try similar searches and see if any of the solutions work.
Or switch to the in-app-browser which I have used to load youtube URLs and I know works

**Comment by shankari** [comment]
Closing this since it is not related to OpenPATH and there is a workaround
