### ISSUE TITLE
Predict only walk and non-walk modes using the model inference model

### ISSUE THREAD

**Issue by asiripanich** [e-mission/e-mission-docs#760]
@shankari How can I make the mode inference model to predict only walk and non-walk modes like in this screenshot below? 

> <img alt="Screen Shot 2022-07-14 at 4 16 47 PM" width="322" src="https://user-images.githubusercontent.com/89606659/179099165-06a4b1a0-5aaa-420d-8e43-4d26ff1d2d47.png">

**Comment by shankari** [comment]
@asiripanich there is no prediction for only walk vs. non-walk. There is a prediction for walk/bike/motorized, which is pretty close. If you read the pipeline documentation from chapter 4 of my thesis, you will see that we initially split into those three categories based on the phone APIs and store the results in `analysis/cleaned_section`. We then infer the mode and store the results in `analysis/inferred_section`.

Changing the `analysis.result.section.key` in `conf/analysis/debug.conf.json` will return one or the other.
