### ISSUE TITLE
Add a dynamic config for Denver CASR

### ISSUE THREAD

**Issue by sebastianbarry** [e-mission/e-mission-docs#776]
Since we are taking on the study for Denver CASR, we want to set them up with their own dynamic config like we have for the other studies. The MOU has been filled out and can be used to create the json file, similar to the other configs found here:

[https://github.com/e-mission/nrel-openpath-deploy-configs/tree/main/configs](https://github.com/e-mission/nrel-openpath-deploy-configs/tree/main/configs)

**Comment by sebastianbarry** [comment]
Created a rough draft for the first dynamic config json file for Denver CASR:
https://github.com/e-mission/nrel-openpath-deploy-configs/pull/1

I just based what I wrote for the text, off of the Durham program dynamic config file, and then I took from the MOU what sounded good. I don't know if it follows the exact scheme or highlights all the points Denver wants us to. Question for @shankari : **Do you think we should send this to them for them to confirm it's what they want?**

**Comment by shankari** [comment]
> I just based what I wrote for the text, off of the Durham program dynamic config file, and then I took from the MOU what sounded good. 

The MOU has an appendix where CASR has specified the text they want to use. Please use this instead of pulling from the MOU. Program admins care a lot about text.

> Do you think we should send this to them for them to confirm it's what they want?

No, that is what the appendix is for.

**Comment by sebastianbarry** [comment]
I created a new PR to reflect the MOU's appendix exactly in https://github.com/e-mission/nrel-openpath-deploy-configs/pull/2

Since that old PR https://github.com/e-mission/nrel-openpath-deploy-configs/pull/1 is outdated, I closed it
