### ISSUE TITLE
Display the Version Number of the App in the app

### ISSUE THREAD

**Issue by sebastianbarry** [e-mission/e-mission-docs#777]
Right now, to see the current version of the app you need to go to the App Store/Google Play Store. We want to be able to see the app version from within the app, and the Developer Zone would be a good place to put it.

**Comment by sebastianbarry** [comment]
I found a way to get the version number displayed in the [www/js/control/general-settings.js](https://github.com/e-mission/e-mission-phone/blob/master/www/js/control/general-settings.js) file, by using the function from [www/js/stats/clientstats.js](https://github.com/e-mission/e-mission-phone/blob/master/www/js/stats/clientstats.js)

```javascript
  clientStat.getAppVersion = function() {
    if (angular.isDefined(clientStat.appVersion)) {
        return clientStat.appVersion;
    } else {
        if (angular.isDefined($window) && angular.isDefined($window.cordova) &&
            angular.isDefined($window.cordova.getAppVersion)) {
            $window.cordova.getAppVersion.getVersionNumber().then(function(version) {
                clientStat.appVersion = version;
            });
        }
        return;
    }
  }
```

However, when I implemented the function like this (using the already created `ClientStats` controller:

```javascript
    $scope.settings.clientAppVer = ClientStats.getAppVersion();
```

The app crashes when it feeds the app version in:
<img width="1588" alt="Screen Shot 2022-08-22 at 9 33 16 AM" src="https://user-images.githubusercontent.com/61334340/185961788-826074fe-880c-4d79-b1e5-ade87c999d78.png">
<img width="1584" alt="Screen Shot 2022-08-22 at 9 33 38 AM" src="https://user-images.githubusercontent.com/61334340/185961807-fc8a83c6-3c91-4821-8575-94a724562fd2.png">
<img width="1591" alt="Screen Shot 2022-08-22 at 9 34 39 AM" src="https://user-images.githubusercontent.com/61334340/185961824-f11584e3-0458-4b53-a787-23c3d27770f1.png">
<img width="1592" alt="Screen Shot 2022-08-22 at 9 34 49 AM" src="https://user-images.githubusercontent.com/61334340/185961838-d0819ee9-b947-4639-9439-624d750d11dd.png">

**Comment by sebastianbarry** [comment]
This has been completed in PR https://github.com/e-mission/e-mission-phone/pull/879
<img width="405" alt="Screen Shot 2022-08-23 at 10 16 51 AM" src="https://user-images.githubusercontent.com/61334340/186210554-0b2f3ed5-832f-45e6-b01e-e5d44d773bd3.png">

**Comment by sebastianbarry** [comment]
I didn't like the black text for the version number so I changed it to gray:

<img width="407" alt="Screen Shot 2022-08-23 at 10 23 26 AM" src="https://user-images.githubusercontent.com/61334340/186211135-b6c01e7d-c429-48e9-b636-431dfe9c1206.png">

**Comment by sebastianbarry** [comment]
Added Spanish, French, Italian translations: https://github.com/e-mission/e-mission-translate/pull/17

**Comment by shankari** [comment]
Also pulled translation changes into `master_for_platform` in https://github.com/e-mission/e-mission-translate/pull/18 before I forget.

This is now done.
