### ISSUE TITLE
Move the frontend dashboard over to NREL's default template

### ISSUE THREAD

**Issue by zackAemmer** [e-mission/e-mission-docs#780]
https://github.com/e-mission/em-public-dashboard/pull/50

**Comment by shankari** [comment]
@zackAemmer please file a separate issue for the notebook changes.

**Comment by zackAemmer** [comment]
I filed this:
https://github.com/e-mission/e-mission-docs/issues/781

Let me know if those are not the notebook changes you're thinking of.

**Comment by shankari** [comment]
Waiting to hear from NREL comms on whether we can merge this publicly or need to keep it on a private repo given the NREL branding

**Comment by shankari** [comment]
Can merge publicly. Merged.
Deployed.
