### ISSUE TITLE
Make the public dashboard be configurable

### ISSUE THREAD

**Issue by zackAemmer** [e-mission/e-mission-docs#781]
Only generate plots that make sense for a certain configuration. Begin by separating plots by "study" or "program", but leave code open to adding more parameters in the future.

To-Do
- Implement Github requests so that a single configuration file is specified here: https://github.com/e-mission/nrel-openpath-deploy-configs/blob/main/configs/dev-emulator-program.nrel-op.json
- Set up the public dashboard and/or so that a configuration file is specified which only generates plots relevant to the program or study. The primary example of this would be that a "study" should not show replacement metrics, but a "program" would show replacement metrics for a specific mode of interest.

**Comment by zackAemmer** [comment]
https://github.com/e-mission/em-public-dashboard/pull/51

Thoughts on process/implementation:

- Some notebooks have a mix of plots that rely on being a "program" while others are either all-program or all-study plots.
- Want to find the best way to accommodate all of these notebooks with minimal repeated code.
- Assuming that whatever instance calling each notebook corresponds to a given study, we can read the config from Github just once in generate_plots.py and pass the information of the study into each notebook run, using the same parameter approach that exists for the "month/year/program" variables in the first cell.
- The main difference between program/study is whether to generate plots based on the "Replaced_mode". For now, this only really applies to ebikes, but in the future there may be other programs where we might have a different mode of interest.
- For this reason, another parameter is added ("mode_of_interest"), which can be specified in the config files for programs. Generate_plots.py first checks if the config is a program, if so, it reads the mode of interest in as another notebook parameter.
- I also tried to clean up the annotations, and the data ingestion process so that they are uniform across notebooks. This is not strictly necessary since they don't all use the same variables (e.g., energy impact factors) so each could be trimmed, but it seemed nice to have them all the same for clarity in future notebooks. This could even be a function in scaffolding like "load_notebook_viz_data".

* One thing to still do is work out the plot titles/axes/labels for a generic mode of interest. This may require a map of in-data mode names to labels, or an additional argument, or just put "Pilot ebike" as it stands into the labels.
* I have not made any changes to the config files, but we would need to make sure each has a program or study, and a mode of interest if it is a program.
* Need to add alt-text to each image saved as a separate set of files.

**Comment by zackAemmer** [comment]
Added initial implementation of alt text for all plots in the viz notebooks. The text is saved in a single json file, where the plot filename identifies a specific plot's alt text. The frontend needs to be adjusted to read from this file when rendering plots on the web page.

**Comment by shankari** [comment]
Changes I need to commit:
- [ ] change scaffolding to remove `_test_` users
- [ ] need to handle the new modes `e-car_drove_alone` and `e-car_with_others`
   - [ ] add them to the energy intensity table
   - [ ] add them to the list of modes so they show up as non-other
- [ ] mapping from e-bike to pilot e-bike
   - [ ] e-bike is the standard and pilot e-bike maps to it

After all these changes, somebody needs to create a non-dev docker-compose that copies the notebooks into the container instead of mounting them for both the frontend and the containers.

**Comment by zackAemmer** [comment]
Addressed comments from first pass review of the code; now moving back to the TODO list.

**Comment by zackAemmer** [comment]
This and the nrel-frontend PR should work nicely together whenever that one is ready to be incorporated. https://github.com/e-mission/em-public-dashboard/pull/50

**Comment by shankari** [comment]
Reviewed both the viz scripts and the dashboard

**Comment by shankari** [comment]
This required a pretty significant change to deal with cold start issues as well. But I resolved them in 
https://github.com/e-mission/em-public-dashboard/issues/69

The site has been deployed on staging and reviewed by NREL Comms.
Finally closing this.
