### ISSUE TITLE
Diary Trip Confirm Not Reflecting on UI for Confirmed Trips on Previous Days

### ISSUE THREAD

**Issue by promie** [e-mission/e-mission-docs#793]
Good morning, my name is Promie and I am one of the developers for the FourStep project under the guidance of @asiripanich. We have forked and pulled the latest commit from the `e-mission-phone` repository (dated 29th August 2022) and have applied our own server configuration to it.

Upong testing the app, we've noticed a strange behaviour when confirming the trips on the previous days. For example, today is the 19th of September and if you navigate to say the 1st of September (or any dates before the 19th where you have unconfirmed trips) via the calendar picker on the **Diary** tab, confirm the trip, and press the refresh icon on the top right hand side.

Expected: Confirmed trip to be persisted and the button stays green
Actual: Trip not confirmed as button goes back to red prompting the user to confirm the trip (again)

We've added the screenshot for this behaviour for an easier illustration.

![issue-saving](https://user-images.githubusercontent.com/92339996/190924872-7392fa44-4ae8-4146-9dc7-c932b359a97e.gif)

It appears that this is the UI-related issue as per the below screenshot, you can see the entry for the 1st of September is persisted in the database.

![image](https://user-images.githubusercontent.com/92339996/190925041-b241b62b-e5a9-4e60-8653-1b45b4e7a1bb.png)

Our team has done an investigation on this issue and we have identified the cause of the issue. The approach we took in diagnosing this is to place console.logs to checkpoints to effectively trace the code from the diary `service.js` layer on how the `timeline.data.unifiedConfirmsResults` object is firstly constructed and how the data gets passed to the UI to render whether the trip has been confirmed. The outcome of this investigation as we suspect that the issue is caused by the race condition of the `Promise` where some of the checkpoints is resolved first before the previous checkpoint.

Before we deep dive into the technical discussion, we've also included the illustration of different checkpoints in the comment below so its easier to follow.

This is our understanding of different checkpoints:

```
Checkpoint A: On the `readTripsandUnprocessedInputs()` function is where the `timeline.data.unifiedConfirmsResults` object is initiated alongside the `manualPromises` which is an array of the confirmed trips. Both of these variables are passed through a function called `processManualInputs()`, which leads to

Checkpoint B: The `processManualInputs()` function main job is to append the confirmed trips to the `unifiedConfirmsResults` object with the key called SURVEY

{
 SURVEY: [ARRAY OF CONFIRMED TRIPS]
}

Once this step is completed, it emits an event called `UPDATE_DONE` to Checkpoint C

Checkpoint C: Utilise the `TImeline` service and inherits the `data.unifiedConfirmedResults` object

Checkpoint D: Calls the function called `populateInputsAndInferences()` which firstly constructs the `trip.userInput = {}` with the information from the `data.unifiedConfirmedResults` to ultimately pass this information the UI to render.

Checkpoint E: Calls the `input-matcher.js` to pretty logs the trips in a much more readable format.
```

We've tested two scenarios: 1. The scenario that works and 2. The scenario that doesn't (as per the screenshot)

1. Scenario that works.
As we've traced through the logs, the checkpoints is printed in the correct order as per our expectation.

```
Checkpoint A
Checkpoint B
Checkpoint C
Checkpoint D
Checkpoint E

=> UI Renders correctly
```

However, on the second scenario, it prints.

```
Checkpoint A
Checkpoint C
Checkpoint D
Checkpoint E
Checkpoint B

=> UI Renders incorrectly
```

Notice that checkpoint B this comes last. We learn that checkpoint B is the vital step that creates the confirmed trips. This results in checkpoint C, D and E with an empty object for `data.unifiedConfirmsResults` as checkpoint B is resolved late so it has no confirmed trips to inherit to hence the UI recognised that there aren't any confirmed trips.

From this exercise, as mentioned above, we suspect that this is due to the order of the `Promise` being resolved. Checkpoint C, D, and E should wait for Checkpoint B to resolve first before running it.

We've created a new branch on top of master for `emission-phone` to resolve this issue hoping to create a PR. However, upon pushing it to the branch, we are greeted with a `FORBIDDEN 403 error`. Do we(I) need to be added to the list of contributes in order to contribute to this project?

![image](https://user-images.githubusercontent.com/92339996/190925635-4f5d8382-17a1-4193-97dc-bb081b1d7ebb.png)

Let me know if this doesn't make sense.

**Comment by promie** [comment]
illustration of different checkpoints and our approach to diagnosing this issue

![ConfrimTripIssue drawio](https://user-images.githubusercontent.com/92339996/190926784-cf3b8249-6bad-4ea8-94d1-583b287a287b.png)

**Comment by shankari** [comment]
@promie 

1. Since this is an open source project, all commits have to be reviewed by the maintainer before merging into the main repo. Please create a fork, make the changes, test them and submit a pull request of your change. **Please do not forget to indicate the testing done in the PR.**

2. I am not sure that your debugging is correct. For newer trips, the "The `processManualInputs()` function main job is to append the ~confirmed trips~ survey inputs to the `unifiedConfirmsResults` object with the key called SURVEY". However, for older trips, the expectation is that the confirmed trip will already include the user input. This ensures that we only have to read a bounded set of entries (from the last pipeline run to now) and match them to the trips, which improves performance.

Please see https://github.com/e-mission/e-mission-server/commit/78a3ebb612077bea923d922e6cdfbca4ccfa1921
and https://github.com/e-mission/e-mission-docs/issues/674, notably after
https://github.com/e-mission/e-mission-docs/issues/674#issuecomment-936653240
https://github.com/e-mission/e-mission-docs/issues/674#issuecomment-938269497

Not sure when you have last updated the server, and whether you have configured it correctly for the confirmed trips to match inputs and fill them in.

**Comment by promie** [comment]
@shankari 

Thank you so much for the response and taking the time to dig up the previous issues regarding this. We very much appreciate it.  We have updated the server to the latest version as per your suggestion and that fixed the issue. Regarding to point number 1, we will make a note of this and will follow the the protocol next time when we create the PR.

We will close off this issue. Thanks again.

Cc: @asiripanich

**Comment by asiripanich** [comment]
> you have configured it correctly for the confirmed trips to match inputs and fill them in.

Might be related to the issue I reported in #810, could you explain more in details how I should "configure" my server to work with the Enketo survey option? or did you mean my e-mission-phone code?

**Comment by asiripanich** [comment]
So I changed the line below in https://github.com/e-mission/e-mission-server/blob/64cb837ee7284619207a13037ef7e95d12c13bbb/conf/analysis/debug.conf.json.sample#L11

from 

```
    "userinput.keylist": ["manual/mode_confirm", "manual/purpose_confirm"]
```

to

```
    "userinput.keylist": ["manual/trip_user_input"]
```

but i'm getting this message error message

```
2022-10-11T12:29:36.068483+11:00**********UUID xxxxx-xxxxx-xxxx-xxxx: updating incoming user inputs**********
Error while matching incoming user inputs, timestamp is unchanged
Traceback (most recent call last):
  File "/Users/amarin/GitHub/e-mission/e-mission-server/emission/analysis/userinput/matcher.py", line 18, in match_incoming_user_inputs
    last_user_input_done = match_incoming_inputs(user_id, time_query)
  File "/Users/amarin/GitHub/e-mission/e-mission-server/emission/analysis/userinput/matcher.py", line 38, in match_incoming_inputs
    confirmed_trip = esdt.get_trip_for_user_input_obj(ts, ui)
  File "/Users/amarin/GitHub/e-mission/e-mission-server/emission/storage/decorations/trip_queries.py", line 191, in get_trip_for_user_input_obj
    tq = estt.TimeQuery("data.start_ts", ui_obj.data.start_ts - ONE_DAY,
  File "/Users/amarin/GitHub/e-mission/e-mission-server/emission/core/wrapper/wrapperbase.py", line 73, in __getattr__
    return self._build(key, self[key])
  File "/Users/amarin/GitHub/e-mission/e-mission-server/emission/core/wrapper/entry.py", line 187, in _build
    key_class = self._get_class(self._wrapper_type)
  File "/Users/amarin/GitHub/e-mission/e-mission-server/emission/core/wrapper/wrapperbase.py", line 129, in _get_class
    return getattr(wrapperModule, wrapperClassName)
AttributeError: module 'emission.core.wrapper.tripuserinput' has no attribute 'Tripuserinput'

```

**Comment by shankari** [comment]
@asiripanich woops, I think you need to change 
https://github.com/e-mission/e-mission-server/blob/master/emission/core/wrapper/tripuserinput.py#L11
from `TripUserInput` to `Tripuserinput`

Sorry, nobody else is using the surveys, so that branch is not as well tested as the other label branches.
