### ISSUE TITLE
App crash when deployed to Google Play Console Internal Testing

### ISSUE THREAD

**Issue by promie** [e-mission/e-mission-docs#796]
Good morning,

We have attempted to deploy our app to Google Play Internal Testing. The branch that we are trying to deploy is not the latest with the master branch. 

The code on this branch still generates the `.apk` extension in the `sign_and_align_keys.sh` script, whereas the new Google standard now only accepts the `.aab` extension to upload to the Play Console. Understandably there has been an update to this script file to accomodate that change.

- https://github.com/e-mission/e-mission-phone/commit/7eca45767c0f5c2baaad96f44c3682be2bfa55f7

The workaround approach we took to tackle this was to borrow the above script when running the Android build hoping that the `.aab` extension will be generated instead of the `.apk`. 

However, the change in that script alone still does not generate the `.aab` extension. The next step we tried was to "borrow" the `setup` and `bin` folders from the latest code as well as `package.cordovabuild.json` to get the latest version of cordova and then ran the build script. The `.aab` extension was successfully generated as per our expectation in which we were able to upload to Google Play Console for Internal Testing.

We also did refer to this issue: https://github.com/e-mission/e-mission-docs/issues/680

Once deployed, we tested the app on a physical Android device but it kept crashing. When checking the logs on the Crashes and ANRs report, below screenshot of the stack trace.

![image](https://user-images.githubusercontent.com/92339996/192163681-cd8f265b-1b4b-43f2-be64-ea5c09d96ee0.png)

Please advise if there is any step configuration step that was missed that is causing the app to crash.

**Comment by promie** [comment]
One thing to also note is that on our `main` branch (which is up-to-date) with the master branch has no issue with the app crashing and we can deploy successfully. It is just this particular branch we want to release on the app store as it includes our own custom TimeUse functionality. 

We are also in the process of applying the TImeUse functionality to the main branch but encountered a separate issue we are vigorously looking into. So we figured we want to (re)deploy the working app (which is out of date) for the users to use.

Any assistance and guidance is appreciated. Thank you so much in advance.

**Comment by shankari** [comment]
The error is right there - it is missing the `ACTIVITY_RECOGNITION` permission.
Make sure you have the version of the e-mission-data-collection plugin that has that permission.
And that the permission is reflected in the `AndroidManifest.xml` in the `platforms/android` directory.

Note that only changing the package.json is not enough to get the new version of cordova plugins
You need to remove and re-add, or delete all plugins and reinstall
Please see previous issues or search for "cordova plugin not updated"
