### ISSUE TITLE
SurveyOptions.ENKETO responses disappeared from previously labelled trips

### ISSUE THREAD

**Issue by asiripanich** [e-mission/e-mission-docs#810]
## Problem

I cannot reproduce the exact steps yet but here is a screen recording of the time a trip label disappeared (at 0:14) and reappeared (0:29) after switching between dates a few times. This may be related to https://github.com/e-mission/e-mission-docs/issues/793. I will report more info later today or tomorrow.

https://user-images.githubusercontent.com/17020181/194453386-71f27113-1baa-411c-a102-a86d79fe03de.mp4

## Setup

My custom client of e-mission-phone is a fork from this commit [fbc63adfbebab887b3ef74d0eaa6b2aab40030b8](https://github.com/e-mission/e-mission-phone/commit/fbc63adfbebab887b3ef74d0eaa6b2aab40030b8). Testing on TestFlight running on iPhone 13 Pro iOS 16.0.

## Note
@shankari at first I thought this problem happened to our fork after introducing new commits from the upstream e-mission-phone's master branch. So I deployed your master branch on TestFlight and I can now confirm that the same issue can be found on the master branch as well. Do you have know if any active studies that are using SurveyOption.ENKETO? Do they have the same problem?

Please let me know what info I should provide for you to identify the root cause of the problem.

**Comment by shankari** [comment]
@asiripanich 

> Please let me know what info I should provide for you to identify the root cause of the problem.

Logs would be helpful.

> Do you have know if any active studies that are using SurveyOption.ENKETO? 

To my knowledge, no other studies are using `SurveyOption.ENKETO`. The push from our partners is to go towards more passive data collection.

**Comment by shankari** [comment]
@asiripanich since this is working now, can you please close this issue?
