### ISSUE TITLE
Separator dates don't work properly if the trips for a particular date are labeled fully

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-docs#817]
It looks like the separator is based on the ending date of the previous trip and not the start time of the next trip.

So when I first launch "To Label", I see that the date is yesterday. But when I pull more trips from the server, the date changes to Sept

| Initial launch | after loading more data |
|-------------|-------------|
| ![Screenshot_20221013-095643](https://user-images.githubusercontent.com/2423263/195674857-7900ecba-c15c-491c-b186-f172f9bb7d77.png) | ![Screenshot_20221013-111023](https://user-images.githubusercontent.com/2423263/195674866-e22532a9-81f6-4581-b046-ce243e7bad3e.png) |

**Comment by shankari** [comment]
Also reported by another user as a difference between "To Label" and "All Trips".

Note that the user had labeled all trips on Tuesday, so they should have only seen Monday and then Wednesday

| All Trips |  To Label   |
|------|-------|
| ![Screenshot_20221013-091810](https://user-images.githubusercontent.com/2423263/195675521-0a26c193-453a-413d-b387-4165c026eb75.png) | ![Screenshot_20221013-091030](https://user-images.githubusercontent.com/2423263/195675525-24c871dd-8d41-4651-b08f-8a7df08e8321.png) |

**Comment by sebastianbarry** [comment]
I have corrected this in my PR:

https://github.com/e-mission/e-mission-phone/pull/895

@shankari could you do a quick code review of this?
