### ISSUE TITLE
Why do we need to query the location addresses of the trips every time we load a screen?

### ISSUE THREAD

**Issue by asiripanich** [e-mission/e-mission-docs#821]
I just find it too slow and worsen the UX to wait for the addresses from OSM every time I load the trip diary screen. Can't we just store it as part of the trip object?

**Comment by shankari** [comment]
If you configure the server with a link to a nominatim server, 
https://github.com/e-mission/e-mission-server/blob/master/conf/net/ext_service/nominatim.json.sample

it should fill in the addresses while creating the places on the server.
https://github.com/e-mission/e-mission-server/blob/master/emission/analysis/intake/cleaning/clean_and_resample.py#L246

Note, however, that the free nominatim service has a limit of a certain number of queries per IP address.
If the queries happen from the individual phones, we don't run into the limit.
If they happen from the server, we almost certainly do.

As indicated in the config file, you are welcome to host your own nominatim service or pick a paid provider to overcome the limits on server matching
