### ISSUE TITLE
Apple discovered a bug on the Permissions page

### ISSUE THREAD

**Issue by asiripanich** [e-mission/e-mission-docs#828]
@shankari this is the same submission as #827. Not sure why we added ipad support in the first place. I'm going to reproduce this issue in an hour and report it here.

---
## Guideline 2.1 - Performance - App Completeness
We discovered one or more bugs in your app.

Specifically, on the Permissions page your app did not prompt a permission request alert for Location access when we tapped the Fix or Refresh buttons.

Please review the details below and complete the next steps.

Review device details:

- Device type: iPad

- OS version: iOS 16.1

Next Steps

Please run your app on a device to reproduce the issues, then revise and submit your app for review. If at first you're unable to reproduce the issue, try the following:

- For new apps, uninstall all previous versions of your app from a device, then install and follow the steps to reproduce.

- For app updates, install the new version as an update to the previous version, then follow the steps to reproduce.

If we misunderstood the intended behavior of your app, please reply to this message in App Store Connect to provide information on how these features were intended to work.

**Comment by shankari** [comment]
I made sure that NREL OpenPATH does not support iPad 😄 
In addition to everything else, it was annoying to have to generate screenshots every time.

**Comment by asiripanich** [comment]
Strange. I tested the same thing on an iPad pro and the same iOS version they tested on and did not see the bug they described. I attached a screen recording of my testing and they are not pressing us about this anymore.
