### ISSUE TITLE
How to add `NSCameraUsageDescription` to config so that it will appear in the Xcode project

### ISSUE THREAD

**Issue by asiripanich** [e-mission/e-mission-docs#830]
I tried setting the property in `config.xml` as you did here https://github.com/e-mission/e-mission-base/blob/a6ccf44dc8219107a666dc8f53c039fa22024641/config.xml#L38-L46:

```
    <platform name="ios">
        <config-file file="*-Info.plist" mode="merge" target="NSCameraUsageDescription">
            <string>To scan the barcode for the study</string>
        </config-file>
        ...
    </platform>
```

but it doesn't seem to add anything to this list in Xcode:

![Screen Shot 2022-11-04 at 2 05 56 pm](https://user-images.githubusercontent.com/17020181/199876369-16330de9-47fa-4bfd-bc8e-43b75cd7e8ad.png)

﻿﻿

**Comment by shankari** [comment]
Fixed in https://github.com/e-mission/e-mission-phone/commit/d318f8f252129e66a59f8a388e51914d7180171a
This should now automatically add the usage description
