### ISSUE TITLE
Testing for Admin Dashboard

### ISSUE THREAD

**Issue by sebastianbarry** [e-mission/e-mission-docs#859]
I have started the admin dashboard found at https://github.com/e-mission/op-admin-dashboard/tree/master and it is working!

I had expected to see more of the other changes, such as the Token generation button, view available tokens, etc. but what I got on my computer working looks far more barebones than that, I may be checking out the wrong branch:

<img width="1562" alt="Screen Shot 2023-02-20 at 10 15 19 AM" src="https://user-images.githubusercontent.com/61334340/220168400-1920d914-8c9f-41d3-b549-32d44bc70300.png">

<img width="1563" alt="Screen Shot 2023-02-20 at 10 15 30 AM" src="https://user-images.githubusercontent.com/61334340/220168403-835969dc-e00d-426c-9235-f7c087b6a8a5.png">

<img width="1569" alt="Screen Shot 2023-02-20 at 10 15 39 AM" src="https://user-images.githubusercontent.com/61334340/220168406-4c887a79-5a46-4918-b4c4-fc45f8eaf0c0.png">

<img width="1563" alt="Screen Shot 2023-02-20 at 10 16 01 AM" src="https://user-images.githubusercontent.com/61334340/220168408-e7781dc6-e072-49df-a558-45cb03f8ea1e.png">

@shankari I see that you are the only person who has made commits to this branch, is @asiripanich branch somewhere?

**Comment by asiripanich** [comment]
Hi @sebastianbarry, please see the dev branch. We are in the final stages of implementing the authentication. :) 

The code in master is just a Dash dashboard template from NREL visualisation team.

**Comment by sebastianbarry** [comment]
Thanks Amarin! I have switched to the dev branch but I'm having trouble using `docker-compose`, it seems to be getting hung up on this point:
<img width="693" alt="image" src="https://user-images.githubusercontent.com/61334340/220681126-6585a761-0fbe-43f6-bf92-9c7470a6e18e.png">

Have you encountered this before, or have any tips for me?

**Comment by sebastianbarry** [comment]
I see that this line was added to the `dev` branch in this commit: https://github.com/e-mission/op-admin-dashboard/commit/054132c42691f5dd80a0a8f6666dc625e3f9444c#diff-f34da55ca08f1a30591d8b0b3e885bcc678537b2a9a4aadea4f190806b374ddc

This may be why the `main` branch was working for me but the `dev` branch is not (using docker-compose method)

**Comment by asiripanich** [comment]
I havent tested the latest version of commits. Alireza should be able to guide you to setup the dashboard during our today meeting. :)

**Comment by sebastianbarry** [comment]
I was able to get the admin dashboard working and loaded some test user data!


| | |
:---:|:---:
| <img width="1565" alt="Screen Shot 2023-03-02 at 4 31 38 PM" src="https://user-images.githubusercontent.com/61334340/222590446-faf20a7a-b61f-4580-958f-234fb9b747cb.png"> | So far the dashboard looks good. I am not used to being a program admin, so I don't know what the above diagrams mean necessarily or how they are helpful, but I do believe they look really good |
| <img width="1556" alt="Screen Shot 2023-03-02 at 4 43 48 PM" src="https://user-images.githubusercontent.com/61334340/222590451-7c70d389-55a2-4fd5-a764-35beac96e7c5.png"> | I see that the users opcodes are loaded in the above image, that is great! I know that one of the challenges of admins is knowing which User's name/email associates with which OPcode, @shankari would it be against users data privacy if we were to store this information together? |
| <img width="1559" alt="Screen Shot 2023-03-02 at 4 44 25 PM" src="https://user-images.githubusercontent.com/61334340/222590456-58d89600-3a03-4dd0-95d6-09a841ce8e7a.png"> | Because a lot of our users are in US, we may want to change this date picker to be in the mm/dd/yyyy format |

**Comment by shankari** [comment]
@sebastianbarry 

> I was able to get the admin dashboard working and loaded some test user data!

how much test user data?

> I know that one of the challenges of admins is knowing which User's name/email associates with which OPcode, would it be against users data privacy if we were to store this information together?

correct. we are not allowed to store any PII (name/email etc) on the NREL hosted system per our cyber security rules. Most admins store this separately in an excel file/google doc on their local computer.

**Comment by shankari** [comment]
Closing this since the related issues are being tracked separately in the admin dashboard repo
