### ISSUE TITLE
Pipeline not running properly on staging

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-docs#865]
@JGreenlee @sebastianbarry I deployed the new composite trip code to staging and ran into the following error.

```
2023-03-22 05:10:07,486:ERROR:140038563837760:Found error 'confirmed_place' while processing pipeline for user d83a43a1-df6b-42ed-986f-f5b5f6150221, skipping
Traceback (most recent call last):
File "/usr/src/app/emission/pipeline/intake_stage.py", line 77, in run_intake_pipeline
run_intake_pipeline_for_user(uuid)
File "/usr/src/app/emission/pipeline/intake_stage.py", line 190, in run_intake_pipeline_for_user
eaum.create_composite_objects(uuid)
File "/usr/src/app/emission/analysis/userinput/matcher.py", line 97, in create_composite_objects
confirmed_place_id = ct["data"]["confirmed_place"]
KeyError: 'confirmed_place'
```

Because of this, no composite trips are being generated, so nothing is visible in the UI of the new staging app, which relies on the composite trips for display

**Comment by shankari** [comment]
Happens for all users

```
2023-03-22 05:06:15,818:ERROR:140038563837760:Found error 'confirmed_place' while processing pipeline for user 1d469f01-efaa-4ded-b11d-f5e5e99ad546, skipping
2023-03-22 05:06:28,903:ERROR:140038563837760:Found error 'confirmed_place' while processing pipeline for user 0951d756-b17a-4a33-aa90-a44830928a9e, skipping
2023-03-22 05:06:35,672:ERROR:140038563837760:Found error 'confirmed_place' while processing pipeline for user af046be2-3593-42b3-b2e5-ea4ba8287bbf, skipping
2023-03-22 05:07:01,414:ERROR:140038563837760:Found error 'confirmed_place' while processing pipeline for user 7614965c-1d07-485b-98a9-6416be91fc08, skipping
...


2023-03-22 05:09:10,946:ERROR:140038563837760:Found error 'confirmed_place' while processing pipeline for user ef477bef-b12a-4b25-9654-97355aae2584, skipping
2023-03-22 05:09:35,120:ERROR:140038563837760:Found error 'confirmed_place' while processing pipeline for user eb45666f-552a-4a87-a8b7-d40c0a48365c, skipping
2023-03-22 05:10:07,486:ERROR:140038563837760:Found error 'confirmed_place' while processing pipeline for user d83a43a1-df6b-42ed-986f-f5b5f6150221, skipping
```

**Comment by JGreenlee** [comment]
When confirmed trips are generated, I give them the id of their corresponding confirmed_place. Later, when composite trip is being generated, it uses this id to fill in the confirmed_place.
I thought this would be more performant than looking up by timestamp.

However, I'm guessing that we're having this issue now because there are existing entries in the database, processed before these changes, and they don't know which confirmed_place they go to.

Not sure how to go about this. What do you recommend?

**Comment by shankari** [comment]
I bet its happening because you have existing confirmed trips without any associated confirmed places.
Note that this can also happen if we don't have place confirm or place additions defined.

**Comment by shankari** [comment]
@JGreenlee, this can also happen if there are no confirmed places (e.g. no place_confirm and no place additions, right?)

**Comment by JGreenlee** [comment]
As it stands now, confirmed_places are being generated, and expected for composite trips, even if there are no place-level additions.
So this issue is pretty critical.

**Comment by shankari** [comment]
yeah I figured that out.
So the classic solution for this would be to reset and re-run the pipeline.
This will generate the confirmed trips and confirmed places from scratch

I can reset the pipeline on staging, but am a little reluctant to reset on all the production environments.
And deal with the additional load.

**Comment by shankari** [comment]
Let's think about how best to fix this.
- There will be no matched confirmed places before this because we did not have that functionality

So a more gradual, lazy, just-in-time upgrade would be that in the composite trip creation, if the confirmed trip doesn't have an associated confirmed place, we just create one on the fly.

This should slowly fill in the confirmed places as needed, and we can eventually remove the hack, once all the environments that are currently active have been deactivated.

**Comment by JGreenlee** [comment]
I agree, that's what I was thinking.
For existing entries that don't have the confirmed_place id set, we can look it up by its start_ts.
For new entries, the id will be set and the current implementation will be fine.

**Comment by shankari** [comment]
>  For existing entries that don't have the confirmed_place id set, we can look it up by its start_ts.

No, we can't because the confirmed place won't exist. We will have to actually create it.
See https://github.com/e-mission/e-mission-docs/issues/865#issuecomment-1478981724

**Comment by JGreenlee** [comment]
Oh right, of course.

**Comment by JGreenlee** [comment]
I can probably do this in the morning.

Circling back to https://github.com/e-mission/e-mission-docs/issues/865#issuecomment-1478977051, is this something you want? To only generate confirmed_places if needed according to dynamic config?

It makes sense in hindsight but I didn't consider it before - I just thought confirmed_places would always be generated even if they aren't used for inputs

**Comment by shankari** [comment]
I think that is what I had originally assumed because there is no point in creating a bunch of unused objects.
But now that I think about it, having a consistent data model is also a Good Thing, and will certainly simplify the composite trip creation code, for example.

Let me sleep on this and get back in the morning; I don't trust my judgement at this point.

**Comment by shankari** [comment]
@JGreenlee Thought about https://github.com/e-mission/e-mission-docs/issues/865#issuecomment-1478986305 some more, and I think it is fine to always create the confirmed place. It certainly makes the downstream analysis simpler.

And more practically, if we change our mind later, it should be trivial to turn off the confirmed place creation in the pipeline and then just delete all confirmed places. The reverse is not as easy because we would need to create confirmed places lazily like we do now and would have to make sure that we don't miss a confirmed trip.

**Comment by JGreenlee** [comment]
I pushed a fix to [fix-mission-confirmed-place](https://github.com/sebastianbarry/e-mission-server/tree/fix-missing-confirmed-place) and I'm trying to test it.
It's tricky to recreate the conditions in which the error occurred in a dev environment.

My thought was 1) clear pipeline 2) switch to `master`, load trips, run pipeline 3) switch to `add-composite-trip`, run pipeline. Observe error.

I did not observe the error so I can't be sure that my fix is working.

**Comment by shankari** [comment]
@JGreenlee that should work. How did you clear the pipeline?

**Comment by JGreenlee** [comment]
Here is what I'm trying
```python
    # Before confirmed_place was introduced, we created confirmed_trips without a confirmed_place
    # For those trips, we will first have to regenerate the confirmed objects just-in-time
    # Once every user has been migrated, we can remove this code
    if any(not hasattr(ct["data"], "confirmed_place") for ct in confirmedTrips):
        logging.info("Previous version of confirmed trip, no confirmed_place. Regenerating confirmed objects")
        epq.mark_confirmed_object_creation_done(user_id, None)
        create_confirmed_objects(user_id)
```

But `epq.mark_confirmed_object_creation_done(user_id, None)` does not work.
I want to reset the `CREATE_CONFIRMED_OBJECTS` stage without resetting the other stages. How can I do that?

**Comment by JGreenlee** [comment]
It will not be enough to just generate the missing confirmed places. The trips are expected to have an identifier for which `confirmed_place` they correspond to.

Does that need to be rethought as well?

**Comment by shankari** [comment]
Here's what I had in mind:

```
for ct in confirmed_trips:
   # Fill in the confirmed place first
   if "confirmed_place" not in ct["data"]:
     cleaned_end_place = ts.get_object_with_id(ct["data"]["cleaned_trip"]["end_place"])
     cpid = create_confirmed_place(cleaned_end_place)
     ct["data"]["confirmed_place"] = cpid
     # move on to creating composite trip
    ...
```

You will need to refactor `create_confirmed_places` but it doesn't seem too complicated

**Comment by JGreenlee** [comment]
That works right now, but this doesn't actually fill in the confirmed place ID does it? We put it into `ct`, but not the database entry?

So wouldn't we have to keep this as a hack forever?

**Comment by shankari** [comment]
@JGreenlee right so you would add an update, similar to 

```
            import emission.storage.timeseries.builtin_timeseries as estbt
            estbt.BuiltinTimeSeries.update(confirmed_obj)
```

after you have changed the `ct`

**Comment by JGreenlee** [comment]
I'll try it

**Comment by JGreenlee** [comment]
^ that should do it. @shankari Can you review?

**Comment by shankari** [comment]
Fixed in https://github.com/shankari/e-mission-server/pull/5
