### ISSUE TITLE
Diary and label screen issues IOS

### ISSUE THREAD

**Issue by allenmichael099** [e-mission/e-mission-docs#868]
OpenPATH version: 1.1.9
The forward and back arrows by the date do nothing on the diary screen for ios 16.3.1 on my iPhone 8. Also, when I hit refresh after selecting a date, the date jumps back to the current date. 

On the label screen, the only available tab at the top is "All", and it only shows the characters "Al".

With no trips to load, I get the "undefined is not an object" error on the label screen, seen below. Trips don't seem to be recording, but I'll update this issue if one from today appears.
<img src="https://user-images.githubusercontent.com/56986329/227378614-2310931b-2307-485b-b0d5-6033f61b83f3.jpg" width=35% height=20%>

**Comment by shankari** [comment]
My husband ran into this error as well. In his case, he had the newer version of the app (1.1.8) but was connected to a production server (the open access server), so he also did not actually have any composite trips to retrieve

**Comment by shankari** [comment]
Resolved after hiding the dashboard for the trip confirm survey
