### ISSUE TITLE
join page i18n does not correctly distinguish between "study" and "program" for token generation

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-docs#869]
@dcolondavila @sebastiandsc

Before the i18n changes, the text on the join page was customized based on whether this was a study or a program.
https://github.com/e-mission/nrel-openpath-join-page/blob/dcdcd00919d0a0030a6b6e7f8d0d06e8d11a97c0/frontend/index.html#L475

In the new page, this is hardcoded.
It needs to be changed to be study/program specific.
Please also double check that you have not missed any of the other customizations.

**Comment by shankari** [comment]
This is also always showing "autogenerated", 
https://github.com/e-mission/nrel-openpath-join-page/blob/main/frontend/index.html#L533
even for a program such as https://uprm-nicr-openpath.nrel.gov/join/

**Comment by shankari** [comment]
@dcolondavila @sebastiandsc please check the old version of the join page (before your i18n changes) carefully and make sure that there are no other such regressions.

**Comment by dcolondavila** [comment]
@shankari Ok, @sebastiandsc will take a look at this. I will continue working with the dashboard.

**Comment by shankari** [comment]
@sebastiandsc Is there an ETA for this? This is a regression and the UPRM NICR page currently has the wrong instructions.

**Comment by sebastiandsc** [comment]
@shankari I expect to have the changes made by 23:59 GMT-4 today.

**Comment by shankari** [comment]
@sebastiandsc the changes were correct but incomplete. Please see review.

**Comment by shankari** [comment]
@sebastiandsc is there an ETA for actually finishing this change?

**Comment by shankari** [comment]
@sebastiandsc is there an ETA for actually finishing this change?

**Comment by dcolondavila** [comment]
@shankari Do to multiple personal issues I have not been able to work with the project. I believe that I will be MIA for some time do to the circumstances. Therefore I have decided to remove myself from the team, but @sebastiandsc will continue the work and if he ever requires any assistance I will be able to help him.

**Comment by shankari** [comment]
@sebastiandsc it looks like @dcolondavila is not going to work on this any more. Is there an ETA for this fix from your side?

**Comment by sebastiandsc** [comment]
@shankari  Good evening, I apologize for my absence these past few weeks. I think Daniel has not informed you but Diego and I are no longer part of the project since March 31. On the other hand, I promise to have the changes ready by Friday May 5th at the latest. On the other hand, I can help with other arrangements that the join page needs for at least two more weeks to compensate for my absence in the month of March.

**Comment by shankari** [comment]
It is now May 8th. It is currently more effort to keep following up on these changes than it is to just make them myself.

**Comment by shankari** [comment]
Fixed in https://github.com/e-mission/nrel-openpath-join-page/commit/c3896da8117ac6cd60e5f4b654d3434ea834d8e8 which has now been merged to main and will be in production next week
