### ISSUE TITLE
Untracked time can lead to issues with place-based additions due to zero duration dwell times

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-docs#870]
@JGreenlee Please see attached video.
@sebastianbarry did this work for you? Is it just an artifact of my particular trips?

Steps to reproduce:
- I have pulled all changes from `survey_refactor_expansion`
- I am not syncing the changes or running the pipeline or anything
- I am literally adding a new activity to the existing place
- I was at the place from 8:44 to 3:59
- I have already entered one activity from 8:44 to 2:00
- Trying to add a new activity from 2:00 to 2:45, it is not showing up

https://user-images.githubusercontent.com/2423263/227752810-6666a7cf-b6f7-4f82-a3ab-c40c5cf7f648.mov

**Comment by shankari** [comment]
I can confirm that the notes list has only one entry, so this is a matching issue not a display issue.

```
<ion-item class="notes-list item" style="background-color: transparent">
<ul>
<!-- ngRepeat: entry in additionEntries | orderBy: 'data.start_ts' -->
<li class="notes-list-entry" ng-repeat="entry in additionEntries | orderBy: 'data.start_ts'">grid
<b class="two-lines ng-binding" ng-click="editEntry(entry)">1 Employment/Education, </b>
<i ng-click="editEntry(entry)" class="ng-binding">8:44 AM - 2:00 PM</i>
<i class="icon ion-trash-a" ng-click="confirmDeleteEntry(entry)">…</i>
</li>
<!-- end ngRepeat: entry in additionEntries | orderBy: 'data.start_ts' -->
</ul>
</ion-item>
```

**Comment by shankari** [comment]
@JGreenlee as an aside, a nice feature request (if not too complicated) would be to change the prefilled time to exclude any ranges that have already been filled out. So if I have already filled in my activities until 2pm, then it would be good if the next activity was prefilled to start at 2pm.

**Comment by JGreenlee** [comment]
This isn't the behavior I observe in the emulator with test data, so I'm inclined to say it has to do with this real-life data.

Does this particular place not have an 'exit' time?
Notice how the prefill end time is the same as the start time for that place? That isn't expected. Specifically, the `exit_fmt_time` is what should be used for prefill.
It doesn't appear to be the last place, so if it does lack an exit ts, the problem could even be server-side.

**Comment by shankari** [comment]
Looked at the place object; it does have both enter and exit times, but they are both set to 8:44am

```
  Object = $3
_id: {$oid: "641ba7f134dda48794b6c6fd"}
additions: [] (0)
additionsList: [Object] (1)
background: "bg-light"
cleaned_place: {$oid: "6419d70fb034859dd9aa3ae1"}
display_date: "Tue 21 Mar 2023"
display_end_time: "8:44 AM"
display_name: "South Shoreline Boulevard, Mountain View"
display_start_time: "8:44 AM"
display_time: "a few seconds"
duration: 5
end_display_name: " "
ending_trip: {$oid: "6419d70db034859dd9aa3aab"}
enter_fmt_time: "2023-03-21T08:44:53.584000-07:00"
enter_local_dt: {minute: 44, hour: 8, second: 53, day: 21, weekday: 1, …}
enter_ts: 1679413493.584
exit_fmt_time: "2023-03-21T08:44:53.584000-07:00"
exit_local_dt: {minute: 44, hour: 8, second: 53, day: 21, weekday: 1, …}
exit_ts: 1679413498.584
listCardClass: "list card list-card bg-light list-card-lg"
location: {type: "Point", coordinates: [-122.0865042, 37.3910047]}
raw_places: [{$oid: "6419d709b034859dd9aa3aa2"}, {$oid: "6419d709b034859dd9aa3aa2"}] (2)
source: "DwellSegmentationTimeFilter"
start_display_name: " "
starting_trip: {$oid: "641a4777a31e1ca8695376d5"}
userInput: {}
user_input: {}
verifiability: "cannot-verify"
```

**Comment by shankari** [comment]
Let's try to look at the various objects on the server

#### Confirmed trip

```
{'_id': ObjectId('641ba7f134dda48794b6c6fd'),
'data': {
   'enter_fmt_time': '2023-03-21T08:44:53.584000-07:00',
   'raw_places': [ObjectId('6419d709b034859dd9aa3aa2'), ObjectId('6419d709b034859dd9aa3aa2')],
   'cleaned_place': ObjectId('6419d70fb034859dd9aa3ae1')}}
```

#### Cleaned place

```
{'_id': ObjectId('6419d70fb034859dd9aa3ae1'),
'data': {
   'enter_fmt_time': '2023-03-21T08:44:53.584000-07:00', 
   'raw_places': [ObjectId('6419d709b034859dd9aa3aa2'), ObjectId('6419d709b034859dd9aa3aa2')]
   'exit_fmt_time': '2023-03-21T08:44:53.584000-07:00'
}}
```

#### Raw places

```
{'_id': ObjectId('6419d709b034859dd9aa3aa2'),
'data': {
'enter_fmt_time': '2023-03-21T08:44:53.584000-07:00',
'exit_fmt_time': '2023-03-21T08:44:53.584000-07:00'
}}
```

Both the raw place IDs are identical!!

**Comment by shankari** [comment]
Looking at the starting trip for that place, we see that there is some untracked time. 
Untracked time = time where we were not sure what was going on, potentially due to a reboot - e.g.
https://github.com/e-mission/e-mission-docs/issues/205

We currently don't display untracked time although there is a very old open issue for it that I can't find and was possibly lost while moving the issues from e-mission-phone

But certainly we have https://github.com/e-mission/e-mission-docs/issues/622

```
{'_id': ObjectId('641a4771a31e1ca8695376c7'),
'metadata': {'key': 'segmentation/raw_untracked',
'data': {'start_fmt_time': '2023-03-21T08:44:53.584000-07:00',
'start_place': ObjectId('6419d709b034859dd9aa3aa2'),
'end_fmt_time': '2023-03-21T15:59:53.104000-07:00',
'end_place': ObjectId('641a4771a31e1ca8695376c8')
}}
```

A fairly simple fix seems to be to actually display untracked time in the list, at least for time-use-based entries.
The user can then add the split time-use in there, including travel if needed.
The places before and after the untracked time will have very small durations so I guess we can think about skipping them

```
{'_id': ObjectId('6419d709b034859dd9aa3aa2'),
'data': {
'enter_fmt_time': '2023-03-21T08:44:53.584000-07:00',
'exit_fmt_time': '2023-03-21T08:44:53.584000-07:00'
'duration': 5.0
}}

{'_id': ObjectId('641a4771a31e1ca8695376c8'), 
'data': {
    'enter_fmt_time': '2023-03-21T15:59:53.104000-07:00',
    'exit_fmt_time': '2023-03-21T15:59:53.104000-07:00',
    'duration': 0.0}}
```

**Comment by JGreenlee** [comment]
Ah, that would explain it - because currently for the UI we rely on the assumption that trip end always equals place enter.

So, if I'm understanding this right:

When a place has the same enter and exit time (or within 1 minute or so), we won't display that place, and we will replace it with some indicator "Untracked Time".
We will consider that place ineligible for additions.

**Comment by JGreenlee** [comment]
If trip end is not always the same as place enter, then we might need to revisit some server code as well.
I am pretty sure that this assumption was relied on for composite trip creation.

**Comment by shankari** [comment]
Final investigation: why was this time marked as untracked?

```
2023-03-22 00:10:25,541:DEBUG:139780467152704:Iterated over all points, just_ended = True, len(transition_df) = 4
2023-03-22 00:10:25,682:DEBUG:139780467152704:In range 1679413493.584 -> 1679439593.104 found transitions                            fmt_time  curr_state  transition
0  2023-03-21T08:47:51.731000-07:00           2           2
2023-03-22 00:10:25,685:DEBUG:139780467152704:while determining new_start_place, transition_distance = 1550.9175173699641
2023-03-22 00:10:25,686:DEBUG:139780467152704:while determining new_start_place, time_delta = 26099.519999980927, transition_speed = 0.05942321994316744
2023-03-22 00:10:25,686:DEBUG:139780467152704:transition_speed 0.05942321994316744 <= 0.8333333333333334, 'stopped', returning True
2023-03-22 00:10:25,758:DEBUG:139780467152704:Created untracked period 641a4771a31e1ca8695376c7 from 1679413498.584 to 1679439593.104
```

Which is a result of this code

```
    transition_distance = ecc.calDistance(last_place.location.coordinates,
                       start_loc.loc.coordinates)
    logging.debug("while determining new_start_place, transition_distance = %s" % transition_distance)
    if transition_distance < 1000:
        logging.debug("transition_distance %s < 1000, returning False", transition_distance)
        return False

    time_delta = start_loc.ts - last_place.enter_ts
    transition_speed = old_div(transition_distance, time_delta)
    logging.debug("while determining new_start_place, time_delta = %s, transition_speed = %s"
                  % (time_delta, transition_speed))

    # Let's use a little less than walking speed 3km/hr < 3mph (4.83 kmph)
    speed_threshold = old_div(float(3000), (60*60))
```

So basically, our trip started quite a bit away from the previous stop. So we wondered if this was a reboot. We checked to see if we were moving during that time (to handle transitions in multi-modal trips) and we were not. So we assumed that this was untracked time with the phone turned off.

Since we now have a greater delay in geofence exits with the background restrictions, maybe we should tweak this filter.

**Comment by shankari** [comment]
@JGreenlee

> If trip end is not always the same as place enter, then we might need to revisit some server code as well.
> I am pretty sure that this assumption was relied on for composite trip creation.

Trip end *is* always the same as place enter, but we are not reading all trip-like objects.
The timeline here is: trip -> place -> untracked (could have any number of trips, we don't know) -> place -> trip ...

**Comment by shankari** [comment]
> Since we now have a greater delay in geofence exits with the background restrictions, maybe we should tweak this filter.

We could get away so far without tweaking the filter, since we don't display untracked time or places.
So if the large gap at the beginning of the trip resulted in untracked time, it would just look like the trip started much later.
But as we start getting more complex, we may need to tweak this.

**Comment by shankari** [comment]
We seem to have the following ratio for my trips on the staging server. 10% is a bit high, particularly since I don't remember when I last actually rebooted the pixel, but maybe not excessively so?

```
>>> edb.get_analysis_timeseries_db().count_documents({"user_id": UUID(""), "metadata.key": "segmentation/raw_untracked"})
33
>>> edb.get_analysis_timeseries_db().count_documents({"user_id": UUID(""), "metadata.key": "segmentation/raw_trip"})
373
```

Let's plot the distance characteristics of the untracked trips.

**Comment by shankari** [comment]
> When a place has the same enter and exit time (or within 1 minute or so), we won't display that place, and we will replace it with some indicator "Untracked Time".
We will consider that place ineligible for additions.

There is an untracked time object in the database, and if you use the `Timeline` object to iterate over entries (`emission/storage/decorators/timeline`) it will return them in order.

**Comment by shankari** [comment]
The untracked time on staging seems to happen more often on android than on iOS.

```
data.source
DwellSegmentationDistFilter    266
DwellSegmentationTimeFilter    447
```

![image](https://user-images.githubusercontent.com/2423263/227798484-965a73ef-c42a-473b-a3b3-f648b84c2bd3.png)

**Comment by shankari** [comment]
There are some clear outliers in the data

```
> all_untracked_df['data.distance'].describe()

count    7.130000e+02
mean     6.010592e+03
std      5.212906e+04
min      9.716969e-01
25%      2.245484e+02
50%      1.159247e+03
75%      2.552519e+03
max      1.292153e+06
```

```
all_untracked_df['data.distance'].plot(kind='box')
```

![image](https://user-images.githubusercontent.com/2423263/227799278-b9eba7a0-3820-4143-a875-50b88ed2db6c.png)


But after removing everything above 90% , we get a much better figure

![image](https://user-images.githubusercontent.com/2423263/227799313-9f0650f3-de22-412e-931f-49e424707a92.png)

which seems to indicate a new threshold of around 1.75km

```
> all_untracked_df[all_untracked_df['data.distance'] < pct_90]['data.distance'].describe()
count     641.000000
mean     1331.164122
std      1318.998027
min         0.971697
25%       198.932551
50%      1083.412799
75%      1722.088261
max      5621.775788
```

![image](https://user-images.githubusercontent.com/2423263/227799380-4d00a5b8-c349-4906-b550-8899426198a9.png)

**Comment by shankari** [comment]
Let's quickly split by OS, and on android, check for the reboot transition and/or the foreground service restart.
iOS is definitely much shorter than android

```
> all_untracked_df.groupby('data.source')['data.distance'].describe()
```



| | count | mean | std | min | 25% | 50% | 75% | max
|-- | -- | -- | -- | -- | -- | -- | -- | --
Dist Filter | 266.0 | 2222.113003 | 11853.881439 | 0.992267 | 158.220443 | 1012.777706 | 1304.737990 | 1.566984e+05
Time Filter | 447.0 | 8265.034397 | 65123.035597 | 0.971697 | 440.873561 | 1517.428567 | 3523.025137 | 1.292153e+06

```
> all_untracked_df[all_untracked_df['data.distance'] < pct_90].groupby('data.source').boxplot(column='data.distance', subplots=True)
```

![image](https://user-images.githubusercontent.com/2423263/227799844-ca5fe06c-7b4e-413b-8171-564a6380f311.png)

So the original 1k seems to be fine for iOS, or maybe move it up to 1.25k.
But for android, we need to have 2.5k

**Comment by shankari** [comment]
Number of reboots is almost exactly evenly split between 0 and 1 reboots
![image](https://user-images.githubusercontent.com/2423263/227802674-e7b100ff-19cf-48eb-8944-0ce05b1c9d2b.png)

**Comment by shankari** [comment]
It looks like there is a pretty big difference between 0 reboots and the rest.

The IQR for zero reboots is pretty consistently over 1.5k and closer to 1.75k
The IQR for the others is closer to 500, although this is for android phones, so we will get the reboot transition
![image](https://user-images.githubusercontent.com/2423263/227803069-5db0b0b1-e9ec-482d-839e-eeefeaf1e0fc.png)

So current tweaks:
- different thresholds for iOS and android
- on android:
   - if no reboots, threshold is 1.7k
   - if reboots, we don't need a threshold
- on iOS:
   - don't know how many reboots
   - threshold is 1.25k although probably 1.5k is fine too

@JGreenlee I am going to make the server changes right now
can you plan on making the phone changes?

**Comment by JGreenlee** [comment]
@shankari I think it would help if we could quickly meet tomorrow morning to check my understanding. Then, I'll feel more comfortable taking on the task and can spend the day working on it.

**Comment by shankari** [comment]
Fixed in https://github.com/e-mission/e-mission-phone/pull/935
