### ISSUE TITLE
Regression in the diary detail screen

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-docs#874]
Reported by @TTAlex
We have clearly not been testing the diary screen enough.
@sebastianbarry did you see this in your testing of the new composite trip functionality?

```
Error: undefined is not an object (evaluating '$scope.surveyOpt.filter')
@ionic://localhost/js/diary/detail.js:25:60
@[native code]
instantiate@ionic://localhost/lib/ionic/js/ionic.bundle.js:18010:61
$controller@ionic://localhost/lib/ionic/js/ionic.bundle.js:23412:39
@ionic://localhost/lib/ionic/js/ionic.bundle.js:59900:35
render@ionic://localhost/lib/ionic/js/ionic.bundle.js:57893:58
init@ionic://localhost/lib/ionic/js/ionic.bundle.js:57813:26
@ionic://localhost/lib/ionic/js/ionic.bundle.js:59759:18
@ionic://localhost/lib/ionic/js/ionic.bundle.js:59717:16
updateView@ionic://localhost/lib/ionic/js/ionic.bundle.js:65398:31
@ionic://localhost/lib/ionic/js/ionic.bundle.js:65375:21
$broadcast@ionic://localhost/lib/ionic/js/ionic.bundle.js:30718:33
@ionic://localhost/lib/ionic/js/ionic.bundle.js:52157:32
processQueue@ionic://localhost/lib/ionic/js/ionic.bundle.js:29127:30
@ionic://localhost/lib/ionic/js/ionic.bundle.js:29143:39
$digest@ionic://localhost/lib/ionic/js/ionic.bundle.js:30211:36
$apply@ionic://localhost/lib/ionic/js/ionic.bundle.js:30503:31
@ionic://localhost/lib/ionic/js/ionic.bundle.js:65426:19
dispatch@ionic://localhost/lib/jquery/dist/jquery.min.js:2:43341
dispatchEvent@[native code]
triggerMouseEvent@ionic://localhost/lib/ionic/js/ionic.bundle.js:2953:20
tapClick@ionic://localhost/lib/ionic/js/ionic.bundle.js:2942:20
tapTouchEnd@ionic://localhost/lib/ionic/js/ionic.bundle.js:3069:13
```

**Comment by shankari** [comment]
In https://github.com/e-mission/e-mission-phone/commit/c9fc41fc40c62a9f1376b776a9e612064b0f7793, we put the label type into the dynamic config and changed all the config locations to read from it.

In infinite_scroll_detail.js, we ensured that everything that used the survey config was inside the callback

```
  DynamicConfig.configReady().then((configObj) => {
    const surveyOptKey = configObj.survey_info['trip-labels'];
    $scope.surveyOpt = SurveyOptions[surveyOptKey];
    console.log('surveyOpt in infinite_scroll_details.js is', $scope.surveyOpt);
    $scope.tripFilterFactory = $injector.get($scope.surveyOpt.filter);
    $scope.filterInputs = $scope.tripFilterFactory.configuredFilters;
  });
```

in the detail, we left some out

```
  DynamicConfig.configReady().then((configObj) => {
    const surveyOptKey = configObj.survey_info['trip-labels'];
    $scope.surveyOpt = SurveyOptions[surveyOptKey];
    console.log('surveyOpt in details.js is', $scope.surveyOpt);
  });

  $scope.tripFilterFactory = $injector.get($scope.surveyOpt.filter);
  $scope.filterInputs = $scope.tripFilterFactory.configuredFilters;
```

So we try to initialize the `tripFilterFactory` before `surveyOpt` is read, which breaks.
@JGreenlee @sebastianbarry I am not sure how this ever worked.

**Comment by JGreenlee** [comment]
I included this fix, and a few others for the diary screen, in https://github.com/e-mission/e-mission-phone/pull/935.

It had been broken for a while, but I have prioritized the label screen because, if I understand correctly, we will no longer use the diary screen soon.

**Comment by shankari** [comment]
@JGreenlee I patched both issues in https://github.com/e-mission/e-mission-phone/pull/936 so we can fix the regressions before the next big rewrite wrt untracked time.

Feel free to review; I'm going to deploy the server code first.

> It had been broken for a while, but I have prioritized the label screen because, if I understand correctly, we will no longer use the diary screen soon.

Prioritizing the label screen is correct, and we should not add any new functionality to the diary screen. But as long as we have it, we also can't let the diary screen be egregiously broken. We should definitely prioritize removing it so that we can stop maintaining it 😄

**Comment by shankari** [comment]
Fixed in https://github.com/e-mission/e-mission-phone/pull/936
