### ISSUE TITLE
P0: trip detail survey cannot complete because it fails time validation

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-docs#879]
@JGreenlee see attached screenshot

<img src="https://user-images.githubusercontent.com/2423263/230530362-b906c439-3fff-4a9d-880a-9ce13f6ca5d5.png" width="330px"/>

**Comment by JGreenlee** [comment]
https://github.com/e-mission/e-mission-phone/pull/948

**Comment by shankari** [comment]
Fix included in 1.2.3
