### ISSUE TITLE
Several tapping on download button is needed to see all trips- version 1.2.2

### ISSUE THREAD

**Issue by MaliheTabasi** [e-mission/e-mission-docs#883]
@shankari  I have to hit download button several times ( in my case 5 times) so that I can see all my trips in the 'All trip" tab. Is it supposed to work like this? because I thought if I hit this button once, it will display all my trips.

**Comment by shankari** [comment]
The download button downloads data for another week.
That is what I meant by "it downloads data week by week"
It does not download all trips and will not ever download all trips.

OpenPATH supports longitudinal operation, and we used it to collect 1.5 years worth of data for the CanBikeCO full pilot.
If we downloaded a years worth of data at a time, it would:
a) take a long time
b) fill up the full phone memory and crash the app

Again, I think we should discuss this in person so I can set expectations on how the download button works.
Maybe on Wed or Thu

**Comment by shankari** [comment]
I will close this issue after we have that in-person discussion.

**Comment by MaliheTabasi** [comment]
> The download button downloads data for another week. That is what I meant by "it downloads data week by week" It does not download all trips and will not ever download all trips.
> 
> OpenPATH supports longitudinal operation, and we used it to collect 1.5 **years** worth of data for the CanBikeCO full pilot. If we downloaded a years worth of data at a time, it would: a) take a long time b) fill up the full phone memory and crash the app
> 
> Again, I think we should discuss this in person so I can set expectations on how the download button works. Maybe on Wed or Thu

Thank you. I got it. We do not have any issues with this.

**Comment by shankari** [comment]
Closed since this is clear, and @MaliheTabasi is on vacation.
Please reopen if you still have concerns
