### ISSUE TITLE
Place before/after untracked time

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-docs#887]
Back when @JGreenlee supported untracked time, he decided not to display the place after a trip because it was zero length. However, in https://github.com/e-mission/e-mission-docs/issues/880#issuecomment-1503640756, we see that the place *before* the untracked time is zero  time but the one after is not.

We should just filter on the phone based on the duration in each place.

@JGreenlee can you handle this? We will target it for the point release, so no rush.

**Comment by JGreenlee** [comment]
> We should just filter on the phone based on the duration in each place.

It should already be doing this on the basis of 1 minute. I'm going to see what is causing the inconsistency.

**Comment by shankari** [comment]
For the record, you should be able to reproduce this by loading the 2016 Aug 4 and Aug 5 datasets and running the intake pipeline.

**Comment by JGreenlee** [comment]
The phone code is fine and we can leave it how it is.

`infinite_scroll_list.js, line 324`
```js
...
      if ($scope.showPlaces && place) {
        // Places with duration less than 60 seconds will not be displayed
        if (!isNaN(place.duration) && place.duration < 60) return; 

        if (!place.display_end_time) {
          // If a place does not have a display_end_time, it is the last place
          // We will set display_end_time to the end of the day
          place.display_end_time = moment(place.enter_fmt_time).parseZone().endOf('day').format("h:mm A");
        }
        $scope.data.displayTimelineEntries.push(place);
      }
...
```
---

It is actually server-side that we exclude the end place for composite untracked time
in `composite_trip_creation.py`:
```python
    # The place that follows untracked time has a duration of 0.
    # Thus, we are not going to consider it eligible for additions or user input,
    # and so untracked composite objects will not have a confirmed_place.
    if not isUntrackedTime:
        composite_trip_data["end_confirmed_place"] = eaum.get_confirmed_place_for_confirmed_trip(ct, "end_place")
```

Since `confirmed_untracked` objects now have their `end_place` filled in the same way `confirmed_trip`s do, we can safely remove that conditional and just always set `end_confirmed_place`.

**Comment by JGreenlee** [comment]
https://github.com/shankari/e-mission-server/pull/16

**Comment by shankari** [comment]
@JGreenlee so after this change, we would need to delete and recreate all composite trip objects, right?
although this is not a showstopped, I am tempted to sneak this into the production release just so we don't need to recreate the composite trips when we push out the point release...

**Comment by JGreenlee** [comment]
Yes, this change will require a reset because old "composite untracked" do not have an `end_confirmed_place`.

However, if we are still planning on having `start_confirmed_place`, that will require the same.
Maybe it's better to pospone the reset until both of those changes are merged.

**Comment by shankari** [comment]
Fixed, will be in the next point release
