### ISSUE TITLE
Sorting Activities Based on Start Time and End Time - Discrepancy in the App.

### ISSUE THREAD

**Issue by MaliheTabasi** [e-mission/e-mission-docs#889]
@shankari  Activities are sorted solely based on their start time. In the case of activities with the same start time, the next factor used for sorting is their end time which is not applied in the app as can be seen in the attached screenshot.

![msg-908960961-664294](https://user-images.githubusercontent.com/49550315/233077652-7c6671b9-8ef1-435b-8d69-e4105bbcd6ce.jpg)

**Comment by shankari** [comment]
>  the next factor used for sorting is their end time which is not applied in the app as can be seen in the attached screenshot.

I think you mean that the next factor **should be** their end time.
@sebastianbarry can you handle this fix for the point release?

**Comment by sebastianbarry** [comment]
Here is the progress I've made on this today:

When an addition is added to the list, I want to sort the list of `additionsList` based on the additions' start time, and if the start times are the same we'll sort by end time. Here's the compare function I've created for sorting:
<img width="830" alt="image" src="https://user-images.githubusercontent.com/61334340/233712710-658584bf-2de4-46f1-970d-f8fb89565dc4.png">

The issue I am facing is that this list does not actually sort after running this compare function:
| | |
:---:|:---:
| <img width="962" alt="image" src="https://user-images.githubusercontent.com/61334340/233712924-97b0ad09-9728-4975-96ed-cce822fd70ae.png"> | <img width="963" alt="image" src="https://user-images.githubusercontent.com/61334340/233713062-496ba01b-6824-4695-8905-8625b10d460a.png"> |

I am not sure why it's not sorting, I'll pick this back up on Monday

**Comment by shankari** [comment]
High level comments:
- there is a timestamp in the addition data directly; I don't think you need to have parse out from the jsonDoc
- timestamp comparison should be direct (e.g. endTs1 < endTs2)

You should be able to get that function down to ~ 5 lines of code

**Comment by sebastianbarry** [comment]
I got the additions to be sorted when they are retrieved from the server
- **I still need to sort them when a user creates new additions**

Created a PR for this: https://github.com/e-mission/e-mission-phone/pull/956

**Comment by sebastianbarry** [comment]
This issue has been addressed and fixed in https://github.com/e-mission/e-mission-phone/pull/959 :)

**Comment by shankari** [comment]
Fixed in https://github.com/e-mission/e-mission-phone/pull/959, will be in the next point release
