### ISSUE TITLE
UI problem, untracked place is overlapping the trip

### ISSUE THREAD

**Issue by MaliheTabasi** [e-mission/e-mission-docs#890]
@shankari  The date, distance, origin of the trip cannot be observed by the user as can be seen in the attached screenshot.
![photo1681888397 (1)](https://user-images.githubusercontent.com/49550315/233078124-4494861a-bc1d-4d09-9fd5-17001db15e7c.jpeg)

**Comment by shankari** [comment]
Untracked time overlap issue was found and fixed
https://github.com/e-mission/e-mission-docs/issues/880#issuecomment-1503640756

Are you sure you are on 1.2.3 on this phone? Is it with the same token that you sent me via email?

**Comment by shankari** [comment]
This was because the pipeline was not reset correctly for this user, so we still had `cleaned_untracked` on the server.
Fixed after pipeline was reset.
See https://github.com/e-mission/e-mission-docs/issues/882#issuecomment-1515331664
