### ISSUE TITLE
Design handling sleep activity (and overnight activities in general)

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-docs#891]
Right now, we display a single place card when we are at a place overnight, and at the end of the day
And we also add an end place, which stays there until the next trip on the following day

| Overnight place | End place |
|-------|------|
| ![photo1681888397](https://user-images.githubusercontent.com/49550315/233075807-71c9f3e0-a395-47f1-ac04-675ad7842200.jpeg) | <img src="https://user-images.githubusercontent.com/2423263/233127025-18a576bc-f14a-4ac1-ae25-56e3729bc044.png" width="500px"/> |

We need to decide how we plan to (i) display these places, (ii) to allow users to enter overnight activities and (iii) to display the resulting activities.

**Comment by shankari** [comment]
Prior discussion:
https://github.com/e-mission/e-mission-docs/issues/871#issuecomment-1489740498
https://github.com/e-mission/e-mission-docs/issues/871#issuecomment-1489750959

We had de-prioritized that design based on this comment

https://github.com/e-mission/e-mission-docs/issues/871#issuecomment-1495465078
> Taha and I had a meeting and decided that activities that starts form one day and ends in another day are not essential for our study. So, we can stop worrying about that and instead focus on fixing the errors with the current basic time-use feature.

However, I think we do need to address it before going live, since sleeping overnight is a very common use case.

**Comment by shankari** [comment]
In particular,

> The redundancy of including both start and end place would not hurt us, and it would not be hard to ignore the duplicates when composite trips are received and unpacked on the phone.
> 
> The only difficult and time-consuming task here would be splitting up places, but I think we can avoid this.
> 
> If surveys include an "End date", time use can be recorded overnight. This way, we do not need to split the places. Is that correct @MaliheTabasi?

@JGreenlee Yes, that is correct, however you might need to take care of the the UI changes that are necessary and some validation processes between the start data and time and end date and time for activity insertion. For example, you might want to show both start date and start time of the Place and the end time and end date of the Place on Place card. or you might want to update UI such that each activity aside form title, start time, end time, and delete icon, has a start date and end date as well when it is displayed to users so that they can realise to which date it belongs. 

[redacated discussion around weekly view since we don't have a week-by-week view]

![Place](https://user-images.githubusercontent.com/49550315/228992182-a08f92cf-f64b-4667-ae75-7e8265ac7fd5.jpg)

**Comment by JGreenlee** [comment]
I don't think it is clear yet what implementation is desired.
UNSW said they do not need support for overnight activities, so I see no need to change our overall approach.

I think if a user goes to add an activity on an overnight place, we can just prefill the end time as "11:59 PM".
If they instead intended the activity for the morning, then they can change the Date and Start Time.

Is there a different reason we need to support overnight activities?

**Comment by shankari** [comment]
right, I wanted this issue to serve as a forum for brainstorming the solution.
I see that UNSW said that they don't want support for overnight activities, but I disagree with them.
People are going to sleep overnight every single night. Other than work, it is the most common activity that people are likely to enter. We should make sure that it works smoothly.

Also, UNSW is still complaining about the end time of the place, which suggests to me that they think that we will have two places (one for each day) between two trips.
https://github.com/e-mission/e-mission-docs/issues/882#issuecomment-1514657557

**Comment by shankari** [comment]
My current thoughts on the design:
- we should not have two places; that will just be too confusing
- we should show the date in addition to the time for activities that are associated with an overnight place e.g. as in 
![Place](https://user-images.githubusercontent.com/49550315/228992182-a08f92cf-f64b-4667-ae75-7e8265ac7fd5.jpg)

**Comment by JGreenlee** [comment]
I think we have 2 sensible options
1) Allow activities to span overnight by including "End Date" on surveys
2) Don't allow activities to span overnight, but split overnight place cards into sections so that this is clearer

<table>
<tr>
<td>
Option 1
</td>
<td>
Option 2
</td>
<tr>
<td>

![mockup2](https://user-images.githubusercontent.com/15843932/233157979-921616a7-bad4-4695-b0f9-2bcd8daee68a.png)
</td>
<td>

![mockup1](https://user-images.githubusercontent.com/15843932/233156496-7b77d006-bc54-4448-838f-2fcc0711b953.png)
</td>
<td>
If we choose option 1, we have to show the start and end date when we list activities, which will clutter the UI.
<br>
<br>
If we choose option 2, people cannot record their sleeping as one activity.
</tr>
</table>

**Comment by shankari** [comment]
@JGreenlee which do you prefer? I think that UNSW wants to have a working survey.
But we should think about long-term design and either:
- implement the long-term, OR
- if we are implementing a short-term, one-off solution, implement the one that involves least work

**Comment by JGreenlee** [comment]
> wrt actually representing overnight activities by adding an end date, what do you think?

It's feasible, but I think it introduces more complexity + UI clutter, so I would only recommend it if this use case is truly necessary

**Comment by JGreenlee** [comment]
> @JGreenlee which do you prefer? I think that UNSW wants to have a working survey. But we should think about long-term design and either:
> 
> * implement the long-term, OR
> * if we are implementing a short-term, one-off solution, implement the one that involves least work

Ok, I think it's not a big deal to implement the long-term solution, but let's make sure we don't introduce needless clutter.

On the label screen, activities for non-overnight places don't need to specifically list out the dates, so we'll only show the extra detail on overnight places.

On the survey, we can use ["Date & Time" question types instead of separate "Date" and "Time" questions](https://support.kobotoolbox.org/date_time.html#appearance-of-date-and-time-question-types-in-web-forms-and-kobocollect). This means 2 questions instead of 4, and should feel less clunky from a UX perspective.

To try this, the first thing I'm going to do is create a new survey to test with.

**Comment by shankari** [comment]
> To try this, the first thing I'm going to do is create a new survey to test with.

You should be able to get the original survey from @sebastianbarry so that you only need to edit it.
Also, when you do this, can you add "reading books" to the list of recreational activities? I read fiction for pleasure and I can never record it.

**Comment by shankari** [comment]
> On the label screen, activities for non-overnight places don't need to specifically list out the dates, so we'll only show the extra detail on overnight places.

So you think that the correct long-term solution is Option 1 and not Option 2 (just checking to make sure)
I do think it is better since it is more consistent with a potential "Mark transition" option down the road.

@MaliheTabasi, any thoughts?

**Comment by sebastianbarry** [comment]
Here is the original time use survey file!
https://github.com/sebastianbarry/nrel-openpath-deploy-configs/blob/missing-trips-survey/survey-resources/data-xls/time-use-survey-form-v9.xlsx

**Comment by shankari** [comment]
@JGreenlee for the record, we might also have overnight trips (e.g. redeye flight), so this is not solely a place issue
To me, that also argues for Option 1 and not Option 2; with Option 2, we would also have to change the trip cards appropriately

**Comment by JGreenlee** [comment]
Yes, option 1 is what I will work on implementing (especially now considering the possibility of overnight trips and overnight untracked)

**Comment by MaliheTabasi** [comment]
> On the survey, we can use ["Date & Time" question types instead of separate "Date" and "Time" questions](https://support.kobotoolbox.org/date_time.html#appearance-of-date-and-time-question-types-in-web-forms-and-kobocollect). This means 2 questions instead of 4, and should feel less clunky from a UX perspective.

@JGreenlee  moreover, to deal with UI clutter, I suggest that we can show this date and time form of survey only on place or trips that are expanding overnights. For place and trips that are expanding within a day, we can even remove the date input and only let user selects start and end time. This will also prevent user to input invalid dates in this case.

**Comment by MaliheTabasi** [comment]
> My current thoughts on the design is that we should definitely do both of these:
> 
> * we should not have two places; that will just be too confusing
> * we should show the date in addition to the time for activities that are associated with an overnight place e.g. as in
>   ![Place](https://user-images.githubusercontent.com/49550315/228992182-a08f92cf-f64b-4667-ae75-7e8265ac7fd5.jpg)
> 
> wrt actually representing overnight activities by adding an end date, what do you think?

@shankari  I suggest for places that trips that expand overnights, we display date&time instead of only time on top and bottom of the cards as I have already suggested as can be seen in the image in your comment.

**Comment by MaliheTabasi** [comment]
@shankari  Could you please let me how long you do think implementing this will take? Because we cannot start data collection without having the ability to enter activities for the whole day. In the latest version, 1.2.5, there is no way to insert activities before the first trip in a day.

**Comment by JGreenlee** [comment]
>I suggest that we can show this date and time form of survey only on place or trips that are expanding overnights. For place and trips that are expanding within a day, we can even remove the date input and only let user selects start and end time. This will also prevent user to input invalid dates in this case.

I'll look into this, but I don't think it's feasible without having 2 separate versions of the survey, and I don't think we want to require that. The date will at least be prefilled and not need adjusting by the user, but even this is already pushing the boundaries of what Enketo supports.

**Comment by MaliheTabasi** [comment]
> > I suggest that we can show this date and time form of survey only on place or trips that are expanding overnights. For place and trips that are expanding within a day, we can even remove the date input and only let user selects start and end time. This will also prevent user to input invalid dates in this case.
> 
> I'll look into this, but I don't think it's feasible without having 2 separate versions of the survey, and I don't think we want to require that. The date will at least be prefilled and not need adjusting by the user, but even this is already pushing the boundaries of what Enketo supports.

@JGreenlee It's totally fine. In that case, you might need to set some validation on the dates that user enters.

**Comment by shankari** [comment]
> Could you please let me how long do you think implementing this will take? Because the current version,1.2.5, is not ready for time-use data collection. As we cannot start data collection without having the ability to enter activities for the whole day. In the latest version, 1.2.5, there is no way to insert activities before the first trip in a day.

@MaliheTabasi displaying the "first place" in a timeline is not tracked in this issue - this is tracking the design of overnight places. Displaying the "first place" is tracked in https://github.com/e-mission/e-mission-docs/issues/884

As I indicated in the email to Taha, it will be in the first point release. I will send out the proposed timeline for the point release via email to you and Taha for visibility.

**Comment by shankari** [comment]
Although I intended that https://github.com/e-mission/e-mission-phone/pull/957 would be a hack, as indicated by the 💩 (https://gitmoji.dev/) I think that we might actually want to switch to it, not just for places but also for trips. We can then remove the date from the trip/place body and better support overnight trips/trips with different time zones.

@JGreenlee @MaliheTabasi thoughts?

**Comment by JGreenlee** [comment]
I would suggest that the date *only* shows on the badges of overnight cards (trip/place/untracked), and that we leave non-overnight cards how they are. This will reduce clutter.

I think the use of `parseZone()` was necessary. By default, Moment will convert to the local timezone; using `parseZone()` prevents that and keeps it in the fixed timezone of the string.

**Comment by shankari** [comment]
> I think the use of parseZone() was necessary. By default, Moment will convert to the local timezone; using parseZone() prevents that and keeps it in the fixed timezone of the string.

Agreed. But the formatted date code (see above) does not use `parseZone`!!

**Comment by shankari** [comment]
> I would suggest that the date only shows on the badges of overnight cards (trip/place/untracked), and that we leave non-overnight cards how they are. This will reduce clutter.

So overnight cards will have the date along with the time, but non-overnight cards will have the date in the card body? Won't that be inconsistent/confusing? Once you train people's eyes to navigate the screen in a certain way, it seems like you want to stick to it.

**Comment by JGreenlee** [comment]
> > I suggest that we can show this date and time form of survey only on place or trips that are expanding overnights. For place and trips that are expanding within a day, we can even remove the date input and only let user selects start and end time. This will also prevent user to input invalid dates in this case.
> 
> I'll look into this, but I don't think it's feasible without having 2 separate versions of the survey, and I don't think we want to require that. The date will at least be prefilled and not need adjusting by the user, but even this is already pushing the boundaries of what Enketo supports.

For overnight activities, I will have a working candidate by EOD and I can try out the above.

I am having issues with Enketo, as the `datetime` time actually works quite differently than `date` and `time` individually. It does not work with pre-filing fields in the same way, and I feel like I am putting a hack on top of another hack.
It's also not very elegant in the way the input works.

My next idea is to have 4 separate questions, but show the corresponding date and time inputs side-by-side so it is not so cluttered.

**Comment by JGreenlee** [comment]
> > I would suggest that the date only shows on the badges of overnight cards (trip/place/untracked), and that we leave non-overnight cards how they are. This will reduce clutter.
> 
> So overnight cards will have the date along with the time, but non-overnight cards will have the date in the card body? Won't that be inconsistent/confusing? Once you train people's eyes to navigate the screen in a certain way, it seems like you want to stick to it.

I was thinking about that, but I think we can keep it consistent.
I would still leave the date in the card body and show the range of days if it spans multiple. This may be slightly redundant but clearer in my opinion.
Then on the badges, I would put the start/end date on separate line from the time (for aesthetics and visual hierarchy)

**Comment by shankari** [comment]
ok I trust your judgement on design, which is almost certainly better than mine

**Comment by shankari** [comment]
Merged, closing issue
