### ISSUE TITLE
Remove filters in case we are showing trip additions

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-docs#894]
Since the trip and the associated place(s) are linked in the composite trip, if we have the filtering in place, then when the labels for a trip are filled in, the trip and the associated place disappears from the "main" screen, making it harder to add activities.
We might want to disable filtering if trip or place additions are enabled in the config.

**Comment by shankari** [comment]
This seems even more important now that we have the first place code in place.
Without this, if trips have been labeled, I end up with back to place places in "To Label" but not in "All Trips".

| Back to back places | One place | The other place |
|--------|----------|--------|
|  ![Screenshot_20230508-084553](https://user-images.githubusercontent.com/2423263/236870147-bb2d4f87-dd2c-45cc-8d39-c553d4a1a1f1.png) | ![Screenshot_20230508-084737](https://user-images.githubusercontent.com/2423263/236870140-93069dbe-64b4-421c-97b8-adeaeae5b868.png) | ![Screenshot_20230508-084828](https://user-images.githubusercontent.com/2423263/236870134-eb497462-9475-4c65-b6c6-9d779eecea05.png) |

**Comment by JGreenlee** [comment]
@shankari By "disable filtering," do you mean we'd only use the "All trips" view, and the dropdown would not need to be displayed?

**Comment by shankari** [comment]
> By "disable filtering," do you mean we'd only use the "All trips" view, and the dropdown would not need to be displayed?

Correct. Because if we filter, then once a trip is labeled, then the related place also disappears, but users may want to keep labeling the place...
