### ISSUE TITLE
✨ Have the default start of an activity be the end of the previous activity instead of the start of the timelineEntry

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-docs#901]
Since we want to make the common case easier.
The common case is a sequence of activities, one starting from the end of the other.

**Comment by shankari** [comment]
@JGreenlee would be good to get this done before the next point release as well.
If you can't get to it, I might try.
If we don't get it done by the May 12, though, it will have to be in the next release.

**Comment by JGreenlee** [comment]
https://github.com/e-mission/e-mission-phone/pull/971

**Comment by shankari** [comment]
Fixed in https://github.com/e-mission/e-mission-phone/pull/971
