### ISSUE TITLE
🚸 Figure out how to remove untracked time from "To Label"

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-docs#907]
It is annoying that it still sticks around even after all the trips are labeled.

Report from a program admin

> XXX sent me the below image of the trips he’s not able to label. Ideas?

@JGreenlee can you handle this?

**Comment by JGreenlee** [comment]
Sure, but I'm not clear yet on what the expected behavior should be.

Do we want Untracked Time to only appear in the "All Trips" view?

Or do we want something more sophisticated, like for Untracked Time to only appear when the trips before and after it are showing?

**Comment by shankari** [comment]
I am not 100% sure either. I think basically people want some way to remove the untracked time so that they can get to "to label zero".

Some options are:
- allow people to mark them as "seen" and don't show "seen" untracked time in "to label"
- show untracked time only when trips before and after are showing
- show untracked time only in All Trips

My personal favorite is (2), but not sure if it is too complicated to implement.

**Comment by shankari** [comment]
Fixed in https://github.com/e-mission/e-mission-phone/pull/983/commits/f39affde37701b187ac80d8879ce318540b76881
