### ISSUE TITLE
🚸 last place is not recognized as multi-day even if it is

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-docs#908]
Had my daughter do some testing on staging, and we ran into this issue.
If the last place spans overnight (e.g. came home at 10pm, trying to fill in activities the next morning at 9am, including sleeping from 11pm to 8am), then, since we don't have an end time, the activity is not recognized as overnight, so it doesn't open the date-time version of the survey.

And if the user puts in 11pm to 8am (without a specified day), it goes to the previous night.

**Comment by JGreenlee** [comment]
Ah yeah, we should really only hide the date inputs if we **know** it's a single day trip.
This is easy to fix.

**Comment by shankari** [comment]
Fixed in https://github.com/e-mission/e-mission-phone/pull/983/commits/19a13fbd874245ef91fa533f6d87d6fd4a0b4837
