### ISSUE TITLE
🚸 "logout" aka pink button no longer works to login with another opcode

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-docs#911]
Since, in the intro flow, we now use the pre-cached token from the config. We will either have:
- to go back all the way to the join page
- make the join page part of intro, or
- accept that logout just restarts onboarding, since we don't actually want to be able to login with a different token to the same server.

**Comment by shankari** [comment]
>  When a new code was pasted, it would seem to work, but the server configuration would still point to the old one so nothing would load correctly. I spent some time looking but couldn't figure out why.

I bet it is because we store the token in the dynamic config (the `joined`). And we don't currently rewrite the dynamic config. I bet it will start working if you delete the stored dynamic config before going back to the app join page

**Comment by JGreenlee** [comment]
Incorporated into https://github.com/e-mission/e-mission-phone/pull/979

This make it a LOT easier to test out different configurations

**Comment by shankari** [comment]
Fixed in https://github.com/e-mission/e-mission-phone/pull/983/commits/6557c847342fc86de49977b09b57ef06dcc83aa3
https://github.com/e-mission/e-mission-phone/pull/983/commits/c8a695fbe34e99895fe7dc7d3960c8aab9d2556f
and
https://github.com/e-mission/e-mission-phone/pull/983/commits/e7c38cd57a8eb400e9169d58058e9ddf27da2889
