### ISSUE TITLE
🚸 Tell users which reminderScheme they are enrolled in?

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-docs#913]
Pulling this out into a separate issue because there are a lot of small changes for the point release and I don't want to lose track of them

> The one other fit and finish change we may want to do for this (can wait until the next point release) is to show users which group they are in. Unless we are worried that it will bias the results somehow to do that.

Should check with the social scientists on whether this is legit, and then we can figure out how to show it.

**Comment by JGreenlee** [comment]
I don't think we should say anything that alludes to the nature of the experiment (eg. "You are in Group A, which is receiving the most frequent notifications"), but an indicator that plainly states the schedule (eg. "You are receiving weekly notifications") seems benign.

It's good for participants to be blind to their group assignment, but it's not like they can't observe the cadence of notifications anyway.

**Comment by shankari** [comment]
Agreed that https://github.com/e-mission/e-mission-phone/pull/992 also fixes this in a somewhat subtle way 👍
