### ISSUE TITLE
Display, in the developer options, when the next notification will be?

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-docs#917]
As part of https://github.com/e-mission/e-mission-docs/issues/900 we made the notification schedules be configurable.
So the dynamic config has `reminderSchemes` and they tell you for what range of time, how often the notification should happen.
We have tested this on an android physical phone, and it has worked.
But we recently received a report from a tester that they did not receive any notifications.

To debug this, it would be helpful to show the currently scheduled notifications somewhere in the Profile -> Developer Zone.
We already do read the list of scheduled notifications https://github.com/e-mission/e-mission-phone/blob/e51810937527c0efcd4ec2c5b0fbf0d2c97c8a02/www/js/splash/notifScheduler.js#L61

Easy change:
- just expand `debugGetScheduled` to print out all the notifications (including the dates) on the console

Nicer change:
- display that as a table or a list (even if somewhat ugly looking) in the UI

This will fix #913 as well, but in a less "in your face" way.

**Comment by JGreenlee** [comment]
This is being included in Abby's https://github.com/e-mission/e-mission-phone/pull/992 (but currently a draft PR)

**Comment by Abby-Wheelis** [comment]
> A nice table is being included in Abby's [e-mission/e-mission-phone#992](https://github.com/e-mission/e-mission-phone/pull/992) (but currently a draft PR)

That PR has been merged now, the schedule is shown is the developer zone dropdown in settings, and looks like this:
<img width="400" alt="Screenshot 2023-06-13 at 2 20 28 PM" src="https://github.com/e-mission/e-mission-docs/assets/54848919/7ac9e05f-7bae-4a7a-a561-d5aee9c624d3">

**Comment by shankari** [comment]
Closing this since https://github.com/e-mission/e-mission-phone/pull/992 has been merged
