### ISSUE TITLE
🤔 What library to use for in-app graphs?

### ISSUE THREAD

**Issue by JGreenlee** [e-mission/e-mission-docs#918]
Currently, there are a few places in the app that graphs are displayed (the speed graph on the diary details page and the "Charts" in Dashboard). This has been using [nvd3](https://github.com/novus/nvd3) (which is no longer maintained). `nvd3` is basically just a wrapper around D3 (the well-known JS visualization library).

Meanwhile, we are migrating into React, with the eventual goal of having a React Native app. If we stick with a web-based library, we will have to wrap it in a webview at some point.

I think there are 3 main approaches we can take:

1) Use D3.js, without nvd3
-- Would need to be wrapped it in a WebView when we go fully native
2) Switch to Plotly.js
-- Maybe this is a good idea to be consistent with the admin dashboard, which I believe is using Plotly.py
-- This also would need to be wrapped in a WebView for native rendering, but [there exist tools to aid with that](https://github.com/rynobax/react-native-plotly)
3) Find a React Native charts/graphing library
-- I haven't found much in this area
-- There are RN charting libraries (e.g. [react-native-chart-kit](https://github.com/indiespirit/react-native-chart-kit)), but they are surprisingly limited in comparison to D3 or Plotly

**Comment by JGreenlee** [comment]
Looking forward, the option I am most inclined to is `Plotly.js`, since I think it is not too uncommon to embed in native apps, and it would support more complex visualizations down the road if that's ever something we want.

However if we want a quicker, short term solution, the easiest substitute for `nvd3` is probably just plain D3.

**Comment by shankari** [comment]
I saw this yesterday and I am pretty torn. I like the idea of standardizing on the plotly library for both the admin dashboard and the phone app, but I am also concerned that then we don't have the full nativeness, and that the webview solution may look clunky/non-seamless.

I know we will need to use a webview for the survey, but the survey is always launched as a separate screen anyway, so I am not worried about it looking clunky. But the charts/graphs will be shown inline (at least in some situations), and when we move to full react native, I am concerned that it will look visually more ugly.

For the full native code, there are other options like
https://github.com/wuxudong/react-native-charts-wrapper
which uses pure native components and seems reasonably complete

We can't do super complex charts on the small form factor of the phone anyway, so basic bar/line/pie charts seem like they should be enough.

**Comment by shankari** [comment]
I'm assuming we can't use react-native-charts-wrapper yet, though, because we are still on cordova.
Given that, I would go with the plotly version.

However, we should definitely create our own wrapper over the chart component instead of using it directly.
This should make it easier to migrate between charting libraries as needed.

I briefly took a look at the three candidates - plotly, react-native-chart-kit and react-native-charts-wrapper and how they represented the data that they need to use, and it is not that different. As long as we have isolated the code into the same component, it seems like we should be able to switch between them fairly easily as we modify the codebase.

**Comment by JGreenlee** [comment]
>I'm assuming we can't use react-native-charts-wrapper yet, though, because we are still on cordova.

Correct; that one is native-only and doesn't support RN Web.

`react-native-chart-kit` does support both Native and Web. I experimented with it a bit, but I found it quite limited. It is challenging to graph any data where points aren't evenly spaced along the X axis. https://github.com/indiespirit/react-native-chart-kit/issues/686#issue-1712875376
Thus, it's best for categorical data, bar charts and not much else.

>I am also concerned that then we don't have the full nativeness, and that the webview solution may look clunky/non-seamless.
...
>However, we should definitely create our own wrapper over the chart component instead of using it directly.

Someone has already made a wrapper around Plotly to work with React Native.
https://github.com/rynobax/react-native-plotly
You can also see what they had to say about it: https://dev.to/rynobax_7/using-plotly-to-draw-charts-in-react-native-58cc

They have a demo (I forked it and upgraded the version so that we can see it working)
https://snack.expo.dev/@jgreenlee/react-native-plotly-demo?platform=ios
I was able to test this on my phone and it seems to integrate pretty well within its React Native context.

It's smooth to me, and the author said the graphs outperform the native libraries; the one drawback they mentioned is that Plotly graphs take 1-2 seconds to initialize. I'm pretty sure we could work around that (either init graphs in the background before they're needed; or display some 'reveal' animation during init)

**Comment by JGreenlee** [comment]
Either way, sounds like the way forward for right now is to use Plotly.

And when we go native, we'll reevaluate for performance/sleekness

**Comment by shankari** [comment]
> Someone has already made a wrapper around Plotly to work with React Native.

Right, I saw that. However, I suggest that we create our own wrapper for charting and use it instead of using the react-native-plotly directly. Then, we can change all the plots by changing that wrapper. Similar to the new leafletview wrapper that you created.

The reason I say this is that chart/plot libraries are a bit like datepickers - there are a ton of them with slightly different functionality/look-and-feel, and there are new ones that show up periodically and become the New Hot version. Having a module that abstracts the functionality and provides a unified wrapper for our codebase will allow us to swap chart libraries much more easily down the road.

**Comment by JGreenlee** [comment]
After some discussion about the design of the Dashboard, I am reconsidering whether Plotly.js is the best option here.

Plotly has a fairly rich ecosystem and undoubtedly would support any type of chart we wanted.
However, as I am playing around with embedding Plotly in the Dashboard, I am finding that it is not super mobile-friendly. It doesn't support animations without some extra trickery, and the interactivity it does have is definitely geared towards desktop users.

And it seems that although Plotly is great for data viz, it's not necessarily optimized for user interface. You'd use Plotly for an analysis project and include charts from Plotly in your report, but you wouldn't necessarily display Plotly charts to an end user who's just navigating around your app.

Given this, I'm looking at `Chart.js` as an alternative. It can create largely the same types of plots as Plotly, but is more optimized for mobile users. And, from a UI perspective, it seems to be a very sleek and intuitive interface, and will be easier to style in the context of our app.

And in consideration for the future of the OpenPATH, I will definitely put a wrapper around it.

As Shankari said:
> there are new ones that show up periodically and become the New Hot version

Presently, `Chart.js` is that New Hot version. But it could be something different in 5 years. So I'll try to set things up to be generic and modular.

**Comment by JGreenlee** [comment]
Chart.JS is working pretty nicely. I re-implemented the original Chart tab bar charts (I put the axis horizontal instead of vertical, though).
I know this is about to be redesigned anyway, but I think it's best to do this temporarily so that we can get a release out to production without a broken Charts tab.

<img src=https://github.com/e-mission/e-mission-docs/assets/15843932/773da21a-6deb-41a3-b8b9-987dc67753e3 width=350>
