### ISSUE TITLE
🚑 Yellow labels not showing up *only* on the label screen

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-docs#921]
| Diary screen | Label screen
|-------|-------|
|  ![simulator_screenshot_9FC83342-B883-43DD-8856-E428F9A45C68](https://github.com/e-mission/e-mission-docs/assets/2423263/491b7c96-6ffe-4cee-ad87-3abad6a59906)  |  ![simulator_screenshot_CBAF56F1-64C0-4671-9CAA-9BD3D7E4ADD1](https://github.com/e-mission/e-mission-docs/assets/2423263/1d354086-de5e-4333-8350-6ba8387155be) |

@JGreenlee This is a P0 that we should fix before the unification of diary and label screens. It would be bad if we suddenly started showing fewer yellow labels.

**Comment by JGreenlee** [comment]
Is this not the same as https://github.com/e-mission/e-mission-docs/issues/903?

Is this issue being seen, even on a release that includes e-mission/e-mission-phone#972 ?

**Comment by shankari** [comment]
@JGreenlee yup, I double checked the phone version and it was the latest.
The screenshots above are from my devapp, synced to 1b2611a83184e6b712bef69c40c697a864efd370, from Jun 1
And it is not that we don't see yellow labels at all; it is that we don't see *some* yellow labels.

| Next trip has yellow labels | And so does the next one |
|-------|-------|
| ![simulator_screenshot_07CCA001-C8A4-4430-A3AF-33A708FE0726](https://github.com/e-mission/e-mission-docs/assets/2423263/df75d552-5f69-4f0a-bcb7-562a5dc989dd) | ![simulator_screenshot_7B3D5503-F2B9-4FB7-9D52-3FCE1F23B64F](https://github.com/e-mission/e-mission-docs/assets/2423263/fa722f97-c8ba-4e9d-818c-84cc7495f41e) |

**Comment by shankari** [comment]
I'm debugging this now and will share the user opcode before going to sleep in case you have time to investigate tomorrow

**Comment by shankari** [comment]
This may be an error with the diary screen and not the label screen (which is fine; we can mark this as wontfix).
Even before putting in breakpoints, I notice that the diary screen always seems to have the same yellow labels, which is a bit suspicious.

| All walk, pick up drop off | Except for the last one? | 
|-----|------|
| ![simulator_screenshot_64F97568-0C72-4555-88F4-7C88A72D9BF3](https://github.com/e-mission/e-mission-docs/assets/2423263/0d833de3-2be1-4e4e-bce5-675046ee943d) | ![simulator_screenshot_9B83FAD0-9F63-4EC6-AB40-61D2C49632A3](https://github.com/e-mission/e-mission-docs/assets/2423263/cd5105a1-503c-429e-b132-a63561f674e7) |
| ![simulator_screenshot_4EA12482-E0B4-40B1-A860-DA588197C123](https://github.com/e-mission/e-mission-docs/assets/2423263/9d7cfbdb-eed8-4426-84c7-f537ccae7215) | ![simulator_screenshot_8CB34944-152A-4E29-843F-30B04D1E6904](https://github.com/e-mission/e-mission-docs/assets/2423263/2f767ad7-eb02-4667-aaa1-1a4b3563e0bb) |

**Comment by shankari** [comment]
And here it is again. Let's focus on this set of trips because:
1. It is fairly recent
2. one of the label screen trips actually has a yellow label
3. The first trip is the walk + pickup-dropoff that we see earlier

| Diary | Label |
|------|------|
| ![simulator_screenshot_4CC0D031-0997-42E6-8706-9750B2D8873F](https://github.com/e-mission/e-mission-docs/assets/2423263/47cc4edc-c9e4-46e1-bc78-668b9ca0a157) | ![simulator_screenshot_5A4E3A44-D0F0-4840-AEC1-D47540BD8816](https://github.com/e-mission/e-mission-docs/assets/2423263/9aeb3937-3a24-4a54-89c5-fc895f33b95f) |

**Comment by shankari** [comment]
Here's the trip that we are focusing on (5:35 to 6:24). It does have several inferred labels, but the `finalInference` is set to `{}` and although a walk + pickup/dropoff entry exists, it does not have the highest p value. Its p value is 0.04380024762690879 while the highest p values are 0.23828642179116796 (walk + home) and 0.23199422203879488 (e_car_shared_ride + pick_drop_person).

I wonder if those two are being combined somehow to generate the walk+pick_drop_off_person in the diary...

<img width="866" alt="Screenshot 2023-06-22 at 6 58 21 AM" src="https://github.com/e-mission/e-mission-docs/assets/2423263/47b710a6-aee6-4a0a-ab66-a34aab758dd7">

**Comment by shankari** [comment]
`finalInference` is not set on the server.

```
$ grep -r finalInference emission/
emission//analysis/configs/expectation_notification_config.py:    # If we were doing this on the phone, we would use finalInference.
```

Filled in on the phone in `  mls.inferFinalLabels = function(trip) {`
So maybe it is just not filled in yet

**Comment by shankari** [comment]
`totalCertainty` is 0.9900000000000001

We look at the labels separately, so walking is really the most probable

<img width="216" alt="Screenshot 2023-06-22 at 7 43 37 AM" src="https://github.com/e-mission/e-mission-docs/assets/2423263/a5fe8f20-cf5d-484d-9644-16eb82bd8399">

Max label is indeed `walk`

<img width="190" alt="Screenshot 2023-06-22 at 7 45 46 AM" src="https://github.com/e-mission/e-mission-docs/assets/2423263/2362b47a-6f26-4448-b053-81eca3a9d5f1">

But it is just below the confidence threshold (0.55), so it is not displayed

```
        // Display a label as red if its most probable inferred value has a probability less than or equal to the trip's confidence_threshold
        // Fails safe if confidence_threshold doesn't exist
        if (max.p <= trip.confidence_threshold) max.labelValue = undefined;
```

Ok, so that makes sense.

Let's check that for purpose as well...

<img width="248" alt="Screenshot 2023-06-22 at 7 51 41 AM" src="https://github.com/e-mission/e-mission-docs/assets/2423263/a502a46d-b460-489c-97b5-22000bc63ada">

Again, `pick_drop_person` is the max, but is below the confidence threshold.

For the next trip, where mode is non-yellow but purpose is yellow, the mode is again below the threshold but the purpose is above. So the label screen seems to be working properly

| Mode | Purpose |
|-------|-------|
| <img width="248" alt="Screenshot 2023-06-22 at 7 54 09 AM" src="https://github.com/e-mission/e-mission-docs/assets/2423263/12625561-fe59-4d72-bdc9-64527abe3ae9"> | <img width="248" alt="Screenshot 2023-06-22 at 7 54 30 AM" src="https://github.com/e-mission/e-mission-docs/assets/2423263/95dbefec-6494-4f68-b52c-91ac82168bd4"> |

**Comment by shankari** [comment]
Yup! While loading the trip in the diary screen, there is no `confidenceThreshold` set

<img width="697" alt="Screenshot 2023-06-22 at 8 07 28 AM" src="https://github.com/e-mission/e-mission-docs/assets/2423263/81b27009-58ce-4c06-8713-19d58af9d0ab">


The max values are still the same, but because `trip.confidenceThreshold` is undefined, we don't filter them out

| Mode | Purpose |
|-------|--------|
| <img width="199" alt="Screenshot 2023-06-22 at 8 08 27 AM" src="https://github.com/e-mission/e-mission-docs/assets/2423263/f7e6b675-2dcd-4f2b-a87a-b4cdd48145dc"> | <img width="246" alt="Screenshot 2023-06-22 at 8 08 48 AM" src="https://github.com/e-mission/e-mission-docs/assets/2423263/21d3dfd9-4bb9-4938-aa5f-4086deeb4328"> |

**Comment by shankari** [comment]
These kinds of subtle regressions are the reason that we really need better testing.
However, since this is an error in the diary screen, and we are going to remove it soon, I will close this with `wontfix`
