### ISSUE TITLE
Dynamically configure language options in join page

### ISSUE THREAD

**Issue by Abby-Wheelis** [e-mission/e-mission-docs#931]
As OpenPath expands, there is a need to support more languages, and particularly to support a custom set of languages. With a list of the languages ISO codes and their names, a custom dropdown can be configured on the join page. There are two ways that getting this data could be accomplished:

### Option 1 (explicit) - add a key to the config files with list of supported languages
pros:

- providing the languages supported in config files makes it very clear what languages are intended to be supported
- can specify iso -> language name mapping in the config file itself

cons: 

- requires validation: if the languages listed as supported and the languages actually supported (translated text provided) differ, this would create issues. Therefore, validation would be required to ensure that mismatch is handled -> depending on rates of user error, this could cause frequent issues. 
- older config files don't have this [easily fixable through setting up en and es as language options when none given]

### Option 2 (implicit) - use the keys to the translations already in the configs
pros:

- prevents mismatch through only one source of truth

cons: 

- mapping from ISO code to language name (in that language) would require external resource. This library may help: [https://github.com/dejurin/language-name-map](https://github.com/dejurin/language-name-map), as it includes the native names of languages, which are most useful for display

I believe the implicit method is the better choice because of the mismatched truth issue. While config file creators might not make these mistakes often, they can be prevented entirely by only relying on one source of languages supported. Finding a mapping of ISO code to language names is not too big a hurdle, especially since this is a common need and there are some libraries we can choose from. 

In terms of changing our minds later, this also seems the better choice. Changing over to explicit would require adding to the config file and creating a validation method. However, changing over to implicit, should we choose the explicit route, would leave unused information in the config file, which could create confusion around supported languages, and it would also require implementation of the ISO mapping at that time.

I’m thinking that the implicit solution is worth the trouble of implementing a mapping library, as it avoids the need for validation and creation of errors through truth mismatch. The implicit method also relies on data that is already a part of the config file, and therefore limits changes to one place (join page) rather than two (join page and future configs).

**Comment by JGreenlee** [comment]
For the name of the language itself, why can't we just have it as a required property at the root level of that language's JSON file?

For example, Spanish translations currently live in `es.json`.

Why not just add some field like `_languageName` at the top, like this?
```json
{
    "_languageName": "Español",
    ...
    ...
```

**Comment by Abby-Wheelis** [comment]
That makes a lot of sense, and would not be difficult to maintain, since it would only be introduced once per language. Thank you for pointing that route out!

**Comment by shankari** [comment]
@JGreenlee since the join page is also dynamic, there are two locations for the languages - the translation of the join page template and the translations of the "text to fill in" in the dynamic config. We were thinking of specifying the text in the dynamic config, but you are right that it could also be in the template!

@Abby-Wheelis I agree with you on the implicit mapping, and the suggestion of putting the text into the language template makes it even better!

**Comment by Abby-Wheelis** [comment]
I took @JGreenlee's suggestion of placing the text in the language template, and have everything working! However, I have reservations about the timing of the calls in relation to the two promises happening on the Join page. I have more details and code in the PR that mentioned this issue, and I think having more eyes on the issue would be good before I feel confident with this solution to a dynamic language menu.

**Comment by shankari** [comment]
Largely fixed in https://github.com/e-mission/nrel-openpath-join-page/pull/18
Will leave open briefly for polishing changes:
- [ ] Regenerate screenshot after calories i18n is fixed
- [ ] Polish code by potentially removing `langSel` `val` set before it has any entries

**Comment by Abby-Wheelis** [comment]
I figured out the cause of the wrong i18n text in the screenshot with the cookies - the way those keys are configured in en.json and the other files (es.json, lo.json...) are different in `framework_migration_prep` as of [use i18next instead of angular translate](https://github.com/e-mission/e-mission-phone/commit/14e8a67866ccd624070728ff6d55d6b362542ff3) -- so the rest of the i18n files will need to be updated eventually to have those new keys. With `master_for_platform`, the keys still match, so I might be able to get a screenshot with the right text using that branch.

**Comment by Abby-Wheelis** [comment]
I can do that! And thank you! When is the release candidate, so I know when to target being done? 

I can make sure to take care of any changes made to the `en i18n` content for `es` and `lo`, should I work on `fr` and `it` as well or are those maintained separately

**Comment by shankari** [comment]
Depends on when @JGreenlee gets done. But I would say tentatively, tonight or tomorrow.
`es` and `lo` are sufficient for now

**Comment by JGreenlee** [comment]
If we need Lao translations in this RC, we have to do a little more after [#1000](https://github.com/e-mission/e-mission-phone/pull/1000) is merged

@Abby-Wheelis There are about a dozen Lao translations we will need for `react-native-paper-dates`, find them listed here: https://web-ridge.github.io/react-native-paper-dates/docs/intro#custom
If you want to add those translations, I'll figure out how to register them

**Comment by shankari** [comment]
Yes, we need Lao translations in this RC

**Comment by JGreenlee** [comment]
The RN Paper Dates translations are not critical.

The day / month names are already internationalized using the underlying Intl API in JS.
It's just things in the datepicker like the "Save" button and "Select a day" text that would be missing translations

**Comment by Abby-Wheelis** [comment]
I was able to add the react native paper dates for lo, the few new keys raised by the label screen in lo, and address the issue with the food equivalencies in `e-mission-translate`. I was then able to replace the screenshot in `nrel-openpath-join-page`, so I think everything might be good to go here now!

**Comment by shankari** [comment]
Thanks @Abby-Wheelis. Very productive!
I'm closing this issue now.

**Comment by JGreenlee** [comment]
Since Abby set up the translations nicely and they are already merged, it was easy to register them. I just included the necessary change as a part of [#1000](https://github.com/e-mission/e-mission-phone/pull/1000)
