### ISSUE TITLE
💄 Finish rewriting diary/service implementation

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-docs#932]
Tracking pending issues from https://github.com/e-mission/e-mission-phone/pull/1000

- [ ] Memoize all `display_` properties so they are not recomputed every time (https://github.com/e-mission/e-mission-phone/pull/1000#discussion_r1255004569, https://github.com/e-mission/e-mission-phone/pull/1000#discussion_r1255020461)
- [ ] Unify the imperial computations (km/miles) https://github.com/e-mission/e-mission-phone/pull/1000#discussion_r1255038689
- [ ] Add translation for paper dates https://github.com/e-mission/e-mission-phone/pull/1000#discussion_r1255052905

**Comment by JGreenlee** [comment]
- [ ] Rename variables to distinguish `loading` vs `isLoading` in LabelTab https://github.com/e-mission/e-mission-phone/pull/1000/files#r1257746004

**Comment by shankari** [comment]
- [ ] Display error if things go wrong during address loading https://github.com/e-mission/e-mission-phone/pull/1000#discussion_r1259094242

**Comment by shankari** [comment]
Feedback from @mRaffill
- Make the symbols on the map and the origin/destination text be the same
- In the enketo survey, for multiple selection, the check mark still doesn't show up as a check mark - it is blank even when selected
- walk and car and bus are both shades of red which is a little confusing; kind of OK for car and bus because they are both motorized, but bad for walk
    - also seems to have some significance like bike is good because it is green and walk is bad because it is a shade of red
- trip split is missing in the detail screen if it is unimodal; bothered me because it wasn't consistent
- I like the calendar now; would be nice to have a way to jump to today; if there is, it is not very clear right now

| Multimodal trip | Unimodal trip |
|-----|-----|
|  ![Image](https://github.com/e-mission/e-mission-docs/assets/2423263/395a5c11-7813-4a39-94e2-a06f72016fc8) | ![Image](https://github.com/e-mission/e-mission-docs/assets/2423263/11c7d090-506c-49e6-9bc7-6079ec60d7bb) |

**Comment by shankari** [comment]
**Time use only**: so not a blocker to push NREL OpenPATH to production

|  Activities are now getting duplicated multiple times (I added three activities, ended up with 6 (3 + 2 + 1)  |  No place between draft trips         |
|---------|--------|
| ![Image](https://github.com/e-mission/e-mission-docs/assets/2423263/05c4d038-808b-4c95-8872-f2c5b31765ac) | ![Image](https://github.com/e-mission/e-mission-docs/assets/2423263/f2adcb02-c5a3-44d6-9fa2-1109cddb6d80) |

**Comment by shankari** [comment]
Sharing QR code from the profile screen (Profile -> My OPCode -> Share button) does not do anything.

**Comment by Abby-Wheelis** [comment]
I'm seeing errors on my dashboard in both Android and iPhone testing both are popup alerts that clear when I tap ok that happen when I "refresh" the dashboard screen. After clearing the error, the all the cards have not information in them.

Android error reads: "Error loading aggregate data, averages not avaliable" "cannot read property of undefined (reading 'drove_alone') TypeError: Cannot read properties of undefined (reading 'drove_alone') an o.getMet ... at e.fillCalorieAggVals ... at e.fillAggregateVals ..." 

iPhone error reads: "Error loading aggregate data, averages not avaliable" "undefined is not an object (evaluating 'i[e]') ... promiseReactionJob@[native code]

**Comment by shankari** [comment]
@Abby-Wheelis are you able to reproduce this in the emulator?

**Comment by Abby-Wheelis** [comment]
@shankari no, not yet, everything seems fine in the emulator (using a current branch of `framework_migration_prep`)

**Comment by shankari** [comment]
> no, not yet, everything seems fine in the emulator

And this logging in with your test opcode to the staging environment?

**Comment by shankari** [comment]
I confirmed that, on the emulator, logging in to a test stage user, I don't see any error

**Comment by JGreenlee** [comment]
> * also seems to have some significance like bike is good because it is green and walk is bad because it is a shade of red

"Walk" is supposed to be "brown" but I can see how it looks reddish and thus perceived as 'bad'. I have not changed the colors from what they were in the diary tab, but I do think we could revise the color coding to be more semantic. I might suggest something like this:

"Bad" highest-emission modes:
- Car / In Vehicle - **red**
- Plane - **orange**

"Good" emission-free modes:
- Bicycle - **green**
- Walk / On Foot - **blue**

"So-so" modes:
- Bus - **purple/magenta**
- Subway, Train, or other Rail - **purple/periwinkle**
- Ferry or other 'nonstandard' mode - **yellow**

Unprocessed or Unknown - **grey**

<hr>

Would that be loosely accurate enough?

**Comment by JGreenlee** [comment]
### Sometimes dates are wrong

If you take a hard look at the timestamps of this trip and place, you realize that the trip should have been marked as only July 1, while the place was an overnight stay between July 1 and July 2.
The timestamps are right, but the determination of which days the trip/place fell on is wrong. This probably has to do with timezones.

<img src=https://github.com/e-mission/e-mission-docs/assets/15843932/24a661df-3a0a-4fa8-a7c6-faa4053bb4c2 width=360>

**Comment by Abby-Wheelis** [comment]
> Sharing QR code from the profile screen (Profile -> My OPCode -> Share button) does not do anything.

I just ran into this working with the profile migrations! I think it's probably something that broke when the QrCode was migrated to a React component. It seems the share code for the QR required going and getting the link to the code from the element `const c = document.getElementsByClassName('qrcode-link');
        const cbase64 = c[0].getAttribute('href');` which is no longer the way that element is displayed. If that link is the same as the "tokenURL" then something like this : `const cbase64 = "emission://login_token?token="+settings?.auth?.opcode;`might be a good replacement? I've tested in the devapp but it's a little hard to tell if things share properly there.

**Comment by JGreenlee** [comment]
> I just ran into this working with the profile migrations! I think it's probably something that broke when the QrCode was migrated to a React component. It seems the share code for the QR required going and getting the link to the code from the element `const c = document.getElementsByClassName('qrcode-link'); const cbase64 = c[0].getAttribute('href');` which is no longer the way that element is displayed. If that link is the same as the "tokenURL" then something like this : `const cbase64 = "emission://login_token?token="+settings?.auth?.opcode;`might be a good replacement? I've tested in the devapp but it's a little hard to tell if things share properly there.

Good catch.
You should be able to use the value that's in `$scope.tokenURL`, which is the same as `"emission://login_token?token="+settings?.auth?.opcode` would be

**Comment by JGreenlee** [comment]
It is probably broken in `intro.js` as well, it's the same shareQR function

**Comment by JGreenlee** [comment]
TODO now:
- fix incorrect dates / timezones
- fix QR code sharing (both profile and intro)
- look into dashboard errors
- fix duplicated activities
- fix Enketo checkboxes (CSS?)
- implement new color coding for modes
- unify map markers icons


TODO later / cleanup:
- draft places (I have not begun on this at all)
- memoize `display_` properties
- unify imperial computations
- rename vars & cleanup LabelTab


Need more info:
- should unimodal trips show something in place of the sections list, or is it redundant / unnecessary?

**Comment by JGreenlee** [comment]
Keep em coming!

**Comment by shankari** [comment]
I think this was already addressed by Nitish, but when you sign up for the app for the first time (as I did with the LG), then there are no trips, and the load keeps spinning.

**Comment by shankari** [comment]
Feedback from @jRaffill
- overall background is gray but the background for each card is blue. That really bothers me. It should be different shades of blue.
- in the detail screen, I zoomed out all the way and my trip disappeared and when I zoomed in again, the trip wasn't there
    - seems to happen intermittently, could not replicate on second try
- why can't you have the same flag inside the map as in the address?
- when you click on the check mark you should go out of the detail screen. Or wait, maybe not?
- when I select values from the dropdown, the checkmark becomes enabled, but then when I press it, there is no response
   - of it being checked off and becoming "done" so then I just keep clicking on it out of frustration
   - make it disappear sooner but also give some kind of response to my checking
   - alternate option: disappear immediately after check mark
   - check mark button should be bigger, otherwise I accidentally go to the view mode when I check it off

**Comment by shankari** [comment]
version 1.3.7 is not working on iPhone6, iOS 12.
100% reproducible in an iOS13.7 emulator
@JGreenlee, what are we transpiling to?

**Comment by JGreenlee** [comment]
> version 1.3.7 is not working on iPhone6, iOS 12.
> 100% reproducible in an iOS13.7 emulator
> @JGreenlee, what are we transpiling to?

All Typescript is being transpiled to ES5, which should be safe.
Any remaining JavaScript is not being transpiled - maybe there's a problem there.

Can you show/send me error logs (from a dev build)? I am not able to test iOS<15 due to issues with my XCode installation.

**Comment by shankari** [comment]
Added logs to https://github.com/e-mission/e-mission-docs/issues/932#issuecomment-1637153502
This seems to be from react code? Unless line numbers in bundle.js are off somehow...

**Comment by shankari** [comment]
Card is actually from react-native-paper. Maybe these are related:
https://github.com/callstack/react-native-paper/issues/2261
https://github.com/callstack/react-native-paper/issues/689

**Comment by JGreenlee** [comment]
Yes, I think that it is probably some incompatibility between `react-native-paper` and webpack.

I could look into it, but let me first ask this: do we actually need to support iOS 13? I believe Apple themselves consider it obsolete - all phones that could run iOS 13 can be upgraded to later versions. My understanding is that no one is stuck on iOS 13 unless they just refuse to upgrade. Should we, or do we need to, make special accommodations for situations like that?
My older iPhones are using iOS 15/16 with no problems.

**Comment by shankari** [comment]
we don't need to support iOS 13, but we do need to support iOS 12, because iPhone 6 phones cannot be updated beyond iPhone 12. We told the current set of deployers that we support iOS 12, and I did the work #924 to actually implement it after receiving an email from a user who had an iPhone 6.

Most commercial apps can choose to drop support for older versions since they can't make a lot of money off poor people. But as a public app, we should try to support the largest variety of phones possible. On android, for example, we support API 22+, although I don't think we are testing with any android 22 phones. I have android 23 test phones, though.

**Comment by shankari** [comment]
Quick check on actual deployment percentages:
https://developer.apple.com/support/app-store/

~ 6% of phones are running an OS below iOS 15. I think that if a version gets to 2-3%, we can consider dropping support if it is too onerous to maintain.

**Comment by JGreenlee** [comment]
I don't think the above links are detailing the same issue as we are having.

I found out that, surprisingly, Safari did not support static fields in class definitions until 14.x (https://caniuse.com/?search=static%20fields)
This would explain why `static defaultProps = ...` fails.

The TypeScript transpilation we have set up only applies to our code, not our dependencies (we sort of expect React libraries to have already compiled into 'safe' JS - but in this case it's not safe enough for us)

I think we can remedy this with Babel and point it to RN Paper (+ any other affected dependencies)
Might also be nice to post an issue on RN Paper with the solution, for the benefit of the open source community

**Comment by JGreenlee** [comment]
So, it is not too bad. It could be worse.
I suppose this is to be expected when rapidly modernizing.

**Comment by shankari** [comment]
you could set it up so that it only transpiles the dependencies in `node_modules` during production. I know you were concerned about the performance of the compile/test cycle during development; and I don't think we need to develop on iOS 12. It is enough if the resulting production app works on iOS12/iPhone6

**Comment by Abby-Wheelis** [comment]
I just ran into a similar situation on my Android, the "all trips" page is only showing unlabeld trips right now. After I labeled them and refreshed the page it went back to showing all of the trips. The infinite loading is also happening to me on the "to label" screen if I don't have any trips that require a label.

**Comment by JGreenlee** [comment]
I have a solution for the infinite loading spinner.

I will add the filter weirdness to my list of things to check out.

As for the 'weird gap', what's weird about it? What would be expected?

**Comment by shankari** [comment]
> As for the 'weird gap', what's weird about it? What would be expected?

Since we only have one trip, that it would be at the top of the screen

**Comment by JGreenlee** [comment]
> you could set it up so that it only transpiles the dependencies in `node_modules` during production. I know you were concerned about the performance of the compile/test cycle during development; and I don't think we need to develop on iOS 12. It is enough if the resulting production app works on iOS12/iPhone6

I can make the appropriate change here, but I won't have a way to verify that it fixed the issue because don't have a way to run a Simulator on iOS < 14

**Comment by shankari** [comment]
no worries, i can test on my iphone6

**Comment by Abby-Wheelis** [comment]
> Make the symbols on the map and the origin/destination text be the same

With this, were we thinking change the card or change the map? I think both are possible, but in the experimenting I've done so far neither format easily. 
<img width="287" alt="Screenshot 2023-07-21 at 1 50 22 PM" src="https://github.com/e-mission/e-mission-docs/assets/54848919/970302dd-d270-4c2a-b5df-e2533a20d9af">
Above is an easy change just swapping from a `map-marker-star` to `star-circle-outline` (and a `star-circle` is actually an even closer match). Unfortunately, the icon library doesn't have something like that for a flag.

There are ways to style them closer to what appears on the map (outline, fill) but they just look worse from what I've tried. It is also possible to embed a React element into a marker on the Leaflet map, but when I tried this with an IconButton there were a lot of warnings in the console and the icons were off-placed when I tried.

Does anyone have any opinions on what the best end-goal is here?

**Comment by Abby-Wheelis** [comment]
### Some more questions about P2 fixes/goals for when I go to address these:
> fix 'weird gap' above trip list if only 1 trip is loaded 

So display the card at the top if there's only one? What about if there's two (there would still be a gap)? I know normal is for the most recent trip to be at the bottom since that’s what you see first - would it be more confusing for the location of the "most recent trip" to change?
> reconsider color theming of label tab:"overall background is gray but the background for each card is blue"

I get why it's slightly blue, it falls in line with the the red and green schemes for draft and untracked. Would the concern here be addressed by a slightly more distinct shade of blue? I could also see how having all the cards be "brightly" colored could overwhelm a user. Anyone have a strong opinion of a change to be made here?
> enforce min/max zoom on Leaflet maps:"in the detail screen, I zoomed out all the way and my trip disappeared and when I zoomed in again, the trip wasn't there"

I was unable to recreate this behavior (tried emulator, android, and iOS). @shankari can you give more details about the conditions that caused this? If the trips stop disappearing, do we still want to enforce zoom? It seems like zoom 1 (1/4th of the earth) would be a good min,  and zoom 18 (a few blocks) is a typical max. [leaflet zooms](https://leafletjs.com/examples/zoom-levels/)

**Comment by shankari** [comment]
> Does anyone have any opinions on what the best end-goal is here?

From @mRaffill The flag is less of an issue. The main goal is to have it look consistent. The flag is OK because it is same color and same shape. Star is better now because it is the same shape, would be better if it was the same color.

**Comment by JGreenlee** [comment]
> Does anyone have any opinions on what the best end-goal is here?

The best end-goal is don't use Ionicons anymore; pick 2 icons from https://pictogrammers.com/library/mdi/ and unify in all places they are used.

maybe 'map-marker' and 'flag'

**Comment by JGreenlee** [comment]
Relevant to the 'weird gap' issue:
https://github.com/Shopify/flash-list/discussions/773

There is no posted solution or workaround.

**Comment by shankari** [comment]
> There is no posted solution or workaround.

I guess we can skip that then

**Comment by shankari** [comment]
ok so we don't get a WSOD on the iPhone 6 (iOS 12) BUT we don't display any trips. ARGHHH!!!

While logged in as the same user:

| iPhone 6 no trips | Android shows trips | iOS 13 emulator trips |
|-----------|------------|---------|
| ![iphone6_no_trips](https://github.com/e-mission/e-mission-docs/assets/2423263/e927567a-b181-4666-8d1c-5dc3581da604) | ![Screenshot_2023-08-11-17-46-37-92_5062a5234f99d532322a40d030e8949e](https://github.com/e-mission/e-mission-docs/assets/2423263/79e41452-8298-4612-b7c3-eb9adf1fac26) | ![simulator_screenshot_127571BF-D79E-4A60-9499-C88485C3C3B8](https://github.com/e-mission/e-mission-docs/assets/2423263/ef351e18-58a1-4516-8ccd-8ff1c7f3bfab) |

**Comment by shankari** [comment]
This is turning out to be super hard to debug. Note that we cannot use the iOS13 emulator to test since everything works there. So I tried to install a dev version of the app on the iPhone and connect to it. The first part of this worked but the second part did not. Concretely, while trying to connect to the WKWebview on iOS12 using safari, the console would crash and all further attempts to connect would show that safari was "connecting"...

<img width="741" alt="Screenshot 2023-08-11 at 6 36 37 PM" src="https://github.com/e-mission/e-mission-docs/assets/2423263/56832a68-9476-449f-86c3-586bc060c1c3">

**Comment by shankari** [comment]
Trying to use the console to read the full phone logs, I get the attached gzip file.
But 
[openpath_console_logs.gz](https://github.com/e-mission/e-mission-docs/files/12326150/openpath_console_logs.gz)

**Comment by JGreenlee** [comment]
Since it's not WSOD but is specific to the Label screen, I have a hunch that it has to do with our use of the `Map` object, which is used for `timelineMap`.
It's already being transpiled into older JS, was tested against older emulators, and shown to work there, but maybe not as old as iOS 12.

If that is the issue, I can go back on that and use a different data structure if I have to.

**Comment by JGreenlee** [comment]
But since Apple no longer supports tooling to emulate and debug iOS 12, I don't know a way to  confirm my suspicions - short of making the change and observing whether it works.

**Comment by shankari** [comment]
> But since Apple no longer supports tooling to emulate and debug iOS 12, I don't know a way to confirm my suspicions - short of making the change and observing whether it works.

Right. I think that this is the real problem. We don't know what the problem is and/or how to fix it.

I spent some time hacking together a script to see how widespread the problem is, and there is exactly one iPhone 12 user in a real program [1].

[1] Technically, there is also one in nrel_commute, but I am pretty sure that is me logging in with one of the test iPhones.

**Comment by shankari** [comment]
verified that there is only one user - relaunched the app on my personal phone and the android test phone and the nrel_commute user went away. Let's see if this one user has any recent trips.

**Comment by shankari** [comment]
Unfortunately, the most recent trips for the user are from today 😦 
If we set the min compatible version of this version to 13, I wonder if iOS 12 users will stay with 1.3.3
In that case, we can just have 1.3.3 be the last "ios12 compatible version"

**Comment by shankari** [comment]
ok, so per this:
https://appleinsider.com/inside/ios/tips/how-to-get-apps-for-old-iphones-and-ipads
that one user can keep using the 1.3.3 version of the app since they already have it installed.
I will verify this on my test iphone6.
which seems to be consistent: https://support.apple.com/en-us/HT211841

I am not sure whether we should try to fix this or just stop supporting iOS 12.
At least on my laptop, xcode can connect to the phone and install the app on it; I just can't debug the javascript because Safari won't connect. I was hoping to get away with using the iOS 13 emulator, but it looks like there are differences between iOS12 and iOS13, so there is no alternative to testing this on a physical iPhone through trial and error.

**Comment by shankari** [comment]
I tried to look for iOS12 market share numbers.
https://developer.apple.com/support/app-store/ claims that 6% of phones are running versions below iOS15, but does not break down further.

https://gs.statcounter.com/ios-version-market-share/mobile-tablet/worldwide
has way more detailed stats, including a downloadable csv.

**I don't know the provenance of these numbers**

but they seem to show ~ 2% share for iOS 12 in general.
Given the hassle of supporting iOS12, I feel comfortable dropping support for it if those numbers are true.

```
>>> client_versions[["Date", "iOS 12.0", "iOS 12.1", "iOS 12.2", "iOS 12.3", "iOS 12.4", "iOS 12.5"]]
       Date  iOS 12.0  iOS 12.1  iOS 12.2  iOS 12.3  iOS 12.4  iOS 12.5
0   2022-07      0.05      0.14      0.07      0.13      0.29      3.02
1   2022-08      0.07      0.13      0.07      0.12      0.28      2.70
2   2022-09      0.07      0.12      0.06      0.10      0.25      2.39
3   2022-10      0.04      0.10      0.06      0.10      0.21      2.19
4   2022-11      0.04      0.10      0.06      0.11      0.21      2.32
5   2022-12      0.05      0.11      0.06      0.10      0.22      2.21
6   2023-01      0.04      0.10      0.05      0.09      0.21      2.16
7   2023-02      0.04      0.10      0.05      0.09      0.21      2.17
8   2023-03      0.04      0.09      0.05      0.08      0.19      2.06
9   2023-04      0.03      0.09      0.05      0.08      0.17      1.95
10  2023-05      0.03      0.08      0.05      0.08      0.17      1.92
11  2023-06      0.03      0.08      0.05      0.07      0.15      1.85
12  2023-07      0.03      0.07      0.04      0.06      0.13      1.64
```

**Comment by shankari** [comment]
I also took a look at our stats

We have ~ 400 iOS users

```
>>> counts = [77, 25, 36, 76, 2, 17, 14, 6, 54, 26, 21, 22, 7, 8, 5]
>>> sum(counts)
396
```

So with one iOS 12 user, we are at 0.25% (1/4th of 1%)

If this was as simple as changing the babel transpile level, I would still do it (international users are more likely to have older iPhones and older iOS versions). But it is also clearly not worth spending significant development effort on.

ok, so my current proposal is:
- we bump up the min supported version to iOS 13
  - I send out an email to the one iOS12 user and their program admin indicating that they can keep using version 1.3.3 for the rest of the program
- we get a physical iPhone 12 to Jack just in case
  - other changes that we make, e.g. transition to full react native, might get this to work again since we will no longer use the maps and the webview in exactly the same way
  - if that happens, we look at the percentages (particularly of our international deployments) and decide whether to expand support to iOS 12 or not.

**Comment by shankari** [comment]
while on the topic of versions, I realized that we were currently on android 5, and I don't think anybody has an android 5 phone to test.

I checked, and there are *no* android 5 users in our database

```
>>> counts = [39, 12, 20, 36, 10, 3, 4, 14, 12, 21, 12, 9, 2, 5, 2]
>>> sum(counts)
201
```

 so I am bumping up the minSDK version to android 6 as well. I do have an android 6 phone that I have verified the install against (including viewing trips in the trip diary).

**Comment by shankari** [comment]
I am seeing some errors in the dashboard on android 6. The dashboard is not as critical as the label screen, and I can verify that the dashboard doesn't seem to have the error on android 7+  

These are while logged in to my personal `nrel_commute` account. It almost seems like they are not able to map the CO2 values correctly. 

| Error 1 | Error 2 |
|------|------|
| ![Image](https://github.com/e-mission/e-mission-docs/assets/2423263/2c6d0bf1-44e7-4b2f-8b54-05b000e8e10c) |![Image](https://github.com/e-mission/e-mission-docs/assets/2423263/fd825c70-07d1-492b-9e52-2c28b45fdc26) |

**Comment by shankari** [comment]
These are while logged in to my personal `nrel_commute` account. It almost seems like they are not able to map the CO2 values correctly. @Abby-Wheelis can you file a new issue for this so that you can investigate and fix while working on the dashboard.

| Error 1 | Error 2 |
|------|------|
| ![Image](https://github.com/e-mission/e-mission-docs/assets/2423263/2c6d0bf1-44e7-4b2f-8b54-05b000e8e10c) |![Image](https://github.com/e-mission/e-mission-docs/assets/2423263/fd825c70-07d1-492b-9e52-2c28b45fdc26) |

**Comment by shankari** [comment]
I also get the error while launching the trip survey on android 6.
Android system webview is 74.0.3729.157
@Abby-Wheelis which version do you have on your LG test phone.
I might try to upgrade to see if it fixes the issue.

**Comment by shankari** [comment]
Upgrading the webview fixed the survey but not the dashboard @Abby-Wheelis you might want to file an issue to at least see what the problem is.

**Comment by Abby-Wheelis** [comment]
My LG phone is on 115.0.5790.138 WebView - that error was the same one I was getting previously, when WebView was not yet installed on the phone I was trying to use. 

I've seen dashboard errors from time to time on my Android test phone (including the same one about drove_alone), which resolve when I close and reopen the app. I was thinking it was to do with how often I'm off wifi, but I'll definitely file an issue so we can keep investigating since it seems like it's a consistent issue.

**Comment by shankari** [comment]
This is out on production right now. Closing this; pending issues will be addressed in subsequent releases
