### ISSUE TITLE
Lao issues: Lao language selection broken on android, Lao demographic survey has two entries, consent screen in English

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-docs#938]
While taking the demographic survey after choosing Lao, I see that there are two Lao options, one with "Lao" and the other with ລາວ. If I select "ລາວ" then the survey questions are in Lao, but there are no choices. If I select "Lao", then there is no survey question, but all the choices are in Lao.

Please see screenshots below. I think we need to adjust the excel file to say ລາວ in both places.

| Lao gives options only | ລາວ gives questions only |
|----|-----|
| ![Screenshot_20230724-163851](https://github.com/e-mission/e-mission-docs/assets/2423263/b7c83294-d57c-4c48-9ddf-52751490c844) | ![Screenshot_20230724-163812](https://github.com/e-mission/e-mission-docs/assets/2423263/65ab039f-2f89-4edd-b706-309e55a4890d) |

**Comment by shankari** [comment]
Couple of other issues:
- on android, if there are multiple langugages defined, even if Lao is the first, we don't choose it (@JGreenlee has a one-line fix)
- I see the Lao summary, but not the Lao consent screen (at least on OpenPATH)
   - But it works for Spanish
- I also notice that there is no Lao translation in

```
$ ls www/i18n/intro/
consent-es.html			login-fr.html
consent-fr.html			sensor_explanation-fr.html
consent-text-es.html		summary-es.html
consent-text-fr.html		summary-fr.html
login-es.html
```

Although there is in `locales`

```
$ ls locales/lo/intro/
consent-lo.html		consent-text-lo.html	summary-lo.html
```

This discrepancy might help explain why Spanish works but not Lao.

Do we need to do some special webpack stuff to put in the locales? Do we need to change the `intro.js` to read from the `../locales` location?

| Lao summary works | Lao intro does not work | Spanish intro works |
|---------|----------|------|
| ![Screenshot_20230725-085413](https://github.com/e-mission/e-mission-docs/assets/2423263/c107c409-c777-4f5c-8b7f-dfd06d417bc6) | ![Screenshot_20230725-085439](https://github.com/e-mission/e-mission-docs/assets/2423263/9328878b-4203-4604-a582-da701645b7f6) | ![Screenshot_20230725-085553](https://github.com/e-mission/e-mission-docs/assets/2423263/bb5e8f99-b0b8-4e3e-be18-c8b7556934ce) |

Couple of things to note so you are not confused:
- the summary basically has no actual text in it any more; everything comes in from the dynamic config. (as an aside, we can probably remove it from the list of i18n files in `intro.js` (`var allIntroFiles`) since all the `summary-*` files are the same :)
- the intro template is what is different between Lao and Spanish
   - the part that is read from the config is correctly in Lao when the language in Lao and in English when the language is Spanish, since the Lao config does not include any Spanish translations
   - the template part from `consent-lo.html` and `consent-es.html` is the one that is "broken". It is in Spanish for Spanish but in English for Lao

**Comment by Abby-Wheelis** [comment]
> Please see screenshots below. I think we need to adjust the excel file to say ລາວ in both places.

Looking at the excel file, I saw that the column headers were inconsistent, as you pointed out - in [e-mission-phone #1005](https://github.com/e-mission/e-mission-phone/pull/1005) I've updated the .xlsx and .xml files to reflect this change, but the .json file still needs to be updated

**Comment by Abby-Wheelis** [comment]
@JGreenlee pointing out a discrepancy in the file structure in `e-mission-translate` which would explain why es works and lo does not we fixed that discrepancy [here](https://github.com/e-mission/e-mission-translate/pull/34)

**Comment by shankari** [comment]
- Survey is fixed and autopopulates to Lao
<img width="415" alt="Screenshot 2023-07-25 at 7 32 43 PM" src="https://github.com/e-mission/e-mission-phone/assets/2423263/55d2baf7-1ff7-407c-8280-365a22f1887f">
https://github.com/e-mission/e-mission-phone/pull/1005#issuecomment-1650882239


- Consent screen is fixed, but found new issue with agree and disagree, fixed
<img width="415" alt="Screenshot 2023-07-25 at 7 30 06 PM" src="https://github.com/e-mission/e-mission-phone/assets/2423263/f028930a-56cc-4c39-9694-a811066323ec">
https://github.com/e-mission/e-mission-phone/pull/1005#issuecomment-1650879705

**Comment by shankari** [comment]
Now I see a weird issue in which we skip the QR code completely.
As you can see from the video below, the QR code screen moves on without my clicking on it, and the survey looks weird and offset. Trying to debug it for ~ 30 mins will give up after that

https://github.com/e-mission/e-mission-docs/assets/2423263/6fca05b2-cf7e-4370-8f94-16c76d8a56c3

**Comment by shankari** [comment]
I can confirm that this behavior happens on English too and is 100% reproducible. I put a breakpoint in `intro.js` `next()` and it is not invoked. And it almost looks like the demographic survey is loaded over the save token page. Maybe the `ng-if` is triggered too soon?

This is going to take more than 30 mins to fix, so I'm going to push out RC2 tonight and hope we can investigate this for an RC3 later in the week

**Comment by shankari** [comment]
Here's the video for what happens. As you can see, there is a breakpoint at `intro.js` `$scope.next` which is triggered when we go from consent -> explain -> saveToken. Then we transition from saveToken to survey *without* pressing any buttons or triggering the `next` breakpoint.


https://github.com/e-mission/e-mission-docs/assets/2423263/1dfaf9a7-96ab-4ab4-83aa-d070874af237


Given the location, I suspect that this is related to the recent QR code save changes by @Abby-Wheelis 
@Abby-Wheelis  can you test and fix? In the absence of automated testing, it would be great if you could add a video to the PR showing both this UI, and the one in the profile screen, working.

**Comment by JGreenlee** [comment]
This is related to the Enketo modal, not QR code.
I will fix tomorrow

**Comment by Abby-Wheelis** [comment]
It's working for me in both places using the emulator and a `dev-emulator-study` opcode (I took videos and can upload) **BUT** I just noticed that the images are different in the two places! I will look into this asap and see what the difference is, I'm guessing it's that the string encoded into a code in the two places is different...

**Comment by Abby-Wheelis** [comment]
I clicked through the survey on a test phone in Lao this morning and noticed a few things:
- there's still two options for Lao in the language dropdown at the top, and though they look the same only one text (the default is fine, but the other option looks like it will be Lao and then when clicked the survey appears blank)
- the title of the survey is in English, which I think might be because the title itself isn't translated by nature of the form?

**Comment by shankari** [comment]
@Abby-Wheelis Not sure where the two options in the dropdown come from; you should be able to check the enekto code to figure out.
The title of the survey, though, I think we can fix. It is in the "settings" tab of the excel file.
You can also load the excel file into kobotoolbox and edit it there if it is easier.
That might also fix the dropdown issue (we don't have two entries for Spanish, for example).

**Comment by Abby-Wheelis** [comment]
I found the issue with the dropdown, it was another column mismatch in the spreadsheet (this time the hint column) which I found and then verified the form is fully functioning in Lao using kobotoolbox (I'll definitely use this workflow in the future, it helped to be able to preview the form!).

Unfortunately, it looks like title translations is not yet a supported feature for these forms, even though several have asked [like here](https://community.kobotoolbox.org/t/need-xlsform-code-to-display-form-title-in-multiple-languages-french-english-by-default-at-same-time-with-form-other-contents/13829). It seems the suggested workaround is to have all the translations included in the title - would we want to do that? It feels like it might clutter the screen. Another suggestion in the forum is placing a note at the beginning of the survey that is translated - would this be something we want to implement? The way you enter the survey through the app makes it feel pretty clear to me what the form is, so I don't things it's something we should be too worried about, but I'm also not a first-time user anymore.

**Comment by shankari** [comment]
Didn't we have the title in Spanish for the Spanish version? How did we get that to work?
If you change your real phone to Spanish and then click the demographic survey again from the profile, is the title in Spanish?

> Another suggestion in the forum is placing a note at the beginning of the survey that is translated - would this be something we want to implement? 

Maybe. We should see what it looks like in the preview (maybe add some screenshots here?) and decide.

**Comment by Abby-Wheelis** [comment]
> If you change your real phone to Spanish and then click the demographic survey again from the profile, is the title in Spanish?

No, I just tried it on a fresh install and the survey title (in the survey window itself) is in English

>We should see what it looks like in the preview (maybe add some screenshots here?) and decide.

I'll work on seeing what this would be like!

**Comment by Abby-Wheelis** [comment]
![Screenshot 2023-07-27 at 10 30 09 AM](https://github.com/e-mission/e-mission-docs/assets/54848919/82e3c58f-bbc7-47cf-9142-9aa66360f738)
The text is `Weclome to the OpenPATH Demographics Survey, please answer all the questions`, which I could easily change if we wanted it to be something different, and clicking the blue "next" button takes you to the first question.

The English title is still very prominent, but adding this introductory slide is very simple and offers a little bit of an explanation, even if the title isn't understandable. I'd hope they would introduce the translatable title soon, but it looks like requests for that feature go back as far as 2019.

**Comment by shankari** [comment]
> I'd hope they would introduce the translatable title soon, but it looks like requests for that feature go back as far as 2019.

Well, the **correct** solution if there is an open source project that doesn't do exactly what you want is to build it yourself and contribute it to them. That's what it means to have an open source community 😄 

This particular change is trickier because it might require a change to the XLSForm standard https://xlsform.org/en/ . Kobotoolbox is just a survey builder that generates xlsforms.

If you feel ready to branch out to open source projects beyond OpenPATH, I'd be supportive of your engaging with the xlsforms/ODK/enketo community into start a discussion around potentially contributing this change.

**Comment by JGreenlee** [comment]
I think the demographics survey is pretty inconvenient in the first place because every question is on a separate page.
It should really just be 2 pages: Personal Level Information and Household Level Information

If we condense it down as such, then I think adding one introductory page at the beginning isn't so bad

**Comment by shankari** [comment]
@JGreenlee I think it is set up this way so that people can just click through questions instead of scrolling to make it easier for mobile devices. UNSW set it up this way first, but I kind of agree with them - I just keep getting questions that I have to respond to like a video game instead of having to scroll and find things.

**Comment by JGreenlee** [comment]
> people can just click through questions instead of scrolling to make it easier for mobile devices

I think mobile devices are optimized for scrolling, and that's why digital design has moved away from pagination.
@Abby-Wheelis what do you think?

**Comment by Abby-Wheelis** [comment]
Most of the surveys I've taken on my phone were google forms, which are scroll based, and I found that easier than if every question were on a different page. All the longer surveys I've taken recently (mostly Qualitrics) were easier to fill out on a laptop and had lots of pages, but even those were usually "page-per-section" rather than "page-per-question". 

I think it makes sense that we'd stick to mostly scrolling on a mobile device, certainly most of the apps I use on my phone are scrolling based. My only concern would be if the scrolling felt "sticky" and then it was harder to navigate. But if the page is easy to scroll I think I like the idea of the 2 scrollable pages!

**Comment by JGreenlee** [comment]
If we do choose to make that change, it is as simple as checking this box in Kobo on each of the 2 sections

<img width="1440" alt="Screenshot 2023-07-27 at 1 09 39 PM" src="https://github.com/e-mission/e-mission-docs/assets/15843932/fcb8daef-1a7c-4a0b-bf01-18a312327768">

**Comment by shankari** [comment]
I wonder if we should give deployers the choice of pagination or not (with "not" being the default).
That can also use the configurable demographic survey feature and highlight that it is even more configurable.
Although we don't want them to remove too many questions - then the data will not be as useful to other researchers.

**Comment by Abby-Wheelis** [comment]
I'm encountering a new survey issue on an LG test phone running Android 10: There is an error popup when the survey first opens, photo below, but then all three language are displaying at once despite English being selected in the menu, and none of my answers are saving such that the "required question" alert stays after I select and option and when I get to the end I can't save and close the survey. 
 <img width="300" alt="Screenshot 2023-06-13 at 2 20 28 PM" src="https://github.com/e-mission/e-mission-docs/assets/54848919/ddb686f0-d6bd-4478-a170-e5851d80c6f9">

**Comment by JGreenlee** [comment]
Seems like a bug in Enketo.

It has been documented before: https://community.kobotoolbox.org/t/failed-to-execute-queryselectorall-on-element/34636

It's possible this was fixed in newer versions of enketo-core.
We are currently using enketo-core version 6, while the latest is 7.x. I was waiting for them to merge a fix from me, which they now have, so it's a TODO

**Comment by shankari** [comment]
I finally got around to testing this on a Pixel 4 running Android 12. And I don't see any issues.

| No error while loading survey | No error while navigating to the next page | No error while loading survey in Lao |
|------|------|-------|
| ![Screenshot_20230803-213530](https://github.com/e-mission/e-mission-docs/assets/2423263/b88f2b19-4a73-4d69-b540-1e19cb6eb459) | ![Screenshot_20230803-213609](https://github.com/e-mission/e-mission-docs/assets/2423263/2c0d77be-28bd-4283-8815-3f4675d499fb) | ![Screenshot_20230803-213711](https://github.com/e-mission/e-mission-docs/assets/2423263/217f6174-832b-445e-a05c-e9fe53ccc147) | 

@Abby-Wheelis are you sure this was not just an error downloading the survey config? If you try uninstalling + reinstalling on the LG, does it work?

@JGreenlee are you seeing this behavior on your test phone?

**Comment by Abby-Wheelis** [comment]
@shankari I uninstalled and reinstalled and had the same exact issues with the survey

**Comment by shankari** [comment]
@Abby-Wheelis can you switch to the production version and see if the problem recurs? you will likely have to sign out and sign in with a different google account?

**Comment by Abby-Wheelis** [comment]
@shankari I installed the production version and the survey is perfectly fine (not getting any errors, the questions are showing up just in the target language, answered them and "cleared" that stage). Looking at the difference between `framework_migration_prep` and `master_for_platform` I can see the switch to defining `enketo-core 6.1.7` as the dependency that's used on staging, not sure what enketo is used on production. Once I have the android emulator up I will work to reproduce there, to hopefully find the issue / to test upgrading enketo. [Here](https://github.com/enketo/enketo-core/compare/6.1.7...7.2.4) is what has changed between `enketo-core` 6.1.7 and 7.2.4.

**Comment by JGreenlee** [comment]
I haven't been able to reproduce on any of my test phones, one of which is also on Android 10

**Comment by JGreenlee** [comment]
I have some hope that the issue will not be present in Enketo v7.x because the diff includes this change: https://github.com/enketo/enketo-core/commit/a6b7add062c5e406db23c8f5fda3332d8dd649d2

But if not we should file an issue with Enketo and maybe patch it ourselves

**Comment by shankari** [comment]
I wonder if this is related to some weird issue with the LG webview in particular. But we are transpiling, so it should work even with older webviews, and @Abby-Wheelis indicated that it does work on older android phones. I can verify that it works on an LG Stylo 3, running Android 7 so it is definitely not all LGs.

If the upgrade doesn't fix it, we should consider running a dev version of the app on this specific LG to verify.

**Comment by JGreenlee** [comment]
I don't expect JS transpilation to affect this. For some reason, that LG phone's webview doesn't like this selector:
```js
'.question input[data-type-xml="geopoint"]:not([data-setvalue], [data-setgeopoint]), .question input[data-type-xml="geotrace"]:not([data-setvalue], [data-setgeopoint]), .question input[data-type-xml="geoshape"]:not([data-setvalue], [data-setgeopoint])'
```
and no amount of transpilation is going to change that string.

**Comment by JGreenlee** [comment]
@Abby-Wheelis Can you figure out what version of Android Webview that LG phone is running?

**Comment by Abby-Wheelis** [comment]
@JGreenlee the phone is running version 115.0.5790.138 of Android System WebView, apparently updated on Jul 25th. In googling to see if there were any known bugs with that version, I ran across the suggestion to reboot the phone - I restarted the phone, uninstalled and reinstalled the app, and the survey ran smoothly this time. This was definitely an issue on my individual phone's end, and I probably should have tried the reboot earlier, sorry.

**Comment by JGreenlee** [comment]
> @JGreenlee the phone is running version 115.0.5790.138 of Android System WebView, apparently updated on Jul 25th. In googling to see if there were any known bugs with that version, I ran across the suggestion to reboot the phone - I restarted the phone, uninstalled and reinstalled the app, and the survey ran smoothly this time. This was definitely an issue on my individual phone's end, and I probably should have tried the reboot earlier, sorry. 

That's strange. So you can no longer reproduce it?

**Comment by Abby-Wheelis** [comment]
Correct, there aren't any issues with the survey anymore and I don't see the error pop up, just tried reinstalling again. I just got this phone and had never rebooted before so maybe it was a fluke with the system somehow.

**Comment by JGreenlee** [comment]
My best guess is that before the reboot, it was stuck an older webview version (possibly very old, if you had never rebooted before), and rebooting the device put the new version into effect.

I don't think there is any way to see what version it was running prior to the reboot. It would be good to know what version the issue occurs on though.

**Comment by shankari** [comment]
At this point, I am fine with going to production with this issue lingering (since presumably people's regular phones are being updated fairly frequently). I agree that it would be good to know what version that was, and also that we should consider upgrading to a more recent version after this release is out.

@Abby-Wheelis just curious: if you do a "factory reset" does it go back to the old versions?

**Comment by Abby-Wheelis** [comment]
@shankari not sure why, but when I factory reset, the error came back (so good news it is reproducible) - despite the fact that where I'm looking, at least, the WebView version is the same each time (before reboot, after reboot, after reset). I'll keep the phone in this state because maybe I was looking in the wrong place for the WebView versioning and do some more research (I've been looking in the Google Play store)

**Comment by JGreenlee** [comment]
@Abby-Wheelis I believe the Play Store will show the latest available version.
The installed version will be found in Settings -> "App Info".

 something like Settings -> Apps -> Android System WebView -> at the very bottom

**Comment by Abby-Wheelis** [comment]
After the weekend, the survey started working again, and I found that it was the most recent version when I checked in the App Info. I then reset the phone again and have figured out that for whatever reason, WebView was not installed on initial setup (it didn't appear in App Info) but that resolves when the update cycle goes through (WebView is one of the queued updates right after logging in post-factory-rest), so I think it's safe to assume that this shouldn't affect any "typical" phone users that have updates turned on and aren't trying to install openPATH 5 minutes after setting the phone up for the first time. 

If there's a way to catch that there's an error with WebView specifically, would we be able to throw an error to that effect?

**Comment by JGreenlee** [comment]
I'm not sure about a catch-all for WebView version-related errors, but what we definitely _can_ do is catch errors from Enketo that happen upon initialization of a Form, and display a more meaningful error message in those instances.

In the upcoming weeks, I am hoping we can do a lot of work on rewriting the Enketo mechanism as a whole.
In the process, we can be more mindful of catching those errors.

**Comment by shankari** [comment]
We just got an email from Laos with a list of "lao translations". I have forwarded to @Abby-Wheelis. It seems to me that this is the same list that we got from them earlier, and does not include the new values that we translated directly using Google Translate.

@Abby-Wheelis can you spot check? We will need to follow up with them if needed.

If they have sent over additional translations, we should incorporate them and then close this issue.
If they have *not* sent over additional translations, we should close this issue, follow up with them and open an new issue for the follow-up changes

**Comment by Abby-Wheelis** [comment]
@shankari, on initial glance, we're still missing the biggest part I Google Translated (mode & purpose) AND there are a few updates / corrections. I'll comb through, get the corrections we have in, then close this issue and start another for the follow-up.

**Comment by Abby-Wheelis** [comment]
Additional translations are being added in [e-mission-translate #38](https://github.com/e-mission/e-mission-translate/pull/38) and in [nrel-openpath-deploy-configs #28](https://github.com/e-mission/nrel-openpath-deploy-configs/pull/28) to reflect the updates and corrections that we received. The issue above is going to rest of the translations, so I think we're ready to close this one.

**Comment by shankari** [comment]
We created a follow-up to this (https://github.com/e-mission/e-mission-docs/issues/943). That was also closed today, so we can close this as well.
