### ISSUE TITLE
Samsung Permissions Investigation

### ISSUE THREAD

**Issue by Abby-Wheelis** [e-mission/e-mission-docs#959]
See prev discussion: [phone#1009](https://github.com/e-mission/e-mission-phone/pull/1009#issuecomment-1684451156), pulling the discussion that started in this comment, since it's clear this requires some investigation and experimentation. 

**Starting point:** In the process of the Profile Settings migration into React, I've made a rough draft of the Permissions as a React Modal. In writing this, we've come across some code related to Samsung-specific permissions that isn't currently displayed, so we're investigating how well the app works on a Samsung device. Samsung is the worst-rated permissions blocker on [dontkillmyapp](https://dontkillmyapp.com/samsung), so we know there could be issues other Android devices don't encounter. Thanks to @nataliejschultz we have the ability to work closely with someone running a Samsung device with Android Pie or higher (the most likely to have issues).

**Initial Data:** After setting up the app, Natalie took a few trips, and encountered weird behavior. She saw WSOD while trying to check the app on the trip (we're thinking this was just connectivity related) but also "teleported" as a part of the trip. The clip of screenshot below shows the location jumping West (note she did not go to the place marked as trip end at all). Accurate trip on left, Samsung trip on right. 

<img src="https://github.com/e-mission/e-mission-docs/assets/54848919/f715998c-ef22-470e-b718-13196aa07636" height="500"  /><img src="https://github.com/e-mission/e-mission-docs/assets/54848919/14f6f19b-5168-4714-b766-71cb41eb949e" height="500"  />

Not shown, to keep personal data private, but she was also able to show me a comparison of the same trip on three phones (production, testing on Samsung, testing on iPhone) and the three were *roughly* equal in terms of time and distance, but varied in accuracy - some, including Samsung, had more of the "straight line" behavior than others. 

**Changes made:** After seeing the weird behavior, we walked through the directions on "don't kill my app" together and turned off "auto optimize" in her battery settings as well as "put unused apps to sleep" in an advanced page of battery settings.

**Next Steps:** She is going to continue carrying the phone and report back on if the performance changes at all.

**Comment by JGreenlee** [comment]
> turned off "auto optimize" in her battery settings as well as "put unused apps to sleep" in an advanced page of battery settings.

Are these settings per-app or do they affect the entire phone?

**Comment by Abby-Wheelis** [comment]
yes, if I'm remembering correctly, @nataliejschultz can correct me if I'm wrong. We were following the instructions in the don't kill my app site about Samsung > Android 11 to check on things. If it is for the whole phone, is that bad? I haven't researched into the app store approvals, but I can see where prompting to alter whole-phone settings might get in the way of that.

**Comment by shankari** [comment]
I don't think that this is necessarily related to Samsung phones - you see the "big jump" issue on your test iPhone as well.
I think that the Samsung phone permission issue should reflect as seeing _no points_ not bad points.
But Samsung is weird so anything is possible.

If this fixes it, do we really want to tell people to turn these settings off manually? Note that there is no way for us to get them to the screen automatically and no way for us to check if they have actually done so.

**Comment by nataliejschultz** [comment]
A potential happy medium might be to non-invasively suggest that users _can_ turn off certain phone settings for app optimization without forcing them to? I only suggest it because of the qualitative difference between the accuracy of my iPhone trips vs my Samsung trip (a separate trip that didn’t see the big jump in the screenshots above). 

@Abby-Wheelis the settings we changed today were for the whole phone, because all of the OpenPATH app settings were already set to what was suggested by the setup prompts :)

**Comment by Abby-Wheelis** [comment]
closing this as duplication of #535
