### ISSUE TITLE
Labels are not sticking for a user (server investigation)

### ISSUE THREAD

**Issue by JGreenlee** [e-mission/e-mission-docs#965]
For the past few weeks, a user (who happens to be me) has noticed that their labels are disappearing.
On the phone, the labels appear to be recorded and saved. After refreshing or closing the app, the labels still show up. However, when logging in with that OPCode in an emulator or on a different device, none of the labels show up. And after some time, the labels just disappear.
This suggests an issue with matching on the server (or possibly an issue with sync on the phone).

___

First, I searched for my OPCode so I could find my UUID because I know the log statements print out UUIDs sometimes, but the OPCode is only referenced in the user DB.

Now that I got my UUID, I'm going to search and see if anything jumps out at me.

**Comment by JGreenlee** [comment]
I want to focus on the pipeline intake logs relating to user inputs being processed. So let's just see if I can find that happening for my UUID.
Looking at `intake_stage.py` I can see that the stage where incoming user inputs are checked has this log statement:
https://github.com/e-mission/e-mission-server/blob/94e7478e627fa8c171323662f951c611c0993031/emission/pipeline/intake_stage.py#L105.
So I can probably find that happening for for my UUID by searching for `UUID <my UUID>: updating incoming`.

**Comment by JGreenlee** [comment]
Just a few lines down from the "updating incoming" log statement, I can see an error:

```
  | 2023-08-19 21:31:34,317:ERROR:140009876084544:Error while matching incoming user inputs, timestamp is unchanged
  | 2023-08-19T17:31:34.318-04:00 | Traceback (most recent call last):
  | 2023-08-19T17:31:34.318-04:00 | File "/usr/src/app/emission/analysis/userinput/matcher.py", line 23, in match_incoming_user_inputs
  | 2023-08-19T17:31:34.318-04:00 | last_user_input_done = match_incoming_inputs(user_id, time_query)
  | 2023-08-19T17:31:34.318-04:00 | File "/usr/src/app/emission/analysis/userinput/matcher.py", line 45, in match_incoming_inputs
  | 2023-08-19T17:31:34.318-04:00 | confirmed_obj = esdt.get_confirmed_obj_for_user_input_obj(ts, ui)
  | 2023-08-19T17:31:34.318-04:00 | File "/usr/src/app/emission/storage/decorations/trip_queries.py", line 293, in get_confirmed_obj_for_user_input_obj
  | 2023-08-19T17:31:34.318-04:00 | return final_candidate(valid_timeline_entry(ts, ui_obj), potential_candidates)
  | 2023-08-19T17:31:34.318-04:00 | File "/usr/src/app/emission/storage/decorations/trip_queries.py", line 177, in final_candidate
  | 2023-08-19T17:31:34.318-04:00 | extra_filtered_potential_candidates = list(filter(filter_fn, potential_candidate_objects))
  | 2023-08-19T17:31:34.318-04:00 | File "/usr/src/app/emission/storage/decorations/trip_queries.py", line 262, in curried
  | 2023-08-19T17:31:34.318-04:00 | return valid_user_input_for_timeline_entry(ts, confirmed_obj, user_input)
  | 2023-08-19T17:31:34.318-04:00 | File "/usr/src/app/emission/storage/decorations/trip_queries.py", line 134, in valid_user_input_for_timeline_entry
  | 2023-08-19T17:31:34.318-04:00 | user_input.data.label,
  | 2023-08-19T17:31:34.318-04:00 | File "/usr/src/app/emission/core/wrapper/wrapperbase.py", line 77, in __getattr__
  | 2023-08-19T17:31:34.318-04:00 | return self._build(key, self[key])
  | 2023-08-19T17:31:34.318-04:00 | File "/usr/src/app/emission/core/wrapper/wrapperbase.py", line 145, in _build
  | 2023-08-19T17:31:34.318-04:00 | key_class = self._get_class(key)
  | 2023-08-19T17:31:34.318-04:00 | File "/usr/src/app/emission/core/wrapper/wrapperbase.py", line 131, in _get_class
  | 2023-08-19T17:31:34.318-04:00 | wrapperModule = importlib.import_module("emission.core.wrapper.%s" % wrapper_name)
  | 2023-08-19T17:31:34.318-04:00 | File "/root/miniconda-23.1.0/envs/emission/lib/python3.9/importlib/__init__.py", line 127, in import_module
  | 2023-08-19T17:31:34.318-04:00 | return _bootstrap._gcd_import(name[level:], package, level)
  | 2023-08-19T17:31:34.318-04:00 | File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  | 2023-08-19T17:31:34.318-04:00 | File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  | 2023-08-19T17:31:34.318-04:00 | File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
  | 2023-08-19T17:31:34.318-04:00 | ModuleNotFoundError: No module named 'emission.core.wrapper.label'
```

I verified that this error was not being thrown for everyone by searching for "Error while matching" and found that every time it is thrown, it is for my UUID

**Comment by JGreenlee** [comment]
It seems like this might be thrown every single time the pipeline is run, so I wanted to see how far this error goes back.

I kept searching further back to find a time when the error wasn't thrown. Evidently, my UUID has been broken for a while.
Eventually I had to search as far back as June 1, and found that this issue started on **June 15**.

**Comment by JGreenlee** [comment]
I had a suspicion that this issue was my own fault. I sometimes use my own OPCode for testing out new development features, especially those that aren't easily recreated with a local instance of the server.
And the likelihood of this issue affecting me in particular, but no one else, is low.

I looked back at my Github activity to see what I was working on around June 15. That's around the time that I was rewriting the Multilabel functionality, rewriting `multilabel-ui` into `MultilabelButtonGroup` (https://github.com/e-mission/e-mission-phone/pull/993#issue-1757709219).
And I specifically remember that I was using my personal OPCode while testing it because my personal one has a better history of inferred trips (for the yellow/orange labels). And I didn't know how to test that with the server running on my local machine.

I probably mucked something up while I was straightening out the new labeling functionality, sent a bad input to the server, and it's been chewing on it ever since.

**Comment by JGreenlee** [comment]
I bet if we can find that bad input and delete it, it will catch up on the next pass and finally match my labels from the last 2 months.

**Comment by JGreenlee** [comment]
Looking more closely at the traceback, I think it means there is a user input without `label` defined because it gets caught on `user_input.data.label`.

**Comment by shankari** [comment]
> Looking more closely at the traceback, I think it means there is a user input without label defined because it gets caught on user_input.data.label.

This actually means that we are trying to find a class called `emission.core.wrapper.label` (which doesn't exist)

```
  | 2023-08-19T17:31:34.318-04:00 | File "/usr/src/app/emission/storage/decorations/trip_queries.py", line 134, in valid_user_input_for_timeline_entry
  | 2023-08-19T17:31:34.318-04:00 | user_input.data.label,
  | 2023-08-19T17:31:34.318-04:00 | File "/usr/src/app/emission/core/wrapper/wrapperbase.py", line 77, in __getattr__
  | 2023-08-19T17:31:34.318-04:00 | return self._build(key, self[key])
  | 2023-08-19T17:31:34.318-04:00 | File "/usr/src/app/emission/core/wrapper/wrapperbase.py", line 145, in _build
  | 2023-08-19T17:31:34.318-04:00 | key_class = self._get_class(key)
  | 2023-08-19T17:31:34.318-04:00 | File "/usr/src/app/emission/core/wrapper/wrapperbase.py", line 131, in _get_class
  | 2023-08-19T17:31:34.318-04:00 | wrapperModule = importlib.import_module("emission.core.wrapper.%s" % wrapper_name)
  | 2023-08-19T17:31:34.318-04:00 | ModuleNotFoundError: No module named 'emission.core.wrapper.label'
```

and is because in the wrapper base, if the field is an object, we try to find the corresponding object for it.

```
    elif isinstance(obj, coll.Mapping):
        key_class = self._get_class(key)
        # logging.debug("key_class = %s" % key_class)
        return key_class._constructor(obj, self._configuration())
```

In the case of the userinput, the label is supposed to be a string

```
             "label": ecwb.WrapperBase.Access.RO, # string summary of the survey
```

so this if should not have been triggered. But I guess during testing, you saved it as an object temporarily.
We just need to find the input with the object and ensure that it is deleted...

**Comment by shankari** [comment]
Checking the list of unique labels for this user, we get

```
>>> edb.get_timeseries_db().find({"metadata.key": {"$in": ["manual/mode_confirm", "manual/purpose_confirm"]}, "user_id": testuuid}).distinct("data.label")
['access_recreation', 'ambulance', 'bike', 'bikeshare', 'bus', 'drove_alone', 'e-bike', 'e_car_drove_alone', 'entertainment', 'exercise', 'home', 'meal', 'not_a_trip', 'personal_med', 'pick_drop_item', 'pick_drop_person', 'refueling', 'scootershare', 'shared_ride', 'shopping', 'train', 'transit_transfer', 'walk', 'work', {'co2PerMeter': 0, 'value': 'walk', 'met_equivalent': 'WALKING', 'text': 'Walk'}, {'value': 'personal_med', 'text': 'Personal/ Medical'}]
```

The erroneous ones are: 
1. `{'co2PerMeter': 0, 'value': 'walk', 'met_equivalent': 'WALKING', 'text': 'Walk'}`
2. `{'value': 'personal_med', 'text': 'Personal/ Medical'}`

Let's see if we can select only them...

**Comment by shankari** [comment]
Yup

```
>>> for e in list(edb.get_timeseries_db().find({"metadata.key": {"$in": ["manual/mode_confirm", "manual/purpose_confirm"]}, "user_id": testuuid, "data.label.value": {"$exists": 1}})):
...     print(e['metadata']['key'], e['data']['label'], e['metadata']['write_fmt_time'])
...
manual/mode_confirm {'co2PerMeter': 0, 'value': 'walk', 'met_equivalent': 'WALKING', 'text': 'Walk'} 2023-06-15T05:56:33.667007-04:00
manual/mode_confirm {'co2PerMeter': 0, 'value': 'walk', 'met_equivalent': 'WALKING', 'text': 'Walk'} 2023-06-15T05:56:30.514501-04:00
manual/purpose_confirm {'value': 'personal_med', 'text': 'Personal/ Medical'} 2023-06-15T05:56:33.669958-04:00
manual/purpose_confirm {'value': 'personal_med', 'text': 'Personal/ Medical'} 2023-06-15T05:56:30.517327-04:00
```

**Comment by shankari** [comment]
Deleted them 

```
>>> edb.get_timeseries_db().delete_many({"metadata.key": {"$in": ["manual/mode_confirm", "manual/purpose_confirm"]}, "user_id": testuuid, "data.label.value": {"$exists": 1}}).raw_result
{'n': 4, 'ok': 1.0, 'operationTime': Timestamp(1694122404, 1)}
```

**Comment by shankari** [comment]
@JGreenlee please close this once you have verified that this has fixed the issue

**Comment by JGreenlee** [comment]
Resolved! New labels are being processed correctly, and the old labels which were missing have been processed too.
