### ISSUE TITLE
🚑️ Launching app with incorrect permissions did not take me to the app status

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-docs#967]
Over the weekend, the Pixel 4 randomly reset some of the app permissions. I got a notification, but when I launched the app, it did not take me to the app settings. This seems to be a regression of https://github.com/e-mission/e-mission-phone/pull/964

| Permission error notification | No popup on label screen |
|--------|-------|
| ![permissions_error_notification](https://github.com/e-mission/e-mission-docs/assets/2423263/ed58a6a0-7c3d-4e9a-a76d-6acd359bd50f) | ![no_popup_on_label_screen](https://github.com/e-mission/e-mission-docs/assets/2423263/78e14ab1-4860-476d-a2e9-cc9885d70875) |
| But background permissions have been reset | and it was the unused apps |
| ![but_background_permissions_have_been_reset](https://github.com/e-mission/e-mission-docs/assets/2423263/9a1d3edc-f89d-4eda-898e-e8c655ada6fa) | ![and_it_was_the_unused_apps](https://github.com/e-mission/e-mission-docs/assets/2423263/1c3fa90d-468b-4bd8-867e-ac195c8f1f86) |

**Comment by Abby-Wheelis** [comment]
With the new permission modal in [e-mission-phone#1009](https://github.com/e-mission/e-mission-phone/pull/1009), the permissions are checked every time to app comes into the foreground and opens the permissions screen if any of them are not set properly. I've tested on the devapp, and the modal pops up when I turn off a permission and then reopen the app. Hopefully these changes will address the issue, we can check once its on staging.

**Comment by JGreenlee** [comment]
> I've tested on the devapp, and the modal pops up when I turn off a permission and then reopen the app.

Does this work even when not on the Profile tab?
If I just launched the app, I'm on the label screen and my permissions are wrong, will I get a popup?

**Comment by JGreenlee** [comment]
The preferred / most organized way to do this, once the Dashboard is migrated and we switch the routing away from Angular/Ionic, is for all 3 tabs (Label, Dashboard, Profile) to be included in a common component (the `App` component), where `AppStatusModal` could also be included, along with any other app-wide logic (like reading the dynamic config).

**Comment by JGreenlee** [comment]
That is not what I am observing. After a fresh launch, the permissions popup only shows once you go to the Profile tab.

![gif](https://github.com/e-mission/e-mission-docs/assets/15843932/bc2bb771-4c96-480b-a99e-5321c5074828)

This is because the Profile tab is not initialized on app launch

**Comment by Abby-Wheelis** [comment]
I worked with the `label_dashboard_profile_sept_2023` a bit, and the permissions will launch the next time the label screen is refreshed if the permissions break while the app is in the background, but not if the app is freshly launched after breaking a permission. I wasn't able to figure out why, but maybe it has something to do with that component (the one for angular permissions) not being intialized? 

One way to solve this is to incorporate my new `AppStatusModal` on the Label screen, I cherry-picked the commits over to [a new branch](https://github.com/Abby-Wheelis/e-mission-phone/tree/permission-launch-fix) to test, and it works when bringing the app into the foreground and on fresh launch: 

1. app in foreground -> background -> break permission -> foreground -> modal pops up
2. kill app entirely -> break permission -> fresh launch -> modal pops up

This would be a temporary fix until we have the `App` component.

**Comment by shankari** [comment]
Confirmed that this is fixed by resetting the permission on my phone, waiting until the prompt and then clicking on the prompt.
