### ISSUE TITLE
🚑️ handle custom labels better

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-docs#969]
we had a report from a user that their app was hanging.
"it has been like this since Saturday"

<img src="https://github.com/e-mission/e-mission-docs/assets/2423263/efa33523-af47-4e4f-a8ba-857a1794671f" width="330px"/>

**Comment by shankari** [comment]
Fortunately, we were able to reproduce the error in the emulator. This is 100% reproducible.

```
[Error] Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'word[0].toUpperCase')
    step (bundle.js:60708)
    fulfilled (bundle.js:60609)
    promiseReactionJob
```

This occurs in `valueToOtherText`:
The user's `otherValue` is `"drove_to bike night "` and the trailing space causes the error because we split by `" "` and end up with an empty string that we try to capitalize the first letter of.

As far as I can tell, [it's always been like this](https://github.com/e-mission/e-mission-phone/blob/ca2da7184080218f2a9b000d9280eacba636fc45/www/js/survey/multilabel/trip-confirm-services.js#L118), so maybe we've just been lucky to not have people put trailing spaces in their 'other' text until now.

I see 3 takeaways from this:

- The user entered something like "Drove to bike night " and we converted this to `"drove_to bike night "` when we accepted their input, which is not what we really wanted.
  - We should strip any leading/trailing whitespace and filter out non-alphanumeric characters
  - We should have replaced _all_ the spaces with underscores, not just the first one.
    - (in JS, `str.replace(' ', '_')` only does the first occurrence. To do all occurences you need `str.replace(/ /g, '_')`. I was already planning on fixing this)
- `"drove_to bike night "` is already recorded in the DB, so we do have to deal with it. When reading, we should remove any leading/trailing spaces (the JS `trim()` method does this)
- If there's an error ***anywhere*** during the load sequence, we should catch it, show it to the user, and stop the spinner

**Comment by shankari** [comment]
Fixed this in the server DB as a workaround. Principled fix coming in next release.
Note that it is not sufficient to change only the user input, we also had to change the confirmed and composite trips since the input had already been processed.

```
>>> edb.get_timeseries_db().update_one({"metadata.key": "manual/replaced_mode", "user_id": testuuid, "data.label": "drove_to bike night "}, {"$set": {"data.label": "drove_to_bike_night"}})
>>> edb.get_analysis_timeseries_db().update_one({"metadata.key": "analysis/confirmed_trip", "user_id": testuuid, "data.user_input.replaced_mode": "drove_to bike night "}, {"$set":  {"data.user_input.replaced_mode": "drove_to_bike_night"}})
>>> edb.get_analysis_timeseries_db().update_one({"metadata.key": "analysis/composite_trip", "user_id": testuuid, "data.user_input.replaced_mode": "drove_to bike night "}, {"$set":  {"data.user_input.replaced_mode": "drove_to_bike_night"}})
```

**Comment by shankari** [comment]
Added custom labels, including trailing spaces, to a study environment.
Took a trip.
Data reloaded properly.
Marking this as closed...

**Comment by Abby-Wheelis** [comment]
I tried to replicate this on the current staging, and was able to put in a label with leading and trailing whitespace without issue. I put in other, and then " Hybrid Car Alone  " for one of my trips on my test iPhone yesterday, and had no issues. Today, that label is showing up in the emulator, indicating it has been stored on the server without issue. In the log statements, I can see the label was converted to "hybrid_car_alone" and is displayed as "Hybrid Car Alone".
