### ISSUE TITLE
✔️ Revise the "Verify Checkmark"

### ISSUE THREAD

**Issue by JGreenlee** [e-mission/e-mission-docs#979]
The app supports mode and purpose labels so you can say how & why you took a trip, and we have models to generate inferences based on past labels.

Trips that haven't been labeled by the user show buttons with a white background. After labels are provided, the buttons have a blue, 'filled in' background:

<table><td>

![image](https://github.com/e-mission/e-mission-docs/assets/15843932/0765f8d7-5ed6-4dbc-8078-cf81548550b3)
</td><td>

![image](https://github.com/e-mission/e-mission-docs/assets/15843932/698e4fc4-406f-446b-aae4-8e775a7eb391)
</td><table>

If there is an inference, it shows in yellow as a sort of 'pending' state. So since I have taken this trip many times before, and labeled it this way in the past, OpenPATH is **guessing** that I drove alone and it was for an Entertainment/ Social purpose. But it still wants me to verify that the guess is correct - and that's what the checkmark is for.

<img src=https://github.com/e-mission/e-mission-docs/assets/15843932/fe4695e7-5856-4033-93c3-70ea2e3e684c width=50%>

We have had feedback from users that the function of the checkmark is not very clear. We have also had feedback that the click area for the checkmark is too small - this is bad for usability as well as accessibility.

To remedy this, I suggest we:
- adjust the position and size of the checkmark button, to be bigger and vertically centered with the label buttons
- have it show yellow to more clearly indicate that it is related to the yellow inferred labels
- **only** show it when there is at least one inferred label waiting to be verified (there's no reason to display a button that does nothing)

<hr>

In the end, it should look something like this:

<img src=https://github.com/e-mission/e-mission-docs/assets/15843932/3df2da23-2a2d-4ce0-bc38-0d0372641aaa width=50%>

**Comment by the-bay-kay** [comment]
Finally got my development environment working, and just did the first third!  To help center the button, I added `1rem` to the top margin, to account for the 'Mode' text (the idea being, we want to center it relative to the bottom 3 elements).  I increased the checkmark and button size a few pixels, and shortened the left margin slightly, to better match the reference photo.  I've tested the new GUI on an iPhone 15 / 15Plus, Xs, and an iPad Mini, just to make sure it scales fine!  Next up is the dynamic appearance / color change, I'm thinking I'll do that in a similar way to how the Diary buttons are dynamically changed in the same file.

The small adjustments I made to `www/js/survey/multilabel/MultiLabelButtonGroup.tsx` were:

**Old Code**
```

  <View> // Line 107
        <IconButton icon='check-bold' mode='outlined' size={16} onPress={verifyTrip}
                    disabled={trip.verifiability != 'can-verify'}
                    style={{width: 20, height: 20, margin: 3}}/>
  </View>

```
<img width="373" alt="Before" src="https://github.com/e-mission/e-mission-docs/assets/98350084/e9dd6665-cf18-4961-b795-f58ea9d670e1">


**New Code**
```
  <View style={{marginTop:'1rem', marginLeft:'-0.2rem',}}> // Line 107
        <IconButton icon='check-bold' mode='outlined' size={18} onPress={verifyTrip}
                    disabled={trip.verifiability != 'can-verify'}
                    style={{width: 24, height: 24, margin: 3}}/>
  </View>
```
<img width="373" alt="After" src="https://github.com/e-mission/e-mission-docs/assets/98350084/57726495-b0e3-4e3a-a0e7-faf20b85ab27">

**Comment by the-bay-kay** [comment]
Quick update!  Added the following code to the same component: now the check mark dynamically appears when verifiable, and the color matches (color is working but not shown in photo, I forgot to screenshot before verifying the given sample trip).    I'll go ahead and make a PR, unless there are any changes you'd like me to make - The new code is below:

```
{trip.verifiability === 'can-verify' && (
        <View style={{marginTop:'1rem'}}>
          <IconButton icon='check-bold' mode='outlined' size={18} onPress={verifyTrip}
                       style={{width: 24, height: 24, margin: 3, backgroundColor: colors.secondaryContainer}}/>
        </View>
      )}
```

<img width="422" alt="DynamicVisiblity_1" src="https://github.com/e-mission/e-mission-docs/assets/98350084/f6684c81-b902-4cb1-9ace-601f2a34a3b7">

<img width="422" alt="DynamicVisibility_2" src="https://github.com/e-mission/e-mission-docs/assets/98350084/caf29ca3-7870-4df1-ae81-f8e436c13d81">

<img width="422" alt="afterVerify" src="https://github.com/e-mission/e-mission-docs/assets/98350084/d62060a8-6464-42b0-934e-3ed66f820e93">

**Comment by JGreenlee** [comment]
The result looks great! I'll leave my comments once you have that PR up.

**Comment by JGreenlee** [comment]
This has been implemented for a while and is on `master`
